[KOGITO-3915] Introducing OpenAPI client codegen for SW
kiegroup/kogito-runtimes pull request #1014
Opened 2021-01-28 21:00 UTC by ricardozanini

See: https://issues.redhat.com/browse/KOGITO-3915

This is a WIP. I'll push my updates daily for others who would like to follow the progress of the feature implementation.

For now, we can parse SW and extract the spec files from the functions defitions.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

2021-01-28 21:01 UTC, ricardozanini commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/openapi/OpenAPIClientCodegen.java
> +                !workflow.getFunctions().getFunctionDefs().isEmpty() &&
remove this

2021-02-10 13:35 UTC, ricardozanini commented
Jenkins retest this please

2021-02-10 13:36 UTC, ricardozanini commented
> Jenkins retest this please

2021-02-12 07:37 UTC, danielezonca reviewed
Nice work, well done 👍 
I did initial review so added some comments :)

2021-02-12 07:37 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiClientCodegen.java
> +            final String resolvedPath =
Is it really necessary to save the file? I would like to keep the generator as an in memory only process (to be thread safe and idempotent).
If there are no other option, what about add a finally block to remove it?
Moreover, can you please make it explicitly in method name if it saves a file (instead of just `resolve`)?

2021-02-12 07:37 UTC, danielezonca commented on kogito-quarkus-extension/deployment/pom.xml
> +            <artifactId>kogito-codegen-openapi</artifactId>
Make sure to do the same for `kogito-maven-plugin`

2021-02-12 07:37 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/resources/custom-templates/resteasy/README
> +These are the custom templates used by the OpenAPI Generator Tool to create the REST client code.
What about add `md` extension to the file?

2021-02-12 07:37 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiClientCodegen.java
> +    private static final int PRIORITY = 0;
Please don't use priority 0, any number between 1 and 9 should be fine. As alternative you can even update all other priorities to shift by 10 and make this priority 10.

2021-02-12 07:37 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiUtils.java
> +        return new File(classLoader.getResource("").getFile()).getParentFile().getPath();
Please use `context.getAppPaths().getFirstProjectPath()`. It should be equivalent and it handled in a centralised way.

2021-02-12 07:37 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiUtils.java
> +        requireNonNull(resource.getURI());
Please add a message too, otherwise it will just throw a NPE

2021-02-12 07:37 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/ServerlessWorkflowCodegenUtils.java
> +    public static final Set<String> SUPPORTED_SW_EXTENSIONS = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(".sw.json", ".sw.yaml", ".sw.yml")));
We should centralise this somewhere else with a future ticket, same for other generator files. Wdyt?

2021-02-12 07:37 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/KogitoBuildContext.java
> +    Map<String, Object> getContextAttributes();
@evacchi 
FYI
I agreed with @ricardozanini to create this map to make generators share info for now and then migrate to symbol table as soon as available.

2021-02-12 07:37 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/impl/AbstractKogitoBuildContext.java
> +        throw new AssertionError("Impossible to cast key value " + output + " as " + asClass.getName());
```suggestion
        throw new AssertionError("Impossible to cast '" + key + "' key value as " + asClass.getName() + ", found " + output.getClass().getCanonicalName());
```

2021-02-12 14:18 UTC, ricardozanini commented on kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/openapi/client/OpenApiClientCodegenTest.java
> +class OpenApiClientCodegenTest extends AbstractCodegenTest {
Oh, I'll expand these unit tests today to do the actual compilation. Otherwise, I'll move them. It's there since you did the modules refactoring.

2021-02-12 14:19 UTC, ricardozanini commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiUtils.java
> +        return new File(classLoader.getResource("").getFile()).getParentFile().getPath();
I didn't know about this method :sweat:

2021-02-12 14:20 UTC, ricardozanini commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/ServerlessWorkflowCodegenUtils.java
> +    public static final Set<String> SUPPORTED_SW_EXTENSIONS = Collections.unmodifiableSet(new HashSet<>(Arrays.asList(".sw.json", ".sw.yaml", ".sw.yml")));
I will open a JIRA to centralize all the core modules' extensions. It's on my plate. wdyt?

2021-02-12 14:22 UTC, ricardozanini commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiClientCodegen.java
> +    private static final int PRIORITY = 0;
Everyone is using `Interger.MAX`, IIRC. :/

2021-02-12 14:27 UTC, ricardozanini commented on kogito-codegen-modules/kogito-codegen-openapi/src/main/java/org/kie/kogito/codegen/openapi/client/OpenApiClientCodegen.java
> +            final String resolvedPath =
I'll take a look. The interface is `String resolve(spec)`. For some resolvers (e.g., classpath or file), it won't "save" the file but only translate it. For HTTP(S), we need to download it. My first plan was to save on OS temp location instead, but we lack control. The file is saved on `target` dir, cleaned after any `mvn clean` command. Plus, a user might want to inspect the downloaded file for debugging reasons.

Not sure if we should delete it. The process is idempotent.

2021-02-18 14:52 UTC, ricardozanini commented
> The Linux check has **failed**. Please check [the logs](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/pullrequest/job/kogito-runtimes/144/console).

LOL

```
java.io.IOException: No space left on device
	at java.base/sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at java.base/sun.nio.ch.FileDispatcherImpl.write(FileDispatcherImpl.java:62)
	at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:113)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:79)
	at java.base/sun.nio.ch.FileChannelImpl.write(FileChannelImpl.java:280)
```

2021-02-22 13:18 UTC, danielezonca commented on kogito-quarkus-extension/deployment/src/test/java/org/kie/kogito/quarkus/serverless/workflow/OpenApiClientTest.java
> +public class OpenApiClientTest {
I think it is better to move this test to [integration-tests-quarkus-processes](https://github.com/kiegroup/kogito-runtimes/tree/master/integration-tests/integration-tests-quarkus-processes) module (you can create an integration test for SprintBoot too if you need).

2021-02-25 18:45 UTC, ricardozanini commented on kogito-quarkus-extension/deployment/src/test/java/org/kie/kogito/quarkus/serverless/workflow/OpenApiClientTest.java
> +public class OpenApiClientTest {
Oh, this slipped. I just added it for debugging purposes.

2021-02-25 18:46 UTC, ricardozanini commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
>          }
Oh! Brain fart, I should've done it.

2021-02-25 18:46 UTC, ricardozanini commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/TaskDescriptorBuilder.java
> +    }
I'll refactor it again. :D

2021-02-25 21:50 UTC, ricardozanini commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
>          }
nvm, I kept the same algorithm. If it's not supported, it's not supposed to create a service task, we are fine.

2021-03-05 19:53 UTC, ricardozanini commented
Not sure why these files have 0% coverage:

```
kogito-workitems/kogito-openapi-workitem/src/main/java/org/kogito/workitem/openapi/JsonNodeParameterResolver.java
kogito-workitems/kogito-openapi-workitem/src/main/java/org/kogito/workitem/openapi/JsonNodeParser.java
kogito-workitems/kogito-openapi-workitem/src/main/java/org/kogito/workitem/openapi/JsonNodeResultHandler.java
```

Since this is  a new module, should I do something about it? Does someone know what I have to do?
 

2021-03-06 15:40 UTC, tsurdilo approved these changes

2021-03-06 15:40 UTC, tsurdilo commented
@ricardozanini great job!! 💯

2021-03-08 02:57 UTC, cristianonicolai approved these changes
nice work @ricardozanini !

2021-03-08 10:06 UTC, danielezonca approved these changes
Thanks for the PR, approving 👍 
What about including as README of `open-api-codegen` module the description of the PR?

2021-03-08 12:15 UTC, ricardozanini commented on kogito-build-parent/pom.xml
> +    <version.org.jboss.resteasy>4.5.9.Final</version.org.jboss.resteasy>
https://github.com/quarkusio/quarkus/blob/1.11/bom/application/pom.xml#L21

2021-03-08 12:38 UTC, ricardozanini commented
For some reason, my description update with the follow-up JIRAS was lost. But here they are https://issues.redhat.com/browse/KOGITO-3915.

2021-03-08 14:25 UTC, ricardozanini commented
@danielezonca I've removed the `package` modifiers and added the README to describe the new codegen module. Thanks!

2021-03-08 16:37 UTC, evacchi approved these changes

2021-03-08 17:09 UTC, evacchi commented
Please notice that we are downgrading master to Quarkus 1.11 so if there are Classpath related issues I'd invite to verify if those still hold rebasing on top of https://github.com/kiegroup/kogito-runtimes/pull/1115. This has a high priority as it should go in 1.4.x /cc @radtriste @spolti

2021-03-08 18:50 UTC, ricardozanini commented
@evacchi I think we can wait, yes. Also, I've removed the `resteasy` dependencies using `exclusions` on `jbpm-serverless-workflow` module since it's used only by the end-user project. That dependencies were messing with the DMN integration tests.

2021-03-08 20:25 UTC, ricardozanini commented
@danielezonca, the CI is failing because of this: 
https://github.com/kiegroup/kogito-runtimes/blob/master/addons/cloudevents/cloudevents-spring-boot-addon-it/pom.xml#L37-L38

It looks like the local repo doesn't have the updated Kogito BOM with the new openapi module, thus the failure on the maven plugin dependency. I checked locally and Maven is downloading the BOM file from the jboss repository instead of the local `.m2`. I don't see a reason to configure this option in the invoker since it's using the same .m2 repository from the machine where the build is running. :thinking: 

I just pushed a new commit without this configuration to verify if it works. The error vanished locally. If you're ok with this change, I can remove this configuration for good.

2021-03-09 08:22 UTC, danielezonca commented
> @danielezonca, the CI is failing because of this:
> https://github.com/kiegroup/kogito-runtimes/blob/master/addons/cloudevents/cloudevents-spring-boot-addon-it/pom.xml#L37-L38
> 
> It looks like the local repo doesn't have the updated Kogito BOM with the new openapi module, thus the failure on the maven plugin dependency. I checked locally and Maven is downloading the BOM file from the jboss repository instead of the local `.m2`. I don't see a reason to configure this option in the invoker since it's using the same .m2 repository from the machine where the build is running. 🤔
> 
> I just pushed a new commit without this configuration to verify if it works. The error vanished locally. If you're ok with this change, I can remove this configuration for good.

I think it is related to the same issue reported here
https://github.com/kiegroup/kogito-runtimes/pull/1051
Try to apply the change in your branch and see if CI becomes green.
We don't agree on that PR (see comments) but at least we can check if it is the same problem

2021-03-09 11:45 UTC, ricardozanini commented
> I think it is related to the same issue reported here
> #1051
> 
> @cristianonicolai
> Can you please have a look to the changes done by Ricardo with this commit [377066d](https://github.com/kiegroup/kogito-runtimes/commit/377066d6d0cb715c60fe405183f98bf9ab0b5ae4) ?

It's working now. I'm willing to make my changes permanent and rebase with Quarkus downgrade. @cristianonicolai @danielezonca wdyt?

2021-03-09 16:48 UTC, ricardozanini commented
Jenkins retest please

2021-03-09 21:33 UTC, ricardozanini commented
@danielezonca @cristianonicolai once you guys wake up, mind taking a look? I think we should be fine to merge.

2021-03-09 21:59 UTC, ricardozanini commented
Jenkins retest this please

2021-03-10 07:31 UTC, radtriste commented
@tsurdilo @ricardozanini what is the targeted version for this PR ?

2021-03-10 10:34 UTC, evacchi requested changes

2021-03-10 10:34 UTC, evacchi commented on addons/cloudevents/cloudevents-spring-boot-addon-it/pom.xml
> -                <localRepositoryPath>${project.build.directory}/local-repo</localRepositoryPath>
remember you'll have to restore these before we can merge

2021-03-10 10:36 UTC, evacchi commented
I had left a comment about restoring the invoker configuration, but I see that was intended now? @danielezonca

2021-03-10 13:22 UTC, ricardozanini commented
> I had left a comment about restoring the invoker configuration, but I see that was intended now? @danielezonca
> 
> > Timeout has been exceeded
> > Finished: ABORTED
> 
> AFAIK the reason for those lines is time outs :/

It's timing out in the last step, testing the persistence with ISPN. I believe it's an infra problem?

2021-03-10 13:23 UTC, ricardozanini commented
Jenkins retest this please

2021-03-10 17:02 UTC, ricardozanini commented
@cristianonicolai @danielezonca feel free to merge.

2021-03-11 14:36 UTC, merged