KOGITO-3759: Implement event persistence based on MongoDB
kiegroup/kogito-runtimes pull request #1027
Opened 2021-02-02 05:15 UTC by xieshenzh

Implement event persistence based on MongoDB to support outbox pattern and solve the consistency issue.

Jira: https://issues.redhat.com/browse/KOGITO-3759

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2021-06-29 00:36 UTC, xieshenzh commented
Jenkins retest this

2021-06-29 17:34 UTC, tiagodolphine reviewed
Thanks @xieshenzh, in general LGTM, I'm just concerned if the usage of the addon would be clear for the users, I think we would need good documentation to explain how to use and configure this to work with the outbox.
One other point should we prevent to have multiple EventPublisher in the same app, in case the outbox is enabled? For instance, the user could configure a Kafka eventPublisher + MongoDBEventPublisher.... just to open for discussion.
c/c @danielezonca

2021-07-01 19:54 UTC, MarianMacik reviewed
Looks good, just minor comments.

2021-07-01 19:54 UTC, MarianMacik commented on addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/CodecUtilsTest.java
> +        assertTrue(CodecUtils.codec().getClass().isAssignableFrom(DocumentCodec.class));
Why not to use equals instead of `isAssignableFrom` here?

2021-07-01 19:54 UTC, MarianMacik commented on addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/EventMongoDBCodecProviderTest.java
> +        assertTrue(provider.get(VariableInstanceDataEvent.class, null).getClass().isAssignableFrom(VariableInstanceDataEventCodec.class));
Why not to use equals instead of `isAssignableFrom` here?

2021-07-01 19:54 UTC, MarianMacik commented on addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/ProcessInstanceDataEventCodecTest.java
> +        when(nodeInstanceEventBody.getLeaveTime()).thenReturn(leaveTime);
Why not to use the included builder for this? The code will be much shorter. Same goes for `MilestoneEventBody`.

2021-07-01 19:54 UTC, MarianMacik commented on addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/ProcessInstanceDataEventCodecTest.java
> +        assertTrue(codec.getEncoderClass().isAssignableFrom(ProcessInstanceDataEvent.class));
Same here.

2021-07-01 19:54 UTC, MarianMacik commented on addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/UserTaskInstanceDataEventCodecTest.java
> +        assertTrue(codec.getEncoderClass().isAssignableFrom(UserTaskInstanceDataEvent.class));
Same here.

2021-07-01 19:54 UTC, MarianMacik commented on addons/common/events/mongodb/src/test/java/org/kie/kogito/events/mongodb/codec/VariableInstanceDataEventCodecTest.java
> +        assertTrue(codec.getEncoderClass().isAssignableFrom(VariableInstanceDataEvent.class));
Same here.

2021-07-01 19:54 UTC, MarianMacik commented on addons/quarkus/events/mongodb/src/main/java/org/kie/kogito/events/mongodb/QuarkusMongoDBEventPublisher.java
> +        return this.processInstancesEvents.orElse(true);
What about using the default value construct here as well?

2021-07-05 16:08 UTC, xieshenzh commented
Jenkins retest this

2021-07-07 14:04 UTC, MarianMacik approved these changes
Looks good now, thanks!

2021-07-22 05:32 UTC, cristianonicolai approved these changes

2021-07-23 13:50 UTC, tiagodolphine approved these changes

2021-07-23 21:46 UTC, ricardozanini requested changes
Hi @xieshenzh! Many thanks for this PR. I have some questions, if you don't mind:

1. Is this compatible with events in CE format? If so, some of these attributes can come in the CE headers as extensions, so the keys you're using might fail to serialize and data can be lost.
2. Can you please add a `README.md` file in the root of the `addons/common/events/mongodb` and include this addon in the `addons/README.md` table?

Many thanks!

2021-07-23 21:46 UTC, ricardozanini commented on addons/common/events/mongodb/src/main/java/org/kie/kogito/events/mongodb/codec/CodecUtils.java
> +        doc.put("kogitoAddons", event.getKogitoAddons());
Are these keys based on CloudEvents? Please note that we have constants for these: https://github.com/kiegroup/kogito-runtimes/blob/1.8.0.Final/addons/common/cloudevents/utils/src/main/java/org/kie/kogito/cloudevents/extension/KogitoProcessExtension.java#L40-L48

2021-07-24 00:29 UTC, xieshenzh commented
> Hi @xieshenzh! Many thanks for this PR. I have some questions, if you don't mind:
> 
> 1. Is this compatible with events in CE format? If so, some of these attributes can come in the CE headers as extensions, so the keys you're using might fail to serialize and data can be lost.
> 2. Can you please add a `README.md` file in the root of the `addons/common/events/mongodb` and include this addon in the `addons/README.md` table?
> 
> Many thanks!

Hi @ricardozanini ,

1. This implementation with MongoDB is an alternative to Kafka events which are used by data index.
The keys you mentioned are the fields names of the MongoDB documents. The MongoDB documents will be converted to Kafka messages by Debezium, and eventually consumed by data index. During this process, the fields names will remain unchanged. As far as I know, the keys are compatible with the current data index implementation.
The purpose of doing this is to have strong consistency of data for kogito runtime and data index with MongoDB transaction.
I have very little knowledge of Kogito could events, so I am not sure if they are supposed to be compatible. Please let me know.
2. Sure, I'll add readme files.

Thanks.

2021-07-26 12:14 UTC, ricardozanini commented
Thanks for the explanation! :)

2021-07-26 20:47 UTC, ricardozanini approved these changes

2021-07-27 11:40 UTC, cristianonicolai commented
Jenkins rerun examples tests

2021-07-28 00:40 UTC, xieshenzh commented
Jenkins rerun examples tests

2021-07-28 13:11 UTC, ricardozanini commented
Jenkins rerun examples tests

2021-07-29 11:45 UTC, cristianonicolai commented
Jenkins rerun examples tests

2021-07-29 14:39 UTC, xieshenzh commented
Jenkins rerun examples tests

2021-07-30 06:52 UTC, danielezonca reviewed
Overall looks good to me, just few minor comments

2021-07-30 06:52 UTC, danielezonca commented on addons/common/events/mongodb/README.md
> +Once the events are inserted to MongoDB, they will be deleted immediately. Then Debezium will read the events from the MongoDB operation log, and publish to Kafka.
Is Debezium configuration/integration part of this PR?

2021-07-30 14:13 UTC, xieshenzh commented on addons/common/events/mongodb/README.md
> +Once the events are inserted to MongoDB, they will be deleted immediately. Then Debezium will read the events from the MongoDB operation log, and publish to Kafka.
No, I'll create an example in kogito-examples.

2021-07-30 19:57 UTC, xieshenzh commented
Jenkins rerun apps tests

2021-08-03 20:01 UTC, xieshenzh commented on springboot/addons/events/mongodb/pom.xml
> +                <version>${version.org.springframework.boot}</version>
Removed

2021-08-03 20:01 UTC, xieshenzh commented on quarkus/addons/events/mongodb/pom.xml
> +    <dependencyManagement>
Removed

2021-08-03 20:59 UTC, danielezonca approved these changes
LGTM :+1:

2021-08-10 11:44 UTC, cristianonicolai commented
@xieshenzh can you rebase

2021-08-11 00:36 UTC, xieshenzh commented
> @xieshenzh can you rebase

@cristianonicolai sure, it is rebased.

2021-08-11 12:31 UTC, cristianonicolai commented
Jenkins rerun apps tests

2021-08-11 12:31 UTC, cristianonicolai commented
Jenkins rerun runtimes tests

2021-08-11 13:36 UTC, ricardozanini commented
@cristianonicolai @xieshenzh I think is doable fixing the Sonar issues: https://sonarcloud.io/dashboard?id=org.kie.kogito%3Akogito-runtimes&pullRequest=1027

2021-08-11 17:09 UTC, xieshenzh commented
Jenkins rerun apps tests

2021-08-11 20:37 UTC, merged