KOGITO-4376 Review license header validation during maven build
kiegroup/kogito-runtimes pull request #1046
Opened 2021-02-09 05:35 UTC by cristianonicolai

- Centralize license header settings in `kogito-build-parent` bom
 - Use checkstyle to validate license header based on regex ( no git dependency )
 - For now Checkstyle will log errors in console but not break the build, this will allow changes to be pushed later on before we turned it on
 - For automatically formatting classes we will still use `license-maven-plugin`. To format code please run:  `mvn com.mycila:license-maven-plugin:format`

Assembly:
- https://github.com/kiegroup/kogito-examples/pull/553
-

2021-02-09 07:24 UTC, mareknovotny commented on kogito-build-parent/pom.xml
> +    </checkstyle.header.template>
please add new properties in  alphabetically order

2021-02-09 07:27 UTC, mareknovotny requested changes
Even the standards are not fully written in kogito contribution guide, it will be there soon and we had some traditional conventions in pom.xml files. So to have easier change for KOGITO-4064, sort at least new properties in alphabetical order. Thanks in advance!

2021-02-09 08:06 UTC, mareknovotny commented
I quickly send new conventions in this PR https://github.com/kiegroup/kogito-runtimes/pull/1049

2021-02-09 10:14 UTC, cristianonicolai commented on kogito-build-parent/pom.xml
> +    </checkstyle.header.template>
@mareknovotny done

2021-02-09 10:42 UTC, ricardozanini approved these changes

2021-02-09 12:29 UTC, mareknovotny approved these changes

2021-02-09 13:51 UTC, danielezonca approved these changes
Thanks for the PR :) 
Can you please add instruction about automatic header formatting to [CONTRIBUTING](https://github.com/kiegroup/kogito-runtimes/blob/master/CONTRIBUTING.md) file?

2021-02-09 15:07 UTC, mareknovotny commented
@danielezonca that is not part of the JIRA i worked on this ;), we should not mixed it IMHO

2021-02-09 15:19 UTC, MarianMacik approved these changes

2021-02-09 17:54 UTC, ricardozanini approved these changes

2021-02-09 18:01 UTC, radtriste approved these changes

2021-02-10 03:30 UTC, cristianonicolai commented
@danielezonca added instructions to contributing guide.

2021-02-10 12:14 UTC, cristianonicolai commented
jenkins please retest this

2021-02-11 05:01 UTC, cristianonicolai commented
jenkins please retest this

2021-02-11 07:25 UTC, merged