[KOGITO-4425] Split quarkus extension for decisions, rules and predictions
kiegroup/kogito-runtimes pull request #1073
Opened 2021-02-15 17:19 UTC by danielezonca

https://issues.redhat.com/browse/KOGITO-4425

## Summary
The goal of this ticket is to split Kogito quarkus extension to enable the user to select a subset of feature.
New extensions are introduced by this PR:
- `kogito-quarkus-decisions`: to add DMN support
- `kogito-quarkus-rules`: to add DRL support
- `kogito-quarkus-predictions`: to add PMML support
The existing `kogito-quarkus` extension is still the same and it provides access to the whole platform
To obtain a similar flexibility a new common `kogio-quarkus-common` module has been created with most of the shared (existing) code.
One of the key design choice of this PR is to enable extension composition: if user wants DMN and PMML it should be enough to add `kogito-quarkus-decisions` and `kogito-quarkus-predictions` without the need to remove one of them or add the `kogito-quarkus` just because it contains all the others.

## Details
- Created `KogitoQuarkusResourceUtils` utility class with common utils method to compile/save/register generated resources
- Each extension should (must) declare a `*AssetsProcessor` to declare extension specific code (i.e. class to register for reflection) and Feature/Capability
- `KogitoAssetsProcessor` moved to common module and now only covers generators that can be loaded via SPI (aka all generator expect PersistenceGenerator and JsonSchemaGenerator for now)
- Enabled post generation customisation via `KogitoGeneratedClassesBuildItem`: this build item contains a Jandex index that contains all the generated Kogito classes. `ProcessesAssetsProcessor` uses this mechanism to plug persistence and jsonSchema generators
- Each extension can have a `kogito-*-integration-test` and a `kogito-*-integration-test-hot-reload` module to provide smoke test for the extension. **NOTE**: full integration test coverage should be implemented in the [`integration-tests`](https://github.com/kiegroup/kogito-runtimes/tree/master/integration-tests) module, these integration tests are executed by `quarkus-platform` pipelines to make sure the extension works after the inclusion in the platform.

To be merged after https://github.com/kiegroup/kogito-runtimes/pull/1066

2021-02-16 21:30 UTC, danielezonca commented
jenkins retest this please

2021-02-18 08:01 UTC, evacchi approved these changes
left a couple minor comments. Great job :)

2021-02-18 08:01 UTC, evacchi commented on kogito-quarkus-parent/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test/src/test/java/org/kie/kogito/quarkus/drools/DroolsTest.java
> +//}
delete/restore these?

2021-02-18 08:53 UTC, evacchi commented
/cc @gsmet @aloubyansky when this PR will get merged, Kogito will be provide n > 1 extensions maybe we'll have to update platform (?)

2021-02-18 08:58 UTC, aloubyansky commented
@evacchi sounds reasonable

2021-02-18 09:09 UTC, danielezonca commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-hot-reload/pom.xml
> +            <scope>provided</scope>
The reality is that we don't need this dependency so I don't want to have it at runtime (I think it will break native compilation of this module). It is only used by quarkus for codegen, but in this way if deployment fails, integration test is skipped.

2021-02-18 09:19 UTC, aloubyansky commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-hot-reload/pom.xml
> +            <scope>provided</scope>
This doesn't look right either way. What happens if you don't add it at all? I assume this the deployment artifact of the kogito extension.

2021-02-18 14:49 UTC, danielezonca commented on kogito-quarkus-parent/kogito-quarkus-rules-extension/kogito-quarkus-rules-integration-test/src/test/java/org/kie/kogito/quarkus/drools/DroolsTest.java
> +//}
Thanks for the comment, fixed 👍

2021-02-18 15:24 UTC, gitgabrio requested changes
@danielezonca 
Not sure if you already did it, but since you are at it, and you have moved packages around, could you please rename artifactid or directories to have them matching ? E.g. kogito-quarkus-parent (artifactid) is inside kogito-quarkus-extension (directory). The same goes true for subdirectories as afar as I can see.

2021-02-18 17:25 UTC, danielezonca commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-hot-reload/pom.xml
> +            <scope>provided</scope>
@aloubyansky
See [this ticket](https://github.com/kiegroup/kogito-runtimes/pull/834) to the reason of the introduction of these "implicit" dependencies in integration test modules.
In summary: if `-deployment` module is skipped because one of its dependencies failed, integration test should not be executed (otherwise usually it fails with a "missing artifact" error raised by quarkus executor) but it does because from maven perspective it depends only on `-runtime` part of the extension.
We can probably move integration test to a different profile to be executed after a first `mvn clean install` build as alternative solution but we have many integration tests so it is sort of mandatory to execute them to understand if the system behave correctly.

2021-02-18 17:31 UTC, aloubyansky commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-hot-reload/pom.xml
> +            <scope>provided</scope>
Have you tried the following instead?
````
        <dependency>
            <groupId>org.kie.kogito</groupId>
            <artifactId>kogito-quarkus-deployment</artifactId>
            <version>${project.version}</version>
            <type>pom</type>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>*</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
````

2021-02-18 18:15 UTC, danielezonca commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-hot-reload/pom.xml
> +            <scope>provided</scope>
I tried the proposed configuration and works well so I updated all of them :)
Thanks @aloubyansky for the suggestion 👍

2021-02-18 20:07 UTC, aloubyansky commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test-hot-reload/pom.xml
> +            <scope>provided</scope>
Great. We are actually using the same trick in the quarkus repo.

2021-02-19 02:34 UTC, cristianonicolai commented
@danielezonca will a `-process` extension be possible with mix and match to what we currently have aready? Lets say on processes ( no decision ), processes + decisions ( meaning users need to check both extensions? ) and a kogito-qarksu that would still include the entire platform?

2021-02-19 08:46 UTC, danielezonca commented
> @danielezonca will a `-process` extension be possible with mix and match to what we currently have already? Let's say on processes ( no decision ), processes + decisions ( meaning users need to check both extensions? ) and a kogito-quarkus that would still include the entire platform?

Yes the approach is quite flexible each extension can be combined with the others (thanks to common module).
We can easily split and create additional extensions like a process extension or even (not sure if make sense) a serverless workflow specific and a bpmn one (this proposal will probably requires changes in codegen too).
My idea is that in the future we can use this approach to plug different integrations like kogito-lambda or in general kogito-funqy etc.
The only drawback/aspect to consider is that when there are explicit reference from one resource to another (like process code to RuleUnit/DMN classes) we need to add a validation check during codegen to fail if a required feature is not available (and prevent strange runtime exception).

2021-02-19 09:13 UTC, cristianonicolai approved these changes

2021-02-19 13:14 UTC, danielezonca commented
jenkins retest this please

2021-02-21 16:52 UTC, danielezonca commented
jenkins retest this please

2021-02-22 07:43 UTC, danielezonca commented
jenkins retest this please

2021-02-22 19:09 UTC, MarianMacik approved these changes
Looks good, only minor comments.

2021-02-22 19:09 UTC, MarianMacik commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-deployment/src/main/java/org/kie/kogito/quarkus/deployment/ProcessesAssetsProcessor.java
> +            List<KogitoGeneratedClassesBuildItem> generatedKogitoClasses,
How is the order of these BuildSteps defined? Is it guaranteed that this BuildStep will be executed after all processes are created because of the CDI-like dependency on `KogitoGeneratedClassesBuildItem`?

2021-02-22 19:09 UTC, MarianMacik commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-deployment/src/main/java/org/kie/kogito/quarkus/deployment/ProcessesCompilationProvider.java
> +public class ProcessesCompilationProvider extends KogitoCompilationProvider {
So we cannot use just processes extension without other extensions, right? As the process-related generator is a part of the whole `kogito-quarkus-extension`, which in turn pulls decisions, rules and predictions extensions.

2021-02-23 09:27 UTC, danielezonca commented on archetypes/kogito-quarkus-archetype/pom.xml
> +      <type>pom</type>
I think in this way it prevents to download the jar 🤔

2021-02-23 09:53 UTC, danielezonca commented on kogito-quarkus-parent/kogito-quarkus-decisions-extension/kogito-quarkus-decisions/pom.xml
> +        <!-- quarkus -->
No, now all quarkus specific dependencies are centralised in common module

2021-02-23 09:56 UTC, danielezonca commented on kogito-quarkus-parent/kogito-quarkus-decisions-extension/kogito-quarkus-decisions-deployment/src/main/java/org/kie/kogito/quarkus/decisions/deployment/DecisionsCompilationProvider.java
> + * Copyright 2021 Red Hat, Inc. and/or its affiliates.
You are right but to avoid any issue with checkstyle I usually run 
`mvn com.mycila:license-maven-plugin:format`
on the whole modified module so also other files are updated

2021-02-23 10:01 UTC, danielezonca commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-deployment/src/main/java/org/kie/kogito/quarkus/deployment/ProcessesCompilationProvider.java
> +public class ProcessesCompilationProvider extends KogitoCompilationProvider {
Yes for now we only have the "platform" extension `kogito-quarkus` with all the other components. We can also add a process specific extension with the same mechanism. The only problem of splitting processes is to also implement proper validation like if a process invokes a DMN and no dmn extension is provided.

2021-02-23 10:17 UTC, danielezonca commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-deployment/src/main/java/org/kie/kogito/quarkus/deployment/ProcessesAssetsProcessor.java
> +            List<KogitoGeneratedClassesBuildItem> generatedKogitoClasses,
Yes execution order is handled by Quarkus based on dependencies in a CDI-like approach.
Now `KogitoAssetsProcessor` returns a [list of `KogitoGeneratedClassesBuildItem`](https://github.com/kiegroup/kogito-runtimes/blob/41672397d4a4c6d3496ae52a6f1856f8506cc3e0/kogito-quarkus-parent/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java#L69) so this processor is invoked only after that step

2021-02-23 10:26 UTC, danielezonca commented on kogito-quarkus-parent/README.md
> +- `kogito-quarkus-*-extension`: root module an extension
Done

2021-02-23 10:26 UTC, danielezonca commented on kogito-quarkus-parent/kogito-quarkus-extension/kogito-quarkus-integration-test/src/main/java/io/quarkus/it/kogito/jbpm/CalculationService.java
>   * you may not use this file except in compliance with the License.
Done

2021-02-23 13:35 UTC, danielezonca commented
jenkins retest this please

2021-02-23 15:29 UTC, danielezonca commented
jenkins retest this please

2021-02-23 20:12 UTC, danielezonca commented
jenkins retest this please

2021-02-24 07:00 UTC, danielezonca commented
jenkins retest this please

2021-02-24 10:30 UTC, danielezonca commented
jenkins retest this please

2021-02-24 14:00 UTC, msmagnanijr commented
jenkins retest this please

2021-02-24 16:04 UTC, danielezonca commented
jenkins retest this please

2021-02-24 16:55 UTC, danielezonca commented
Timeout...

jenkins retest this please

2021-02-24 19:50 UTC, danielezonca commented
![unnamed](https://user-images.githubusercontent.com/244607/109057380-f67c6a00-76e1-11eb-8059-074d5fb86373.jpg)

2021-02-24 19:51 UTC, merged