KOGITO-4451 - Skip metrics generation for requests coming from explainability addon
kiegroup/kogito-runtimes pull request #1105
Opened 2021-03-01 09:45 UTC by r00ta

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2021-03-02 11:14 UTC, danielezonca approved these changes
Thanks for the PR, approving with minor comments

2021-03-02 11:14 UTC, danielezonca commented on addons/explainability-addon/explainability-addon-common/src/main/java/org/kie/kogito/explainability/DecisionExplainabilityResourceExecutor.java
> +    DecisionModel getDecisionModel(DecisionModels decisionModels, ModelIdentifier modelIdentifier) {
Why not public? Default visibility is rarely useful, I would suggest `protected` at least

2021-03-02 11:14 UTC, danielezonca commented on addons/explainability-addon/explainability-addon-common/src/test/java/org/kie/kogito/explainability/DmnDecisionModelStub.java
> +public class DmnDecisionModelStub extends DmnDecisionModel {
`Stub`?

2021-03-02 14:10 UTC, r00ta commented on addons/explainability-addon/explainability-addon-common/src/test/java/org/kie/kogito/explainability/DmnDecisionModelStub.java
> +public class DmnDecisionModelStub extends DmnDecisionModel {
`DmnDecisionModelSpy` is better, since this is not really a mock

2021-03-05 12:43 UTC, jiripetrlik requested changes
I have some concerns doubts here.

2021-03-05 12:43 UTC, jiripetrlik commented on addons/explainability-addon/explainability-addon-common/src/main/java/org/kie/kogito/explainability/DecisionExplainabilityResourceExecutor.java
> +    protected DecisionModel getDecisionModel(DecisionModels decisionModels, ModelIdentifier modelIdentifier) {
What is the purpose of these changes of method scope. It seems to me unrelated to the topic of PR.

2021-03-05 12:43 UTC, jiripetrlik commented on addons/monitoring/monitoring-core/monitoring-core-common/pom.xml
> +    <dependency>
I think it is in general not a good idea to nest addons one to another. What if user wants to use monitoring addon without any explainability stuff?

2021-03-05 15:28 UTC, r00ta commented on addons/monitoring/monitoring-core/monitoring-core-common/pom.xml
> +    <dependency>
Hi @jiripetrlik , we import the explainability addon just to import a constant. There is no constraint on the usage

2021-03-05 15:29 UTC, r00ta commented on addons/explainability-addon/explainability-addon-common/src/main/java/org/kie/kogito/explainability/DecisionExplainabilityResourceExecutor.java
> +    protected DecisionModel getDecisionModel(DecisionModels decisionModels, ModelIdentifier modelIdentifier) {
Actually it's just a small improvement since there is no need for this method to be public

2021-03-08 15:43 UTC, jiripetrlik commented on addons/explainability-addon/explainability-addon-common/src/main/java/org/kie/kogito/explainability/DecisionExplainabilityResourceExecutor.java
> +    protected DecisionModel getDecisionModel(DecisionModels decisionModels, ModelIdentifier modelIdentifier) {
Understand. It is ok. Just curious if did not overlook something.

2021-03-08 16:23 UTC, r00ta commented on addons/monitoring/monitoring-core/monitoring-core-common/pom.xml
> +    <dependency>
As per chat, I've duplicated the constant and removed the dependency

2021-03-09 07:41 UTC, merged