KOGITO-4581 - Fix template exception handling and refactoring
kiegroup/kogito-runtimes pull request #1113
Opened 2021-03-04 10:56 UTC by r00ta

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2021-03-04 13:11 UTC, tarilabs requested changes
No sorry this is not convincing, I'm pretty sure you are eviscerating `stronglytyped`.

2021-03-04 13:11 UTC, tarilabs commented on kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java
> -
Sorry, no.
I'm pretty sure if you remove this, `stronglytyped` would no longer work.

2021-03-04 13:11 UTC, tarilabs commented on kogito-codegen-modules/kogito-codegen-decisions/src/main/resources/class-templates/DecisionRestResourceQuarkusTemplate.java
> +    public Response dmn($inputType$ variables) {
as above.

2021-03-04 13:11 UTC, tarilabs commented on kogito-codegen-modules/kogito-codegen-decisions/src/main/resources/class-templates/DecisionRestResourceSpringTemplate.java
> +    public ResponseEntity<?> dmn(@RequestBody(required = false) $inputType$ variables,
as above.

2021-03-04 18:50 UTC, r00ta commented
> No sorry this is not convincing, I'm pretty sure you are eviscerating `stronglytyped`.

As clarified by call, switching to `Response` and `ResponseEntity` is not going to break `stronglytyped`. With these changes we remove a bit of complexity and codegen, which is good. 
If anybody sees any problem with these changes, let me know

2021-03-04 18:51 UTC, r00ta commented on kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionRestResourceGenerator.java
> -
See main comment

2021-03-05 10:26 UTC, tarilabs approved these changes
as anticipated within call of https://github.com/kiegroup/kogito-runtimes/pull/1113#issuecomment-790846234
I re-checked with @danielezonca 

It is fine this modification since:
 - we have a orthogonal feature which would render the OAS return information anyway (openapi descriptors)
 - on the long term, for "programmatic API / scaffolding" perspective, it is fine the return type is a bit more opaque (Response instead of Object) so dealing with a REST semantic (Response); if a end-user wants to bind to the java method anyway, it can always make a call to `body` and extract the return payload. Tho it would be more appropriate to get a local client call.

So it is fine to be departing from the previous "requirement" to be "kogito-ergo-domain" in the return type of the java method for the REST call, approving.

2021-03-05 13:32 UTC, r00ta commented
Hi @hellowdan , let me know if you can review this or if another QE should look at it. Thanks!

2021-03-09 08:07 UTC, danielezonca approved these changes

2021-03-09 10:52 UTC, jiripetrlik reviewed
@r00ta 
Would it be possible to add some tests which checks that exceptions are handled correctly and correct exception metrics are provided?

2021-03-09 11:10 UTC, r00ta commented
> @r00ta
> Would it be possible to add some tests which checks that exceptions are handled correctly and correct exception metrics are provided?

Hi @jiripetrlik , I've created this ticket. I'll start working on it as soon as I'm done with other tasks https://issues.redhat.com/browse/KOGITO-4624

2021-03-09 11:18 UTC, jiripetrlik approved these changes
@r00ta 
Thank you for ticket for additional test coverage! Looks good to me.

2021-03-09 12:03 UTC, merged