[KOGITO-4456] - Fix CloudEvents Kogito extension naming
kiegroup/kogito-runtimes pull request #1124
Opened 2021-03-09 21:40 UTC by ricardozanini

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-4456 

In this PR we adjust the extension CloudEvent data to match the required rules from the spec: https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#attribute-naming-convention

I plan to remove the `knative-addon` module in https://issues.redhat.com/browse/KOGITO-4457 (cc @MarianMacik)

@kostola @danielezonca I think you can move your extension properties to the `events-api` as well and verify if the names matches the specification.

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

2021-03-10 09:26 UTC, cristianonicolai commented
@ricardozanini this will break data index, we need to merge the fix together and I will also try to get an IT test to verify this during the buid.

2021-03-10 10:59 UTC, ruromero requested changes
I'd rather prefix extension attributes with `kogito` in order to:
a) avoid conflicts with other extensions
b) easily identify/filter/trace kogito attributes in CloudEvents

2021-03-10 10:59 UTC, ruromero commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String PROCESS_INSTANCE_ID = "procinstanceid";
```suggestion
    public static final String PROCESS_INSTANCE_ID = "kogitoinstanceid";
```

2021-03-10 10:59 UTC, ruromero commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String PROCESS_REFERENCE_ID = "referenceid";
```suggestion
    public static final String PROCESS_REFERENCE_ID = "kogitorefid";
```

2021-03-10 10:59 UTC, ruromero commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String PROCESS_INSTANCE_STATE = "procinstancestate";
```suggestion
    public static final String PROCESS_INSTANCE_STATE = "kogitopistate";
```

2021-03-10 10:59 UTC, ruromero commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String PROCESS_ID = "procid";
```suggestion
    public static final String PROCESS_ID = "kogitopid";
```

2021-03-10 10:59 UTC, ruromero commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String PROCESS_PARENT_PROCESS_INSTANCE_ID = "parentprocinstanceid";
```suggestion
    public static final String PROCESS_PARENT_PROCESS_INSTANCE_ID = "kogitoparentid";
```

2021-03-10 10:59 UTC, ruromero commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String PROCESS_ROOT_PROCESS_INSTANCE_ID = "rootprocinstanceid";
```suggestion
    public static final String PROCESS_ROOT_PROCESS_INSTANCE_ID = "kogitorootinstanceid";
```

2021-03-10 10:59 UTC, ruromero commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String PROCESS_ROOT_PROCESS_ID = "rootprocid";
```suggestion
    public static final String PROCESS_ROOT_PROCESS_ID = "kogitorootid";
```

2021-03-10 10:59 UTC, ruromero commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String PROCESS_START_FROM_NODE = "startfromnode";
```suggestion
    public static final String PROCESS_START_FROM_NODE = "kogitostartfrom";
```

2021-03-10 13:41 UTC, ricardozanini commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String PROCESS_INSTANCE_STATE = "procinstancestate";
> I'd rather prefix extension attributes with `kogito` in order to:

I know, and I thought about that. Hence `kogitopistate` sounds too awkward to me. @cristianonicolai any ideas? We need to stick to 20 characters long.

2021-03-10 14:07 UTC, ricardozanini commented
Guys,

I did a quick search around the terms, and I come up with the following.

Prefix: `kogito`

Names:
- process: `proc` (https://www.acronymfinder.com/Process-(PROC).html)
- instance: `i` (https://www.acronymfinder.com/~/search/af.aspx?string=exact&Acronym=instance)
- reference: `ref` (https://www.acronymfinder.com/Reference-to-(REF).html)
- state: `st` (https://www.acronymfinder.com/State-(ST).html)
- parent: `parent` (can't find a relevant abbreviation for it: https://www.acronymfinder.com/~/search/af.aspx?Acronym=PARENT&string=on)
- root: `root` (can't find any good abbreviation: https://www.acronymfinder.com/~/search/af.aspx?Acronym=Root&string=on)

That put, we can go with:

```
PROCESS_INSTANCE_ID:                kogitoprocinstanceid
PROCESS_REFERENCE_ID:               kogitoprocessrefid
PROCESS_INSTANCE_STATE:             kogitoprocinstancest
PROCESS_ID:                         kogitoprocessid
PROCESS_PARENT_PROCESS_INSTANCE_ID: kogitoparentprociid
PROCESS_ROOT_PROCESS_INSTANCE_ID:   kogitorootprocessiid
PROCESS_ROOT_PROCESS_ID:            kogitorootprocessid
PROCESS_START_FROM_NODE:            kogitoprocstartfrom
ADDONS:                             kogitoaddons
```

@cristianonicolai @ruromero @danielezonca wdyt?

2021-03-10 14:21 UTC, ruromero commented
Thanks @ricardozanini I think that's a better reasoned naming but I'd use the abbreviations everywhere. 

```
PROCESS_INSTANCE_ID:                kogitoprocinstanceid
PROCESS_REFERENCE_ID:               kogitoprocrefid
PROCESS_INSTANCE_STATE:             kogitoprocist
PROCESS_ID:                         kogitoprocid
PROCESS_PARENT_PROCESS_INSTANCE_ID: kogitoparentprociid
PROCESS_ROOT_PROCESS_INSTANCE_ID:   kogitorootprociid
PROCESS_ROOT_PROCESS_ID:            kogitorootprocid
PROCESS_START_FROM_NODE:            kogitoprocstartfrom
ADDONS:                             kogitoaddons
```

If `parent` is too long we can use `dad` and for `root` we can use `√`
`kogitodadprocid`
`kogito√prociid`
:sweat_smile:

2021-03-10 14:27 UTC, ricardozanini commented
@ruromero, once a data architect, told me that we should use the naming if possible and abbreviate if need to. So I took this path, shrug: 

@cristianonicolai asked the same thing.

WDYT?

2021-03-10 14:34 UTC, ricardozanini commented
> @ricardozanini IMO it's easier to remember only abbreviations and not also in which cases they're used but other than that I don't have any strong opinion against one or the other.

I liked the "full abbreviation" approach the better. I'll update the PR. :)

2021-03-12 16:05 UTC, ricardozanini commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/CloudEventExtensionConstants.java
> +    public static final String ADDONS = "kogitoaddons";
I think it makes sense to unify. @kostola mind send a PR to my fork?

2021-03-12 16:06 UTC, ricardozanini commented on addons/events/knative-eventing-addon/src/main/java/org/kie/kogito/events/knative/ce/extensions/KogitoProcessExtension.java
>  public class KogitoProcessExtension implements Extension {
I think we must rename the `KogitoExtension` to maybe `KogitoDecisionExtension` like we have `KogitoProcessExtension`. I'll register `KogitoProcessExtension` in this PR. But it's working as far as I can tell.

2021-03-12 19:08 UTC, ricardozanini commented on addons/events/knative-eventing-addon/src/main/java/org/kie/kogito/events/knative/ce/extensions/KogitoProcessExtension.java
>  public class KogitoProcessExtension implements Extension {
Thinking again, it's better to resolve KOGITO-4457 first. Opened: https://issues.redhat.com/browse/KOGITO-4679

2021-03-15 13:35 UTC, ricardozanini commented
We need to wait for Data Index fix and merge them together. cc @cristianonicolai 
Ideally, `kogito-apps` will depend on `events-api` to use the same property naming. As we discussed in today's meeting, we should have integration tests to break in this scenario. Since we changed the CE events properties, Data Index tests should fail as well.

2021-04-05 12:00 UTC, ricardozanini commented
Jenkins retest this please

Error duo to timeout/infra problems (?)

2021-04-05 12:01 UTC, ricardozanini commented
Jenkins retest this please

2021-04-05 12:03 UTC, ricardozanini commented
Jenkins retest this

2021-04-06 06:17 UTC, cristianonicolai commented
jenkins please retest this

2021-04-06 06:17 UTC, cristianonicolai approved these changes

2021-04-06 06:40 UTC, cristianonicolai commented
jenkins please retest this

2021-04-06 11:24 UTC, cristianonicolai commented
jenkins please retest this

2021-04-06 11:54 UTC, cristianonicolai commented
jenkins please retest this

2021-04-06 13:08 UTC, ricardozanini commented
> jenkins please retest this

Not working :)

2021-04-06 13:11 UTC, ricardozanini commented
Jenkins retest this

2021-04-06 18:57 UTC, ricardozanini commented
Jenkins retest this

2021-04-07 02:31 UTC, cristianonicolai commented
jenkins please retest this

2021-04-07 07:42 UTC, evacchi approved these changes

2021-04-07 17:35 UTC, ricardozanini commented
jenkins run native

2021-04-08 10:38 UTC, cristianonicolai commented
Jenkins run native

2021-04-09 16:33 UTC, ricardozanini commented
> The Native check has **failed**. Please check [the logs](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/pullrequest/job/kogito-runtimes.native/36/console).

It seems a infrastructure problem:

```
java.lang.RuntimeException: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.testcontainers.quarkus.KeycloakQuarkusTestResource@6ea1bcdc
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.kie.kogito.testcontainers.quarkus.KeycloakQuarkusTestResource@6ea1bcdc
Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed
Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=jboss/keycloak:11.0.3, imagePullPolicy=DefaultPullPolicy())
Caused by: org.testcontainers.containers.ContainerFetchException: Failed to get Docker client for jboss/keycloak:11.0.3
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not pull image: write /var/lib/docker/tmp/GetImageBlob011882367: no space left on device
```

2021-04-09 16:34 UTC, ricardozanini commented
Jenkins run native

2021-04-12 02:01 UTC, cristianonicolai commented
Jenkins run native
Jenkins run native

2021-04-12 12:11 UTC, ricardozanini commented
@cristianonicolai this PR is quite critical, I think we should merge before the cut. Error in native not related:

```
java.lang.NullPointerException
	at org.optaplanner.core.impl.score.stream.drools.OptaPlannerRuleEventListener.undoPreviousMatch(OptaPlannerRuleEventListener.java:39)
```

2021-04-12 17:43 UTC, ricardozanini commented
Jenkins run native


OptaPlanner bug has been fixed

2021-04-13 02:46 UTC, merged