KOGITO-4629 - Refactoring KogitoKafkaContainer
kiegroup/kogito-runtimes pull request #1140
Opened 2021-03-15 10:16 UTC by r00ta

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-03-16 08:09 UTC, r00ta commented
Jenkins retest this please

2021-03-16 10:29 UTC, r00ta commented
Jenkins retest this please

2021-03-16 16:42 UTC, r00ta commented
Jenkins retest this please

2021-03-17 08:17 UTC, r00ta commented
Jenkins retest this please

2021-03-17 13:39 UTC, r00ta commented
Jenkins retest this please

2021-03-17 13:55 UTC, r00ta commented
Jenkins retest this please

2021-03-17 16:36 UTC, jstastny-cz requested changes
Please consider more general naming of the image property.

2021-03-17 16:36 UTC, jstastny-cz commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +            <container.image.confluent.kafka>${container.image.confluent.kafka}</container.image.confluent.kafka>
please call the property more general: 'container.image.kafka' , we might want to use also different distribution than confluent and this naming would be misleading.

2021-03-17 16:36 UTC, jstastny-cz commented on kogito-build-parent/pom.xml
> +    <container.image.confluent.kafka>confluentinc/cp-kafka:${version.org.confluent.kafka}</container.image.confluent.kafka>
Here it would be fine to keep the version-property naming even after renaming to `container.image.kafka` I think.

2021-03-18 02:37 UTC, cristianonicolai commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +            <container.image.confluent.kafka>${container.image.confluent.kafka}</container.image.confluent.kafka>
+1 to drop confluent from the naming

2021-03-18 07:34 UTC, r00ta commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +            <container.image.confluent.kafka>${container.image.confluent.kafka}</container.image.confluent.kafka>
@jstastny-cz @cristianonicolai for the current implementation that uses `KafkaContainer` only confluent images are allowed, that's why I called the property `confluent.kafka`: it's not possible to use strimzi for example.  
Do you think it's still the case to call the property `container.image.kafka`?

2021-03-18 08:06 UTC, jstastny-cz commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +            <container.image.confluent.kafka>${container.image.confluent.kafka}</container.image.confluent.kafka>
I understand the naming now, I think we can either keep it with the plan to rename the property when a general support for arbitrary Kafka images is introduced (I think it's inevitable in near future). Or name it more generally so that the changes later are scoped just to the container implementation change (still planned as https://issues.redhat.com/browse/KOGITO-4707).
I would prefer the latter option, but let's get some consensus, I am not that strongly opinionated.

2021-03-18 09:43 UTC, cristianonicolai commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +            <container.image.confluent.kafka>${container.image.confluent.kafka}</container.image.confluent.kafka>
although it makes sense why you went with that naming, I still think we should focus on the functionality it provides, so if tomorrow is another container, we would still keep the same name.

2021-03-24 08:17 UTC, r00ta commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +            <container.image.confluent.kafka>${container.image.confluent.kafka}</container.image.confluent.kafka>
Renamed `container.image.kafka`

2021-03-24 08:18 UTC, r00ta commented
Hi @cristianonicolai @jstastny-cz do you mind having a final look?

2021-03-24 08:20 UTC, r00ta commented
Jenkins retest this please

2021-03-24 08:22 UTC, r00ta commented
Jenkins retest this please

2021-03-24 09:10 UTC, jstastny-cz approved these changes
LGTM.

2021-03-24 09:44 UTC, r00ta commented
Jenkins retest this please

2021-03-24 13:37 UTC, cristianonicolai approved these changes

2021-03-25 07:34 UTC, r00ta commented
Jenkins retest this please

2021-03-25 12:15 UTC, r00ta commented
Jenkins retest this please

2021-03-26 17:54 UTC, r00ta commented
Jenkins retest this please

2021-03-29 09:55 UTC, r00ta commented
Jenkins retest this please

2021-03-29 12:23 UTC, r00ta commented
Jenkins retest this please

2021-03-30 06:37 UTC, r00ta commented
Jenkins retest this please

2021-03-30 06:38 UTC, r00ta commented
Jenkins retest this please

2021-04-01 16:35 UTC, merged