KOGITO-4809 Delegate Process REST to a class
kiegroup/kogito-runtimes pull request #1195
Opened 2021-04-05 21:05 UTC by tiagodolphine

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-04-05 21:23 UTC, tiagodolphine commented
@evacchi @fjtirado this is WIP but this is more or less what I was thinking...  here is an example of the generated code
https://gist.github.com/tiagodolphine/3ac3d80b3cce3d5e28c19dd509d66b71

Comments, suggestions, ideas on how to improve?

2021-04-06 14:53 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +    public <T extends Model> Optional<ProcessInstance<T>> signalTask(Process<T> process, String id, String taskNodeName) {
It wont be better if signalTask just return the Task (that will make the template shorter)

2021-04-06 14:55 UTC, fjtirado commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceUserTaskQuarkusTemplate.java
> +        return processService.signalTask(process, id, "$taskNodeName$")
If ProcessService.signalTask returns Optional<WorkItem> the generated code will shorter

2021-04-06 14:58 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +public class ProcessService {
This should be an interface, isnt it?

2021-04-06 15:05 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +                .map(comments -> comments.get(commentId));
This is style, but in this case Im not sure three map invocations is better (in terms of performance and readability) than one map with pi-> HumanTaskHelper.findTask(pi, taskId, Policies.of(user, groups)).getComments().get(commentId)

2021-04-06 15:08 UTC, fjtirado commented
Great proposal Tiago!

My only concern is the number of method we are going to have in ProcessService class can be potentially long. 
Also I'm not sure if, to keep the template even shorter, it will be better to avoid returning optional and throwing the exception from ProcessService and use Exception handler in quarkus and springboot to generate the right HTTP response.

2021-04-06 15:11 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +                .map(pi -> pi.variables())
Im maybe missing something, but If pi.variables returns T and MappableToModel also returns T, what's the point of invoking toModel over the value returned by pi.variables?

2021-04-14 08:47 UTC, evacchi reviewed
I left some comments

2021-04-14 08:47 UTC, evacchi commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +                application,
`addPhases` uses `application` only for `application.config().get(ProcessConfig.class).workItemHandlers().forName("Human Task")`; we can pass the `KogitoWorkItemHandler` to  `getSchemaAndPhases()` directly.

Then instead of `application` this class can be given just the `unitOfWorkManager`

2021-04-14 08:47 UTC, evacchi commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +            return pi;
I've been thinking that we may add a `ProcessInstance#start(nodeId)` method and if nodeId == null then we can start from the initial node, and remove this if

```
            ProcessInstance<T> pi = process.createInstance(businessKey, model);
            pi.start(startFromNodeId);
```

alternatively, we can just use startFrom:

```
            ProcessInstance<T> pi = process.createInstance(businessKey, model);
            pi.startFrom(startFromNodeId);
```

2021-04-14 08:47 UTC, evacchi commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +                .map(pi -> pi.variables())
from the usages that could be an outputModel
BTW this can be rewritten as:

```
                .map(ProcessInstance::variables)
                .map(MappableToModel::toModel) 
                .findFirst(); <-- return optional : we only have at most 1 (right?)
```

however, we could let `variables()` accept a `Class<T>` then we could turn this into:


```
                .map(pi -> pi.variables(TheModelType.class))
                .findFirst(); <-- return optional : we only have at most 1 (right?)
```

2021-04-14 08:47 UTC, evacchi commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +        return UnitOfWorkExecutor.executeInUnitOfWork(application.unitOfWorkManager(), () -> {
first thing that comes to mind: I think if we can create a CDI interceptor (@UnitOfWork) that wraps the body inside `executeInUnitOfWork.`

2021-04-14 08:47 UTC, evacchi commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +    }
I have ideas on how we could refactor task-related methods into a different class but I'll write this separately

2021-04-15 09:00 UTC, evacchi commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +                .map(pi -> pi.variables())
I just realized that getProcessInstanceOutput and findById are pretty much identical...

2021-04-19 20:19 UTC, tiagodolphine commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +    public <T extends Model> Optional<ProcessInstance<T>> signalTask(Process<T> process, String id, String taskNodeName) {
:+1:

2021-04-19 20:22 UTC, tiagodolphine commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +public class ProcessService {
done

2021-04-19 20:24 UTC, tiagodolphine commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +                .map(comments -> comments.get(commentId));
well I prefer the mapping for readability but this is just a preference but it avoids null checks.. anyway this is minor IMO.

2021-04-19 20:27 UTC, tiagodolphine commented
> Great proposal Tiago!
> 
> My only concern is that the number of methods we are going to have in ProcessService class might be potentially long.
> Also I'm not sure if, to keep the template even shorter, it will be better to not use Optional as return value (we can keep its usage inside ProcessService), throw exception from ProcessService instead and add specific Exception handler in quarkus and springboot to generate the error HTTP response.
> So, in the template we just have return processService.findTask(id); and NotFoundException thrown by findTask being handled in a hardcoded ExcepcionMapper (actually this is already the case for Quarkus, we just need to add exception mapper to SpringBoot) wdty?

Agree, but this is just the first step, to improve the APIs, the idea is to continue this work with subsequent PRs, the ProcessService probably will be removed and actions / methods we have there incorporated into the classes responsible for each domain, like Process WorkItem etc.. @evacchi FYI

2021-04-19 21:05 UTC, tiagodolphine commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +                .map(pi -> pi.variables())
we can change the methods names btw, I just kept the same as they were in the endpoints.

2021-04-19 21:10 UTC, tiagodolphine commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +                application,
:+1:

2021-04-19 21:20 UTC, tiagodolphine commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +            return pi;
Agree, don't know if it is worth refactoring in this PR, because this requires changing different places using this API, I just moved the same logic we had in the endpoints... I'll take a look, just want to avoid this PR becoming too big...

2021-04-19 21:23 UTC, tiagodolphine commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +        return UnitOfWorkExecutor.executeInUnitOfWork(application.unitOfWorkManager(), () -> {
yeah.. something like JTA... but don't know.. so why not just using JTA? anyway I think we should keep the scope of the PR just to delegate and open a JIRA to review the usage of UnitOfWork, wdyt @evacchi ?
@cristianonicolai ^

2021-04-19 21:27 UTC, tiagodolphine commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/ProcessService.java
> +    }
yeah, sure, as we already talked we could handle all task/workitem related stuff in the workitem itself (probably become a unit) and the information about security could be abstracted to a context that could be accessed in any place.. like using Quarkus SecurityIdentity https://quarkus.io/guides/security, anyway there are quite a lot of things we can improve, but anyway let's try to keep this PR just focused in the delegate.

2021-04-21 11:57 UTC, fjtirado approved these changes

2021-04-21 12:50 UTC, cristianonicolai approved these changes
@tiagodolphine looks really good, just some minor comments

2021-04-21 12:50 UTC, cristianonicolai commented on kogito-codegen-modules/kogito-codegen-integration-tests/pom.xml
> +            <version>2.0.1.Final</version>
would be best to move these to version management in build pom.

2021-04-21 12:50 UTC, cristianonicolai commented on kogito-codegen-modules/kogito-codegen-integration-tests/pom.xml
> +            <version>2.0</version>
would be best to move these to version management in build pom.

2021-04-21 12:50 UTC, cristianonicolai commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessResourceGenerator.java
> +            //TODO: remove from template
@tiagodolphine should we have a follow-up JIRA or just going to do in another PR?

2021-04-23 16:48 UTC, MarianMacik commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/ReactiveRestResourceQuarkusTemplate.java
>                              } else {
Can't we use the ProcessService in this template as well?

2021-04-23 16:48 UTC, MarianMacik commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceQuarkusTemplate.java
>      Application application;
I guess we don't need this anymore?

2021-04-23 16:48 UTC, MarianMacik commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSpringTemplate.java
>      Application application;
Same here?

2021-04-23 16:48 UTC, MarianMacik commented on kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/CodegenUtils.java
> +    public static boolean isInjectableField(FieldDeclaration fd) {
Is this used anywhere?

2021-04-26 08:41 UTC, evacchi commented
this is green, Tiago is away; I'd respin the build just to be safe, but I'd merge it otherwise it may conflict soon.

jenkins please retest this

2021-04-26 08:41 UTC, evacchi approved these changes

2021-04-26 09:03 UTC, MarianMacik commented
@evacchi Just bear in mind there are unaddressed reviews from me and Cristiano.

2021-04-26 09:19 UTC, fjtirado commented
@evacchi I think is better wait for @tiagodolphine to come back and just add the comments from Marian and do small rebase related with https://github.com/kiegroup/kogito-runtimes/pull/1217

2021-05-03 11:55 UTC, tiagodolphine commented
I'll rebase because there are some conflicts in the templates.. probably I need to do some refactoring after the rebase... anyway I'll let you know when this is updated + apply the missing comments.
Thanks.

2021-05-04 13:28 UTC, tiagodolphine commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessResourceGenerator.java
> +            //TODO: remove from template
removing, it was a real todo in the PR, I missed it.

2021-05-04 13:28 UTC, tiagodolphine commented on kogito-codegen-modules/kogito-codegen-integration-tests/pom.xml
> +            <version>2.0</version>
removed, this was just used during the dev phase...

2021-05-04 13:28 UTC, tiagodolphine commented on kogito-codegen-modules/kogito-codegen-integration-tests/pom.xml
> +            <version>2.0.1.Final</version>
removed, this was just used during the dev phase...

2021-05-04 13:29 UTC, tiagodolphine commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceQuarkusTemplate.java
>      Application application;
+1, I forgot to remove this

2021-05-04 13:29 UTC, tiagodolphine commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSpringTemplate.java
>      Application application;
+1, I forgot to remove this

2021-05-04 13:31 UTC, tiagodolphine commented on kogito-codegen-modules/kogito-codegen-core/src/main/java/org/kie/kogito/codegen/core/CodegenUtils.java
> +    public static boolean isInjectableField(FieldDeclaration fd) {
+1, I forgot to remove this

2021-05-04 13:52 UTC, tiagodolphine commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/ReactiveRestResourceQuarkusTemplate.java
>                              } else {
done

2021-05-04 13:53 UTC, tiagodolphine commented
@MarianMacik PR updated with your comments + rebased with master

2021-05-04 14:38 UTC, fjtirado requested changes
A small problem when rebasing, the return value of getTasks API

2021-05-04 14:38 UTC, fjtirado commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/ReactiveRestResourceQuarkusTemplate.java
>      public CompletionStage<List<WorkItem>> getTasks_$name$(@PathParam("id") String id,
This should return a list of TaskModel instance (a subset of WorkItem parameters)

2021-05-05 10:35 UTC, fjtirado approved these changes
Great work Tiago

2021-05-06 13:16 UTC, cristianonicolai commented
@MarianMacik good with you?

2021-05-11 06:19 UTC, merged

2021-05-12 13:54 UTC, MarianMacik commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceQuarkusTemplate.java
>      Application application;
@tiagodolphine I see this still present here, is it needed?