[WIP] Pom improvements
kiegroup/kogito-runtimes pull request #1210
Opened 2021-04-08 13:06 UTC by danielezonca

- Created `kogito-build` module to contain `kogito-build-parent` and `kogito-ide-config`
- Removed many unused dependencies from dependency management
- Removed some platform specific dependencies to reduced kogito core "footprint": we had multiple dependencies declared in kogito-built-parent that are platform specific (i.e. kafka version or restAssured) and that are already overridden by importing quarkus-bom/spring-dependencies
- Removed dependencies used only in `kogito-apps` (to be moved there as part of this PR)

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-04-08 13:29 UTC, evacchi approved these changes
beautiful cleanup. Let's hope CI is green

2021-04-13 08:40 UTC, danielezonca commented
jenkins retest this please

2021-04-20 03:22 UTC, cristianonicolai commented on kogito-build/pom.xml
> +        <activeByDefault>true</activeByDefault>
@danielezonca dont we have to avoid this active by default because of IntelliJ?

2021-04-20 12:42 UTC, danielezonca commented on kogito-build/pom.xml
> +        <activeByDefault>true</activeByDefault>
My bad, I originally created this PR before that change so fixed now 👍

2021-04-21 15:39 UTC, danielezonca commented
jenkins retest this please

2021-04-22 10:14 UTC, danielezonca commented
jenkins retest this please

2021-04-22 20:46 UTC, danielezonca commented
jenkins retest this please

2021-04-26 08:51 UTC, evacchi commented
@danielezonca conflict

2021-04-29 12:36 UTC, danielezonca commented
jenkins retest this please

2021-05-03 10:28 UTC, danielezonca commented
jenkins retest this please

2021-05-03 12:28 UTC, danielezonca commented
Network problem

jenkins retest this please

2021-05-03 16:36 UTC, danielezonca commented
jenkins retest this please

2021-05-04 07:52 UTC, danielezonca commented
jenkins retest this please

2021-05-04 08:39 UTC, evacchi approved these changes

2021-05-04 09:40 UTC, jstastny-cz commented on integration-tests/integration-tests-springboot/pom.xml
> -    <dependency>
Is it safe to remove these? I've explicitly added these test deps for maven reactor to be in order: https://github.com/kiegroup/kogito-runtimes/pull/1188/files#diff-48f36d228f186a4252f88c2ebd6cdc3500608ea5117846970543a58b2ced7e9b

2021-05-04 09:45 UTC, jstastny-cz requested changes
I am mostly concerned about invoker-based tests - there are removals of explicit test dependencies that make sure reactor is in good shape (to assure deps of src/it projects are in reactor and not relying on previously released snapshots in some repository). I think here we're about to reach the situation of not being able to run full build in env detached from our nexus (like quarkus CI for example).

2021-05-05 16:41 UTC, danielezonca commented on integration-tests/integration-tests-springboot/pom.xml
> -    <dependency>
You are right, restored 👍

2021-05-06 07:55 UTC, danielezonca commented
jenkins retest this please

2021-05-07 07:46 UTC, danielezonca commented
@jstastny-cz 
Can you please review again?

2021-05-11 07:26 UTC, cristianonicolai approved these changes

2021-05-11 07:26 UTC, cristianonicolai commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-norest-it/pom.xml
> -            <!-- Manually override to 3.3.0 because Spring boot uses rest-assured-common internally -->
@danielezonca if we remove this, what version would be pick? or is just that versions are aligned and this is not needed any more.

2021-05-11 07:48 UTC, danielezonca commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-norest-it/pom.xml
> -            <!-- Manually override to 3.3.0 because Spring boot uses rest-assured-common internally -->
RestAssured is both declared in `quarkus-bom` and in `spring-boot-dependencies` so the compatible version is automatically provided with the platform: "kogito-core" doesn't really need RestAssured, it is only required to perform e2e test on a specific platform so in this way everything works automatically (same apply to kafka dependency)

2021-05-11 07:53 UTC, cristianonicolai commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-norest-it/pom.xml
> -            <!-- Manually override to 3.3.0 because Spring boot uses rest-assured-common internally -->
makes sense, thanks

2021-05-11 12:03 UTC, danielezonca commented
jenkins retest this please

2021-05-13 09:49 UTC, danielezonca commented
jenkins retest this please

2021-05-13 14:16 UTC, danielezonca commented
jenkins retest this please

2021-05-15 06:57 UTC, merged

2021-05-18 19:08 UTC, manstis commented
Did I miss the email communicating the move of the IDE configuration files?

2021-05-18 20:46 UTC, danielezonca commented
> Did I miss the email communicating the move of the IDE configuration files?

You are right, it took ages to get a green build and when I merged it I forgot to update the team, email sent now :)