[BXMSPROD-1208] added community vs prod modules activation profile
kiegroup/kogito-runtimes pull request #1244
Opened 2021-04-21 17:21 UTC by mareknovotny

This PR is trying to fix [issue](https://youtrack.jetbrains.com/issue/IDEA-266880) in Intellij IDEA where modules in profiles cannot be loaded even the profile is activated by default. The original jira where the profile(s) where created 

https://issues.redhat.com/browse/BXMSPROD-1208

- [X ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [X] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [X ] Pull Request contains description of the issue
- [X] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-04-22 09:35 UTC, mareknovotny commented
hmm, timeout `Timeout has been exceeded` after 10 hours and last step it seems docker image pulling.

jenkins retest this please

2021-04-22 10:26 UTC, Ginxo requested changes
please check

2021-04-22 10:26 UTC, Ginxo commented on pom.xml
> +        <module>kogito-codegen-modules</module>
according to previous configuration `kogito-codegen-modules` should be included on the productization build. still valid?

2021-04-22 10:56 UTC, mareknovotny commented on pom.xml
> +        <module>kogito-codegen-modules</module>
updated

2021-04-23 06:55 UTC, mareknovotny commented
```
08:54:33,968 [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:yarn (yarn test) on project kogito-apps-ui-packages: Failed to run task: 'yarn run test --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

jenkins retest this please

2021-04-23 12:26 UTC, lucamolteni commented
@mareknovotny is this the backport? for https://github.com/kiegroup/kogito-runtimes/pull/1245 ? I assumed yes :)

2021-04-23 12:27 UTC, lucamolteni approved these changes

2021-04-23 13:00 UTC, mareknovotny commented
> @mareknovotny is this the backport? for #1245 ? I assumed yes :)

sort of, as 1.5.x branch change was not reverted it is not very the same.

2021-04-23 13:13 UTC, mareknovotny commented
failed `org.kie.kogito.integrationtests.springboot.PingPongMessageTest.testPingPongBetweenProcessInstances`

2021-04-23 13:13 UTC, mareknovotny commented
jenkins retest this please

2021-04-26 07:07 UTC, mareknovotny commented
jenkins retest this please

2021-04-26 09:49 UTC, mareknovotny commented
Now it fails due yarn install cmd in kogito-apps repo :(
```
05:22:52,897 [INFO] ------------------------------------------------------------------------
05:22:52,898 [INFO] BUILD FAILURE
05:22:52,898 [INFO] ------------------------------------------------------------------------
05:22:52,898 [INFO] Total time:  45:12 min
05:22:52,898 [INFO] Finished at: 2021-04-26T05:22:52-04:00
05:22:52,898 [INFO] ------------------------------------------------------------------------
05:22:52,900 [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:yarn (yarn test) on project kogito-apps-ui-packages: Failed to run task: 'yarn run test --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
05:22:52,901 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.2:verify (default) on project integration-tests-data-index-service-quarkus: There are test failures.
05:22:52,901 [ERROR] 
05:22:52,901 [ERROR] Please refer to /home/jenkins/workspace/KIE/kogito/pullrequest/kogito-runtimes/kogito-apps/apps-integration-tests/integration-tests-data-index-service/integration-tests-data-index-service-quarkus/target/failsafe-reports for the individual test results.
05:22:52,902 [ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
05:22:52,902 [ERROR] -> [Help 1]
05:22:52,902 [ERROR] 
05:22:52,902 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
05:22:52,902 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
05:22:52,902 [ERROR] 
05:22:52,902 [ERROR] For more information about the errors and possible solutions, please read the following articles:
05:22:52,903 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
05:22:52,903 [ERROR] 
05:22:52,903 [ERROR] After correcting the problems, you can resume the build with the command
05:22:52,903 [ERROR]   mvn <args> -rf :kogito-apps-ui-packages
```

2021-04-26 12:21 UTC, mareknovotny commented
jenkins retest this

2021-04-27 07:39 UTC, mareknovotny commented
hanged while in kogito-apps integration tests

jenkins retest this please

2021-04-27 15:29 UTC, almope commented
jenkins retest this

2021-04-28 06:13 UTC, merged