[WIP] GitHub Action improvements
kiegroup/kogito-runtimes pull request #1292
Opened 2021-05-07 09:51 UTC by danielezonca

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-05-10 12:36 UTC, Ginxo requested changes
please check

2021-05-10 12:36 UTC, Ginxo commented on .github/workflows/apps-pr.yml
> +        uses: kiegroup/github-action-build-chain@v2.4
```suggestion
        uses: kiegroup/github-action-build-chain@v2.5.4
```

2021-05-10 12:36 UTC, Ginxo commented on .github/workflows/ci-pr.yml
> +        uses: kiegroup/github-action-build-chain@v2.4
```suggestion
        uses: kiegroup/github-action-build-chain@v2.5.4
```

2021-05-10 12:36 UTC, Ginxo commented on .github/workflows/examples-pr.yml
> +        uses: kiegroup/github-action-build-chain@v2.4
```suggestion
        uses: kiegroup/github-action-build-chain@v2.5.4
```

2021-05-10 12:36 UTC, Ginxo commented on .github/workflows/optaplanner-pr.yml
> +        uses: kiegroup/github-action-build-chain@v2.4
```suggestion
        uses: kiegroup/github-action-build-chain@v2.5.4
```

2021-05-12 12:53 UTC, radtriste commented
do we really want to run all 4 in parallel ? this is quite resources consuming and we are already limited on resources for GHAction ...

2021-05-12 12:53 UTC, radtriste commented
do we really want to run all 4 in parallel ? this is quite resources consuming and we are already limited on resources for GHAction ...
But I do like the idea :)

2021-05-12 16:01 UTC, danielezonca commented
> do we really want to run all 4 in parallel ? this is quite resources consuming and we are already limited on resources for GHAction ...
> But I do like the idea :)

It is true that it creates more builds but the aggregated execution time is similar: the overhead of each `compile install -DskipTests` for upstream repos of each job is like ~5 minutes.
In this way each build is way faster and even more important lightweight in terms of disk usage so I don't need anymore to cleanup the executor as first step (quite error prone script because it prevents us to simply take `ubuntu-latest`).
I would like to try this setup and see if it is stable, if so we can consider to partially merge them again (I think it could make sense only for OptaPlanner + Runtimes 🤔 )

2021-05-13 17:30 UTC, merged