[WIP] Move all kie7 dependencies to kogito-kie7-bom
kiegroup/kogito-runtimes pull request #1329
Opened 2021-05-21 11:40 UTC by danielezonca

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-05-24 12:55 UTC, danielezonca commented on kogito-build/kogito-kie7-bom/pom.xml
> +    </properties>
This BOM is intended to group and version kie7 artifacts so that the perimeter is clearly defined. This required to create an "independented" and standalone module (that can be reused also by OptaPlanner for example) that is not inheriting from `kogito-build-parent` (otherwise it will also take all dependencyManagement). 
The consequence of this is that `version.org.kie7` property is defined here.
@mareknovotny 
Wdyt?

2021-05-24 14:13 UTC, danielezonca commented
jenkins retest this please

2021-05-25 08:03 UTC, almope approved these changes

2021-05-25 08:12 UTC, Ginxo requested changes
please check my comments

2021-05-25 08:12 UTC, Ginxo commented on kogito-build/kogito-kie7-bom/pom.xml
> +    </properties>
@danielezonca @mareknovotny 
I totally understand the purpose for having `7` on the artifactId and `version.org.kie7` property, but I'm not totally sure this is right. What if we don't heritage version from parent and we force `kogito-kie-bom` to be the one from kie projects? :thinking: This way we won't have to change artifactId in case we want to just point to a different kie version.

2021-05-25 08:12 UTC, Ginxo commented on kogito-build/kogito-kie7-bom/pom.xml
> +
empty line to remove

2021-05-25 08:12 UTC, Ginxo commented on kogito-build/kogito-kie7-bom/pom.xml
> +
empty line to remove

2021-05-25 08:12 UTC, Ginxo commented on kogito-build/kogito-kie7-bom/pom.xml
> +
empty line to remove

2021-05-25 08:12 UTC, Ginxo commented on kogito-build/kogito-kie7-bom/pom.xml
> +
empty line to remove

2021-05-25 08:43 UTC, danielezonca commented on kogito-build/kogito-kie7-bom/pom.xml
> +    </properties>
What do you mean?
Some artifacts has a different GAV (org.kie.kogito instead of org.drools) on purpose because they are designed to only work in kogito and viceversa.
Some other will be removed in the future (for example I expect `kie-api` will be removed or at least massively changed).
In general we don't want to include all kie7 artifacts because only few of them (mainly from drools.git repo) are necessary so we cannot reuse existing kie-bom or similar.
It is not clear to me what you are proposing 🤔

2021-05-25 09:13 UTC, evacchi commented on kogito-build/kogito-kie7-bom/pom.xml
> +    </properties>
I think the question is only if having a number in the artifactId ("7") is correct :) I don't think it's an issue

2021-05-25 09:14 UTC, evacchi approved these changes
Let's not forget to update the script at https://github.com/kiegroup/kogito-pipelines/blob/master/tools/update-kie7-versions.sh

2021-05-25 09:26 UTC, Ginxo commented on kogito-build/kogito-kie7-bom/pom.xml
> +    </properties>
@danielezonca it's exactly what @evacchi means. It's not an issue, just wondering whether this `7` should be there or not. If you all agree it is good to keep it there I totally agree with it.

2021-05-25 09:49 UTC, AntStephenson approved these changes
LGTM

2021-05-25 11:16 UTC, ge0ffrey commented on kogito-build/kogito-kie7-bom/pom.xml
> +        <dependencies>
Can we add a comment to note that this bom is a user bom, so it can not import other groupId's than org.kie and org.drools?
```suggestion
        <dependencies>
           <!-- This bom can only import dependencies from the groupId's org.kie and org.drools. -->
```

2021-05-25 11:16 UTC, ge0ffrey approved these changes

2021-05-25 11:56 UTC, radtriste approved these changes

2021-05-25 12:21 UTC, danielezonca commented
> Let's not forget to update the script at https://github.com/kiegroup/kogito-pipelines/blob/master/tools/update-kie7-versions.sh

Done https://github.com/kiegroup/kogito-pipelines/pull/175

2021-05-25 12:21 UTC, danielezonca commented on kogito-build/kogito-kie7-bom/pom.xml
> +        <dependencies>
Done 👍

2021-05-25 12:21 UTC, danielezonca commented on kogito-build/kogito-kie7-bom/pom.xml
> +
Done 👍

2021-05-25 12:21 UTC, danielezonca commented on kogito-build/kogito-kie7-bom/pom.xml
> +
Done 👍

2021-05-25 12:21 UTC, danielezonca commented on kogito-build/kogito-kie7-bom/pom.xml
> +
Done 👍

2021-05-25 12:21 UTC, danielezonca commented on kogito-build/kogito-kie7-bom/pom.xml
> +
Done 👍

2021-05-25 12:46 UTC, mareknovotny commented on kogito-build/kogito-kie7-bom/pom.xml
> +    </properties>
well, if that is really only Drools it should be mentioned there instead of kie as that is more than drools.

2021-05-25 12:51 UTC, danielezonca commented on kogito-build/kogito-kie7-bom/pom.xml
> +    </properties>
Ah ok thanks for the clarification, I would prefer to keep the `7` explicit, even because this will probably be removed in the future together with Drools8.
For example OptaPlanner already has both 7 and 8 versions so its "latest" artifacts should not be never included in this bom. That's why I think `kogito-kie-bom` name is more misleading

2021-05-25 12:52 UTC, Ginxo approved these changes
LGTM

2021-05-25 12:54 UTC, danielezonca commented on kogito-build/kogito-kie7-bom/pom.xml
> +    </properties>
@mareknovotny 
It is `drools.git` repo mainly but that repo contains DMN, PMML and test scenario runner too for example so `kogito-drools-bom` is still misleading from my point of view

2021-05-26 12:09 UTC, merged