[KOGITO] kie v7 legacy API for Kogito
kiegroup/kogito-runtimes pull request #1347
Opened 2021-06-03 16:55 UTC by mariofusco

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/KieBase.java
> +public interface KieBase extends org.kie.api.KieBase {
I would prefer to duplicate methods we want to expose instead of extends kie7 `KieBase`. Wdyt?

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/KieSession.java
> +public interface KieSession extends org.kie.api.runtime.KieSession {
I would prefer to duplicate methods we want to expose instead of extends kie7 `KieSession`. Wdyt?

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieBaseImpl.java
> +    }
Do we really need this method? I don't think we plan to support the possibility to get a Process out of a KieBase

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
Please remove this method, as far as I can see it has only one usage that can be removed (see my other comment about `SessionUnit`)

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
If we avoid to extend kie7 `KieSession` we can get rid of this method

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
Are `Channel` something we want to preserve?

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
Same question for `LiveQuery`

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    public <T> T execute(Command<T> command) {
I'm not sure we want to preserve `execute` method but at least let's improve it using `ExecutableCommand` interface :)
```suggestion
    public <T> T execute(ExecutableCommand<T> command) {
```

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
To be removed

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
To be removed

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +        return delegate.getWorkItemManager();
To be removed

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
Are signal process specific? As far as I know yes so we should remove these methods

2021-06-04 12:32 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
Is this something we want to preserve? As far as I can see it only defines a [`close` method](https://github.com/kiegroup/droolsjbpm-knowledge/blob/master/kie-api/src/main/java/org/kie/api/logger/KieRuntimeLogger.java) so user has to downcast to impl to use it. I think we can take the opportunity to hide this method (I expect it is used only internally and it is in the public API by mistake)

2021-06-04 13:39 UTC, evacchi requested changes
I stopped +1'ing @danielezonca's comments at some point, but I agree with most of them

2021-06-04 13:39 UTC, evacchi commented on api/kogito-legacy-api/pom.xml
> +  <description>The Kogito public API which is backwards compatible between releases.</description>
we may consider using the enforcer plugin to ban some unwanted dependencies from v7 (to avoid mistakes) ; eg see https://github.com/kiegroup/kogito-runtimes/pull/1299/files#diff-92ea472a232268fb2f2f19a43781426b6a32b255ff6c0666f6d5b4967899ada1R25-R57

2021-06-04 13:39 UTC, evacchi commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/KieSession.java
> +public interface KieSession extends org.kie.api.runtime.KieSession {
My question is different, why are we extending if it is legacy? Shouldn't we just use the original one? I mean as user, I would probably expect to import from the same namespace; WDYT?

2021-06-04 13:39 UTC, evacchi commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieBaseImpl.java
> +    }
- +1 throw UnsupportedOperationException() for all process-related methods
- we may also want to throw for all methods that alter the state of the session, such as removeRule() etc.

2021-06-04 13:39 UTC, evacchi commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    public <T> T execute(Command<T> command) {
+1 to throw UOE

2021-06-04 13:39 UTC, evacchi commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +        delegate.registerChannel(s, channel);
I think we should also take the opportunity to throw UOE for other methods such as this one, getCalendars() or getEnvironment() etc ?

2021-06-04 13:39 UTC, evacchi commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
+1

2021-06-04 13:39 UTC, evacchi commented on kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/SessionRuleUnitJavaTemplate.java
> +        return new SessionRuleUnitInstance(this, memory, ((org.kie.kogito.legacy.rules.impl.KieSessionImpl) runtimeBuilder.newKieSession("$SessionName$")).getDelegate());
Yes I agree. I think it would make sense one such class for "soft" migration between legacy and "new" use cases, but it still makes sense to revisit it

2021-06-04 13:56 UTC, mariofusco commented on kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/SessionRuleUnitJavaTemplate.java
> +        return new SessionRuleUnitInstance(this, memory, ((org.kie.kogito.legacy.rules.impl.KieSessionImpl) runtimeBuilder.newKieSession("$SessionName$")).getDelegate());
@danielezonca I'm not sure it makes sense to move `SessionRuleUnitInstance` to the `legacy-api` module. That was indeed an attempt to wrap a session into a rule unit, but if you want to use the legacy API, by definition you don't want to use the rule unit imo.

2021-06-04 14:12 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-rules/src/main/resources/class-templates/SessionRuleUnitJavaTemplate.java
> +        return new SessionRuleUnitInstance(this, memory, ((org.kie.kogito.legacy.rules.impl.KieSessionImpl) runtimeBuilder.newKieSession("$SessionName$")).getDelegate());
Well it is still part of the "legacy" API because it is a wrapper that help the migration. Said differently user cannot use `SessionRuleUnitInstance` if he is using `unit` API so from my point of view we can drop it or move in the legacy module

2021-06-04 15:26 UTC, evacchi commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/KogitoBuildContext.java
> +    boolean hasLegacyApi();
this is specific to rules, and yet it goes on a public API on the shared class. Not great

2021-06-04 15:35 UTC, mariofusco commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/KogitoBuildContext.java
> +    boolean hasLegacyApi();
Not sure I understand this, do we have an equivalent of the `KogitoBuildContext` specific only for rules?

2021-06-04 15:38 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieBaseImpl.java
> +    }
Can you move all unsupported methods at the end of the class?

2021-06-04 15:38 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
Same comment here

2021-06-04 15:38 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-integration-tests/pom.xml
> +        </dependency>
Why is this needed?

2021-06-04 15:51 UTC, mariofusco commented on kogito-codegen-modules/kogito-codegen-integration-tests/pom.xml
> +        </dependency>
To test the generation of the `ProcessRuntime`.

2021-06-04 15:52 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/KogitoBuildContext.java
> +    boolean hasLegacyApi();
Well, you don't need expose this method: you can directly use 
`hasClassAvailable("org.kie.kogito.legacy.rules.KieRuntimeBuilder")`
in the codegen like we [already do](https://github.com/kiegroup/kogito-runtimes/blob/master/kogito-codegen-modules/kogito-codegen-predictions/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java#L72) without the need to expose it :)

2021-06-04 15:57 UTC, evacchi commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/context/KogitoBuildContext.java
> +    boolean hasLegacyApi();
+1

2021-06-04 16:52 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
To be moved

2021-06-04 16:52 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/impl/KieSessionImpl.java
> +    }
To be moved

2021-06-04 16:53 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-integration-tests/pom.xml
> +        </dependency>
Can you add a comment like ?
`<!--  https://issues.redhat.com/browse/KOGITO-5269 -->`

2021-06-22 10:04 UTC, evacchi commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/KieRuntimeBuilder.java
>  public interface KieRuntimeBuilder {
Naming things and cache invalidation: Not necessarily for this PR, but what if we rename it to `KieRuntimeProvider` ? I think it would make more sense, and it would be more aligned with other components ... /cc @danielezonca

2021-06-24 14:16 UTC, danielezonca commented on api/kogito-legacy-api/src/main/java/org/kie/kogito/legacy/rules/KieRuntimeBuilder.java
>  public interface KieRuntimeBuilder {
I don't have strong opinion, we have many `*Generator` `*Producer` `*Builder` already 🤔 
Technically speaking probably `Provider` is a better fit but again I don't have strong opinion 🤔

2021-06-25 15:36 UTC, mariofusco commented on jbpm/jbpm-flow/pom.xml
> +      <artifactId>kogito-legacy-api</artifactId>
@tiagodolphine I had to add the dependency to the new module containing the kogito legacy API adapter for Drools here, because the code generated by jbpm still uses it in a few points, in particular when it does something like

```
ruleSetNode3.ruleFlowGroup("person", () -> {
            return org.drools.project.model.ProjectRuntime.INSTANCE.newKieSession("defaultStatelessKieSession", app.config().get(org.kie.kogito.rules.RuleConfig.class));
        });
```

There the generated `ProjectRuntime` implements `KieRuntimeBuilder` that now is part of that legacy-api. My suggestion is getting rid of any part of jbpm generated code still using it and once this will be done you could also remove this dependency.

2021-06-28 11:08 UTC, danielezonca commented on jbpm/jbpm-flow/pom.xml
> +      <artifactId>kogito-legacy-api</artifactId>
What about mark it as `<optional>true</optional>`? In this way the user has to explicitly provide it if necessary (aka if the process is not using rule unit)

2021-06-29 13:41 UTC, gitgabrio commented on kogito-codegen-modules/kogito-codegen-predictions/src/test/java/org/kie/kogito/codegen/prediction/PredictionCodegenTest.java
> +        generateAllFiles(context, codeGenerator, 62, 13, 1, true);
@danielezonca 
Probably related to introduction of `getKiePMMLMiningModelSourcesMapCompiled`. Thanks for letting me know, though!

2021-07-01 17:29 UTC, merged