KOGITO-4765: Errors when executing models using imported inputs and/or decisions nodes - VS Code
kiegroup/kogito-runtimes pull request #1349
Opened 2021-06-04 13:41 UTC by yesamer

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-07-20 12:51 UTC, jomarko requested changes
Could we please:
- use different folder name than `sampleTest`? The added fileas are about import dmn model featurre. As we aready have `importedDMN` folder focused on the same feature, could we please rename `sampleTest`  to `importedDMNAdvanced` ? or something similar? Or maybe we can merge these two folders somehow? 
- Could we please rename also scenarios descriptons? We have currently `Case 1`, `Case 2` ...  We use that description for generating IDs in test results tracking system, could we please update to something more self explaining? For example `Imported DMN Input and Decision Case 1` ...

2021-07-20 14:35 UTC, yesamer commented
@jomarko Changes applied. Thank you.

2021-07-20 14:51 UTC, jomarko approved these changes

2021-07-29 12:39 UTC, karreiro approved these changes
Thank you, @yesamer!

2021-07-29 14:42 UTC, merged