[KOGITO-5196] - JDBC addon with optmistic locking
kiegroup/kogito-runtimes pull request #1357
Opened 2021-06-07 23:05 UTC by swati-kale

Signed-off-by: Swati Kale <swkale@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Pull Request</b>  
  Please add comment: <b>Jenkins retest this</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-06-08 04:12 UTC, swati-kale commented
@cristianonicolai, Please review.

2021-06-08 14:51 UTC, cristianonicolai approved these changes

2021-06-08 16:34 UTC, tiagodolphine approved these changes

2021-06-09 03:33 UTC, cristianonicolai requested changes

2021-06-09 03:33 UTC, cristianonicolai commented on addons/persistence/jdbc-persistence-addon/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java
> +            ((AbstractProcessInstance<?>) instance).setVersion((Long) map.get(VERSION));
needs review

2021-06-10 03:47 UTC, swati-kale commented on addons/persistence/jdbc-persistence-addon/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java
> +            ((AbstractProcessInstance<?>) instance).setVersion((Long) map.get(VERSION));
Updated for this as well as for Postgres addon.

2021-06-14 02:30 UTC, cristianonicolai approved these changes

2021-06-15 17:08 UTC, MarianMacik commented on addons/persistence/jdbc-persistence-addon/src/test/java/org/kie/persistence/jdbc/JdbcProcessInstancesWithLockIT.java
> +    }
Pretty much the only difference here is the `lock()` method which returns once true and then false. Is it possible to create a common parent class to avoid such duplication?

2021-06-15 21:57 UTC, swati-kale commented on addons/persistence/jdbc-persistence-addon/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java
> +            throw uncheckedException(null, "The document with ID: %s was updated or deleted by other request.", id);
I thought there could be a concurrent request which might update the process instance(model variables etc) by some other user  and change the version before this delete could happen. WDYT, I might be wrong.

2021-06-16 02:18 UTC, swati-kale commented on addons/persistence/jdbc-persistence-addon/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java
> +                PreparedStatement statement = connection.prepareStatement("UPDATE process_instances SET payload = ?, version = ? WHERE id = ? and version = ?")) {
ok done.

2021-06-16 02:18 UTC, swati-kale commented on addons/persistence/jdbc-persistence-addon/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java
> +            if (map.containsKey(VERSION)) {
> Based on the implementation of findByIdInternal there will always be the `VERSION` key specified.

yes,  updated.

2021-06-16 02:18 UTC, swati-kale commented on addons/persistence/jdbc-persistence-addon/src/test/java/org/kie/persistence/jdbc/JdbcProcessInstancesWithLockIT.java
> +    }
updated.

2021-06-16 11:14 UTC, MarianMacik commented on addons/persistence/jdbc-persistence-addon/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java
> +            throw uncheckedException(null, "The document with ID: %s was updated or deleted by other request.", id);
@swati-kale Yes, that may be an option but you don't check the version here because it is not available. So either the data is in DB under the specified id or it is not there. So in case another user updates the variables of the instance, the data will still be in the DB under the same id, what do you think?

2021-06-16 12:55 UTC, swati-kale commented on addons/persistence/jdbc-persistence-addon/src/main/java/org/kie/kogito/persistence/jdbc/JDBCProcessInstances.java
> +            throw uncheckedException(null, "The document with ID: %s was updated or deleted by other request.", id);
Ok will remove "updated" from msg.

2021-06-16 13:37 UTC, MarianMacik approved these changes

2021-06-17 00:02 UTC, merged