[KOGITO-5444] SpringBoot Kogito Archetypes with parameterized addons
kiegroup/kogito-runtimes pull request #1443
Opened 2021-07-14 20:46 UTC by ricardozanini

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

See: https://issues.redhat.com/browse/KOGITO-5444

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/master/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-07-16 18:06 UTC, ricardozanini commented
Jenkins rerun runtimes tests

2021-07-16 18:07 UTC, ricardozanini commented
Jenkins rerun apps tests

2021-07-16 18:42 UTC, ricardozanini commented
Jenkins rerun examples tests

2021-07-23 21:20 UTC, ricardozanini commented
@hmanwani-rh @briandooley, can you take a quick look at the README included in this PR? Maybe we will need to create a new section explaining how to use the Spring Boot starters, addons, and archetypes. I would suggest a brand new section merging all of these READMEs.

2021-07-29 11:48 UTC, cristianonicolai commented
Jenkins rerun examples tests

2021-07-29 11:48 UTC, cristianonicolai commented
Jenkins rerun runtimes tests

2021-07-29 11:49 UTC, cristianonicolai approved these changes

2021-07-29 20:52 UTC, ricardozanini commented
Jenkins rerun optaplanner tests

2021-07-29 20:53 UTC, ricardozanini commented
Jenkins rerun optaplanner tests

2021-07-30 05:10 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/README.md
> +For a list of valid Kogito Spring Boot addons, please check [this table](../../springboot/addons).
What about common addons?

2021-07-30 05:10 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/pom.xml
> +        <version>${version.org.codehaus.gmavenplus}</version>
What about using kogito-build-parent pluginManagement?

2021-07-30 05:10 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    String packagePath = appPackage.replace(".", "/")
Is this compatible with Windows?

2021-07-30 05:10 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +        Files.deleteIfExists(projectPath.resolve("src/test/java/" + packagePath + "/GreetingsTest.java"))
Same here

2021-07-30 05:10 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +        Files.deleteIfExists(projectPath.resolve("src/test/java/" + packagePath + "/TrafficViolationTest.java"))
Same here

2021-07-30 05:10 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    return addons.split(",").collect { addon -> "kogito-addons-springboot-" + addon }
What about validate the list? In case of typo or similar it will produce a "bad" compilation error

2021-07-30 05:10 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    def pomFile = new File(request.getOutputDirectory() + "/" + request.getArtifactId() + "/pom.xml")
Is this compatible with Windows?

2021-07-30 05:10 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    def writer = new FileWriter(request.getOutputDirectory() + "/" + request.getArtifactId() + "/pom.xml")
Same here

2021-07-30 05:10 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/src/test/resources/projects/it-custom-decisions/archetype.properties
> +# TODO: including processes since the codegen is generating ProcessConfig.java every time. Need to investigate, might be a bug.
Looks like a bug, can you link a Jira?

2021-07-30 05:10 UTC, danielezonca commented on springboot/starters/kogito-spring-boot-starter/pom.xml
> -  <packaging>pom</packaging>
Are starters intended to be jar?

2021-07-30 13:28 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    return addons.split(",").collect { addon -> "kogito-addons-springboot-" + addon }
I thought about this. We would need to have a metafile with all our available add-ons that are updated regularly based on our codebase. Then I could read this file and check it here, rather than have it hardcoded. Maybe in another JIRA?

2021-07-30 13:28 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/test/resources/projects/it-custom-decisions/archetype.properties
> +# TODO: including processes since the codegen is generating ProcessConfig.java every time. Need to investigate, might be a bug.
Oh I forgot to open it.

2021-07-30 13:28 UTC, ricardozanini commented on springboot/starters/kogito-spring-boot-starter/pom.xml
> -  <packaging>pom</packaging>
Yes, this was a mistake.

2021-07-30 18:48 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +        Files.deleteIfExists(projectPath.resolve("src/test/java/" + packagePath + "/GreetingsTest.java"))
Despite from the path separator I used in the replace above, it will work:

> The Path is obtained by invoking the getPath method of the default FileSystem.

All other paths are handled by the `Path` API.

2021-07-30 18:48 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +        Files.deleteIfExists(projectPath.resolve("src/test/java/" + packagePath + "/TrafficViolationTest.java"))
See my comment above.

2021-07-30 18:52 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    def pomFile = new File(request.getOutputDirectory() + "/" + request.getArtifactId() + "/pom.xml")
Should be, but I've changed to Paths API just in case.

2021-07-30 18:52 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    def writer = new FileWriter(request.getOutputDirectory() + "/" + request.getArtifactId() + "/pom.xml")
Paths API.

2021-07-30 19:05 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    return addons.split(",").collect { addon -> "kogito-addons-springboot-" + addon }
See https://issues.redhat.com/browse/KOGITO-5619

2021-07-30 19:21 UTC, ricardozanini commented
jenkins rerun optaplanner tests
jenkins rerun apps tests
jenkins rerun examples tests

2021-07-30 19:37 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/test/resources/projects/it-custom-decisions/archetype.properties
> +# TODO: including processes since the codegen is generating ProcessConfig.java every time. Need to investigate, might be a bug.
See:
https://issues.redhat.com/browse/KOGITO-5621

And you are a winner as well: https://issues.redhat.com/browse/KOGITO-5622

2021-08-02 02:52 UTC, cristianonicolai commented
Jenkins rerun apps tests

2021-08-02 02:52 UTC, cristianonicolai commented
Jenkins rerun examples tests

2021-08-02 13:13 UTC, danielezonca commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    return addons.split(",").collect { addon -> "kogito-addons-springboot-" + addon }
As discussed in chat, current naming convention doesn't cover common addons (aka addons without a springboot specific version

2021-08-02 13:15 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    return addons.split(",").collect { addon -> "kogito-addons-springboot-" + addon }
I'll update the PR now with the mapping of the addons we have

2021-08-02 16:37 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/test/groovy/AddDependencyToPomTest.groovy
> +class AddDependencyToPomTest extends Specification {
I added this class to play around with the XML API, and it's not meant to test the actual groovy script. For this, I created two more IT to verify all the scenarios with custom addons/starters. This way, we can cover the entire groovy script.

2021-08-02 16:40 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> +    XmlUtil.serialize(XmlUtil.serialize(pomXml).trim().replace("\n", "").replaceAll("( *)<", "<"), writer)
We remove the new lines from the original file, just to be added back by the internal printer. Otherwise the resulted POM file will be something like this:

```xml
<tag>

     <tag>

     </tag>

</tag>
```

2021-08-02 16:42 UTC, ricardozanini commented on archetypes/kogito-springboot-archetype/src/test/groovy/AddDependencyToPomTest.groovy
> +class AddDependencyToPomTest extends Specification {
The final output of the `it-custom-process` is:

```xml
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-addons-springboot-process-svg</artifactId>
      <version>${kogito.version}</version>
    </dependency>
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-addons-springboot-monitoring-prometheus</artifactId>
      <version>${kogito.version}</version>
    </dependency>
    <dependency>
      <groupId>org.kie.kogito</groupId>
      <artifactId>kogito-processes-spring-boot-starter</artifactId>
      <version>${kogito.version}</version>
    </dependency>
```

2021-08-03 12:04 UTC, briandooley requested changes
Made some changes in https://github.com/ricardozanini/kogito-runtimes/pull/4 .

2021-08-03 15:42 UTC, MarianMacik approved these changes

2021-08-03 15:53 UTC, ricardozanini commented
@briandooley, your changes have been merged. Can you take a final look?

2021-08-03 18:58 UTC, ricardozanini commented
@danielezonca it's up to you to merge this one.

2021-08-04 03:04 UTC, cristianonicolai commented
Jenkins rerun examples tests

2021-08-04 06:12 UTC, danielezonca approved these changes

2021-08-04 09:58 UTC, briandooley commented
> @briandooley, your changes have been merged. Can you take a final look?

LGTM.

2021-08-04 13:05 UTC, ricardozanini commented
Jenkins rerun examples tests

2021-08-04 18:08 UTC, tiagodolphine approved these changes

2021-08-04 20:23 UTC, ricardozanini commented
Jenkins rerun examples tests

2021-08-04 23:42 UTC, merged