[KOGITO-5300] Updating documentation of addons modules
kiegroup/kogito-runtimes pull request #1463
Opened 2021-07-21 21:14 UTC by ricardozanini

Signed-off-by: Ricardo Zanini <zanini@redhat.com>

2021-07-23 15:33 UTC, ricardozanini commented
@hmanwani-rh, can you please take a first look at the general structure of the documents and writing style? Also, please feel free to modify the files if you see some broken links or identify other sections in our docs that can be linked in theREADMEs.

2021-07-23 16:19 UTC, ricardozanini commented
Adding @briandooley to the loop :)

2021-07-30 10:59 UTC, briandooley requested changes

2021-07-30 10:59 UTC, briandooley commented on addons/README.md
> +   either [`quarkus`](../quarkus/addons) or [`springboot`](../springboot/addons)). You can choose to give support to
```suggestion
   [`quarkus`](../quarkus/addons) or [`springboot`](../springboot/addons)). You can give support to
```

2021-07-30 10:59 UTC, briandooley commented on addons/README.md
> +   only one of them, just make it clear why and discuss this decision with the community.
```suggestion
   one add-on only. Make the reason for your decision clear and discuss this decision with the community.
```

2021-07-30 10:59 UTC, briandooley commented on addons/README.md
> +persistence technologies that can have their specific details. Each implementation can be handled differently based on
```suggestion
persistence technologies that can have their specific details. Each implementation is handled differently based on
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/cloudevents/README.md
> +Use this addon to make the events produced and consumed by a Kogito project accept
Decide whether to use "addon" or "add-on", throughout the entire document, for consistency.

2021-07-30 10:59 UTC, briandooley commented on addons/common/cloudevents/README.md
> +the [CloudEvents](https://cloudevents.io) format. There are many use cases where you will need to use this addon. Please
```suggestion
the [CloudEvents](https://cloudevents.io) format. There are many use cases where you can use this addon.
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/cloudevents/README.md
> +check the following sections in our documentation to find out more:
```suggestion
See the following sections in our documentation to find out more:
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/events/README.md
> +Adds the capability to handle with events use cases on Kogito projects. Please find out more in the following sections
```suggestion
The Kogito Events add-on adds the capability to handle use cases with events on Kogito projects. See the following documentation sections to find out more.
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/events/README.md
> +of our official documentation:
```suggestion
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/events/README.md
> +Please check the following examples to explore more about this capability.
```suggestion
See the following examples to explore more about this capability.
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/explainability/README.md
> +This addon enables the integration with Explainability and Trusty Services. Please check out
```suggestion
The Kogito Explainability Addon enables the integration with Explainability and Trusty Services. See 
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/explainability/README.md
> +to find out more about it.
```suggestion
to find out more.
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/explainability/README.md
> +Please check the following example to explore more about this capability:
```suggestion
See the following example to explore more about this capability:
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/jobs/README.md
> +This add-on allows the integration and configuration of a Kogito project with the Jobs Service supporting service.
```suggestion
Kogito Jobs Management Add-on allows the integration and configuration of a Kogito project with the Jobs Service supporting service.
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/jobs/README.md
> +Please check
```suggestion
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/jobs/README.md
> +the [official documentation](https://docs.jboss.org/kogito/release/latest/html_single/#con-jobs-service_kogito-configuring)
```suggestion
See the [official documentation](https://docs.jboss.org/kogito/release/latest/html_single/#con-jobs-service_kogito-configuring)
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/jobs/README.md
> +Please check the following examples to explore more about this capability:
```suggestion
See the following examples to explore more about this capability:
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/mail/README.md
> +This addon enables the capability of sending emails in a Kogito Process project. An example of usage is the Kogito Task
```suggestion
The Kogito Mail Addon adds the capability of sending emails in a Kogito Process project. An example of this is the Kogito Task
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/mail/README.md
> +Please check the following examples to explore more about this capability:
```suggestion
See the following examples to explore more about this addon:
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/monitoring/README.md
> +These are the addons for adding monitoring capabilities to Kogito projects. Please check
```suggestion
The Kogito Monitoring Addons add monitoring capabilities to Kogito projects. See 
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/persistence/README.md
> +These addons add the persistence capability to Kogito projects. Please check
```suggestion
The Kogito Persistence Addons add persistence capability to Kogito projects.See 
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/process-management/README.md
> +This addon adds the capability of process management to Kogito project and is also part of the integration with the
```suggestion
The Kogito Process Management Addons add process management capability to Kogito projects and are also part of the integration with the
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/process-management/README.md
> +[Kogito Management Console](https://github.com/kiegroup/kogito-apps/tree/master/management-console). Please check
```suggestion
[Kogito Management Console](https://github.com/kiegroup/kogito-apps/tree/master/management-console). See
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/process-management/README.md
> +to find out more!
```suggestion
to find out more.
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/process-management/README.md
> +Please check the following examples to explore more about this capability:
```suggestion
See the following examples to explore more about this capability:
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/process-svg/README.md
> +This addon adds the capability to enable SVG visualization to process diagrams. Please check
```suggestion
The Kogito Process SVG Addon adds the capability to enable SVG visualization to process diagrams. See
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/process-svg/README.md
> +Please check the following examples to explore more about this capability:
```suggestion
See the following examples to explore more about this capability:
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/rest-exception-handler/README.md
> +This addon is supposed to be used internally by other addons. It's not meant to be used directly by end-user's projects.
```suggestion
The Kogito REST Exception Handler Addon is used internally by other addons. It is not to be used directly by end-user's projects.
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/task-management/README.md
> +Enables the integration with the Kogito supporting
```suggestion
The Kogito Task Management Addon enables integration with the Kogito supporting 
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/task-management/README.md
> +service [Task Console](https://github.com/kiegroup/kogito-apps/tree/master/task-console). Please check
```suggestion
service [Task Console](https://github.com/kiegroup/kogito-apps/tree/master/task-console). See 
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/task-management/README.md
> +to find out more!
```suggestion
to find out more.
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/task-management/README.md
> +Please check the following examples to explore more about this capability:
```suggestion
See the following examples to explore more about this capability:
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/tracing/README.md
> +Adds the capability of tracing to Kogito projects. At this time, we only support DMN services tracing. To find out more
```suggestion
The Kogito Tracing addon adds tracing capability to Kogito projects. Currently, we support DMN services tracing only. To find out more
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/tracing/README.md
> +about this capability, please check
```suggestion
about this capability, see 
```

2021-07-30 10:59 UTC, briandooley commented on addons/common/tracing/README.md
> +Please check the following examples to explore more about this capability:
```suggestion
See the following examples to explore more about this capability:
```

2021-08-04 13:13 UTC, MarianMacik approved these changes
Looks good, just some typos.

2021-08-04 13:13 UTC, MarianMacik commented on addons/README.md
> +The following table lists all the add-onss, independent of runtime implementation, supported by the Kogito Community:
```suggestion
The following table lists all the add-ons, independent of runtime implementation, supported by the Kogito Community:
```

2021-08-04 13:13 UTC, MarianMacik commented on addons/README.md
> +it is a generic implementation that can work either on [Quarkus](../quarkus/addons) or [Spring Boot](../quarkus/addons).
Probably `they are a generic implementation` just to keep it uniform.

2021-08-04 13:13 UTC, MarianMacik commented on addons/common/cloudevents/README.md
> +Use this addon to make the events produced and consumed by a Kogito project accept
```suggestion
Use this add-on to make the events produced and consumed by a Kogito project accept
```

2021-08-04 13:13 UTC, MarianMacik commented on addons/common/cloudevents/README.md
> +the [CloudEvents](https://cloudevents.io) format. There are many use cases where you can use this addon.
```suggestion
the [CloudEvents](https://cloudevents.io) format. There are many use cases where you can use this add-on.
```

2021-08-04 13:13 UTC, MarianMacik commented on addons/common/monitoring/README.md
> +The Kogito Monitoring Add-ons add monitoring capabilities to Kogito projects. See
```suggestion
The Kogito Monitoring Add-ons adds monitoring capabilities to Kogito projects. See 
```

2021-08-04 13:13 UTC, MarianMacik commented on addons/common/persistence/README.md
> +The Kogito Persistence Add-ons add persistence capability to Kogito projects.See
```suggestion
The Kogito Persistence Add-ons adds persistence capability to Kogito projects.See 
```

2021-08-04 13:13 UTC, MarianMacik commented on addons/common/process-management/README.md
> +The Kogito Process Management Add-ons add process management capability to Kogito projects and are also part of the integration with the
```suggestion
The Kogito Process Management Add-ons adds process management capability to Kogito projects and are also part of the integration with the
```

2021-08-04 15:28 UTC, briandooley approved these changes
LGTM

2021-08-04 18:30 UTC, merged