KOGITO-5627 Added native LTS check
kiegroup/kogito-runtimes pull request #1491
Opened 2021-08-02 11:47 UTC by radtriste

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-08-03 06:27 UTC, Ginxo requested changes
please check

2021-08-03 06:27 UTC, Ginxo commented on Jenkinsfile.native
> +    if (getNativeBuilderImage()) {
I propose to add a new argument to the `getNativeMavenCommand` method and avoid using `getNativeBuilderImage()` inside this method. This way we keep method isolated and the method is called only once.

2021-08-03 07:01 UTC, radtriste commented on Jenkinsfile.native
> +    if (getNativeBuilderImage()) {
The `getNativeMavenCommand` is totally dependent on `getNativeBuilderImage` in fact as it is a global setting. and in fact `getNativeBuilderImage` would only be used here. But maybe we could directly check here `params.NATIVE_BUILDER_IMAGE` instead of having an external method ...

2021-08-03 07:28 UTC, radtriste commented
tested ok

2021-08-04 09:06 UTC, Ginxo commented on Jenkinsfile.native
> +    if (getNativeBuilderImage()) {
it looks like we are discussing more about personal style here. 

IMHO I would keep `getNativeBuilderImage` since it is general style you always follow (on every Jenkinsfile) and I would add a new argument to `getNativeMavenCommand` as I said and call it like `getNativeMavenCommand('kogito-runtimes', getNativeMavenCommand())`.

I can't "force" you to follow it since it is just my style, so please follow the way you feel more comfortable with, I'm ok with whatever you decide you style is also good!

2021-08-04 09:11 UTC, Ginxo approved these changes
LGTM, just decide whether you want to apply my proposal or not

2021-08-05 07:21 UTC, radtriste commented on Jenkinsfile.native
> +    if (getNativeBuilderImage()) {
@Ginxo changed method signature to `MavenCommand getNativeMavenCommand(String directory, String builderImage = getNativeBuilderImage()) {`

2021-08-05 07:24 UTC, Ginxo commented on Jenkinsfile.native
> +        mvnCmd.withProperty('quarkus.native.builder-image', getNativeBuilderImage())
```suggestion
        mvnCmd.withProperty('quarkus.native.builder-image', builderImage)
```

2021-08-05 07:52 UTC, merged