KOGITO-5401 - Remove Kogito Quarkus archetype
kiegroup/kogito-runtimes pull request #1493
Opened 2021-08-02 14:28 UTC by cristianonicolai

2021-08-02 14:41 UTC, cristianonicolai commented
@danielezonca @evacchi @ricardozanini do we still need to have a _kogito-springboot-dm-archetype_? apparently, this one is not even built

2021-08-02 15:39 UTC, ricardozanini commented
I've removed it here: #1443 

Let's wait for #1443 to be merged to merge this one. Then we can move the alone archetype to `springboot/archetypes` module.

2021-08-05 12:00 UTC, ricardozanini commented
One more thing: can you please review the examples for any mention of the Quarkus archetype? Also, [we have a session in the docs dedicated to it](https://docs.jboss.org/kogito/release/latest/html_single/#proc-kogito-creating-project_kogito-creating-running). We ought to update it as well.

2021-08-05 12:24 UTC, cristianonicolai commented on springboot/archetypes/kogito-springboot-archetype/pom.xml
>    <description>Kogito based on Spring Boot runtime Archetype</description>
+1

2021-08-05 12:25 UTC, cristianonicolai commented on springboot/archetypes/pom.xml
>    <artifactId>archetypes</artifactId>
so not match the folder name or also rename it?

2021-08-05 12:44 UTC, cristianonicolai commented on springboot/archetypes/kogito-springboot-archetype/pom.xml
>    <description>Kogito based on Spring Boot runtime Archetype</description>
@ricardozanini I guess as this is used for creating projects, not a dependency, we can simply rename and state in the docs. No need to keep the old artifact id wdyt?

2021-08-05 12:54 UTC, ricardozanini commented on springboot/archetypes/kogito-springboot-archetype/pom.xml
>    <description>Kogito based on Spring Boot runtime Archetype</description>
Fine to me!

2021-08-05 12:55 UTC, ricardozanini commented on springboot/archetypes/pom.xml
>    <artifactId>archetypes</artifactId>
leave the folder as `archetypes` and the id as `springboot-archetypes` to not have a GAV like `org.kie.kogito:archetypes:1.11.0` in maven.

2021-08-05 12:56 UTC, ricardozanini commented on springboot/archetypes/pom.xml
>    <artifactId>archetypes</artifactId>
This is something we need to state in the our contribution docs. The folder names not necessarily have to follow the artifacts id. Same thing Quarkus is doing to keep the paths simpler. @danielezonca @evacchi cc

2021-08-05 14:07 UTC, cristianonicolai commented
@ricardozanini updated changes based on feedback

2021-08-05 15:10 UTC, cristianonicolai commented
Jenkins rerun runtimes tests

2021-08-05 15:10 UTC, cristianonicolai commented
Jenkins rerun examples tests

2021-08-05 15:10 UTC, cristianonicolai commented
Jenkins rerun optaplanner tests

2021-08-05 19:00 UTC, ricardozanini commented
@cristianonicolai the images also uses these archetypes:
https://github.com/kiegroup/kogito-images/blob/main/modules/kogito-s2i-core/added/s2i-core#L105-L120

cc @spolti

2021-08-06 01:53 UTC, cristianonicolai commented
@spolti can you review that, -dm archtype were removed as well

2021-08-06 01:54 UTC, cristianonicolai commented
Jenkins rerun apps tests

2021-08-06 19:58 UTC, spolti commented
> @spolti can you review that, -dm archtype were removed as well

Sure, when it gets merged I'll update the spring-boot archetype.

2021-08-09 14:50 UTC, jstastny-cz requested changes
I would argue not to change the artifactId of the Spring Boot archetype as part of this change. This Jira talks about deleting Quarkus archetypes and moving the rest to `springboot` folder.

2021-08-09 14:50 UTC, jstastny-cz commented on springboot/archetypes/kogito-spring-boot-archetype/pom.xml
> +  <artifactId>kogito-spring-boot-archetype</artifactId>
I understand the goal is to make things more consistent. `spring-boot` would indeed be the correct wording. But it has no relation to KOGITO-5401 and it makes a mess in our kiegroup components, once it's `spring-boot`, the other is `springboot` (even in this single pom.xml).
Also such a change on a user-facing artifact IMO deserves at least a Release Notes entry, which argues for a separate tracker for the change.

2021-08-09 14:50 UTC, jstastny-cz commented on springboot/archetypes/pom.xml
> +  <artifactId>springboot-archetypes</artifactId>
here we're renaming to `springboot` again. I might be missing the reason, again, a separate Jira would be a great place to provide justification.

2021-08-09 15:20 UTC, cristianonicolai commented on springboot/archetypes/kogito-spring-boot-archetype/pom.xml
> +  <artifactId>kogito-spring-boot-archetype</artifactId>
@jstastny-cz we're following the Spring Boot recommendation to use `spring-boot` for user facing dependencies, for our internal ones, there is no need to change. I agree that's not part of the main JIRA, so I created KOGITO-5683 to track this change but reusing the same PR. Release notes are covered in here https://github.com/kiegroup/kie-docs/pull/3832/files#diff-b09724e6a9c8041a227df2397d332d941da0c3296d50bc80d6d90f7e32094b8fR114

2021-08-09 15:20 UTC, cristianonicolai commented on springboot/archetypes/pom.xml
> +  <artifactId>springboot-archetypes</artifactId>
Created KOGITO-5683

2021-08-09 15:55 UTC, jstastny-cz commented on springboot/archetypes/kogito-spring-boot-archetype/pom.xml
> +  <artifactId>kogito-spring-boot-archetype</artifactId>
Understood. Thank you for the Jira.

2021-08-09 16:02 UTC, jstastny-cz requested changes
I think we need to tweak the productization related config.

2021-08-09 16:13 UTC, jstastny-cz commented on springboot/archetypes/kogito-spring-boot-archetype/pom.xml
> +  <artifactId>kogito-spring-boot-archetype</artifactId>
Maybe still one follow-up question, where we'll rename `kogito-springboot-bom`?

2021-08-10 06:29 UTC, danielezonca commented on springboot/archetypes/pom.xml
> +        <module>kogito-spring-boot-archetype</module>
The duplication of the archetype was a temporal workaround related to 7.11 to avoid to include unsupported features in user projects.
Now with the refactoring that Ricardo did about springboot starters and considering that 7.12 includes all the type of resource, I expect a single (parametric) archetype to be enough

2021-08-10 07:03 UTC, danielezonca approved these changes

2021-08-10 14:53 UTC, cristianonicolai commented on springboot/archetypes/pom.xml
> +        <module>kogito-spring-boot-archetype</module>
@mareknovotny could you follow up on this PR to revisit if we can remove the productized specific settings?

2021-08-10 14:58 UTC, cristianonicolai commented on springboot/archetypes/kogito-spring-boot-archetype/src/test/groovy/org/kie/kogito/springboot/archetypes/AddDependencyToPomWithTextReplaceTest.groovy
> +/*
created https://issues.redhat.com/browse/KOGITO-5689

2021-08-10 17:18 UTC, ricardozanini commented on springboot/archetypes/kogito-spring-boot-archetype/pom.xml
> +  <artifactId>kogito-spring-boot-archetype</artifactId>
I thought I was already renamed this. Yes, we should also rename the BOM.

2021-08-10 17:19 UTC, ricardozanini approved these changes

2021-08-11 08:47 UTC, cristianonicolai commented on springboot/archetypes/pom.xml
>    <artifactId>archetypes</artifactId>
@ricardozanini renamed to just `archtype` as we only have one now, no subfolders needed

2021-08-11 08:51 UTC, cristianonicolai commented on springboot/archetypes/pom.xml
> +        <module>kogito-spring-boot-archetype</module>
@jstastny-cz I got rid of the sub folder and now we only have a `archtype` folder in the root.
@mareknovotny I know this needs to be supported, what I don't know is why that prod profile was there in the first place and how it affects your team's work later on. It's been removed now.

2021-08-11 09:00 UTC, jstastny-cz commented on springboot/archetypes/pom.xml
> +        <module>kogito-spring-boot-archetype</module>
@cristianonicolai Daniele touch on that topic a bit in his previous comment. I think we're all set now (archetype included in build all the time, since we have common one now).

2021-08-11 09:09 UTC, jstastny-cz approved these changes
LGTM.

Approving with assumption that `kogito-spring-boot-archetype` `archetype-resources/pom.xml` will be changed to import Spring Boot BOM as part of #1515 .

2021-08-11 09:49 UTC, cristianonicolai commented on springboot/archetypes/kogito-spring-boot-archetype/pom.xml
> +  <artifactId>kogito-spring-boot-archetype</artifactId>
Created a follow up https://issues.redhat.com/browse/KOGITO-5693

2021-08-11 12:12 UTC, cristianonicolai commented on springboot/archetypes/pom.xml
> +        <module>kogito-spring-boot-archetype</module>
@mareknovotny that is true for Quarkus but not Spring Boot archtypes

2021-08-11 13:28 UTC, merged