KOGITO-5747 Public API: Shared Modules (Incubation)
kiegroup/kogito-runtimes pull request #1546
Opened 2021-08-23 15:03 UTC by evacchi

https://issues.redhat.com/browse/KOGITO-5747

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-08-23 15:04 UTC, evacchi commented on api/kogito-api-incubation-application/src/main/java/org/kie/kogito/incubation/application/ReflectiveAppRoot.java
> +            return providerId.getConstructor().newInstance();
however, the proper way to do this would be via service loading -- we may decide to do it; however this is not intended to be used outside tests

2021-08-23 15:07 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/InternalObjectMapper.java
> + * This is an implementation detail. We may move this to a separate module in the future.
another candidate for service loading

2021-08-30 09:54 UTC, gitgabrio requested changes
@evacchi - Thanks for the PR. Copied comments I made [here](https://github.com/kiegroup/kogito-runtimes/pull/1549) and kept discussion about interface inheritance usage

2021-08-30 09:54 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/Castable.java
> +public interface Castable {
Hi @evacchi (copy)
Could you explain the needs of this ? IIUC DataContext extends Castable; so it seems the parent interface is declaring a method that can actually works only on a specific "son" (i.e. another different interface extending "Castable" should always return a "DataContext", and not itself): is my question clear ? Am I misreading something ?

I read your [answer](https://github.com/kiegroup/kogito-runtimes/pull/1549/files/5fe38d63de228823afb0ddfb6dcc6cac3bd18af2#r698337490) but IMO this does not justify that design, that - again IMO - is wrong: a "parent" interface (Castable) has knowledge of and reference to a children one (DataContext): I think this is an antipattern in OOP

2021-08-30 09:54 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DataContext.java
> +public interface DataContext extends Castable {
@evacchi (copy)
Could you please some javadoc explaining what this interface actually is for ?

2021-08-30 09:54 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DefaultCastable.java
> +public interface DefaultCastable extends Castable {
@evacchi
Could you please some javadoc explaining what this interface actually is for ? The provided one seems more related to "Castable" itself, and not specific to this one....

2021-08-30 09:54 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DefaultCastable.java
> +    default <T extends DataContext> T as(Class<T> type) {
@evacchi
See comment above: apparently, there is no direct relationship between DefaultCastable and DataContext: IIUC, an actual implementation of the former would have a different inheritance tree of an actual implementation of the latter. I have the impression this is a little bit worse then the previous comment. Here, one extending interface should have knowledge of and reference to a different extending interface of the same parent

2021-08-30 09:54 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MapDataContext.java
> +public class MapDataContext implements MapLikeDataContext, MetaDataContext {
@evacchi ([see](https://github.com/kiegroup/kogito-runtimes/pull/1549/files/5fe38d63de228823afb0ddfb6dcc6cac3bd18af2#r698317961) for reference)

2021-08-30 10:33 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/Castable.java
> +public interface Castable {
The reason why DataContext extends Castable is because all DataContexts should be Castables, but not all Castables may be DataContexts.The idea would be that you may make any class Castable to a DataContext without being a DataContext, by implementing the `DefaultCastable` interface (or `Castable` itself).

i.e. suppose that you want to provide a data object and make it possible to convert it into a DataContext; but you don't want it to be passed as a DataContext itself.

For instance you may have an object with some extra fields that you don't want to be available to the evaluation. By implementing the `as` method yourself you'd be able to customize what fields should be made available.

TBF I am not necessarily stronly opinionated about this one, I just wanted to keep interface tiny.
I am not strongly opionionated about `as` being an instance method (it may be very constraining). Maybe we will turn that into into some sort of static method; in that case it may make sense for the two interfaces to be separate; e.g.:

     Castable.of(myContext).as(...)

2021-08-30 10:34 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MapDataContext.java
> +public class MapDataContext implements MapLikeDataContext, MetaDataContext {
@gitgabrio 
> IIUC MetaDataContext extends MapLikeDataContext, so this seems a little bit redundant

yeah it's useless without an example, the idea would be that this allows to get "metadata" when you do `.as(MetaDataContext.class)` instead of "regular data" (e.g. params). This interface is not really useful at the moment though; btw still relates to #1546

2021-08-30 11:10 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/Castable.java
> +public interface Castable {
Hi @evacchi I think I've understood the idea, but my remark is about the implementation.
We want to separate two concepts (Castable and DataContext) but then we merge them in a single one, because, how it is written, "Castable" actually is "CastableToDataContext". This means that a "Castable" may be cast only to a DataContext, but a "DataContext" is already a "DataContext" - what's the meaning of _casting_ a DataContext to a DataContext ?
If, on the other side, you want any given "Castable" to returns a DataContext (as the method and your explanation suggest), maybe composition is the pattern to use, not inheritance.

Anyway, beside all this academical reasoning, I think that referring a "son" in an interface/class is something better to avoid. If you find a way to change that, like the static method or whatever, I think it would be better.

2021-08-30 12:26 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/Castable.java
> +public interface Castable {
ok I see your point. The use case is to be able convert into a *subclass* of `DataContext`. Converting a `DataContext` into the same `DataContext` is a no-op just like `(Object) new Object()` is a no-op :-) 

the idea is you are always able to convert a `DataContext` into an arbitrary sub-type; e.g. a `MapDataContext` into a POJO that implements `DataContext`.

e.g.

```
class Person implements DataContext, DefaultCastable { String name; }
MapDataContext ctx = MapDataContext.create();
ctx.set("name", "Paul");
Person p = ctx.as(Person.class);
p.name // "Paul"
```

This is generalizing e.g. the DMNContext to a more "generic" interface that allows conversion of classes from map-like structures (JSON-izable if you will) into arbitrary typed POJOs 

So, both Person and MapDataContext are DataContexts, but they are not of the same type. You convert them at the use-site in order to use typed vs untyped API

2021-08-30 12:54 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/Castable.java
> +public interface Castable {
@evacchi 
I'll keep commenting here, but feel free to ping me - maybe by voice would be easier.
It seems we want that
1) a DataContext should be able to be "casted" to a (different) DataContext
2) a Castable should be able to be "casted" to a  DataContext

My personal opinion is that interfaces, at their core, should actually define "behaviors". Looking that way, it seems to me that  those two interfaces are actually the same. I understand that the "Castable" concept should be slightly different, but the implementation lead to that. Does this make sense ? 
I understand your explanations and requirements, but my point is that the root of current the solution is (again, IMO) wrong. So, I would prefer to have a different design/implementation to fulfill them, even if more verbose/contrived.

2021-08-31 08:54 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DataContext.java
> +public interface DataContext extends Castable {
added

2021-08-31 08:54 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DefaultCastable.java
> +public interface DefaultCastable extends Castable {
added

2021-08-31 08:55 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MapDataContext.java
> +public class MapDataContext implements MapLikeDataContext, MetaDataContext {
I have removed `MetaDataContext.class` for now. I'll have to rebase the other PRs but that's only because it was used in tests -- not necessary for now.

2021-08-31 10:12 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DataContext.java
> + * <li>A DataContext can be always converted into another type
@evacchi 
I add this comment here as remember

2021-08-31 15:39 UTC, ricardozanini reviewed
Looks great for a first step, and the API seems robust enough for an early stage. Many thanks for the documentation. It's well written and informative.

Regarding the `DataContext` and `Castable` interfaces, I tend to agree with @gitgabrio. I think after we settle this discussion, we can move forward.

2021-08-31 15:39 UTC, ricardozanini commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/UriRemoteId.java
> +            this.uri = new URI(String.format("kogito://%s@%s:%d%s", appId, host, port, localId.asPath()));
Maybe this is a `KogitoUriRemoteId`? Given that we will support `kubernetes` or maybe `http|s` in the future? Either way, we should be able to scale the implementation, no?

2021-08-31 15:39 UTC, ricardozanini commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/pom.xml
> +                <artifactId>jandex-maven-plugin</artifactId>
I think this plugin can be inherited from the parent extension module. IIRC, all extensions modules require it.

2021-08-31 16:22 UTC, tiagodolphine approved these changes
LGTM, great job! Just some minor comments.

2021-08-31 16:22 UTC, tiagodolphine commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/InternalObjectMapper.java
> + * This is an implementation detail. We may move this to a separate module in the future.
yeah, and I'd say we probably can share internal object mapper that already exists in other places, mainly to do data conversion, see 
https://github.com/kiegroup/kogito-runtimes/blob/3283958b111b29bf206071eb531cf82bec52ebfb/jbpm/jbpm-flow/src/main/java/org/jbpm/process/core/transformation/JsonResolver.java#L37 
https://github.com/kiegroup/kogito-runtimes/blob/fdc27397ec5fae2ee88576d90975481f409848eb/jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/util/TypeTransformer.java#L36
https://github.com/kiegroup/kogito-runtimes/blob/22195a19dbf27e1bfdc2855bd62a46d896778964/jbpm/jbpm-flow/src/main/java/org/jbpm/util/JsonSchemaUtil.java#L43
https://github.com/kiegroup/kogito-runtimes/blob/f855f1d0d21e1f6c0fa1d4bfcf289fe5cb0956ec/kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/proto/AbstractProtoGenerator.java#L36
..... 
among others... so I'd say this is not the scope of this PR but we could open a Jira to track this, otherwise, we may come with tons of objectMapper instances

2021-08-31 16:22 UTC, tiagodolphine commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/UriRemoteId.java
> +            this.uri = new URI(String.format("kogito://%s@%s:%d%s", appId, host, port, localId.asPath()));
and it would be great to allow a way for customization...

2021-08-31 16:22 UTC, tiagodolphine commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/incubation/application/quarkus/QuarkusAppRoot.java
> +        super("kogito-app");
the same.. should we allow customization of the `name`?

2021-08-31 17:48 UTC, ricardozanini commented
@tiagodolphine regarding ObjectMapper, I have the same opinion, but I let it go since we have it tracked here: https://issues.redhat.com/browse/KOGITO-5618

2021-09-01 09:53 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/InternalObjectMapper.java
> + * This is an implementation detail. We may move this to a separate module in the future.
+1 https://issues.redhat.com/browse/KOGITO-5807

2021-09-01 11:41 UTC, evacchi commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/pom.xml
> +                <artifactId>jandex-maven-plugin</artifactId>
I'll create a JIRA: testing this setup is complicated with broken-down separate PRs; better refactor this all at once when things are more settled https://issues.redhat.com/browse/KOGITO-5810

2021-09-01 11:42 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/UriRemoteId.java
> +            this.uri = new URI(String.format("kogito://%s@%s:%d%s", appId, host, port, localId.asPath()));
Yeah, this is basically here for demo purposes... I think I should just remove it for the time being. It has no real use at the moment.

2021-09-01 11:53 UTC, evacchi commented
@ricardozanini : 
@gitgabrio is suggesting the following refactoring:

```diff
- interface DataContext implements Castable {
+ interface DataContext {
+    <T extends DataContext> T as(Class<T> type);
}
```

so remove the `implements` clause and redeclare the `as` method explicitly. I am not strongly opinionated about this one. The `as()` method is there only to have the fluent:

```
myObject.as(SomeType.class)
```

as mentioned, in order to make it pluggable we may provide a different API, and *static*, instead of instance methods. Or even provide a way to use both strategies (e.g. static method + default method on interface -- the main question: shall we make it pluggable? and how? and when?)

e.g. specific services may want to provide their own DataContext implementation with an `as` method that exposes a specific subset of fields. By using Jackson's ObjectMapper we may be able to define Jackson Modules for each DataContext subtype, but we'll need a loading mechanism to plug them (DI for Quarkus/Spring -- what about "neither" ? ServiceLoaders ?)

in other words: every component should be able to define its own behavior, and that needs some further thinking

2021-09-02 09:53 UTC, evacchi commented on api/kogito-api-incubation-application/src/main/java/org/kie/kogito/incubation/application/ReflectiveAppRoot.java
> +            return providerId.getConstructor().newInstance();
https://issues.redhat.com/browse/KOGITO-5815

2021-09-02 09:53 UTC, evacchi commented on api/kogito-api-incubation-application/pom.xml
> +    <artifactId>kogito-api-incubation-application</artifactId>
I am respecting the name convention of this sub-root. They are all `kogito-api-<something>`

2021-09-02 09:53 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/UriRemoteId.java
> +            this.uri = new URI(String.format("kogito://%s@%s:%d%s", appId, host, port, localId.asPath()));
removed

2021-09-06 13:50 UTC, cristianonicolai approved these changes

2021-09-06 21:44 UTC, danielezonca commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/incubation/application/quarkus/QuarkusAppRoot.java
> +        super("kogito-app");
I agree and also `kogito-app` is quite misleading with kogito-apps repo (at least for us

2021-09-06 22:20 UTC, danielezonca reviewed
Overall looks good to me, just some comments

2021-09-06 22:20 UTC, danielezonca commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> + * An identifier for a local resource
What about `RelativeId` instead of local? Considering that every Id has a "local" part maybe it is easier to understand 🤔

2021-09-06 22:20 UTC, danielezonca commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> +    Path asPath();
Are you sure about this? Is this "reasonable"?
Every Id can be converted to LocalId using `toLocalId()` method so this means that also a RemoteId can be converted as Path and this is impossible 🤔 
Probably URI or similar is more generic or we can consider to remove `toLocalId` method

2021-09-06 22:20 UTC, danielezonca commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DataContext.java
> +public interface DataContext extends Castable {
As we already discussed I think we should have a codepath that doesn't require to implement an interface so that it is possible for users to reuse their existing bean without any need of customisation/rewrite.
Said diffently having the possibility to only use composition instead of inheritance (there are already similar comment from others)
We can do it with a different PR of course

2021-09-06 22:20 UTC, danielezonca commented on api/kogito-api-incubation-application/src/main/java/org/kie/kogito/incubation/application/AppRoot.java
> +public abstract class AppRoot extends PathLocalId implements Id {
I think another missing bit to have a full and comprehensive API is to provide an alternative/equivalent of the old KnoledgeBuilder to let user to have a full library use case with no DI or in general explicit resource wiring.
Is this already in the plan? Without a similar feature it is sort of impossible to apply this API for all the use cases.
Currently `AppRoot` is not in charge at all for resources wiring and each component/service is expected to have them "automagically"

2021-09-07 06:25 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> +    Path asPath();
> this is impossible

it won't be "local" but it would still be a path. Why do you think this is impossible?

2021-09-07 06:25 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> + * An identifier for a local resource
it is not relative because it always starts at `/`

2021-09-07 06:38 UTC, danielezonca commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> +    Path asPath();
Ok maybe I misunderstood, let me do an example to double check:

I have a RemoteId `kogito://decisions/myName/myNamespace`, if I use `toLocalId()` it becomes `/decisions/myName/myNamespace`.
Then if finally I call `asPath()`, this method "verify" if I have the actual file locally (like a "file discovery service") and returns `/path/to/my.dmn`?

Or it only "convert" the localId as a path even if it is not a real path? (Something like `new Path("/decisions/myName/myNamespace")`?

Because if it is this last option, this will ~always generate a Path that is not valid (aka referring to a physical file) and as soon as user try to use it as real Path it will fail

2021-09-07 06:44 UTC, evacchi commented on api/kogito-api-incubation-application/src/main/java/org/kie/kogito/incubation/application/AppRoot.java
> +public abstract class AppRoot extends PathLocalId implements Id {
Well, I'd say this goes well beyond "APIs", and it is more about mechanism. Will this API allow interaction with something that is generated without DI? Well I can't see why not. 

`AppRoot` is not in charge of wiring because its role is to construct a path, regardless of where the resource is actually located. Validation of such a path should not occur at Path construction, but at the use-site (i.e. in the service). This allows for more flexible services (e.g. use cases where the service does not physically reside in the local app). 

At the same time, a local non-DI service implementation could walk the filesystem (or the classpath, or whatever) and expose some resources through some `Id`, just the same as a DI-wired instance. Construction and instantiation of the service could be done through some other mechanism (possibly an equivalent of the KnowledgeBuilder, possibly explicit instantiation), because it is a separate concern.

the "service" +ID idea is that the ID represents an address to a resource, and the service replies to a request for that address. A service may always reply for some ID regardless if it is local, hand-wired, auto-wired, etc

2021-09-07 06:45 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> +    Path asPath();
let me explain. There is always a "local" part that can be extracted. It may not be local to your machine, but it would be local to "some" machine. On that machine, it will address the local resource.

2021-09-07 07:10 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> +    Path asPath();
apparently I posted the clarification but your reply hadn't show up yet. This is correct:

> Or it only "convert" the localId as a path even if it is not a real path? (Something like `new Path("/decisions/myName/myNamespace")`?

a Path in this context is just a "typed"/"structured" string if you will. Validation will occur at the use-site, i.e. in the service.

2021-09-07 09:05 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DataContext.java
> +public interface DataContext extends Castable {
- [KOGITO-5839 Public API: Separate DataContext conversion concern from `as()` instance method](https://issues.redhat.com/browse/KOGITO-5839)
- [KOGITO-5840 Public API: Provide DataContext wrapper for user classes](https://issues.redhat.com/browse/KOGITO-5840)

2021-09-07 09:06 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DefaultCastable.java
> +    default <T extends DataContext> T as(Class<T> type) {
after our conversation I have 
(1) separated the two hierarchies as you suggested
(2) still created the following JIRAs, as I believe it will be better design overall

- [KOGITO-5839 Public API: Separate DataContext conversion concern from `as()` instance method](https://issues.redhat.com/browse/KOGITO-5839)
- [KOGITO-5840 Public API: Provide DataContext wrapper for user classes](https://issues.redhat.com/browse/KOGITO-5840)

2021-09-07 13:42 UTC, evacchi commented
asking @ricardozanini @ricardozanini @gitgabrio for approval :)

Also adding @radtriste for approval

2021-09-08 08:25 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> +    Path asPath();
further clarifications: indeed Path is meant for a local file-system Path; it is not necessary for the Path to exist; however there is a different issue that may bite us: file separators! on Windows, `toString()` for `Path("a/b/c")` prints `Path("a\\b\\c")` so indeed Path is not ideal for this.

I am investigating what to use instead (URI is very limited and quite cumbersome when it comes to appending relative paths) but I would still merge this in the meantime; JIRA: https://issues.redhat.com/browse/KOGITO-5844

2021-09-08 10:53 UTC, gitgabrio reviewed
HI @evacchi 
I understand the idea of delivering something quickly to speed up the iterations, but I'm not convinced on pushing/delivering something (e.g. the Path usage) that we already know it is "wrong". Even if it is an "incubation" attempt, it does not mean that it may contain anything just for the sake of speed. M2C

2021-09-08 10:53 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> +    Path asPath();
Hi @evacchi 
Path is meant to represent a system dependent file path to locate a file in a file system.
It is true that the path may not exists for some reason, but this does not mean that we should use it for something that we already know will never exists (IIUC the discussion).
IMO, as a rule of thumb, we should not use classes for something different then their original scope. This lead to hard-to-find bugs and unexpected behavior (at least, from the "user" point of view).
To give an example:
`protected AppRoot(String name) {
        super(Paths.get("/"));
        this.name = name;
    }`
this is extremely suspicious.

2021-09-08 19:57 UTC, danielezonca approved these changes

2021-09-09 07:03 UTC, gitgabrio requested changes
@evacchi 
Please, remove that usage of Path. Beside being an anti-pattern to use something for a different scope is meant to fulfill, it also introduce a clear bug, making this not working  on Windows and excluding all windows user from this "incubation" iteration.

2021-09-09 09:04 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/LocalId.java
> +    Path asPath();
yeah you guys are right. I opened a JIRA and I am working on an alternative; will fix in the next iteration

2021-09-09 09:07 UTC, evacchi commented
> @evacchi
> Please, remove that usage of Path. Beside being an anti-pattern to use something for a different scope is meant to fulfill, it also introduce a clear bug, making this not working on Windows and excluding all windows user from this "incubation" iteration.

I have started writing https://github.com/evacchi/kogito-runtimes/commit/01ba04f89aaa27e273aba38a90e981cdca7b86dc WDYT ? shall I bring this in? (name HierarchicalPath is temporary. Maybe "LocalUri" ?)

2021-09-09 10:11 UTC, evacchi commented
added a84426889d with the LocalUri API

2021-09-09 10:54 UTC, gitgabrio requested changes
LGTM @evacchi Thanks for modification

2021-09-09 14:45 UTC, ricardozanini approved these changes

2021-09-09 15:28 UTC, radtriste approved these changes

2021-09-09 15:28 UTC, radtriste commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/src/main/java/org/kie/kogito/incubation/application/quarkus/QuarkusAppRoot.java
> +        super("kogito-app");
`kogito-runtime` ?

2021-09-10 10:14 UTC, merged