KOGITO-5750 Public API: PMML Modules (Incubation)
kiegroup/kogito-runtimes pull request #1549
Opened 2021-08-24 07:07 UTC by evacchi

https://issues.redhat.com/browse/KOGITO-5750

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [runtimes|optaplanner|apps|examples] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-08-30 09:05 UTC, gitgabrio requested changes
@evacchi Thanks for the PR!
Maybe it is a WIP, but it looks to me there are too many empty interfaces used just as "labels". Beside that, I would kindly ask to put some more javadoc to better explain what's going on to someone (like me) who read this code for the first time. Thanks :smile:

2021-08-30 09:05 UTC, gitgabrio commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MapDataContext.java
> +public class MapDataContext implements MapLikeDataContext, MetaDataContext {
@evacchi 
IIUC MetaDataContext extends MapLikeDataContext, so this seems a little bit redundant

2021-08-30 09:31 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/Castable.java
> +    <T extends DataContext> T as(Class<T> type);
this refers to #1546 on which this PR is based on, please move this comment there, there is an explanation of the rationale for DataContext -- but specifically the reason is that in my mind the Castable-to-DataContext is a separate concern than "being a DataContext".

2021-08-30 09:31 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DefaultCastable.java
> +    default <T extends DataContext> T as(Class<T> type) {
same

2021-08-30 09:32 UTC, evacchi commented on api/kogito-api-incubation-predictions-services/src/test/java/org/kie/kogito/incubation/predictions/services/TestTypes.java
> +        LocalPredictionId decisionId = appRoot.get(PredictionIds.class).get(modelName);
good point. `modelName` is the name within the model file, so that should be unique, right? we can make it more specific with `get(modelId, modelName)` where `modelId` may be the file name -- or something like that

2021-08-30 09:32 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/DataContext.java
> +public interface DataContext extends Castable {
same as above, this is related to #1546

2021-08-30 09:33 UTC, evacchi commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionService.java
> +        PMML4Result pmml4Result = predictionModel.evaluateAll(ctx);
not sure why you say `asynchronously`; this is all synchronous

2021-08-30 09:34 UTC, evacchi commented on api/kogito-api-incubation-common/src/main/java/org/kie/kogito/incubation/common/MapDataContext.java
> +public class MapDataContext implements MapLikeDataContext, MetaDataContext {
yeah it's useless without an example, the idea would be that this allows to get "metadata" when you do `.as(MetaDataContext.class)` instead of "regular data" (e.g. params). This interface is not really useful at the moment though; btw still relates to #1546

2021-08-30 09:41 UTC, gitgabrio commented on api/kogito-api-incubation-predictions-services/src/test/java/org/kie/kogito/incubation/predictions/services/TestTypes.java
> +        LocalPredictionId decisionId = appRoot.get(PredictionIds.class).get(modelName);
@evacchi 
yes, this is something I have to do anyway

2021-08-30 09:55 UTC, gitgabrio commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionService.java
> +        PMML4Result pmml4Result = predictionModel.evaluateAll(ctx);
:+1:

2021-09-10 15:24 UTC, gitgabrio requested changes
@evacchi Thanks for the PR. I made just a small comment about one naming

2021-09-10 15:24 UTC, gitgabrio commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionIdFactory.java
> +class QuarkusPredictionIdFactory extends PredictionIds {
@evacchi 
Knowing that I am extremely picky about it, this naming seems a little bit inconsistent to me: a factory should not (IMHO) extend the object is meant to build (I'm not sure what this factory is for, but navigating hierarchy it seems to be a ComponentRoot)

2021-09-14 09:28 UTC, evacchi commented on api/kogito-api-incubation-predictions-services/src/test/java/org/kie/kogito/incubation/predictions/services/TestTypes.java
> +        LocalPredictionId decisionId = appRoot.get(PredictionIds.class).get(modelName);
we can improve this in the next iteration https://issues.redhat.com/browse/KOGITO-5889

2021-09-14 09:33 UTC, evacchi commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionIdFactory.java
> +class QuarkusPredictionIdFactory extends PredictionIds {
So, `QuarkusPredictionIdsComponentRoot` ?

2021-09-14 10:44 UTC, gitgabrio commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionIdFactory.java
> +class QuarkusPredictionIdFactory extends PredictionIds {
Hi @evacchi 
I may be wrong, but I read
`public class PredictionIds implements ComponentRoot {
    public LocalPredictionId get(String name) {
        return new LocalPredictionId(name);
    }
}`
so `QuarkusPredictionIdFactory` extends `PredictionIds` that in turns implements `ComponentRoot`.
I may agree (generally speaking) that having "nice" names in fluent API could be... nice; but on the other side I would prefer to have consistent naming without having to go to the sources to try to understand what is going on... and this conversation point exactly to that: I did not realize that PredictionIds is a factory because it extends a `ComponentRoot` and returns a `LocalPredictionId` - all of that is really error-prone to read...

2021-09-15 12:19 UTC, evacchi commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionIdFactory.java
> +class QuarkusPredictionIdFactory extends PredictionIds {
so would `QuarkusPredictionIdsComponentRoot` work?

2021-09-15 12:41 UTC, gitgabrio commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionIdFactory.java
> +class QuarkusPredictionIdFactory extends PredictionIds {
@evacchi   what about simply `QuarkustPredictionsIds` ? My understanding is that `PredictionIds` may be used in all environments (quarkus, spring, not-cdi) and `QuarkustPredictionsIds` is the specialized class for the former.

2021-09-15 12:51 UTC, evacchi commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions/src/main/java/org/kie/kogito/core/prediction/incubation/quarkus/support/QuarkusPredictionIdFactory.java
> +class QuarkusPredictionIdFactory extends PredictionIds {
great, `QuarkusPredictionsIds` it is!

2021-09-15 13:56 UTC, gitgabrio approved these changes
@evacchi 
Thanks for the PR LGTM!

2021-09-16 19:44 UTC, radtriste commented on api/kogito-api-incubation-predictions/src/main/java/org/kie/kogito/incubation/predictions/LocalPredictionId.java
> +    public static final String PREFIX = "predictions";
same question here for the factory
https://github.com/kiegroup/kogito-runtimes/pull/1547/files#diff-1c53618ddac2a63a94ad1fa04a5727c71a7face9e564e9f62fa66254647f5ce4R24-R28

2021-09-16 19:44 UTC, radtriste commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/src/test/java/org/kie/kogito/quarkus/pmml/CustomEndpointIT.java
> +@QuarkusTest
native ?

2021-09-17 06:37 UTC, evacchi commented on quarkus/extensions/kogito-quarkus-predictions-extension/kogito-quarkus-predictions-integration-test/src/test/java/org/kie/kogito/quarkus/pmml/CustomEndpointIT.java
> +@QuarkusTest
I have intentionally left out native test to avoid those headaches at the moment

2021-09-17 06:59 UTC, evacchi commented on api/kogito-api-incubation-predictions/src/main/java/org/kie/kogito/incubation/predictions/LocalPredictionId.java
> +    public static final String PREFIX = "predictions";
good question, Processes were the first thing I wrote, and then I adopted a different pattern everywhere else; so instead, I am removing the nested `Factory` from processes and keeping this as is.

2021-09-17 07:11 UTC, radtriste approved these changes

2021-09-17 18:36 UTC, merged