KOGITO-5861: fix async events and filter in EventDrivenDecisionController
kiegroup/kogito-runtimes pull request #1603
Opened 2021-09-14 12:51 UTC by kostola

2021-09-15 10:05 UTC, fjtirado requested changes
Hi, 
As dicussed with @kostola, I feel the refactor of completablefuture handling both for quarkus and sprinboot might affect the peformance testing that we manually performed several weeks ago. So I will prefer to split this PR in two: one that just fix the type filter issue in EventDrivenDecisionControler and another one with the refactor of the completable future for the event receiver implementations. 
Let me elaborate a bit more. 
The reason the code is different from Quarkus and Sprinboot is because for Quarkus we commit messages indiviaully when the completable future is completed (thats what the callback is doing, commiting the message)   and in Sprinboot we let the framework commit the whole batch (and that why we need to wait for completable future to finish, hence the sequential treatment). 

The refactor wontwork for Quarkus because the returned completablefuture is not completed yet, so it will block delivery of next event till all async completable are done and that will kill performance of start process. 

The refactor wont work for SpringBoot because it will commit the records before the event has been dispatched by Kogito

2021-09-15 11:03 UTC, fjtirado commented on quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/AbstractQuarkusCloudEventReceiver.java
> -        return result;
This is key for performance througput to return a completed future to smallrye so it allow next event in the poll to be processed. with this change we might potentially return a not completed future and that will block event processing, killint througput

2021-09-15 11:04 UTC, fjtirado commented on springboot/addons/messaging/implementation/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringKafkaCloudEventReceiver.java
> -        log.debug("Waiting for all operations in batch to complete");
we need to synchronoulsy wait here for two reasons:
1) let sprinboot automatically commit the batch
2) ensure order of polls is kept

2021-09-15 13:10 UTC, kostola commented
@fjtirado I reverted all the extra changes keeping only the minimum set required to fix the filter in `EventDrivenDecisionController` and update the corresponding test. Please take a look.

2021-09-15 13:10 UTC, kostola commented on quarkus/addons/messaging/common/src/main/java/org/kie/kogito/addon/quarkus/messaging/common/AbstractQuarkusCloudEventReceiver.java
> -        return result;
Thanks for the detailed explanation :pray:

2021-09-15 13:10 UTC, kostola commented on springboot/addons/messaging/implementation/src/main/java/org/kie/kogito/addon/cloudevents/spring/SpringKafkaCloudEventReceiver.java
> -        log.debug("Waiting for all operations in batch to complete");
Thanks for the detailed explanation :pray:

2021-09-15 15:08 UTC, fjtirado approved these changes
LGTM!

2021-09-15 18:18 UTC, danielezonca approved these changes
LGTM, just a minor comment

2021-09-16 06:14 UTC, kostola commented on addons/common/events/decisions/src/main/java/org/kie/kogito/eventdriven/decision/EventDrivenDecisionController.java
> -        CloudEventUtils.decode(event)
It's used quite a lot around..expecially in tests

2021-09-16 06:14 UTC, kostola commented on api/kogito-events-api/src/main/java/org/kie/kogito/event/AbstractEventReceiver.java
> +    private final Collection<Subscription<?>> subscriptions = new CopyOnWriteArrayList<>();
It's gone :)

2021-09-16 07:14 UTC, danielezonca commented on addons/common/events/decisions/src/main/java/org/kie/kogito/eventdriven/decision/EventDrivenDecisionController.java
> -        CloudEventUtils.decode(event)
Ok let's do it in another PR if necessary 👍

2021-09-16 07:15 UTC, merged