KOGITO-5930: implement evaluation of predictions via CloudEvents
kiegroup/kogito-runtimes pull request #1623
Opened 2021-09-23 06:56 UTC by kostola

* [Jira task](https://issues.redhat.com/browse/KOGITO-5930)

2021-09-23 08:11 UTC, gitgabrio requested changes
Hi @kostola 
Thanks for the PR! I have just couple of questions and, maybe, a modification to be done.

2021-09-23 08:11 UTC, gitgabrio commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +            LOG.warn("Model not found with name=\"{}\"", modelName);
@kostola 
I'm not sure of that: what could lead to an "ignorable" runtime exception here ?
Said differently: if 
`predictionModels.getPredictionModel(modelName))` throws an exception, there may be an issue all over the code pasth that lead to `PMMLRuntime` instantiation, and I think we should not simply hide that...

2021-09-23 11:26 UTC, jiripetrlik approved these changes
I have one suggestion.

2021-09-23 11:26 UTC, jiripetrlik commented on quarkus/addons/events/predictions/runtime/pom.xml
> +<!--      <plugin>-->
Please add some info about why this code is commented out or remove it completely.

2021-09-23 12:46 UTC, kostola commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +        if (data == null) {
I consider an empty data map as a valid input for the model. I tried with regression and I get a valid response. Is this wrong somehow?

2021-09-23 12:47 UTC, kostola commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +                    && requestData != null;
I consider an empty data map as a valid input for the model. I tried with regression and I get a valid response. Is this wrong somehow?

2021-09-23 12:48 UTC, kostola commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +            LOG.warn("Model not found with name=\"{}\"", modelName);
I am catching a `RuntimeException` because that's what `getPredictionModel` throws when a model is not found.
I will introduce a specific exception to catch so that all the others (caused by unexpected issues) will be propagated as it should be.

2021-09-23 12:56 UTC, gitgabrio commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +            LOG.warn("Model not found with name=\"{}\"", modelName);
great, thanks!

2021-09-23 13:00 UTC, gitgabrio commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +                    && requestData != null;
TBH it is a very tough question. On one side, PMML spec define the possibility of managing "missing values", but if all values are missing, what does represent the result ?
You are right the code does not throw any exception, though.... Just ignore that for the moment being....

2021-09-23 13:52 UTC, danielezonca commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +public class EventDrivenPredictionsController {
This controller, `EventDrivenRulesController` and `EventDrivenDecisionsController` are quite similar, can you please create a ticket to refactor `predictions`, `decisions` and `rules` events addon with a common module?

2021-09-23 13:52 UTC, danielezonca commented on quarkus/addons/events/predictions/pom.xml
> +    <module>runtime</module>
Please apply same changes mentioned in these comments
https://github.com/kiegroup/kogito-runtimes/pull/1610#discussion_r714772248
https://github.com/kiegroup/kogito-runtimes/pull/1610#discussion_r714774411

2021-09-23 13:57 UTC, gitgabrio commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +            LOG.warn("Model not found with name=\"{}\"", modelName);
Beside that, that exception (whatever it is) should not be swallowed away: if the user ask evaluation of a model that is not available, an error or similar should be raised

2021-09-28 09:31 UTC, danielezonca commented on quarkus/addons/events/predictions/runtime/pom.xml
> +  <artifactId>kogito-addons-quarkus-events-predictions</artifactId>
Please add this new extension to [Quarkus list](https://github.com/kiegroup/kogito-runtimes/tree/main/quarkus/addons#kogito-quarkus-add-ons) and [Spring Boot list](https://github.com/kiegroup/kogito-runtimes/tree/main/springboot/addons#kogito-spring-boot-add-ons)

2021-09-28 13:13 UTC, kostola commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +            LOG.warn("Model not found with name=\"{}\"", modelName);
I added `PredictionModelNotFoundException` for this specific case

2021-09-28 13:13 UTC, kostola commented on quarkus/addons/events/predictions/runtime/pom.xml
> +<!--      <plugin>-->
Now it's not commented anymore and it works

2021-09-28 13:14 UTC, kostola commented on quarkus/addons/events/predictions/pom.xml
> +    <module>runtime</module>
Done :+1:

2021-09-28 13:16 UTC, kostola commented on quarkus/addons/events/predictions/runtime/pom.xml
> +  <artifactId>kogito-addons-quarkus-events-predictions</artifactId>
Done :+1:

2021-09-28 13:16 UTC, kostola commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +                    && requestData != null;
ok :+1:

2021-09-28 13:17 UTC, kostola commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +        if (data == null) {
As per [this comment](https://github.com/kiegroup/kogito-runtimes/pull/1623#discussion_r714771825), we'll think about this later

2021-09-28 13:40 UTC, kostola commented on addons/common/events/predictions/src/main/java/org/kie/kogito/eventdriven/predictions/EventDrivenPredictionsController.java
> +public class EventDrivenPredictionsController {
Created [KOGITO-5972](https://issues.redhat.com/browse/KOGITO-5972)

2021-09-29 17:16 UTC, danielezonca approved these changes
LGTM 👍 

@gitgabrio 
Can you please review/approve?

@kostola 
Please resolve merge conflict

2021-09-30 06:17 UTC, gitgabrio approved these changes
LGTM

2021-10-01 07:16 UTC, merged