KOGITO-5891: JSON Schema generation for ProcessModelInput
kiegroup/kogito-runtimes pull request #1697
Opened 2021-11-05 13:54 UTC by pefernan

Adding JSON schema generation for ProcessModelnput, so we can use it in our quarkus runtime tools extension to start processes via form

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-11-05 15:56 UTC, fjtirado reviewed
LGTM, many thanks Pere!!!
Just some minor comments

2021-11-05 15:56 UTC, fjtirado commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +            Optional<DefinitionKey> optional = ((SchemaGenerationContextImpl) context).getDefinedTypes().stream().filter(key -> key.getType().equals(scope.getDeclaredType())).findFirst();
uneeded? I mean, you are executing this search twice isnt it? This can be refactor to search just once

2021-11-05 15:56 UTC, fjtirado commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +                        context.getKeyword(SchemaKeyword.TAG_REF_MAIN) + "/" + context.getKeyword(SchemaKeyword.TAG_DEFINITIONS) + "/" + strategy.getDefinitionNameForKey(definitionKey, context);
We should avoid using "/" in path and use Paths.get(pahelement1, pathelement2) instead, unless this is not a reference to another file but an internal reference within the same file, Im not sure, so just asking

2021-11-05 15:56 UTC, fjtirado commented on api/kogito-api/src/main/java/org/kie/kogito/ProcessInput.java
> +    String PROCESS_NAME_PARAM = "processName";
Move this constant to the generator class (we should avoid constants in interfaces) 
The reasons are enumerated here https://en.wikipedia.org/wiki/Constant_interface

2021-11-05 16:18 UTC, pefernan commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +                        context.getKeyword(SchemaKeyword.TAG_REF_MAIN) + "/" + context.getKeyword(SchemaKeyword.TAG_DEFINITIONS) + "/" + strategy.getDefinitionNameForKey(definitionKey, context);
@fjtirado this refers to the path to the deinition of that object inside the jsonSchema. See the `traveller.$ref` property: 

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Traveller": {
      "type": "object",
      "properties": {...}
    }
  },
  "type": "object",  
  "properties": {
    "traveller": {
      "$ref": "#/definitions/Traveller"
    }
  }
} 
```

I'd say that's ok, to be like this.

2021-11-05 16:21 UTC, pefernan commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +            Optional<DefinitionKey> optional = ((SchemaGenerationContextImpl) context).getDefinedTypes().stream().filter(key -> key.getType().equals(scope.getDeclaredType())).findFirst();
I had to do this trick to workaround an issue on the victools library. It automatically adds the right `$ref` pointing to the definition unless you use a `CustomPropertyDefinition`,  in this case I had to manually add it. I'll try to cache it somewhere.

2021-11-08 10:57 UTC, pefernan commented on api/kogito-api/src/main/java/org/kie/kogito/ProcessInput.java
> +    String PROCESS_NAME_PARAM = "processName";
ok, I saw the same approach for `UserTask` annotation, that's why I did it like that

2021-11-08 14:56 UTC, pefernan commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +            Optional<DefinitionKey> optional = ((SchemaGenerationContextImpl) context).getDefinedTypes().stream().filter(key -> key.getType().equals(scope.getDeclaredType())).findFirst();
@fjtirado rised this issue https://github.com/victools/jsonschema-generator/issues/205 to see if they provide a solution/fix for this...

2021-11-08 14:57 UTC, pefernan commented
@fjtirado @cristianonicolai @jstastny-cz I think it's ready to go

2021-11-08 15:56 UTC, jstastny-cz requested changes
Just issue with naming conflict.

2021-11-08 15:56 UTC, jstastny-cz commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ProcessToExecModelGenerator.java
> +            Optional<ClassOrInterfaceDeclaration> clazz = cu.findFirst(ClassOrInterfaceDeclaration.class);
This could save us a few lines. I leave to your consideration which way you prefer.
```suggestion
            ClassOrInterfaceDeclaration clazz = cu.findFirst(ClassOrInterfaceDeclaration.class).orElseThrow(()->new NoSuchElementException("Cannot find class declaration in the template"));
```

2021-11-08 15:56 UTC, jstastny-cz commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +            boolean needsJsonSchema = shouldGenSchema(c);
This is puzzling. We have both Predicate shouldGenSchema and static method shouldGenSchema. I would suggest to investigate if the static method can be replaced by the predicate. If not, I would at least argue for distinct naming.

2021-11-08 15:56 UTC, jstastny-cz commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +            boolean needsJsonSchema = shouldGenSchema(c);
This method is called `ensureHasAnnotations`, while it calls `shouldGenSchema` static method, which actually checks if the class has annotations.
The static method is used only here it seems, so I would suggest get rid of it and streamline the implementing code directly into this `ensureHasAnnotations` method.

2021-11-08 17:12 UTC, pefernan commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +            boolean needsJsonSchema = shouldGenSchema(c);
@jstastny-cz Yea you're right. I tried to keep the same behaviour as the we had before but including the ProcessInput into accound, and I did some renames... that in this case is wrong ;D

I'd say that we are initializing the `shouldGenSchema` Predicate initialized as the static `shouldGenSchema`  and then apllying both methods in the filter. First the `shouldGenSchema` Predicate in line [99](https://github.com/kiegroup/kogito-runtimes/pull/1697/files/e683f946c85f2bed15c3f0f01ab8f832330aa652#diff-a9918cde5ab7d553f9c04373900b1ccfa340b2a00376e89cde80c4eca483c832L87) and then when calling the `ensureHasAnnotations` in line [100](https://github.com/kiegroup/kogito-runtimes/pull/1697/files/e683f946c85f2bed15c3f0f01ab8f832330aa652#diff-a9918cde5ab7d553f9c04373900b1ccfa340b2a00376e89cde80c4eca483c832R100).

I'll remove that...

2021-11-09 07:12 UTC, jstastny-cz commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/acme/travels/Traveller.java
> +	public Traveller(String firstName, String lastName, String email, String nationality) {
for some reason this file is formatted using tabs, not spaces. Not only new changes, but also old, not sure if it's worth reformatting now or not.

2021-11-09 07:12 UTC, jstastny-cz commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +        private Predicate<? super Class<?>> shouldGenSchema = clazz -> true;
could we remove the predicate and also filter using it on line 99?

2021-11-11 07:27 UTC, cristianonicolai commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +        private Predicate<? super Class<?>> shouldGenSchema = clazz -> true;
+1

2021-11-11 07:27 UTC, cristianonicolai commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +        UserTask userTask = c.getAnnotation(UserTask.class);
should we also check if isAnnotationPresent?

2021-11-11 07:28 UTC, cristianonicolai commented
Jenkins run native

2021-11-11 08:07 UTC, pefernan commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +        private Predicate<? super Class<?>> shouldGenSchema = clazz -> true;
of course!

2021-11-11 08:13 UTC, pefernan commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonSchemaGenerator.java
> +        UserTask userTask = c.getAnnotation(UserTask.class);
well I was assuming that after the filters we were safe here, but will add the check, whiynot.

2021-11-11 16:02 UTC, pefernan commented
@cristianonicolai @fjtirado @jstastny-cz second round!

2021-11-11 16:04 UTC, pefernan commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/acme/travels/Traveller.java
> +	public Traveller(String firstName, String lastName, String email, String nationality) {
@jstastny-cz didn't applied any formatting here, if you think it is worth it I'll

2021-11-12 01:54 UTC, cristianonicolai approved these changes

2021-11-12 01:54 UTC, cristianonicolai commented
jenkins please retest this

2021-11-15 13:52 UTC, fjtirado commented on kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/json/JsonUtils.java
> +        JsonNode targetNode = target.get(srcEntry.getKey());
Alternative implementation
`private static void writeArray(Map.Entry<String, JsonNode> srcEntry, JsonNode target) {
        JsonNode targetNode = target.get(srcEntry.getKey());
        ArrayNode targetArrayNode;
        Set<JsonNode> existingNodes; 
        if (targetNode instanceof ArrayNode) {
            targetArrayNode = (ArrayNode) targetNode;
            existingNodes = new HashSet<>();            
            targetArrayNode.forEach(existingNodes::add);
        } else {
            targetArrayNode = JsonNodeFactory.instance.arrayNode();
            
            if (targetNode != null) {
                existingNodes = Collections.singleton(targetNode);
                targetArrayNode.add(targetNode);
            } else {
                existingNodes = Collections.emptySet();
            }
        }
        srcEntry.getValue().forEach(node -> addNotDuplicate (targetArrayNode, node, existingNodes));
        ((ObjectNode) target).replace(srcEntry.getKey(), targetArrayNode);
    }
    
    private static void addNotDuplicate (ArrayNode array, JsonNode node, Set<JsonNode> existingNodes) {
        if (!existingNodes.contains(node)) {
            array.add(node);
        }
    }`

2021-11-16 09:08 UTC, pefernan commented
jenkins retest this

2021-11-16 11:47 UTC, fjtirado approved these changes

2021-11-16 16:55 UTC, pefernan commented
jenkins retest this

2021-11-17 17:57 UTC, pefernan commented
Due to the latest changes in the schema generation must add some fixes in the consoles!

2021-11-18 11:12 UTC, pefernan commented
jenkins retest this please

2021-11-24 08:09 UTC, jstastny-cz commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/main/java/org/acme/travels/Traveller.java
> +	public Traveller(String firstName, String lastName, String email, String nationality) {
Good to keep as is.

2021-11-24 08:09 UTC, jstastny-cz approved these changes
LGTM.

2021-11-24 13:32 UTC, MarianMacik approved these changes
Looks good to me.

2021-11-25 12:53 UTC, pefernan commented
jenkins run kogito-apps

2021-11-25 12:54 UTC, pefernan commented
Jenkins run kogito-apps

2021-11-25 13:35 UTC, pefernan commented
jenkins retest this please

2021-11-26 06:49 UTC, cristianonicolai commented
Jenkins rerun kogito-examples tests

2021-11-26 12:55 UTC, merged