KOGITO-6131 Enable codegen when RESTEasy reactive is used
kiegroup/kogito-runtimes pull request #1757
Opened 2021-11-29 07:47 UTC by tkobayas

https://issues.redhat.com/browse/KOGITO-6131

This is a WIP branch to continue https://github.com/kiegroup/kogito-runtimes/pull/1669

Applied AdditionalStaticResourceBuildItem following https://github.com/quarkusio/quarkus/issues/20846#issuecomment-962932557

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2021-11-29 08:10 UTC, tkobayas commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
> +//        }
Temporarily disabled MissingServletCapabilityException check in order to confirm if all tests run fine without servlet (undertow) dependency.

2021-11-29 08:24 UTC, tkobayas commented on quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
> +        registerResources(generatedFiles, staticResProducer, resource, genResBI);
@evacchi Should we change `ProcessesAssetsProcessor` just like `KogitoAssetsProcessor`? (e.g. `BuildProducer<GeneratedJaxRsResourceBuildItem> jaxrsProducer`). I changed only this line because `registerResources` signature changed.

2021-11-29 12:58 UTC, tkobayas commented
Note : In order to access static resources generated by codegen, we need to use `@QuarkusIntegrationTest` instead of `@QuarkusTest`. It seems to be the cause of failing kogito-examples tests. I will check.

2021-11-30 07:39 UTC, evacchi commented on integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicAddIT.java
> +@QuarkusIntegrationTest
honest question: why did we need this change?

2021-11-30 07:57 UTC, evacchi requested changes
looks overall good. I would investigate if it's possible to do a "cleaner" check for static resource paths (i.e. use the type/add a new category). if it's too much work we can at least file a new JIRA for that and do it on the next round.

as for `AdditionalStaticResourceBuildItem` I am not sure whether it is really picked up by resteasy-classic, so I am summoning @geoand's powers for confirmation. If that is the case, that would mean that we don't need to add `undertow` as a forced dependency as @tkobayas was suggesting

However, please keep in mind that it looks like some metrics-related examples are breaking because a static file is missing. So either we are forgetting to register some static resources or undertow is indeed necessary.

2021-11-30 07:57 UTC, evacchi commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
> +                if (f.relativePath().startsWith(STATIC_RESOURCE_DIR)) {
I think it would be better if we only checked the Category. In theory there is even a specific subtype:

 https://github.com/kiegroup/kogito-runtimes/blob/49c622f08f3803d27d0585adfdeabe93200f642e/kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java#L76 

but I don't know if we were consistent with it. I wouldn't check the path, though, it may be brittle

2021-11-30 07:57 UTC, evacchi commented on quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
> +        registerResources(generatedFiles, staticResProducer, resource, genResBI);
`jaxrsProducer` is not for static resources, as confusing as it is, it is for REST endpoints (e.g. `@Path("...") class MyEndpoint` which are called "Resources" by resteasy (and possibly jax-rs spec? I don't know ;) )

2021-11-30 08:18 UTC, geoand commented
> as for `AdditionalStaticResourceBuildItem` I am not sure whether it is really picked up by resteasy-classic, so I am summoning @geoand's powers for confirmation. If that is the case, that would mean that we don't need to add `undertow` as a forced dependency as @tkobayas was suggesting

Using`AdditionalStaticResourceBuildItem` should work with `resteasy-classic` as well

2021-11-30 10:43 UTC, tkobayas commented on integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicAddIT.java
> +@QuarkusIntegrationTest
@evacchi  Sorry about not having commented on that.

For example, if I leave BasicAddIT with @QuarkusTest (and others are @QuarkusIntegrationTest), I hit the BindException because quarkus keeps running across the @QuarkusIntegrationTest tests.

```
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 3, Time elapsed: 6.403 s <<< FAILURE! - in org.kie.kogito.integrationtests.quarkus.BasicAddIT
[ERROR] org.kie.kogito.integrationtests.quarkus.BasicAddIT.testDs1  Time elapsed: 0.001 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Unable to start HTTP server
Caused by: java.util.concurrent.ExecutionException: java.net.BindException: Address already in use
Caused by: java.net.BindException: Address already in use
```

So I think we should not mix @QuarkusTest and @QuarkusIntegrationTest in the same integration-test phase.

2021-11-30 10:52 UTC, geoand commented on integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicAddIT.java
> +@QuarkusIntegrationTest
Yes, you should not mix them

2021-11-30 12:21 UTC, evacchi commented
> > as for `AdditionalStaticResourceBuildItem` I am not sure whether it is really picked up by resteasy-classic, so I am summoning @geoand's powers for confirmation. If that is the case, that would mean that we don't need to add `undertow` as a forced dependency as @tkobayas was suggesting
> 
> Using`AdditionalStaticResourceBuildItem` should work with `resteasy-classic` as well

FYI @danielezonca @r00ta

2021-12-01 08:10 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java
> +        META_INF_RESOURCE,
Hi, @evacchi 
> a "cleaner" check for static resource paths (i.e. use the type/add a new category)

I added `Category.META_INF_RESOURCE`. Does this what you thought of?
Some concerns:
- kogito codegen developers have to be aware whether they want to use `Category.RESOURCE` or  `Category.META_INF_RESOURCE`
- Currently, kogito codegen developers specify both `Category.META_INF_RESOURCE` and path like `"META-INF/resources/xxxfile`. It's redundant and I can automatically add `"META-INF/resources/` to the path (inside GeneratedFile constructor) or maybe I can add a validation error/warn when the category and path don't match. But hmm, it might confuse developers. WDYT?

2021-12-01 08:10 UTC, tkobayas commented on quarkus/extensions/kogito-quarkus-processes-extension/kogito-quarkus-processes-deployment/src/main/java/org/kie/kogito/quarkus/processes/deployment/ProcessesAssetsProcessor.java
> +        registerResources(generatedFiles, staticResProducer, resource, genResBI);
Thanks!

2021-12-01 08:12 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java
> +        META_INF_RESOURCE,
Hi, @evacchi 
> a "cleaner" check for static resource paths (i.e. use the type/add a new category)

I added `Category.META_INF_RESOURCE`. Does this what you thought of?
Some concerns:
- kogito codegen developers have to be aware whether they want to use `Category.RESOURCE` or  `Category.META_INF_RESOURCE`
- Currently, kogito codegen developers specify both `Category.META_INF_RESOURCE` and path like `"META-INF/resources/xxxfile`. It's redundant and I can automatically add `"META-INF/resources/` to the path (inside GeneratedFile constructor) or maybe I can add a validation error/warn when the category and path don't match. But hmm, it might confuse developers. WDYT?

2021-12-01 08:12 UTC, tkobayas commented on integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicAddIT.java
> +@QuarkusIntegrationTest
Thank you for the confirmation!

2021-12-01 10:28 UTC, tkobayas commented
**kogito-examples**
This error is found in daily build so not related to this PR.
```
[2021-12-01T09:04:06.405Z] [ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 9.026 s <<< FAILURE! - in org.acme.sw.onboarding.queries.AssignmentUnitTest
[2021-12-01T09:04:06.405Z] [ERROR] org.acme.sw.onboarding.queries.AssignmentUnitTest.verifyNeurologyAssignmentCollection  Time elapsed: 0.001 s  <<< ERROR!
[2021-12-01T09:04:06.405Z] java.lang.RuntimeException:
[2021-12-01T09:04:06.405Z] java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[2021-12-01T09:04:06.405Z]      [error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.util.NoSuchElementException: SRCFG00011: Could not expand value quarkus.http.test-port in property org.acme.sw.onboarding.services.AssignmentUnitClient/mp-rest/url
[2021-12-01T09:04:06.405Z]      at io.smallrye.config.ExpressionConfigSourceInterceptor.lambda$getValue$0(ExpressionConfigSourceInterceptor.java:63)
```

2021-12-01 10:30 UTC, tkobayas commented
**kogito-apps**
This has to be addressed. Will look tomorrow...
```
[2021-12-01T09:42:25.452Z] [ERROR] Failed to execute goal org.kie.kogito:kogito-maven-plugin:2.0.0-SNAPSHOT:process-model-classes (default-process-model-classes) on project integration-tests-data-index-service-springboot: Error during processing model classes: Found unexpected files:
[2021-12-01T09:42:25.452Z] [ERROR] META_INF_RESOURCE PROTO: META-INF/resources/persistence/protobuf/approvals.proto
[2021-12-01T09:42:25.452Z] [ERROR] META_INF_RESOURCE PROTO: META-INF/resources/persistence/protobuf/list.json
[2021-12-01T09:42:25.452Z] [ERROR] -> [Help 1]
[2021-12-01T09:42:25.452Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.kie.kogito:kogito-maven-plugin:2.0.0-SNAPSHOT:process-model-classes (default-process-model-classes) on project integration-tests-data-index-service-springboot: Error during processing model classes
...
[2021-12-01T09:42:25.452Z] Caused by: java.lang.IllegalStateException: Found unexpected files:
[2021-12-01T09:42:25.452Z] META_INF_RESOURCE PROTO: META-INF/resources/persistence/protobuf/approvals.proto
[2021-12-01T09:42:25.452Z] META_INF_RESOURCE PROTO: META-INF/resources/persistence/protobuf/list.json
[2021-12-01T09:42:25.452Z]     at org.kie.kogito.codegen.core.utils.GeneratedFileValidation.validateGeneratedFileTypes (GeneratedFileValidation.java:42)
[2021-12-01T09:42:25.452Z]     at org.kie.kogito.maven.plugin.ProcessClassesMojo.execute (ProcessClassesMojo.java:111)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2021-12-01T09:42:25.452Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2021-12-01T09:42:25.452Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2021-12-01T09:42:25.452Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2021-12-01T09:42:25.452Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2021-12-01T09:42:25.452Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2021-12-01T09:42:25.452Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2021-12-01T09:42:25.452Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2021-12-01T09:42:25.452Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2021-12-01T09:42:25.452Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

2021-12-01 13:49 UTC, evacchi commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java
> +        META_INF_RESOURCE,
> I added Category.META_INF_RESOURCE. Does this what you thought of?
more or less. Maybe STATIC_HTTP_RESOURCE or something? it's something that we want to publish as a static file to the web server...

> kogito codegen developers have to be aware whether they want to use Category.RESOURCE or Category.META_INF_RESOURCE

I'd say that is reasonable

> It's redundant and I can automatically add "META-INF/resources/ to the path (inside GeneratedFile constructor) or maybe I can add a validation error/warn when the category and path don't match. But hmm, it might confuse developers. WDYT?

uhm, good question. I think the path for Quarkus may be irrelevant, as long as you publish it using the `AdditionalStaticResourceBuildItem`, but it makes sense to at least validate it. For now it may be less confusing than "automatically" append the path. I honestly don't have a strong opinion on this...

2021-12-02 08:20 UTC, tkobayas commented
Okay, I see only a known issue (`Could not expand value quarkus.http.test-port in property org.acme.sw.onboarding.services.AssignmentUnitClient/mp-rest/url`). Removing the temporary Exception...

2021-12-02 09:40 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFile.java
> +        }
@evacchi Is it fine to raise a validation warning at the GeneratedFile consructor?

2021-12-02 09:41 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java
> +        META_INF_RESOURCE,
Sure, changed to `STATIC_HTTP_RESOURCE`.

2021-12-03 03:01 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFile.java
> +        }
@evacchi  also this WARN suggests (not forcing) developers to place STATIC_HTTP_RESOURCE under `META-INF/resources`, which is valid for Quaukus. But for Spring Boot, developers can place static resources under several directories:

(under src/main/resources/)

- META-INF/resources
- public
- static
- resources

Is it okay to suggest only `META-INF/resources`? IMHO, it would be okay because commonizing the path `META-INF/resources` for both Quakus and Spring Boot would make things simpler for kogito codegen developers.

2021-12-03 14:54 UTC, evacchi commented on integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicAddIT.java
> +@QuarkusIntegrationTest
ok !

2021-12-03 14:55 UTC, evacchi commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFile.java
> +        }
looks good!

2021-12-03 14:55 UTC, evacchi approved these changes

2021-12-06 07:39 UTC, tkobayas commented
Hi @evacchi , could you add anyone who are suitable for reviewers? Thanks!

2021-12-06 13:40 UTC, tkobayas commented
hi @danielezonca , @r00ta @jomarko , please review. If you want to add someone to review, please feel free to because I'm not knowledgeable about who to review in kogito-runtimes. (Edoardo is on PTO, will be back on Thursday). Thanks!

2021-12-06 17:39 UTC, danielezonca reviewed
Well done with the changes and the integration tests 👍 
Added some comments to try to simplify the impl

2021-12-06 17:39 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java
> +        STATIC_HTTP_RESOURCE,
Why this new category is necessary? I expect all `RESOURCE` are `STATIC_HTTP_RESOURCE` in terms of runtime and I would like to avoid to add a new type for this.
Said differently, can we just get rid of `RESOURCE` and convert everything to a single category? In the past we used to have many different types with different handling and we had to work to simplify to only few of them so now I'm quite redundant to add a new category back.

2021-12-06 17:39 UTC, danielezonca commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/pom.xml
> +            <scope>provided</scope>
What does it mean to have a `-deployment` that is `provided`? Isn't equivalent to remove it?

2021-12-06 17:39 UTC, danielezonca commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/pom.xml
> +            <scope>provided</scope>
Same here, I think we can remove it

2021-12-06 17:39 UTC, danielezonca commented on integration-tests/integration-tests-quarkus-resteasy-classic/pom.xml
> +    <quarkus.test.list.include>false</quarkus.test.list.include>
I just noticed this configuration, is it necessary also for this module? I'm not sure about how to test it, as far as I remember it is related to quarkus-platform integration test.
@jstastny-cz
Do you know how to test this?

2021-12-06 17:39 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFile.java
> +        }
If this is the case, why don't we just add this prefix while saving? Similar to what we do for `src/main/resource`

2021-12-06 17:39 UTC, danielezonca commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
> +        generatedBeanBuildItems.forEach(b -> jaxrsProducer.produce(new GeneratedJaxRsResourceBuildItem(b.getName(), b.getData())));
As far as I see this generates as `GeneratedJaxRsResourceBuildItem` all generated classes so also a normal java class or a CDI bean is added to this BuildItem.
Is this something expected/accepted by Quarkus?

2021-12-06 17:39 UTC, danielezonca commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
> +            }
I don't think we need to differentiate `RESOURCE` and `STATIC_HTTP_RESOURCE` (see previous comment).
Can you verify if having a single approach for both works?

2021-12-07 10:24 UTC, jstastny-cz commented on integration-tests/integration-tests-quarkus-resteasy-reactive/pom.xml
> +    <quarkus.test.list.include>false</quarkus.test.list.include>
So basically, to execute this test in quarkus-platform, easiest way will be:
1. set the property to `true` for given module
2. build kogito-runtimes so that both kogito-quarkus-test-list and the invoked module are part of reactor -> if we do sth like `mvn clean install -pl :integration-tests-quarkus-resteasy,:kogito-quarkus-test-list` from kogito-runtimes folder this should make sure that in kogito-quarkus-test-list/target there will be the xml artifact with just this single module mentioned (In case of full-repo build all the modules will be there).
3. clone https://github.com/quarkusio/quarkus-platform/
4. change version of https://github.com/quarkusio/quarkus-platform/blob/main/pom.xml#L243 to point to locally built artifact (if implementation was already present in `<kogito-quarkus.version>1.14.0.Final</kogito-quarkus.version>` then this should be enough).
5. Proceed with instructions on how to build the quarkus-platform (in readme).
6. The given test then should pass.

2021-12-07 10:25 UTC, jstastny-cz commented on integration-tests/integration-tests-quarkus-resteasy-reactive/pom.xml
> +    <quarkus.test.list.include>false</quarkus.test.list.include>
If it fails - please report similarly to KOGITO-5338 and update the comment. If it passes, just set the property to true and remove comment altogether.

2021-12-07 10:26 UTC, jstastny-cz commented on integration-tests/integration-tests-quarkus-resteasy-classic/pom.xml
> +    <quarkus.test.list.include>false</quarkus.test.list.include>
Responded to the other comment above.

2021-12-08 09:47 UTC, tkobayas commented on integration-tests/integration-tests-quarkus-resteasy-reactive/pom.xml
> +    <quarkus.test.list.include>false</quarkus.test.list.include>
Thank you, @jstastny-cz

In order to test changes in a PR, we need to change `kogito-quarkus.version` in `quarkus-platform/pom.xml` like `<kogito-quarkus.version>2.0.0-SNAPSHOT</kogito-quarkus.version>`, correct? Then I also needed to change `generated-platform-project/quarkus-universe/bom/pom.xml` for kie version from `8.14.0.Beta` to `8.15.0-SNAPSHOT` after the `generated-platform-project` build.

Then I tested integration tests under quarkus-platform and found that these tests are failing:

- kogito-quarkus-decisions-integration-test
- integration-tests-quarkus-decisions
- integration-tests-quarkus-resteasy-classic
- integration-tests-quarkus-resteasy-reactive

I'll file JIRAs per test to be linked to the epic KOGITO-5337. But they seem to have the mostly same cause because those tests are `@QuarkusIntegrationTest`.

2021-12-08 10:10 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java
> +        STATIC_HTTP_RESOURCE,
> I expect all RESOURCE are STATIC_HTTP_RESOURCE in terms of runtime
> ...
> Said differently, can we just get rid of RESOURCE and convert everything to a single category?

Hmm, I see several cases where files are generated not under "META-INF/resources/" which means those files are not intended to be published as static resources. In other words, they are not directly accessed via http but are retrieved by internal code. Am I misunderstanding?

e.g.
https://github.com/kiegroup/kogito-runtimes/blob/main/kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/ProcessCodegen.java#L539
https://github.com/kiegroup/kogito-runtimes/blob/main/kogito-codegen-modules/kogito-codegen-processes/src/main/java/org/kie/kogito/codegen/process/persistence/PersistenceGenerator.java#L295-L298

@evacchi Do you have any opinions on this?

2021-12-09 05:43 UTC, tkobayas commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/pom.xml
> +            <scope>provided</scope>
@danielezonca  Ah, you mean completely removing the `quarkus-undertow-deployment` dependency? Yeah, we can still compile and user application can add `quarkus-undertow` if needed... It makes sense to me so removing.

@evacchi  let use know if you have an objection.

2021-12-09 05:43 UTC, tkobayas commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common/pom.xml
> +            <scope>provided</scope>
Same as above.

2021-12-09 05:48 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFile.java
> +        }
@evacchi and I discussed that automatically adding prefix may confuse the codegen developers but not very opinionated. Anyway, firstly we need to confirm whether we will define STATIC_HTTP_RESOURCE only or STATIC_HTTP_RESOURCE and RESOURCE.

2021-12-09 08:30 UTC, evacchi commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java
> +            }
@danielezonca RESOURCEs are just `src/main/resources`, while STATIC_HTTP_RESOURCEs are `src/main/resources/META-INF/resources` which have to be notified to Quarkus, so, I do believe they need to be distinct.

2021-12-09 08:32 UTC, evacchi commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFile.java
> +        }
the original PR used RESOURCE and checked against the path, which I advised against.

2021-12-09 08:47 UTC, tkobayas commented on quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java
> +        generatedBeanBuildItems.forEach(b -> jaxrsProducer.produce(new GeneratedJaxRsResourceBuildItem(b.getName(), b.getData())));
@danielezonca  Thank you for pointing this out. I have updated this PR to create `GeneratedJaxRsResourceBuildItem` only for REST resource classes. I think it's the expected usage. Could you kindly confirm @geoand ?

2021-12-10 05:20 UTC, tkobayas commented
Jenkins run kogito-apps tests

2021-12-10 05:22 UTC, tkobayas commented
Jenkins run optaplanner tests
Jenkins run optaplanner-quickstarts tests
Jenkins run optaweb-vehicle-routing tests

2021-12-10 09:10 UTC, evacchi commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java
> +        STATIC_HTTP_RESOURCE,
I replied in the other comments, I believe it is correct that the two are distinct. Although they are both "Java resources", those that have to be "published" to the web server ("static HTTP resources") must be treated differently, so to me it makes sense to advertise the difference in the type

2021-12-10 09:27 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java
> +        STATIC_HTTP_RESOURCE,
Ok thanks for the clarification, what about make this difference explicit also for `RESOURCE`? Like with `INTERNAL_RESOURCE` or `CLASSPATH_RESOURCE`? 
So that it becomes even more clear that in this case the resource is available only for internal usage

2021-12-10 09:39 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFileType.java
> +        STATIC_HTTP_RESOURCE,
`INTERNAL_RESOURCE` sounds good to me. WDYT, @evacchi ?

2021-12-10 09:53 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-api/src/main/java/org/kie/kogito/codegen/api/GeneratedFile.java
> +        }
Okay, now we can come back to the question "Should we automatically add `META-INF/resources` for `STATIC_HTTP_RESOURCE` in `GeneratedFile` constructor?". I'm not opinionated but let me confirm...
@danielezonca , do you still think it's better to add it automatically? 
@evacchi , do you agree with @danielezonca ?

2021-12-14 06:22 UTC, tkobayas commented
@evacchi @danielezonca Regarding the remaining points, I update this PR as follows:
- Changed the name `RESOURCE` to `INTERNAL_RESOURCE`
- Automatically add "META-INF/resources/" to STATIC_HTTP_RESOURCE path. Note that the prefix is added in GeneratedFile constructor, not when the file is written because `GeneratedFile.path` and `GeneratedFile.pathAsString` can be accessed by other classes so it should have its correct path from the beginning.

I'm open to further changes/revisions. Thanks!

2021-12-14 07:25 UTC, tkobayas commented
(build) kogito-runtimes
```
[2021-12-14T06:29:39.426Z] [ERROR] Tests run: 14, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.148 s <<< FAILURE! - in org.kie.kogito.codegen.tests.BusinessRuleUnitIT
[2021-12-14T06:29:39.426Z] [ERROR] org.kie.kogito.codegen.tests.BusinessRuleUnitIT.testSettingOtherVariableFromAutoGeneratedRuleUnit  Time elapsed: 0.099 s  <<< ERROR!
[2021-12-14T06:29:39.426Z] org.kie.kogito.codegen.rules.RuleCodegenError:
[2021-12-14T06:29:39.426Z] Errors were generated during the code-generation process:
[2021-12-14T06:29:39.426Z] java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
[2021-12-14T06:29:39.426Z]
[2021-12-14T06:29:39.426Z]      at org.kie.kogito.codegen.tests.BusinessRuleUnitIT.testSettingOtherVariableFromAutoGeneratedRuleUnit(BusinessRuleUnitIT.java:240)
[2021-12-14T06:29:39.426Z] Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
[2021-12-14T06:29:39.426Z]      at org.kie.kogito.codegen.tests.BusinessRuleUnitIT.testSettingOtherVariableFromAutoGeneratedRuleUnit(BusinessRuleUnitIT.java:240)
[2021-12-14T06:29:39.426Z] Caused by: java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
```
Will check...

2021-12-14 07:41 UTC, danielezonca approved these changes
Thanks for the PR, LGTM 👍

2021-12-14 09:40 UTC, tkobayas commented
Jenkins run kogito-runtimes tests

2021-12-14 10:22 UTC, tkobayas commented
@r00ta @MarianMacik Could you kindly review as well? Thanks!

2021-12-14 11:10 UTC, danielezonca commented
@tkobayas 
Let's remove @r00ta : he is not an expert of this part of the code and he is also off today :) 

PS: there is a conflict to resolve

2021-12-16 08:49 UTC, tkobayas commented
Updated https://github.com/kiegroup/kogito-examples/pull/1004 in order to fix newly added DashboardsListTest.

Jenkins run kogito-examples tests

2021-12-17 02:44 UTC, tkobayas commented
Summary of this PR:
- Users can use RESTEasy reactive (See `integration-tests-quarkus-resteasy-reactive`) with codegen capability
- No need of `quarkus-undertow` for both RESTEasy classic and RESTEasy reactive even if codegen generates static http resources (thanks to AdditionalStaticResourceBuildItem). So `quarkus-undertow` is no longer in the extension's dependecy. If your app need it, add `quarkus-undertow` dependency to the app explicitly.
- Now `GeneratedFileType.Category.RESOURCE` is split into `INTERNAL_RESOURCE` and `STATIC_HTTP_RESOURCE`. Kogito codegen developers need to choose from them. If the resource is retrieved by internal code, use `INTERNAL_RESOURCE`. If the resource is pulished as a static http resource, use `STATIC_HTTP_RESOURCE`. `STATIC_HTTP_RESOURCE` automatically adds `META-INF/resources/` to its path so codegen developer should specify its path without `META-INF/resources/` (e.g. `monitoring/dashboards/`).
- If tests require to access such static http resources, the tests need to be annotated with `@QuarkusIntegrationTest` in integration-test phase rather than `@QuarkusTest`
- You cannot mix `@QuarkusIntegrationTest` and `@QuarkusTest` in the same integration-test phase.

2021-12-17 15:04 UTC, danielezonca commented
> * If tests require to access such static http resources, the tests need to be annotated with `@QuarkusIntegrationTest` in integration-test phase rather than `@QuarkusTest`

@tkobayas 
Can you please better clarify this? As far as I remember we mainly use `@QuarkusTest` so we might add some doc to explain when to use what 🤔

2021-12-21 08:11 UTC, tkobayas commented
hi @danielezonca ,

`AdditionalStaticResourceBuildItem` makes generated static resources available to outside (even without `quarkus-undertow`). However, it requires `@QuarkusIntegrationTest` (https://github.com/quarkusio/quarkus/issues/20846#issuecomment-961026669) because of its build cycle. Sorry, I'm not knowedgable how `@QuarkusTest` intervenes in the build cycle but at the point of `@QuarkusTest`, those static resources are not yet available. In other words, `@QuarkusIntegrationTest` seems to be the true "integration test". 

I think this javadoc explains well.
https://javadoc.io/doc/io.quarkus/quarkus-junit5/2.5.1.Final/io/quarkus/test/junit/QuarkusIntegrationTest.html

Probably tests in Kogito repo should align:

1. `@QuarkusTest` as unit tests for surefire-plugin
2. `@QuarkusIntegrationTest` as integration tests (`*IT.java`) for failsafe-plugin

?

If a case where `@QuarkusTest` is required (e.g. requires injection) and also needs to access static resources, we can work around by `@QuarkusTest` + `quarkus-undertow` dependency (test scope).

Do you think it's acceptable to kogito developers? And where is the good place to document this?

2021-12-22 13:43 UTC, evacchi commented
restarting the GHA build for examples. I think this can be merged if no further changes are required + the build is green

2021-12-22 14:36 UTC, evacchi commented
/cc @ricardozanini 

BTW today GHA is on vacation 🕺

2021-12-22 20:41 UTC, ricardozanini commented
> /cc @ricardozanini
> 
> BTW today GHA is on vacation 🕺

Not anymore. :)

2021-12-23 01:35 UTC, tkobayas commented
Thank you for re-triggering and I see a compilation error. I need to merge main again and fix.

2021-12-23 06:24 UTC, tkobayas commented
Regarding the SonarCloud coverage report, the uncovered codes are not directly related to this PR changes. Maybe we can add more tests to increase the coverage though....

2021-12-23 08:04 UTC, tkobayas commented on quarkus/addons/knative/eventing/deployment/pom.xml
> +    </dependency>
@ricardozanini With this PR, `kogito-quarkus-common-deployment` no longer have `quarkus-undertow-deployment` dependency so adding here.

2021-12-23 08:06 UTC, tkobayas commented on kogito-codegen-modules/kogito-codegen-processes/src/test/java/org/kie/kogito/codegen/process/events/ProcessCloudEventMetaFactoryGeneratorTest.java
> +        assertReturnExpressionContains(processedcustomersMethod, "process.messagestartevent.processedcustomers", EventKind.PRODUCED);
@kostola This test failed randomly (depending on the method order) so changed. If you want to implement it differently, please change it after this PR.

2021-12-23 08:39 UTC, tkobayas commented
GHA : Kogito Examples Build
```
2021-12-23T06:35:28.4106052Z [INFO] Kogito Example :: Onboarding Example :: HR with Drools FAILURE [ 47.107 s]
...
2021-12-23T06:35:28.4321764Z [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.6.0.Final:build (default) on project hr: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2021-12-23T06:35:28.4325176Z [ERROR]    [error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateModel threw an exception: org.kie.kogito.codegen.rules.RuleCodegenError: Errors were generated during the code-generation process:
2021-12-23T06:35:28.4327788Z [ERROR] java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
2021-12-23T06:35:28.4328568Z [ERROR]
2021-12-23T06:35:28.4330305Z [ERROR]    at org.kie.kogito.codegen.rules.IncrementalRuleCodegen.internalGenerate(IncrementalRuleCodegen.java:163)
2021-12-23T06:35:28.4332778Z [ERROR]    at org.kie.kogito.codegen.core.AbstractGenerator.generate(AbstractGenerator.java:69)
2021-12-23T06:35:28.4335005Z [ERROR]    at org.kie.kogito.codegen.core.ApplicationGenerator.lambda$generateComponents$0(ApplicationGenerator.java:97)
2021-12-23T06:35:28.4336947Z [ERROR]    at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
2021-12-23T06:35:28.4338616Z [ERROR]    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
2021-12-23T06:35:28.4340259Z [ERROR]    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-12-23T06:35:28.4342051Z [ERROR]    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-12-23T06:35:28.4343763Z [ERROR]    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
2021-12-23T06:35:28.4345313Z [ERROR]    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-12-23T06:35:28.4346993Z [ERROR]    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
2021-12-23T06:35:28.4349240Z [ERROR]    at org.kie.kogito.codegen.core.ApplicationGenerator.generateComponents(ApplicationGenerator.java:99)
2021-12-23T06:35:28.4351761Z [ERROR]    at org.kie.kogito.codegen.core.ApplicationGenerator.generate(ApplicationGenerator.java:74)
2021-12-23T06:35:28.4354574Z [ERROR]    at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles(KogitoAssetsProcessor.java:159)
2021-12-23T06:35:28.4358012Z [ERROR]    at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateModel(KogitoAssetsProcessor.java:106)
...
2021-12-23T06:35:28.4429735Z [ERROR] Caused by: java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
2021-12-23T06:35:28.4431023Z [ERROR]    at com.github.javaparser.ast.Node.getData(Node.java:505)
2021-12-23T06:35:28.4432570Z [ERROR]    at com.github.javaparser.ast.CompilationUnit.getPrinter(CompilationUnit.java:154)
2021-12-23T06:35:28.4434175Z [ERROR]    at com.github.javaparser.ast.Node.lambda$getPrinter$1(Node.java:199)
2021-12-23T06:35:28.4435167Z [ERROR]    at java.base/java.util.Optional.map(Optional.java:265)
2021-12-23T06:35:28.4436340Z [ERROR]    at com.github.javaparser.ast.Node.getPrinter(Node.java:199)
2021-12-23T06:35:28.4437622Z [ERROR]    at com.github.javaparser.ast.Node.toString(Node.java:322)
2021-12-23T06:35:28.4438978Z [ERROR]    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
```
RuleCodegenError is caused by drools (drools-model-compiler) executable-model code gen processing and the message `No data of this type found. Use containsData to check for this first.` comes from javaparser so not likely related to this PR. I saw this error in kogito-runtimes `org.kie.kogito.codegen.tests.BusinessRuleUnitIT.testSettingOtherVariableFromAutoGeneratedRuleUnit` and kogito-examples `org.kie.kogito.examples:hr` so far. This seems to be a rare random issue. Needs some investigation in the future.

2021-12-23 09:06 UTC, tkobayas commented
> restarting the GHA build for examples. I think this can be merged if no further changes are required + the build is green

Hi @evacchi , I merged main branch again and made some fixes. Currently GHA "Kogito Examples Build" failed but it's not related to this PR (https://github.com/kiegroup/kogito-runtimes/pull/1757#issuecomment-1000135842) and SonarCloud failed but I think it is not caused by this PR (https://github.com/kiegroup/kogito-runtimes/pull/1757#issuecomment-1000073247).

If you think it's okay to merge (with squash), please do. Note that https://github.com/kiegroup/kogito-examples/pull/1004 has be merged as well (I re-run the tests in the PR but it's redundant).

This PR has some ramifications to other kogito developers as I wrote in https://github.com/kiegroup/kogito-runtimes/pull/1757#issuecomment-996390447 and https://github.com/kiegroup/kogito-runtimes/pull/1757#issuecomment-998560583 (and I'll be off next week) so... we may delay merging until new year :)

2021-12-23 15:08 UTC, ricardozanini commented on quarkus/addons/knative/eventing/deployment/pom.xml
> +    </dependency>
@tkobayas the Knative add-on doesn't require explicitly undertow. I believe that it comes from the HTTP Messaging: https://github.com/quarkiverse/quarkus-reactive-messaging-http

Since you've made a lot of changes, can you please confirm if this add-on still requires undertow? Otherwise, we can remove it.

2021-12-24 05:30 UTC, tkobayas commented
(build) kogito-examples : Probably a flaky test. 
```
[2021-12-24T03:28:14.112Z] [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 434.907 s <<< FAILURE! - in org.kie.kogito.examples.OutboxIT
[2021-12-24T03:28:14.112Z] [ERROR] org.kie.kogito.examples.OutboxIT.testSendProcessEvents  Time elapsed: 304.92 s  <<< ERROR!
[2021-12-24T03:28:14.112Z] org.awaitility.core.ConditionTimeoutException:
```

2021-12-24 06:20 UTC, tkobayas commented on quarkus/addons/knative/eventing/deployment/pom.xml
> +    </dependency>
@ricardozanini Thank you for the reply. `quarkus-undertow` dependency was in `quarkus/addons/knative/eventing/runtime/pom.xml`. I removed it so now knative addon works without `quarkus-undertow`. Tests passed.

2021-12-27 14:44 UTC, ricardozanini commented on quarkus/addons/knative/eventing/deployment/pom.xml
> +    </dependency>
Yeah, I had to add because Quarkus Maven Plugin was complaining about it. Glad that worked now that you've removed the transients.

2021-12-27 14:45 UTC, ricardozanini approved these changes
Thank you for this effort!

2022-01-05 08:15 UTC, tkobayas commented
Again, regarding the SonarCloud coverage report, the uncovered codes are not directly related to this PR changes. Maybe we can add more tests to increase the coverage though....

2022-01-05 08:26 UTC, merged

2022-10-12 09:31 UTC, tarilabs commented on integration-tests/integration-tests-quarkus-decisions/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicAddIT.java
> +@QuarkusIntegrationTest
Thanks for pointing me out to this thread @tkobayas , I would like to explore if it's feasible to produce a more meaningful help/warn message, reported in https://github.com/quarkusio/quarkus/issues/28526