KOGITO-6401 SW examples fixes
kiegroup/kogito-runtimes pull request #1783
Opened 2021-12-13 08:26 UTC by cristianonicolai

- Fix jq evaluation for expressions
- Add JsonNode for native build
- Use Quarkus Config for build process

2021-12-13 12:09 UTC, fjtirado requested changes
Although I like the idea of passing KogitoBuildContext to PArserContext rather than having WorkflowAppContext, I do not think is related with the solution provided, so probably we should use a different PR for that. 
About the fix itself I do not think compiling the expression to determine if it is a valid expression is the way to go. We should rather improve the regular expression. That will be a simpler fix.

2021-12-13 12:40 UTC, fjtirado commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
> -              <capabilities>
why this need to be removed?

2021-12-13 12:42 UTC, fjtirado commented on kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/bodybuilders/ParamsRestWorkItemHandlerBodyBuilder.java
> +        return parameters.isEmpty() || (parameters.size() == 1 && parameters.containsKey(BODY_BUILDER)) ? inputModel : parameters;
Body builder should have been removed before

2021-12-13 12:42 UTC, fjtirado commented on kogito-workitems/kogito-rest-workitem/src/main/java/org/kogito/workitem/rest/RestWorkItemHandlerUtils.java
> +    private static void setValue(PropertyDescriptor[] propertyDescriptors, Object target, String name, Object value) {
This code is going to be removed in 6360

2021-12-13 12:44 UTC, fjtirado commented on kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpressionHandler.java
> +        try {
Rather than compiling, we should change the regular expression, there are some discussion going on in the spec about the ways to identify an expression

2021-12-13 12:45 UTC, fjtirado commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java
> +        reflectiveClass.produce(new ReflectiveClassBuildItem(true, true, JsonNode.class));
Ok, nice catch!!

2021-12-13 12:46 UTC, fjtirado commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/pom.xml
> +    <dependency>
This file is not really changed, isnt it?

2021-12-13 12:47 UTC, fjtirado commented on kogito-serverless-workflow/kogito-serverless-workflow-utils/pom.xml
> +    <dependency>
This might be an issue, since serverless-workflow-utils is also intender to be included at runtime

2021-12-13 13:51 UTC, ricardozanini commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
> -              <capabilities>
yeah, we need to fix these poms for the other extensions as well. @cristianonicolai can you please open a JIRA to refactor them?

2021-12-13 15:54 UTC, cristianonicolai commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow/pom.xml
> -              <capabilities>
https://issues.redhat.com/browse/KOGITO-6413

2021-12-15 08:55 UTC, fjtirado commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java
> +    public ServerlessWorkflowParser withContext(KogitoBuildContext context) {
I do not think KogitoBuildContext is optional (withIdGenerator was introduced to allow the possibilitiy of changing the default generator, which is now incremental). 
I think it should be included in of method

2021-12-15 09:01 UTC, fjtirado commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java
> +        reflectiveClass.produce(new ReflectiveClassBuildItem(true, true, JsonNode.class));
Now wondering, since JsonNode is needed because of WIH, if this should be done in a different place, because we are probably having the same issue when using REST WIH in native mode for bpmn

2021-12-15 11:45 UTC, fjtirado commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java
> +        reflectiveClass.produce(new ReflectiveClassBuildItem(true, true, JsonNode.class));
I think this is not needed once this line is merged https://github.com/kiegroup/kogito-runtimes/pull/1776/files#diff-23d9619bb698f20ecb074ae9ba0838a831af05058a4ca396c9b28796558a773fR323

2021-12-15 17:26 UTC, ricardozanini commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java
> +        reflectiveClass.produce(new ReflectiveClassBuildItem(true, true, JsonNode.class));
@fjtirado agreed

2021-12-16 01:53 UTC, cristianonicolai commented on kogito-serverless-workflow/kogito-serverless-workflow-utils/pom.xml
> +    <dependency>
removed

2021-12-16 01:56 UTC, cristianonicolai commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/ServerlessWorkflowParser.java
> +    public ServerlessWorkflowParser withContext(KogitoBuildContext context) {
done

2021-12-16 01:57 UTC, cristianonicolai commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/pom.xml
> +    <dependency>
just formatting

2021-12-16 11:02 UTC, fjtirado commented on kogito-serverless-workflow/kogito-jq-expression/src/main/java/org/kie/kogito/expr/jq/JqExpressionHandler.java
> +        try {
After discussing with Cristiano, compiling is probably the safest way go.
In future, we should change ExpressionHandler interface so rather than having to compile twice, we do that
ExpressionHandlerFactory.of (exprLanguage, expr) and then have isValid() and parse() methods, so we just compile once and not twice (as forced by current interface). 
Lets open a JIRA for that

2021-12-16 11:03 UTC, fjtirado approved these changes
LGTM
Thanks for your patience @cristianonicolai

2021-12-16 11:28 UTC, fjtirado commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/utils/ServerlessWorkflowUtils.java
> +        if (function != null && context != null &&
We can probably write this is a better way, but in any case, not related with the JIRA

2021-12-16 11:29 UTC, fjtirado commented
jenkins rerun kogito-examples tests

2021-12-16 12:20 UTC, fjtirado commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/deployment/ServerlessWorkflowAssetsProcessor.java
> +        reflectiveClass.produce(new ReflectiveClassBuildItem(true, true, JsonNode.class));
I checked in native and still failing, so will be fixing with an Kogito-6430 upcoming PR

2021-12-17 04:11 UTC, cristianonicolai commented
Jenkins rerun kogito-runtimes tests

2021-12-17 10:29 UTC, merged