[DROOLS-6662] move Rule Unit impl from Kogito to Drools
kiegroup/kogito-runtimes pull request #1930
Opened 2022-01-24 18:37 UTC by mariofusco

**JIRA**: https://issues.redhat.com/browse/DROOLS-6662

2022-01-24 19:54 UTC, kie-ci1 commented
**PR job** #863 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2461
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/863/testReport/org.acme.travels/PersonProcessTest/testAdult/">org.acme.travels.PersonProcessTest.testAdult</a></summary>
org.opentest4j.AssertionFailedError: expected: <2> but was: <5>
	at org.acme.travels.PersonProcessTest.testAdult(PersonProcessTest.java:55)

</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/863/testReport/org.acme.travels/PersonProcessTest/testChild/">org.acme.travels.PersonProcessTest.testChild</a></summary>
org.opentest4j.AssertionFailedError: expected: <1> but was: <5>
	at org.acme.travels.PersonProcessTest.testChild(PersonProcessTest.java:71)

</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/863/display/redirect

2022-01-25 08:16 UTC, danielezonca commented on api/kogito-api/src/main/java/org/kie/kogito/Application.java
> +    <T extends KieEngine> T get(Class<T> clazz);
This change is wrong, we should use a kogito marker interface

2022-01-25 08:16 UTC, danielezonca commented on api/kogito-api/src/main/java/org/kie/kogito/Config.java
> +    <T extends KieConfig> T get(Class<T> clazz);
Same here

2022-01-25 08:16 UTC, danielezonca commented on api/kogito-api/src/main/java/org/kie/kogito/KogitoConfig.java
> +public interface KogitoConfig extends KieConfig {
This should be reverted

2022-01-25 08:16 UTC, danielezonca commented on api/kogito-api/src/main/java/org/kie/kogito/KogitoEngine.java
> +public interface KogitoEngine extends KieEngine {
Same here

2022-01-25 08:16 UTC, danielezonca commented on api/kogito-api/src/main/java/org/kie/kogito/StaticApplication.java
> +    private final Map<Class<? extends KieEngine>, KieEngine> engineMap = new HashMap<>();
Same here

2022-01-25 08:16 UTC, danielezonca commented on api/kogito-api/src/main/java/org/kie/kogito/StaticConfig.java
> +    private final Map<Class<? extends KieConfig>, KieConfig> configMap = new HashMap<>();
Same here

2022-01-25 08:16 UTC, danielezonca commented on drools/kogito-drools-wiring-static/src/main/java/org/kie/kogito/wiring/statics/KogitoStaticServiceRegistry.java
> -        registerService("org.kie.kogito.rules.DataSource$Factory", "org.kie.kogito.rules.units.impl.DataSourceFactoryImpl", false);
Is it still necessary to have a Kogito static service registry?

2022-01-25 08:16 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/ApplicationConfigQuarkusTemplate.java
> +            Instance<org.kie.kogito.rules.KieConfig> configs) {
Same here

2022-01-25 08:16 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-core/src/main/resources/class-templates/config/ApplicationConfigSpringTemplate.java
> +            Collection<org.kie.kogito.rules.KieConfig> configs) {
Same here

2022-01-25 08:16 UTC, danielezonca commented on springboot/addons/explainability/src/test/java/org/kie/kogito/explainability/ApplicationMock.java
> +    public <T extends KieEngine> T get(Class<T> clazz) {
Same here

2022-01-25 08:16 UTC, danielezonca commented on quarkus/addons/explainability/runtime/src/test/java/org/kie/kogito/explainability/ApplicationMock.java
> +    public <T extends KieEngine> T get(Class<T> clazz) {
Same here

2022-01-25 08:16 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/unit/PersonsUnit.java
> -    @DefaultEntryPoint
Why this change?

2022-01-25 08:16 UTC, danielezonca commented on kogito-codegen-modules/kogito-codegen-integration-tests/src/test/java/org/kie/kogito/codegen/unit/StockUnit.java
> +import org.drools.ruleunits.impl.EventListDataStream;
This should become part of the API (or hidden with a factory method) given that users access it

2022-01-25 08:32 UTC, mariofusco commented on kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/unit/PersonsUnit.java
> -    @DefaultEntryPoint
Fixed.

2022-01-25 09:56 UTC, kie-ci1 commented
**PR job** #866 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2461
- FAILED: 2

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/866/testReport/org.acme.travels/PersonProcessTest/testAdult/">org.acme.travels.PersonProcessTest.testAdult</a></summary>
org.opentest4j.AssertionFailedError: expected: <2> but was: <5>
	at org.acme.travels.PersonProcessTest.testAdult(PersonProcessTest.java:55)

</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/866/testReport/org.acme.travels/PersonProcessTest/testChild/">org.acme.travels.PersonProcessTest.testChild</a></summary>
org.opentest4j.AssertionFailedError: expected: <1> but was: <5>
	at org.acme.travels.PersonProcessTest.testChild(PersonProcessTest.java:71)

</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/866/display/redirect

2022-01-25 10:06 UTC, kie-ci1 commented
**PR job** #929 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 289
- FAILED: 32

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/929/testReport/org.acme.travels/PersonProcessTest/testAdult/">org.acme.travels.PersonProcessTest.testAdult</a></summary>
org.opentest4j.AssertionFailedError: expected: <2> but was: <5>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
	at org.acme.travels.PersonProcessTest.testAdult(PersonProcessTest.java:55)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:956)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:776)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire [...]

2022-01-25 12:47 UTC, kie-ci1 commented
**PR job** #930 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 321
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/930/display/redirect or see console log:
```spoiler Console Logs
[2022-01-25T12:47:10.654Z] [INFO]    +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[2022-01-25T12:47:10.654Z] [INFO]    +- com.github.jknack:handlebars:jar:4.2.0:test
[2022-01-25T12:47:10.654Z] [INFO]    +- com.github.jknack:handlebars-helpers:jar:4.2.0:test
[2022-01-25T12:47:10.654Z] [INFO]    +- com.flipkart.zjsonpatch:zjsonpatch:jar:0.4.4:test
[2022-01-25T12:47:10.654Z] [INFO]    +- commons-fileupload:commons-fileupload:jar:1.4:test
[2022-01-25T12:47:10.654Z] [INFO]    +- org.eclipse.jetty.http2:http2-server:jar:9.4.39.v20210325:test
[2022-01-25T12:47:10.654Z] [INFO]    |  \- org.eclipse.jetty.http2:http2-common:jar:9.4.39.v20210325:test
[2022-01-25T12:47:10.654Z] [INFO]    |     \- org.eclipse.jetty.http2:http2-hpack:jar:9.4.39.v20210325:test
[2022-01-25T12:47:10.654Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-server:jar:9.4.39.v20210325:test
[2022-01-25T12:47:10.654Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-conscrypt-server:jar:9.4.39.v20210325:test
[2022-01-25T12:47:10.654Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-conscrypt-client:jar:9.4.39.v20210325:test
[2022-01-25T12:47:10.654Z] [INFO]    |  \- org.eclipse.jetty:jetty-alpn-client:jar:9.4.39.v20210325:test
[2022-01-25T12:47:10.654Z] [INFO]    +- org.conscrypt:conscrypt-openjdk-uber:jar:2.2.1:test
[2022-01-25T12:47:10.654Z] [INFO]    \- net.javacrumbs.json-unit:json-unit-core:jar:2.12.0:test
[2022-01-25T12:47:10.654Z] [INFO]       +- org.opentest4j:opentest4j:jar:1.1.1:test
[2022-01-25T12:47:10.654Z] [INFO]       \- org.hamcrest:hamcrest-core:jar:1.3:test
[2022-01-25T12:47:10.654Z] [INFO] ------------------------------------------------------------------------
[2022-01-25T12:47:10.654Z] [INFO] Reactor Summary for Kogito Example 2.0.0-SNAPSHOT:
[2022-01-25T12:47:10.654Z] [INFO] 
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example ..................................... SUCCESS [  2.398 s]
[2022-01-25T12:47:10.654Z] [INFO] kogito-quarkus-examples ............................ SUCCESS [  0.091 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Decision Table - Quarkus ......... SUCCESS [ 30.722 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: DMN Metrics Quarkus .............. FAILURE [  0.996 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: DMN Event-Driven :: Quarkus ...... SUCCESS [01:48 min]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: DMN Incubation API With Quarkus .. SUCCESS [ 18.692 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: DMN with Knative Eventing and Quarkus SUCCESS [ 25.186 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: DMN with listeners - Quarkus ..... SUCCESS [ 25.898 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: DMN :: PMML - QUARKUS ............ SUCCESS [ 41.978 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: DMN .............................. SUCCESS [ 26.010 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: DMN Tracing - Quarkus ............ SUCCESS [ 52.919 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Flexible Process - Quarkus ....... SUCCESS [ 31.221 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Travel Agency .................... SUCCESS [  0.111 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Travel Agency :: Basic ........... SUCCESS [ 26.710 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Travel Agency :: Extended ........ SUCCESS [  0.109 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Travel Agency :: Travels ......... SUCCESS [01:10 min]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Travel Agency :: Visas ........... SUCCESS [ 10.614 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Onboarding Example ............... SUCCESS [  0.074 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Onboarding Example :: HR with Drools SUCCESS [ 34.609 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Onboarding Example :: Payroll with DMN SUCCESS [ 27.414 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Onboarding Example :: Onboarding with Business Process Quarkus SUCCESS [ 32.324 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: PMML Event-Driven - Quarkus ...... SUCCESS [01:15 min]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: PMML Incubation API With Quarkus . SUCCESS [ 28.644 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: PMML - Quarkus ................... SUCCESS [ 27.806 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Business Rules Quarkus ... SUCCESS [ 23.439 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process :: Decisions :: Quarkus .. SUCCESS [ 29.705 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process :: Decisions :: REST Quarkus SUCCESS [ 31.718 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Scripts With Quarkus ..... SUCCESS [ 19.595 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Incubation API With Quarkus SUCCESS [ 20.977 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Infinispan Persistence Quarkus SUCCESS [ 38.692 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process with Kafka and Quarkus, multiple channels SUCCESS [ 42.153 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Kafka Persistence Quarkus  SUCCESS [ 41.685 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process with Kafka and Quarkus ... SUCCESS [ 43.840 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process with Knative Eventing and Quarkus SUCCESS [ 34.910 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process MongoDB Persistence Quarkus SUCCESS [ 43.143 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Monitoring :: Quarkus .... SUCCESS [ 37.913 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process, OptaPlanner and Quarkus . SUCCESS [ 46.221 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Transactional Outbox :: MongoDB and Quarkus SUCCESS [02:59 min]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Client Performance test .......... SUCCESS [  0.652 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Quarkus Performance test ......... SUCCESS [  8.577 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process PostgreSQL Persistence Quarkus SUCCESS [ 37.051 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process and Quarkus .............. SUCCESS [ 37.481 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Service Rest Cal with Quarkus SUCCESS [ 10.727 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Rest :: Quarkus .......... SUCCESS [ 26.616 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Service Rest WorkItem call with Quarkus SUCCESS [ 11.257 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Scripts With Quarkus ..... SUCCESS [ 22.750 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Saga with Quarkus ........ SUCCESS [ 31.388 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Service Calls with Quarkus SUCCESS [ 23.370 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Timer with Quarkus ....... SUCCESS [  8.287 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process Usertasks With Custom Lifecycle SUCCESS [ 22.525 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process with Usertasks Quarkus :: Console SUCCESS [ 54.763 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process with Usertasks Quarkus ... SUCCESS [ 21.419 s]
[2022-01-25T12:47:10.654Z] [INFO] Kogito Example :: Process UserTasks with Timer Quarkus :: Console SUCCES [...]

2022-01-25 15:18 UTC, kie-ci1 commented
**PR job** #939 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 321
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/939/display/redirect or see console log:
```spoiler Console Logs
[2022-01-25T15:17:53.142Z] [INFO]    +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[2022-01-25T15:17:53.142Z] [INFO]    +- com.github.jknack:handlebars:jar:4.2.0:test
[2022-01-25T15:17:53.142Z] [INFO]    +- com.github.jknack:handlebars-helpers:jar:4.2.0:test
[2022-01-25T15:17:53.142Z] [INFO]    +- com.flipkart.zjsonpatch:zjsonpatch:jar:0.4.4:test
[2022-01-25T15:17:53.142Z] [INFO]    +- commons-fileupload:commons-fileupload:jar:1.4:test
[2022-01-25T15:17:53.142Z] [INFO]    +- org.eclipse.jetty.http2:http2-server:jar:9.4.39.v20210325:test
[2022-01-25T15:17:53.142Z] [INFO]    |  \- org.eclipse.jetty.http2:http2-common:jar:9.4.39.v20210325:test
[2022-01-25T15:17:53.142Z] [INFO]    |     \- org.eclipse.jetty.http2:http2-hpack:jar:9.4.39.v20210325:test
[2022-01-25T15:17:53.142Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-server:jar:9.4.39.v20210325:test
[2022-01-25T15:17:53.142Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-conscrypt-server:jar:9.4.39.v20210325:test
[2022-01-25T15:17:53.142Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-conscrypt-client:jar:9.4.39.v20210325:test
[2022-01-25T15:17:53.142Z] [INFO]    |  \- org.eclipse.jetty:jetty-alpn-client:jar:9.4.39.v20210325:test
[2022-01-25T15:17:53.142Z] [INFO]    +- org.conscrypt:conscrypt-openjdk-uber:jar:2.2.1:test
[2022-01-25T15:17:53.142Z] [INFO]    \- net.javacrumbs.json-unit:json-unit-core:jar:2.12.0:test
[2022-01-25T15:17:53.142Z] [INFO]       +- org.opentest4j:opentest4j:jar:1.1.1:test
[2022-01-25T15:17:53.142Z] [INFO]       \- org.hamcrest:hamcrest-core:jar:1.3:test
[2022-01-25T15:17:53.142Z] [INFO] ------------------------------------------------------------------------
[2022-01-25T15:17:53.142Z] [INFO] Reactor Summary for Kogito Example 2.0.0-SNAPSHOT:
[2022-01-25T15:17:53.142Z] [INFO] 
[2022-01-25T15:17:53.142Z] [INFO] Kogito Example ..................................... SUCCESS [  2.867 s]
[2022-01-25T15:17:53.143Z] [INFO] kogito-quarkus-examples ............................ SUCCESS [  0.113 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Decision Table - Quarkus ......... SUCCESS [ 36.749 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: DMN Metrics Quarkus .............. FAILURE [  1.223 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: DMN Event-Driven :: Quarkus ...... SUCCESS [02:00 min]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: DMN Incubation API With Quarkus .. SUCCESS [ 25.255 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: DMN with Knative Eventing and Quarkus SUCCESS [ 28.950 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: DMN with listeners - Quarkus ..... SUCCESS [ 25.763 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: DMN :: PMML - QUARKUS ............ SUCCESS [ 46.202 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: DMN .............................. SUCCESS [ 27.522 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: DMN Tracing - Quarkus ............ SUCCESS [ 55.703 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Flexible Process - Quarkus ....... SUCCESS [ 34.254 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Travel Agency .................... SUCCESS [  0.139 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Travel Agency :: Basic ........... SUCCESS [ 30.612 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Travel Agency :: Extended ........ SUCCESS [  0.139 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Travel Agency :: Travels ......... SUCCESS [01:19 min]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Travel Agency :: Visas ........... SUCCESS [ 11.281 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Onboarding Example ............... SUCCESS [  0.104 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Onboarding Example :: HR with Drools SUCCESS [ 37.485 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Onboarding Example :: Payroll with DMN SUCCESS [ 31.250 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Onboarding Example :: Onboarding with Business Process Quarkus SUCCESS [ 35.238 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: PMML Event-Driven - Quarkus ...... SUCCESS [01:17 min]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: PMML Incubation API With Quarkus . SUCCESS [ 23.295 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: PMML - Quarkus ................... SUCCESS [ 26.113 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Business Rules Quarkus ... SUCCESS [ 24.199 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process :: Decisions :: Quarkus .. SUCCESS [ 30.327 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process :: Decisions :: REST Quarkus SUCCESS [ 33.384 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Scripts With Quarkus ..... SUCCESS [ 21.427 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Incubation API With Quarkus SUCCESS [ 21.997 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Infinispan Persistence Quarkus SUCCESS [ 39.374 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process with Kafka and Quarkus, multiple channels SUCCESS [ 49.493 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Kafka Persistence Quarkus  SUCCESS [ 42.885 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process with Kafka and Quarkus ... SUCCESS [ 41.566 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process with Knative Eventing and Quarkus SUCCESS [ 31.224 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process MongoDB Persistence Quarkus SUCCESS [ 35.540 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Monitoring :: Quarkus .... SUCCESS [ 31.131 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process, OptaPlanner and Quarkus . SUCCESS [ 42.223 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Transactional Outbox :: MongoDB and Quarkus SUCCESS [02:40 min]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Client Performance test .......... SUCCESS [  0.828 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Quarkus Performance test ......... SUCCESS [  8.343 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process PostgreSQL Persistence Quarkus SUCCESS [ 32.968 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process and Quarkus .............. SUCCESS [ 31.293 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Service Rest Cal with Quarkus SUCCESS [  8.713 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Rest :: Quarkus .......... SUCCESS [ 19.919 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Service Rest WorkItem call with Quarkus SUCCESS [  7.898 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Scripts With Quarkus ..... SUCCESS [ 17.136 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Saga with Quarkus ........ SUCCESS [ 24.172 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Service Calls with Quarkus SUCCESS [ 19.285 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Timer with Quarkus ....... SUCCESS [  7.030 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process Usertasks With Custom Lifecycle SUCCESS [ 19.219 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process with Usertasks Quarkus :: Console SUCCESS [ 45.380 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process with Usertasks Quarkus ... SUCCESS [ 21.919 s]
[2022-01-25T15:17:53.143Z] [INFO] Kogito Example :: Process UserTasks with Timer Quarkus :: Console SUCCES [...]

2022-01-25 15:23 UTC, kie-ci1 commented
**PR job** #874 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2462
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/874/testReport/org.kie.kogito.quarkus.drools/StatefulRuleUnitServiceTest/testQueryDsService/">org.kie.kogito.quarkus.drools.StatefulRuleUnitServiceTest.testQueryDsService</a></summary>
java.lang.ClassCastException: class org.kie.kogito.drools.core.data.ListDataStore cannot be cast to class org.kie.kogito.rules.DataSource (org.kie.kogito.drools.core.data.ListDataStore and org.kie.kogito.rules.DataSource are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @32ca397b)
	at org.kie.kogito.core.rules.incubation.quarkus.support.DataSourceServiceImpl.getDataSource(DataSourceServiceImpl.java:116)
	at org.kie.kogito.core.rules.incubation.quarkus.support.DataSourceServiceImpl.add(DataSourceServiceImpl.java:65)
	at org.kie.kogito.core.rules.incubation.quarkus.support.QuarkusDataSourceService.add(QuarkusDataSourceService.java:47)
	at org.kie.kogito.core.rules.incubation.quarkus.support.QuarkusDataSourceService_ClientProxy.add(Unknown Source)
	at org.kie.kogito.quarkus.drools.StatefulRuleUnitServiceTest.testQueryDsService(StatefulRuleUnitServiceTest.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:956)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:776)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestra [...]

2022-01-25 16:01 UTC, kie-ci1 commented
**PR job** #903 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2393
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/903/testReport/org.kie.kogito.taskassigning.service/SolverExecutorTest/stopWithSolverStarted/">org.kie.kogito.taskassigning.service.SolverExecutorTest.stopWithSolverStarted</a></summary>
java.util.concurrent.TimeoutException: stopWithSolverStarted() timed out after 50 seconds
	at org.junit.jupiter.engine.extension.TimeoutInvocation.createTimeoutException(TimeoutInvocation.java:70)
	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:59)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
	Suppressed: java.lang.InterruptedException
		at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:385)
		at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
		at org.kie.kogito.taskassigning.service.SolverExecutorTest.stopWithSolverStarted(SolverExecutorTest.java:133)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMeth [...]

2022-01-25 16:17 UTC, kie-ci1 commented
**PR job** #855 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/855/display/redirect or see console log:
```spoiler Console Logs
[2022-01-25T16:16:23.295Z] QUARKUS_JIB_BASE_JVM_IMAGE=ba-docker-registry.usersys.redhat.com:5000/fabric8/java-alpine-openjdk11-jre
[2022-01-25T16:16:23.295Z] RUN_ARTIFACTS_DISPLAY_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/855/display/redirect?page=artifacts
[2022-01-25T16:16:23.295Z] ghprbCommentBody=null
[2022-01-25T16:16:23.295Z] DA_SERVICE_URL=http://da.psi.redhat.com/da/rest/v-1
[2022-01-25T16:16:23.295Z] ghprbPullTitle=[DROOLS-6662] move Rule Unit impl from Kogito to Drools
[2022-01-25T16:16:23.295Z] GIT_AUTHOR_NAME=Jenkins CI
[2022-01-25T16:16:23.295Z] ghprbActualCommitAuthorEmail=mario.fusco@gmail.com
[2022-01-25T16:16:23.295Z] GIT_COMMITTER_NAME=Jenkins CI
[2022-01-25T16:16:23.295Z] GRAALVM_HOME=/opt/tools/graalvm
[2022-01-25T16:16:23.295Z] MAVEN_OPTS=-Xmx2g
[2022-01-25T16:16:23.295Z] JENKINS_HOME=/var/lib/jenkins
[2022-01-25T16:16:23.295Z] GIT_COMMIT=ebf9ade48cbf9bc02928dfe6a0c35e508e69cbe3
[2022-01-25T16:16:23.295Z] PATH=/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin:/home/jenkins/go/bin:/opt/tools/golang/1.16/go/bin:/opt/tools/jdk1.8/bin:/opt/tools/apache-maven-3.8.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/opt/tools/graalvm/bin
[2022-01-25T16:16:23.295Z] MAVEN_HOME=/opt/tools/apache-maven-3.8.1
[2022-01-25T16:16:23.295Z] MAIL=/var/mail/jenkins
[2022-01-25T16:16:23.295Z] JENKINS_UMB_ID=rhba-eng-jenkins-casc
[2022-01-25T16:16:23.295Z] RUN_DISPLAY_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/855/display/redirect
[2022-01-25T16:16:23.295Z] _=/usr/bin/printenv
[2022-01-25T16:16:23.295Z] DEFAULT_CONFIG_BRANCH=master
[2022-01-25T16:16:23.295Z] GIT_COMMITTER_EMAIL=jenkins@eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com
[2022-01-25T16:16:23.295Z] ghprbPullAuthorLoginMention=@mariofusco
[2022-01-25T16:16:23.295Z] PWD=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[2022-01-25T16:16:23.295Z] CVE_CLASSIFICATION_URL=https://access.redhat.com/security/updates/classification
[2022-01-25T16:16:23.295Z] JAVA_HOME=/opt/tools/jdk1.8
[2022-01-25T16:16:23.295Z] REPO_LIST_FILE_PATH=script/repository-list.txt
[2022-01-25T16:16:23.295Z] HUDSON_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/
[2022-01-25T16:16:23.295Z] SEND_UMB_MESSAGE_JOB_PATH=PROD/send-umb-message
[2022-01-25T16:16:23.295Z] LANG=en_US.UTF-8
[2022-01-25T16:16:23.295Z] JOB_NAME=KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[2022-01-25T16:16:23.295Z] JENKINS_MASTER_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/
[2022-01-25T16:16:23.295Z] sha1=origin/pr/1930/merge
[2022-01-25T16:16:23.295Z] BUILD_DISPLAY_NAME=#855
[2022-01-25T16:16:23.295Z] LOCAL_NEXUS_ENABLED=true
[2022-01-25T16:16:23.295Z] LOCAL_NEXUS_IP=bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com
[2022-01-25T16:16:23.295Z] JENKINS_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/
[2022-01-25T16:16:23.295Z] BUILD_ID=855
[2022-01-25T16:16:23.295Z] NPM_REGISTRY_URL=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/
[2022-01-25T16:16:23.295Z] NIGHTLY_DEPLOYMENT_CREDENTIAL=unpacks-zip-on-qa-nexus
[2022-01-25T16:16:23.295Z] NPM_PUBLISH_SERVICE_URL=http://10.0.152.147
[2022-01-25T16:16:23.295Z] ghprbActualCommit=2913693950ae1e1675b03020ad88a1b912ed7173
[2022-01-25T16:16:23.295Z] OPTAPLANNER_BUILD_MVN_OPTS_UPSTREAM=-Dfull
[2022-01-25T16:16:23.295Z] BUILDCHAIN_CONFIG_BRANCH=main
[2022-01-25T16:16:23.295Z] JOB_BASE_NAME=kogito-runtimes.tests.downstream.optaplanner-quickstarts
[2022-01-25T16:16:23.295Z] GIT_PREVIOUS_SUCCESSFUL_COMMIT=9df30b16c7aa9b3eaf9fdea2f4a85a59e98234cf
[2022-01-25T16:16:23.295Z] RUN_TESTS_DISPLAY_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/855/display/redirect?page=tests
[2022-01-25T16:16:23.295Z] BUILD_CONFIGURATION_REPO_URL=https://gitlab.cee.redhat.com/middleware/build-configurations.git
[2022-01-25T16:16:23.295Z] BXMS_SERVICE_ACCOUNT_LOGIN=bxms-qe-service-user
[2022-01-25T16:16:23.295Z] SHLVL=3
[2022-01-25T16:16:23.295Z] HOME=/home/jenkins
[2022-01-25T16:16:23.295Z] FIREFOX_FOLDER=/opt/tools/firefox-60esr
[2022-01-25T16:16:23.295Z] GOROOT=/opt/tools/golang/1.16/go
[2022-01-25T16:16:23.295Z] NODE_DOWNLOAD_ROOT=http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/node/
[2022-01-25T16:16:23.295Z] GIT_BRANCH=origin/main
[2022-01-25T16:16:23.295Z] CI=true
[2022-01-25T16:16:23.295Z] NEXUS_CACHE_URL=https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/public/
[2022-01-25T16:16:23.295Z] NODEJS_HOME=/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3
[2022-01-25T16:16:23.295Z] WORKSPACE_TMP=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts@tmp
[2022-01-25T16:16:23.295Z] KOGITO_PROPERTIES_GENERATOR_PATH=PROD/kogito-properties-generator
[2022-01-25T16:16:23.295Z] EXECUTOR_NUMBER=0
[2022-01-25T16:16:23.295Z] JENKINS_SERVER_COOKIE=durable-d0ad0e76ce4af98f27d40b639253c550b92c8e7bc8afc00dea48b9aa47e1e949
[2022-01-25T16:16:23.295Z] GIT_URL=https://github.com/kiegroup/kogito-pipelines.git
[2022-01-25T16:16:23.295Z] NODE_LABELS=ff gui-testing kie-mem16g kie-rhel kie-rhel7 rhos-d rhos-d-kie-rhel7-xlarge-544
[2022-01-25T16:16:23.295Z] LOGNAME=jenkins
[2022-01-25T16:16:23.295Z] ghprbActualCommitAuthor=mariofusco
[2022-01-25T16:16:23.295Z] RHBA_PROD_DEPLOYMENT_REPO_URL=https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/service/local/repositories/rhba-snapshots-main/content-compressed
[2022-01-25T16:16:23.295Z] HUDSON_HOME=/var/lib/jenkins
[2022-01-25T16:16:23.295Z] JIRA_SEARCH_URL=https://issues.redhat.com/rest/api/2/search
[2022-01-25T16:16:23.295Z] SSH_CONNECTION=10.0.180.10 37732 10.0.101.27 22
[2022-01-25T16:16:23.295Z] STAGING_SERVER_URL=http://download.eng.bos.redhat.com/rcm-guest/staging/
[2022-01-25T16:16:23.295Z] ghprbPullLongDescription=**JIRA**: https://issues.redhat.com/browse/DROOLS-6662\r\n\r\nRelated PRs\r\nhttps://github.com/kiegroup/drools/pull/4149\r\nhttps://github.com/kiegroup/kogito-runtimes/pull/1930
[2022-01-25T16:16:23.295Z] NODE_NAME=rhos-d-kie-rhel7-xlarge-544
[2022-01-25T16:16:23.295Z] LESSOPEN=||/usr/bin/lesspipe.sh %s
[2022-01-25T16:16:23.295Z] GOPATH=/home/jenkins/go
[2022-01-25T16:16:23.295Z] BUILD_NUMBER=855
[2022-01-25T16:16:23.295Z] ghprbTargetBranch=main
[2022-01-25T16:16:23.295Z] MAVEN_MIRROR_REPOSITORY=https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/
[2022-01-25T16:16:23.295Z] JOB_DISPLAY_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/display/redirect
[2022-01-25T16:16:23.295Z] NPM_REGISTRY_PUBLISH_URL=http://10.0.155.78
[2022-01-25T16:16:23.295Z] HUDSON_COOKIE=2ca6d4a0-3600-41ad-adbe-01b987b1e010
[2022-01-25T16:16:23.295Z] XDG_RUNTIME_DIR=/run/user/1000
[2022-01-25T16:16:23.295Z] GIT_AUTHOR_EMAIL=jenk [...]

2022-01-25 16:37 UTC, kie-ci1 commented
**PR job** #856 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/856/display/redirect or see console log:
```spoiler Console Logs
[2022-01-25T16:36:27.522Z] QUARKUS_JIB_BASE_JVM_IMAGE=ba-docker-registry.usersys.redhat.com:5000/fabric8/java-alpine-openjdk11-jre
[2022-01-25T16:36:27.522Z] RUN_ARTIFACTS_DISPLAY_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/856/display/redirect?page=artifacts
[2022-01-25T16:36:27.522Z] ghprbCommentBody=null
[2022-01-25T16:36:27.522Z] DA_SERVICE_URL=http://da.psi.redhat.com/da/rest/v-1
[2022-01-25T16:36:27.522Z] ghprbPullTitle=[DROOLS-6662] move Rule Unit impl from Kogito to Drools
[2022-01-25T16:36:27.522Z] GIT_AUTHOR_NAME=Jenkins CI
[2022-01-25T16:36:27.522Z] ghprbActualCommitAuthorEmail=mario.fusco@gmail.com
[2022-01-25T16:36:27.522Z] GIT_COMMITTER_NAME=Jenkins CI
[2022-01-25T16:36:27.522Z] GRAALVM_HOME=/opt/tools/graalvm
[2022-01-25T16:36:27.522Z] MAVEN_OPTS=-Xmx2g
[2022-01-25T16:36:27.522Z] JENKINS_HOME=/var/lib/jenkins
[2022-01-25T16:36:27.522Z] GIT_COMMIT=ebf9ade48cbf9bc02928dfe6a0c35e508e69cbe3
[2022-01-25T16:36:27.522Z] PATH=/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin:/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3/bin:/home/jenkins/go/bin:/opt/tools/golang/1.16/go/bin:/opt/tools/jdk1.8/bin:/opt/tools/apache-maven-3.8.1/bin:/opt/tools/apache-ant-1.10.9/bin:/opt/tools/mercurial/:/opt/tools/extras/:/usr/local/bin:/usr/bin:/opt/tools/graalvm/bin
[2022-01-25T16:36:27.522Z] MAVEN_HOME=/opt/tools/apache-maven-3.8.1
[2022-01-25T16:36:27.522Z] MAIL=/var/mail/jenkins
[2022-01-25T16:36:27.522Z] JENKINS_UMB_ID=rhba-eng-jenkins-casc
[2022-01-25T16:36:27.522Z] RUN_DISPLAY_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/856/display/redirect
[2022-01-25T16:36:27.522Z] _=/usr/bin/printenv
[2022-01-25T16:36:27.522Z] DEFAULT_CONFIG_BRANCH=master
[2022-01-25T16:36:27.522Z] GIT_COMMITTER_EMAIL=jenkins@eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com
[2022-01-25T16:36:27.522Z] ghprbPullAuthorLoginMention=@mariofusco
[2022-01-25T16:36:27.522Z] PWD=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[2022-01-25T16:36:27.522Z] CVE_CLASSIFICATION_URL=https://access.redhat.com/security/updates/classification
[2022-01-25T16:36:27.522Z] JAVA_HOME=/opt/tools/jdk1.8
[2022-01-25T16:36:27.522Z] REPO_LIST_FILE_PATH=script/repository-list.txt
[2022-01-25T16:36:27.522Z] HUDSON_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/
[2022-01-25T16:36:27.522Z] SEND_UMB_MESSAGE_JOB_PATH=PROD/send-umb-message
[2022-01-25T16:36:27.522Z] LANG=en_US.UTF-8
[2022-01-25T16:36:27.522Z] JOB_NAME=KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[2022-01-25T16:36:27.522Z] JENKINS_MASTER_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/
[2022-01-25T16:36:27.522Z] sha1=origin/pr/1930/merge
[2022-01-25T16:36:27.522Z] BUILD_DISPLAY_NAME=#856
[2022-01-25T16:36:27.522Z] LOCAL_NEXUS_ENABLED=true
[2022-01-25T16:36:27.522Z] LOCAL_NEXUS_IP=bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com
[2022-01-25T16:36:27.522Z] JENKINS_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/
[2022-01-25T16:36:27.522Z] BUILD_ID=856
[2022-01-25T16:36:27.522Z] NPM_REGISTRY_URL=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/
[2022-01-25T16:36:27.522Z] NIGHTLY_DEPLOYMENT_CREDENTIAL=unpacks-zip-on-qa-nexus
[2022-01-25T16:36:27.522Z] NPM_PUBLISH_SERVICE_URL=http://10.0.152.147
[2022-01-25T16:36:27.522Z] ghprbActualCommit=c8a4f9182ce9efbaee2147b3b804a12630e319aa
[2022-01-25T16:36:27.522Z] OPTAPLANNER_BUILD_MVN_OPTS_UPSTREAM=-Dfull
[2022-01-25T16:36:27.522Z] BUILDCHAIN_CONFIG_BRANCH=main
[2022-01-25T16:36:27.522Z] JOB_BASE_NAME=kogito-runtimes.tests.downstream.optaplanner-quickstarts
[2022-01-25T16:36:27.522Z] GIT_PREVIOUS_SUCCESSFUL_COMMIT=9df30b16c7aa9b3eaf9fdea2f4a85a59e98234cf
[2022-01-25T16:36:27.522Z] RUN_TESTS_DISPLAY_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/856/display/redirect?page=tests
[2022-01-25T16:36:27.522Z] BUILD_CONFIGURATION_REPO_URL=https://gitlab.cee.redhat.com/middleware/build-configurations.git
[2022-01-25T16:36:27.522Z] BXMS_SERVICE_ACCOUNT_LOGIN=bxms-qe-service-user
[2022-01-25T16:36:27.522Z] SHLVL=3
[2022-01-25T16:36:27.522Z] HOME=/home/jenkins
[2022-01-25T16:36:27.522Z] FIREFOX_FOLDER=/opt/tools/firefox-60esr
[2022-01-25T16:36:27.522Z] GOROOT=/opt/tools/golang/1.16/go
[2022-01-25T16:36:27.522Z] NODE_DOWNLOAD_ROOT=http://download.devel.redhat.com/rcm-guest/staging/rhba/dist/node/
[2022-01-25T16:36:27.522Z] GIT_BRANCH=origin/main
[2022-01-25T16:36:27.522Z] CI=true
[2022-01-25T16:36:27.522Z] NEXUS_CACHE_URL=https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/public/
[2022-01-25T16:36:27.522Z] NODEJS_HOME=/home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3
[2022-01-25T16:36:27.522Z] WORKSPACE_TMP=/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts@tmp
[2022-01-25T16:36:27.522Z] KOGITO_PROPERTIES_GENERATOR_PATH=PROD/kogito-properties-generator
[2022-01-25T16:36:27.522Z] EXECUTOR_NUMBER=0
[2022-01-25T16:36:27.522Z] JENKINS_SERVER_COOKIE=durable-d0ad0e76ce4af98f27d40b639253c550b92c8e7bc8afc00dea48b9aa47e1e949
[2022-01-25T16:36:27.522Z] GIT_URL=https://github.com/kiegroup/kogito-pipelines.git
[2022-01-25T16:36:27.522Z] NODE_LABELS=ff gui-testing kie-mem16g kie-rhel kie-rhel7 rhos-d rhos-d-kie-rhel7-xlarge-578
[2022-01-25T16:36:27.522Z] LOGNAME=jenkins
[2022-01-25T16:36:27.522Z] ghprbActualCommitAuthor=mariofusco
[2022-01-25T16:36:27.522Z] RHBA_PROD_DEPLOYMENT_REPO_URL=https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/service/local/repositories/rhba-snapshots-main/content-compressed
[2022-01-25T16:36:27.522Z] HUDSON_HOME=/var/lib/jenkins
[2022-01-25T16:36:27.522Z] JIRA_SEARCH_URL=https://issues.redhat.com/rest/api/2/search
[2022-01-25T16:36:27.522Z] SSH_CONNECTION=10.0.180.10 35662 10.0.101.40 22
[2022-01-25T16:36:27.522Z] STAGING_SERVER_URL=http://download.eng.bos.redhat.com/rcm-guest/staging/
[2022-01-25T16:36:27.522Z] ghprbPullLongDescription=**JIRA**: https://issues.redhat.com/browse/DROOLS-6662\r\n\r\nRelated PRs\r\nhttps://github.com/kiegroup/drools/pull/4149\r\nhttps://github.com/kiegroup/kogito-runtimes/pull/1930
[2022-01-25T16:36:27.522Z] NODE_NAME=rhos-d-kie-rhel7-xlarge-578
[2022-01-25T16:36:27.522Z] LESSOPEN=||/usr/bin/lesspipe.sh %s
[2022-01-25T16:36:27.522Z] GOPATH=/home/jenkins/go
[2022-01-25T16:36:27.522Z] BUILD_NUMBER=856
[2022-01-25T16:36:27.522Z] ghprbTargetBranch=main
[2022-01-25T16:36:27.522Z] MAVEN_MIRROR_REPOSITORY=https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/
[2022-01-25T16:36:27.522Z] JOB_DISPLAY_URL=https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/display/redirect
[2022-01-25T16:36:27.522Z] NPM_REGISTRY_PUBLISH_URL=http://10.0.155.78
[2022-01-25T16:36:27.522Z] HUDSON_COOKIE=cfe53262-f262-4460-bd0a-17155762d4fe
[2022-01-25T16:36:27.522Z] XDG_RUNTIME_DIR=/run/user/1000
[2022-01-25T16:36:27.522Z] GIT_AUTHOR_EMAIL=jenk [...]

2022-01-25 17:20 UTC, kie-ci1 commented
**PR job** #881 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2462
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/881/testReport/org.kie.kogito.quarkus.drools/StatefulRuleUnitServiceTest/testQueryDsService/">org.kie.kogito.quarkus.drools.StatefulRuleUnitServiceTest.testQueryDsService</a></summary>
java.lang.ClassCastException: class org.kie.kogito.drools.core.data.ListDataStore cannot be cast to class org.kie.kogito.rules.DataSource (org.kie.kogito.drools.core.data.ListDataStore and org.kie.kogito.rules.DataSource are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2183db30)
	at org.kie.kogito.core.rules.incubation.quarkus.support.DataSourceServiceImpl.getDataSource(DataSourceServiceImpl.java:116)
	at org.kie.kogito.core.rules.incubation.quarkus.support.DataSourceServiceImpl.add(DataSourceServiceImpl.java:65)
	at org.kie.kogito.core.rules.incubation.quarkus.support.QuarkusDataSourceService.add(QuarkusDataSourceService.java:47)
	at org.kie.kogito.core.rules.incubation.quarkus.support.QuarkusDataSourceService_ClientProxy.add(Unknown Source)
	at org.kie.kogito.quarkus.drools.StatefulRuleUnitServiceTest.testQueryDsService(StatefulRuleUnitServiceTest.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:956)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:776)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestra [...]

2022-01-25 17:31 UTC, kie-ci1 commented
**PR job** #945 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 321
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/945/display/redirect or see console log:
```spoiler Console Logs
[2022-01-25T17:30:53.512Z] [INFO]    +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[2022-01-25T17:30:53.512Z] [INFO]    +- com.github.jknack:handlebars:jar:4.2.0:test
[2022-01-25T17:30:53.512Z] [INFO]    +- com.github.jknack:handlebars-helpers:jar:4.2.0:test
[2022-01-25T17:30:53.512Z] [INFO]    +- com.flipkart.zjsonpatch:zjsonpatch:jar:0.4.4:test
[2022-01-25T17:30:53.512Z] [INFO]    +- commons-fileupload:commons-fileupload:jar:1.4:test
[2022-01-25T17:30:53.512Z] [INFO]    +- org.eclipse.jetty.http2:http2-server:jar:9.4.39.v20210325:test
[2022-01-25T17:30:53.512Z] [INFO]    |  \- org.eclipse.jetty.http2:http2-common:jar:9.4.39.v20210325:test
[2022-01-25T17:30:53.512Z] [INFO]    |     \- org.eclipse.jetty.http2:http2-hpack:jar:9.4.39.v20210325:test
[2022-01-25T17:30:53.512Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-server:jar:9.4.39.v20210325:test
[2022-01-25T17:30:53.512Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-conscrypt-server:jar:9.4.39.v20210325:test
[2022-01-25T17:30:53.512Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-conscrypt-client:jar:9.4.39.v20210325:test
[2022-01-25T17:30:53.512Z] [INFO]    |  \- org.eclipse.jetty:jetty-alpn-client:jar:9.4.39.v20210325:test
[2022-01-25T17:30:53.512Z] [INFO]    +- org.conscrypt:conscrypt-openjdk-uber:jar:2.2.1:test
[2022-01-25T17:30:53.512Z] [INFO]    \- net.javacrumbs.json-unit:json-unit-core:jar:2.12.0:test
[2022-01-25T17:30:53.512Z] [INFO]       +- org.opentest4j:opentest4j:jar:1.1.1:test
[2022-01-25T17:30:53.512Z] [INFO]       \- org.hamcrest:hamcrest-core:jar:1.3:test
[2022-01-25T17:30:53.512Z] [INFO] ------------------------------------------------------------------------
[2022-01-25T17:30:53.512Z] [INFO] Reactor Summary for Kogito Example 2.0.0-SNAPSHOT:
[2022-01-25T17:30:53.512Z] [INFO] 
[2022-01-25T17:30:53.512Z] [INFO] Kogito Example ..................................... SUCCESS [  2.465 s]
[2022-01-25T17:30:53.512Z] [INFO] kogito-quarkus-examples ............................ SUCCESS [  0.085 s]
[2022-01-25T17:30:53.512Z] [INFO] Kogito Example :: Decision Table - Quarkus ......... SUCCESS [ 28.855 s]
[2022-01-25T17:30:53.512Z] [INFO] Kogito Example :: DMN Metrics Quarkus .............. FAILURE [  1.039 s]
[2022-01-25T17:30:53.512Z] [INFO] Kogito Example :: DMN Event-Driven :: Quarkus ...... SUCCESS [01:48 min]
[2022-01-25T17:30:53.512Z] [INFO] Kogito Example :: DMN Incubation API With Quarkus .. SUCCESS [ 19.068 s]
[2022-01-25T17:30:53.512Z] [INFO] Kogito Example :: DMN with Knative Eventing and Quarkus SUCCESS [ 22.889 s]
[2022-01-25T17:30:53.512Z] [INFO] Kogito Example :: DMN with listeners - Quarkus ..... SUCCESS [ 20.396 s]
[2022-01-25T17:30:53.512Z] [INFO] Kogito Example :: DMN :: PMML - QUARKUS ............ SUCCESS [ 35.263 s]
[2022-01-25T17:30:53.512Z] [INFO] Kogito Example :: DMN .............................. SUCCESS [ 21.195 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: DMN Tracing - Quarkus ............ SUCCESS [ 43.035 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Flexible Process - Quarkus ....... SUCCESS [ 25.330 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Travel Agency .................... SUCCESS [  0.143 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Travel Agency :: Basic ........... SUCCESS [ 23.018 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Travel Agency :: Extended ........ SUCCESS [  0.131 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Travel Agency :: Travels ......... SUCCESS [01:02 min]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Travel Agency :: Visas ........... SUCCESS [  8.898 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Onboarding Example ............... SUCCESS [  0.068 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Onboarding Example :: HR with Drools SUCCESS [ 28.405 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Onboarding Example :: Payroll with DMN SUCCESS [ 23.559 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Onboarding Example :: Onboarding with Business Process Quarkus SUCCESS [ 28.124 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: PMML Event-Driven - Quarkus ...... SUCCESS [01:10 min]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: PMML Incubation API With Quarkus . SUCCESS [ 19.369 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: PMML - Quarkus ................... SUCCESS [ 22.936 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Business Rules Quarkus ... SUCCESS [ 20.433 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process :: Decisions :: Quarkus .. SUCCESS [ 26.735 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process :: Decisions :: REST Quarkus SUCCESS [ 28.342 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Scripts With Quarkus ..... SUCCESS [ 17.982 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Incubation API With Quarkus SUCCESS [ 18.280 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Infinispan Persistence Quarkus SUCCESS [ 35.671 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process with Kafka and Quarkus, multiple channels SUCCESS [ 40.126 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Kafka Persistence Quarkus  SUCCESS [ 39.725 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process with Kafka and Quarkus ... SUCCESS [ 40.473 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process with Knative Eventing and Quarkus SUCCESS [ 28.418 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process MongoDB Persistence Quarkus SUCCESS [ 34.612 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Monitoring :: Quarkus .... SUCCESS [ 29.674 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process, OptaPlanner and Quarkus . SUCCESS [ 38.745 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Transactional Outbox :: MongoDB and Quarkus SUCCESS [02:35 min]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Client Performance test .......... SUCCESS [  0.598 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Quarkus Performance test ......... SUCCESS [  7.683 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process PostgreSQL Persistence Quarkus SUCCESS [ 31.805 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process and Quarkus .............. SUCCESS [ 31.192 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Service Rest Cal with Quarkus SUCCESS [  9.146 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Rest :: Quarkus .......... SUCCESS [ 20.610 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Service Rest WorkItem call with Quarkus SUCCESS [  8.287 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Scripts With Quarkus ..... SUCCESS [ 18.150 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Saga with Quarkus ........ SUCCESS [ 24.741 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Service Calls with Quarkus SUCCESS [ 18.829 s]
[2022-01-25T17:30:53.775Z] [INFO] Kogito Example :: Process Timer with Quarkus ....... SUCCESS [  6.808 s]
[2022-01-25T17:30:53.776Z] [INFO] Kogito Example :: Process Usertasks With Custom Lifecycle SUCCESS [ 19.910 s]
[2022-01-25T17:30:53.776Z] [INFO] Kogito Example :: Process with Usertasks Quarkus :: Console SUCCESS [ 47.037 s]
[2022-01-25T17:30:53.776Z] [INFO] Kogito Example :: Process with Usertasks Quarkus ... SUCCESS [ 19.770 s]
[2022-01-25T17:30:53.776Z] [INFO] Kogito Example :: Process UserTasks with Timer Quarkus :: Console SUCCES [...]

2022-01-25 17:52 UTC, kie-ci1 commented
**PR job** #882 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2462
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/882/testReport/org.kie.kogito.quarkus.drools/StatefulRuleUnitServiceTest/testQueryDsService/">org.kie.kogito.quarkus.drools.StatefulRuleUnitServiceTest.testQueryDsService</a></summary>
java.lang.ClassCastException: class org.kie.kogito.drools.core.data.ListDataStore cannot be cast to class org.kie.kogito.rules.DataSource (org.kie.kogito.drools.core.data.ListDataStore and org.kie.kogito.rules.DataSource are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @32ca397b)
	at org.kie.kogito.core.rules.incubation.quarkus.support.DataSourceServiceImpl.getDataSource(DataSourceServiceImpl.java:116)
	at org.kie.kogito.core.rules.incubation.quarkus.support.DataSourceServiceImpl.add(DataSourceServiceImpl.java:65)
	at org.kie.kogito.core.rules.incubation.quarkus.support.QuarkusDataSourceService.add(QuarkusDataSourceService.java:47)
	at org.kie.kogito.core.rules.incubation.quarkus.support.QuarkusDataSourceService_ClientProxy.add(Unknown Source)
	at org.kie.kogito.quarkus.drools.StatefulRuleUnitServiceTest.testQueryDsService(StatefulRuleUnitServiceTest.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:956)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:776)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestra [...]

2022-01-25 18:17 UTC, kie-ci1 commented
**PR job** #946 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 321
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/946/display/redirect or see console log:
```spoiler Console Logs
[2022-01-25T18:17:30.339Z] [INFO]    +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[2022-01-25T18:17:30.339Z] [INFO]    +- com.github.jknack:handlebars:jar:4.2.0:test
[2022-01-25T18:17:30.339Z] [INFO]    +- com.github.jknack:handlebars-helpers:jar:4.2.0:test
[2022-01-25T18:17:30.339Z] [INFO]    +- com.flipkart.zjsonpatch:zjsonpatch:jar:0.4.4:test
[2022-01-25T18:17:30.339Z] [INFO]    +- commons-fileupload:commons-fileupload:jar:1.4:test
[2022-01-25T18:17:30.339Z] [INFO]    +- org.eclipse.jetty.http2:http2-server:jar:9.4.39.v20210325:test
[2022-01-25T18:17:30.339Z] [INFO]    |  \- org.eclipse.jetty.http2:http2-common:jar:9.4.39.v20210325:test
[2022-01-25T18:17:30.339Z] [INFO]    |     \- org.eclipse.jetty.http2:http2-hpack:jar:9.4.39.v20210325:test
[2022-01-25T18:17:30.339Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-server:jar:9.4.39.v20210325:test
[2022-01-25T18:17:30.339Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-conscrypt-server:jar:9.4.39.v20210325:test
[2022-01-25T18:17:30.339Z] [INFO]    +- org.eclipse.jetty:jetty-alpn-conscrypt-client:jar:9.4.39.v20210325:test
[2022-01-25T18:17:30.339Z] [INFO]    |  \- org.eclipse.jetty:jetty-alpn-client:jar:9.4.39.v20210325:test
[2022-01-25T18:17:30.339Z] [INFO]    +- org.conscrypt:conscrypt-openjdk-uber:jar:2.2.1:test
[2022-01-25T18:17:30.339Z] [INFO]    \- net.javacrumbs.json-unit:json-unit-core:jar:2.12.0:test
[2022-01-25T18:17:30.339Z] [INFO]       +- org.opentest4j:opentest4j:jar:1.1.1:test
[2022-01-25T18:17:30.339Z] [INFO]       \- org.hamcrest:hamcrest-core:jar:1.3:test
[2022-01-25T18:17:30.339Z] [INFO] ------------------------------------------------------------------------
[2022-01-25T18:17:30.339Z] [INFO] Reactor Summary for Kogito Example 2.0.0-SNAPSHOT:
[2022-01-25T18:17:30.339Z] [INFO] 
[2022-01-25T18:17:30.339Z] [INFO] Kogito Example ..................................... SUCCESS [  3.125 s]
[2022-01-25T18:17:30.339Z] [INFO] kogito-quarkus-examples ............................ SUCCESS [  0.123 s]
[2022-01-25T18:17:30.339Z] [INFO] Kogito Example :: Decision Table - Quarkus ......... SUCCESS [ 40.003 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: DMN Metrics Quarkus .............. FAILURE [  1.214 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: DMN Event-Driven :: Quarkus ...... SUCCESS [02:04 min]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: DMN Incubation API With Quarkus .. SUCCESS [ 26.449 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: DMN with Knative Eventing and Quarkus SUCCESS [ 30.850 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: DMN with listeners - Quarkus ..... SUCCESS [ 31.365 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: DMN :: PMML - QUARKUS ............ SUCCESS [ 48.970 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: DMN .............................. SUCCESS [ 29.893 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: DMN Tracing - Quarkus ............ SUCCESS [ 58.030 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: Flexible Process - Quarkus ....... SUCCESS [ 39.248 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: Travel Agency .................... SUCCESS [  0.240 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: Travel Agency :: Basic ........... SUCCESS [ 31.518 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: Travel Agency :: Extended ........ SUCCESS [  0.130 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: Travel Agency :: Travels ......... SUCCESS [01:22 min]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: Travel Agency :: Visas ........... SUCCESS [ 12.596 s]
[2022-01-25T18:17:30.340Z] [INFO] Kogito Example :: Onboarding Example ............... SUCCESS [  0.083 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Onboarding Example :: HR with Drools SUCCESS [ 41.792 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Onboarding Example :: Payroll with DMN SUCCESS [ 32.428 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Onboarding Example :: Onboarding with Business Process Quarkus SUCCESS [ 43.516 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: PMML Event-Driven - Quarkus ...... SUCCESS [01:22 min]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: PMML Incubation API With Quarkus . SUCCESS [ 27.359 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: PMML - Quarkus ................... SUCCESS [ 32.304 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Business Rules Quarkus ... SUCCESS [ 28.148 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process :: Decisions :: Quarkus .. SUCCESS [ 37.033 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process :: Decisions :: REST Quarkus SUCCESS [ 50.177 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Scripts With Quarkus ..... SUCCESS [ 30.437 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Incubation API With Quarkus SUCCESS [ 39.922 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Infinispan Persistence Quarkus SUCCESS [01:01 min]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process with Kafka and Quarkus, multiple channels SUCCESS [ 57.455 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Kafka Persistence Quarkus  SUCCESS [ 56.642 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process with Kafka and Quarkus ... SUCCESS [ 57.394 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process with Knative Eventing and Quarkus SUCCESS [ 45.002 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process MongoDB Persistence Quarkus SUCCESS [ 54.454 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Monitoring :: Quarkus .... SUCCESS [ 47.774 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process, OptaPlanner and Quarkus . SUCCESS [ 55.232 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Transactional Outbox :: MongoDB and Quarkus SUCCESS [03:52 min]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Client Performance test .......... SUCCESS [  0.969 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Quarkus Performance test ......... SUCCESS [ 12.683 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process PostgreSQL Persistence Quarkus SUCCESS [01:08 min]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process and Quarkus .............. SUCCESS [ 58.377 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Service Rest Cal with Quarkus SUCCESS [ 11.415 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Rest :: Quarkus .......... SUCCESS [ 29.712 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Service Rest WorkItem call with Quarkus SUCCESS [ 10.952 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Scripts With Quarkus ..... SUCCESS [ 25.445 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Saga with Quarkus ........ SUCCESS [ 35.067 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Service Calls with Quarkus SUCCESS [ 27.709 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Timer with Quarkus ....... SUCCESS [  8.173 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process Usertasks With Custom Lifecycle SUCCESS [ 27.692 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process with Usertasks Quarkus :: Console SUCCESS [01:02 min]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process with Usertasks Quarkus ... SUCCESS [ 28.988 s]
[2022-01-25T18:17:30.606Z] [INFO] Kogito Example :: Process UserTasks with Timer Quarkus :: Console SUCCES [...]

2022-01-26 08:25 UTC, kie-ci1 commented
**PR job** #859 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/859/display/redirect or see console log:
```spoiler Console Logs
 > git rev-list --no-walk 512c0a79a281c6f6d5b20965ec289b4f3d7a38c0 # timeout=10
Loading library jenkins-pipeline-shared-libraries@main
Attempting to resolve main from remote references...
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space
[INFO] Currently running in a labeled security context
 > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh1493522167748132721.key
 > git ls-remote -h https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10
Found match: refs/heads/main revision d0108f3f4d1eff17009a35026b2ab080b0ef6c17
The recommended git tool is: NONE
using credential kie-ci-user-key
 > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space
[INFO] Currently running in a labeled security context
 > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries@tmp/jenkins-gitclient-ssh4173029950319815722.key
 > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision d0108f3f4d1eff17009a35026b2ab080b0ef6c17 (main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d0108f3f4d1eff17009a35026b2ab080b0ef6c17 # timeout=10
Commit message: "KOGITO-6599 Markdown notification (#183)"
 > git rev-list --no-walk d0108f3f4d1eff17009a35026b2ab080b0ef6c17 # timeout=10
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on ‘kie-rhel7&&kie-mem16g&&!master’
Running on rhos-d-kie-rhel7-xlarge-972 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE
using credential kie-ci
Cloning the remote Git repository
Avoid second fetch
Checking out Revision 512c0a79a281c6f6d5b20965ec289b4f3d7a38c0 (origin/main)
Cloning repository https://github.com/kiegroup/kogito-pipelines.git
 > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts # timeout=10
Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git
 > git --version # timeout=10
 > git --version # 'git version 2.34.1'
using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space
 > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse origin/main^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 512c0a79a281c6f6d5b20965ec289b4f3d7a38c0 # timeout=10
Commit message: "Update Jenkinsfile.buildchain (#361)"
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] timeout
[2022-01-26T08:24:08.428Z] Timeout set to expire in 3 hr 0 min
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Tool Install)
[Pipeline] tool
[2022-01-26T08:24:08.562Z] Unpacking https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-d-kie-rhel7-xlarge-972
[Pipeline] envVarsForTool
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Initialize)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] sh
[2022-01-26T08:24:13.037Z] + printenv
[Pipeline] archiveArtifacts
[2022-01-26T08:24:13.155Z] Archiving artifacts
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (check space before build)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] dir
[2022-01-26T08:24:13.848Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[Pipeline] {
[Pipeline] echo
[2022-01-26T08:24:13.874Z] [INFO] space left on the machine
[Pipeline] sh
[2022-01-26T08:24:14.184Z] + df -h
[2022-01-26T08:24:14.184Z] Filesystem      Size  Used Avail Use% Mounted on
[2022-01-26T08:24:14.184Z] devtmpfs        7.8G     0  7.8G   0% /dev
[2022-01-26T08:24:14.184Z] tmpfs           7.8G     0  7.8G   0% /dev/shm
[2022-01-26T08:24:14.184Z] tmpfs           7.8G   17M  7.8G   1% /run
[2022-01-26T08:24:14.185Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
[2022-01-26T08:24:14.185Z] /dev/vda1        60G   18G   43G  30% /
[2022-01-26T08:24:14.185Z] tmpfs           1.6G     0  1.6G   0% /run/user/0
[2022-01-26T08:24:14.185Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000
[Pipeline] echo
[2022-01-26T08:24:14.200Z] [INFO] space of /home/jenkins
[Pipeline] sh
[2022-01-26T08:24:14.492Z] + du -h -d1 /home/jenkins
[2022-01-26T08:24:14.492Z] 4.0K	/home/jenkins/.ssh
[2022-01-26T08:24:14.492Z] 0	/home/jenkins/go
[2022-01-26T08:24:14.492Z] 8.0K	/home/jenkins/.vnc
[2022-01-26T08:24:14.492Z] 8.0K	/home/jenkins/.m2
[2022-01-26T08:24:14.492Z] 2.1G	/home/jenkins/git-repos
[2022-01-26T08:24:14.492Z] 8.0K	/home/jenkins/.config
[2022-01-26T08:24:14.754Z] 4.0K	/home/jenkins/.cekit
[2022-01-26T08:24:15.013Z] 76M	/home/jenkins/virtenvs
[2022-01-26T08:24:15.013Z] 30M	/home/jenkins/remoting
[2022-01-26T08:24:15.013Z] 0	/home/jenkins/.cache
[2022-01-26T08:24:15.013Z] 2.0M	/home/jenkins/workspace
[2022-01-26T08:24:15.013Z] 0	/home/jenkins/.pki
[2022-01-26T08:24:15.271Z] 81M	/home/jenkins/tools
[2022-01-26T08:24:15.271Z] 0	/home/jenkins/caches
[2022-01-26T08:24:15.271Z] 2.3G	/home/jenkins
[Pipeline] echo
[2022-01-26T08:24:15.288Z] [INFO] space of workspace
[Pipeline] sh
[2022-01-26T08:24:15.605Z] + du -h -d3 /home/jenkins/workspace
[2022-01-26T08:24:15.606Z] 2.0M	/home/jenkins/workspace/KIE/kogito/main
[2022-01-26T08:24:15.606Z] 2.0M	/home/jenkins/workspace/KIE/kogito
[2022-01-26T08:24:15.606Z] 2.0M	/home/jenkins/workspace/KIE
[2022-01-26T08:24:15.606Z] 2.0M	/home/jenkins/workspace
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Install build-chain tool)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] echo
[2022-01-26T08:24:15.914Z] [INFO] Getting build-chain version from composite action file
[Pipeline] readFile
[Pipeline] echo
[2022-01-26T08:24 [...]

2022-01-26 08:26 UTC, kie-ci1 commented
**PR job** #915 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/915/display/redirect or see console log:
```spoiler Console Logs
[2022-01-26T08:26:22.117Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:26:22.117Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:26:22.117Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:26:22.117Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:26:22.117Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:26:22.117Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:26:22.117Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:26:22.117Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:26:22.117Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:26:22.117Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:26:22.117Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:424)
[2022-01-26T08:26:22.117Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:26:22.117Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:26:22.117Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:846)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:337)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:377)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:26:22.117Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:26:22.117Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:26:22.117Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:26:22.117Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:26:22.117Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:26:22.117Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:26:22.117Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:26:22.118Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:26:22.118Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:26:22.118Z] Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:369)
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute (BasicRepositoryConnector.java:628)
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:262)
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:513)
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:401)
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:26:22.118Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:26:22.118Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:26:22.118Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:26:22.118Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:26:22.118Z]     at org.apache.maven.model. [...]

2022-01-26 08:26 UTC, kie-ci1 commented
**PR job** #885 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/885/display/redirect or see console log:
```spoiler Console Logs
[2022-01-26T08:26:28.002Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:26:28.002Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:26:28.002Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:26:28.002Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:26:28.002Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:26:28.002Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:26:28.002Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:26:28.002Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:26:28.002Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:26:28.002Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:424)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:846)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:337)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:377)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:26:28.002Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:26:28.002Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:26:28.002Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:26:28.002Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:26:28.002Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:26:28.002Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:26:28.002Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:26:28.002Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:26:28.002Z] Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:369)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute (BasicRepositoryConnector.java:628)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:262)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:513)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:401)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:26:28.002Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:26:28.002Z]     at org.apache.maven.model.buildin [...]

2022-01-26 08:26 UTC, kie-ci1 commented
**PR job** #852 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaweb-employee-rostering/852/display/redirect or see console log:
```spoiler Console Logs
[2022-01-26T08:26:48.445Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:26:48.445Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:26:48.445Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:26:48.445Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:26:48.445Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:26:48.445Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:26:48.445Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:26:48.445Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:26:48.445Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:26:48.445Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:26:48.445Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:424)
[2022-01-26T08:26:48.445Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:26:48.445Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:26:48.445Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:846)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:337)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:377)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:26:48.445Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:26:48.445Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:26:48.445Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:26:48.445Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:26:48.445Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:26:48.445Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:26:48.446Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:26:48.446Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:26:48.446Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:26:48.446Z] Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:369)
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute (BasicRepositoryConnector.java:628)
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:262)
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:513)
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:401)
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:26:48.446Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:26:48.446Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:26:48.446Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:26:48.446Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:26:48.446Z]     at org.apac [...]

2022-01-26 08:27 UTC, kie-ci1 commented
**PR job** #992 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner/992/display/redirect or see console log:
```spoiler Console Logs
[2022-01-26T08:24:21.151Z] [INFO]  kiegroup/optaplanner:main.
[2022-01-26T08:24:21.151Z] [INFO]  ----------------------------------------------
[2022-01-26T08:24:21.151Z] [INFO]  Projects taken from branch "d6662":
[2022-01-26T08:24:21.151Z]   mariofusco/drools. Merged with kiegroup/drools:main
[2022-01-26T08:24:21.151Z] [INFO]  Projects taken from branch "main":
[2022-01-26T08:24:21.151Z]   kiegroup/optaplanner
[2022-01-26T08:24:21.151Z] [INFO]  ----------------------------------------------
[2022-01-26T08:24:21.151Z] ::endgroup::
[2022-01-26T08:24:21.151Z] ::group::[kiegroup/drools]. Command: 'mvn clean install -Dquickly ${{ env.BUILD_MVN_OPTS }} ${{ env.BUILD_MVN_OPTS_UPSTREAM }} ${{ env.DROOLS_BUILD_MVN_OPTS_UPSTREAM }}' in dir bc/kiegroup_drools
[2022-01-26T08:24:21.151Z] [INFO]  [REGEX COMMAND REPLACEMENT] Replacing command: 'mvn clean install -Dquickly  -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3   -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B' by expressions: '(^mvn .*)||$1 -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner@tmp/config8743597882511840912tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true'
[2022-01-26T08:24:21.151Z] [INFO]  [REGEX COMMAND REPLACEMENT] Replaced to: 'mvn clean install -Dquickly  -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3   -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner@tmp/config8743597882511840912tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true'
[2022-01-26T08:24:21.151Z] [INFO]  Execute command 'mvn clean install -Dquickly  -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3   -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner@tmp/config8743597882511840912tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true' in dir 'bc/kiegroup_drools'
[2022-01-26T08:24:21.151Z] [command]/opt/tools/apache-maven-3.8.1/bin/mvn clean install -Dquickly -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false dependency:tree -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner@tmp/config8743597882511840912tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true
[2022-01-26T08:24:23.721Z] [INFO] Error stacktraces are turned on.
[2022-01-26T08:24:23.721Z] [INFO] Scanning for projects...
[2022-01-26T08:27:45.454Z] [ERROR] [ERROR] Some problems were encountered while processing the POMs:
[2022-01-26T08:27:45.454Z] [FATAL] Non-resolvable parent POM for org.kie:drools-parent:8.17.0-SNAPSHOT: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom and 'parent.relativePath' points at wrong local POM @ line 6, column 11
[2022-01-26T08:27:45.454Z]  @ 
[2022-01-26T08:27:45.454Z] [ERROR] The build could not read 1 project -> [Help 1]
[2022-01-26T08:27:45.454Z] org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[2022-01-26T08:27:45.455Z] [FATAL] Non-resolvable parent POM for org.kie:drools-parent:8.17.0-SNAPSHOT: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom and 'parent.relativePath' points at wrong local POM @ line 6, column 11
[2022-01-26T08:27:45.455Z] 
[2022-01-26T08:27:45.455Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:397)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:27:45.455Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:27:45.455Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:27:45.455Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:27:45.455Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:27:45.455Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:27:45.455Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:27:45.455Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:27:45.455Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:27:45.455Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:27:45.455Z] [ERROR]   
[2022-01-26T08:27:45.455Z] [ERROR]   The project org.kie:drools-parent:8.17.0-SNAPSHOT (/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner/bc/kiegroup_drools/pom.xml) has 1 error
[2022-01-26T08:27:45.455Z] [ERROR]     Non-resolvable parent POM for org.kie:drools-parent:8.17.0-SNAPSHOT: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom and 'parent.relativePath' points at wrong local POM @ line 6, column 11: peer not authenticated -> [Help 2]
[2022-01-26T08:27:45.455Z] [...]

2022-01-26 08:28 UTC, kie-ci1 commented
**PR job** #950 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/950/display/redirect or see console log:
```spoiler Console Logs
[2022-01-26T08:28:33.047Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:28:33.047Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:28:33.047Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:28:33.047Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:28:33.047Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:28:33.047Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:28:33.047Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:28:33.047Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:28:33.047Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:28:33.047Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:28:33.047Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:424)
[2022-01-26T08:28:33.047Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:28:33.047Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:28:33.047Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:846)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:337)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:377)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:28:33.047Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:28:33.048Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:28:33.048Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:28:33.048Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:28:33.048Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:28:33.048Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:28:33.048Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:28:33.048Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:28:33.048Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:28:33.048Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:28:33.048Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:28:33.048Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:28:33.048Z] Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:369)
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute (BasicRepositoryConnector.java:628)
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:262)
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:513)
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:401)
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:28:33.048Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:28:33.048Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:28:33.048Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:28:33.048Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:28:33.048Z]     at org.apache.maven.mo [...]

2022-01-26 08:29 UTC, kie-ci1 commented
**PR job** #851 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaweb-vehicle-routing/851/display/redirect or see console log:
```spoiler Console Logs
[2022-01-26T08:29:23.717Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:29:23.717Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:29:23.717Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:29:23.717Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:29:23.717Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:29:23.717Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:29:23.717Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:29:23.717Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:29:23.717Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:29:23.717Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:424)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParent (DefaultModelBuilder.java:846)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:337)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:448)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:414)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:377)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:507)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
[2022-01-26T08:29:23.717Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
[2022-01-26T08:29:23.717Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
[2022-01-26T08:29:23.717Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
[2022-01-26T08:29:23.717Z]     at java.lang.reflect.Method.invoke (Method.java:566)
[2022-01-26T08:29:23.717Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
[2022-01-26T08:29:23.717Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
[2022-01-26T08:29:23.717Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
[2022-01-26T08:29:23.717Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[2022-01-26T08:29:23.717Z] Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.jboss:jboss-parent:pom:36 from/to mirror-central (https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/): transfer failed for https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/org/jboss/jboss-parent/36/jboss-parent-36.pom
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed (ArtifactTransportListener.java:52)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run (BasicRepositoryConnector.java:369)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run (RunnableErrorForwarder.java:75)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute (BasicRepositoryConnector.java:628)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get (BasicRepositoryConnector.java:262)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads (DefaultArtifactResolver.java:513)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:401)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact (DefaultArtifactResolver.java:207)
[2022-01-26T08:29:23.717Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact (DefaultRepositorySystem.java:262)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:192)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.project.ProjectModelResolver.resolveModel (ProjectModelResolver.java:242)
[2022-01-26T08:29:23.717Z]     at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally (DefaultModelBuilder.java:1070)
[2022-01-26T08:29:23.717Z]     at org.apache. [...]

2022-01-26 09:02 UTC, kie-ci1 commented
**PR job** #860 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/860/display/redirect or see console log:
```spoiler Console Logs
 > git rev-list --no-walk 512c0a79a281c6f6d5b20965ec289b4f3d7a38c0 # timeout=10
Loading library jenkins-pipeline-shared-libraries@main
Attempting to resolve main from remote references...
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space
[INFO] Currently running in a labeled security context
 > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh3412946849517425569.key
 > git ls-remote -h https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10
Found match: refs/heads/main revision d0108f3f4d1eff17009a35026b2ab080b0ef6c17
The recommended git tool is: NONE
using credential kie-ci-user-key
 > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space
[INFO] Currently running in a labeled security context
 > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries@tmp/jenkins-gitclient-ssh8070914689518014286.key
 > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision d0108f3f4d1eff17009a35026b2ab080b0ef6c17 (main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d0108f3f4d1eff17009a35026b2ab080b0ef6c17 # timeout=10
Commit message: "KOGITO-6599 Markdown notification (#183)"
 > git rev-list --no-walk d0108f3f4d1eff17009a35026b2ab080b0ef6c17 # timeout=10
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on ‘kie-rhel7&&kie-mem16g&&!master’
Running on rhos-d-kie-rhel7-xlarge-1009 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE
using credential kie-ci
Cloning the remote Git repository
Cloning repository https://github.com/kiegroup/kogito-pipelines.git
 > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts # timeout=10
Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git
 > git --version # timeout=10
 > git --version # 'git version 2.34.1'
using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space
 > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
Checking out Revision 512c0a79a281c6f6d5b20965ec289b4f3d7a38c0 (origin/main)
 > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse origin/main^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 512c0a79a281c6f6d5b20965ec289b4f3d7a38c0 # timeout=10
Commit message: "Update Jenkinsfile.buildchain (#361)"
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] timeout
[2022-01-26T09:01:27.204Z] Timeout set to expire in 3 hr 0 min
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Tool Install)
[Pipeline] tool
[2022-01-26T09:01:27.387Z] Unpacking https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-d-kie-rhel7-xlarge-1009
[Pipeline] envVarsForTool
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Initialize)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] sh
[2022-01-26T09:01:31.643Z] + printenv
[Pipeline] archiveArtifacts
[2022-01-26T09:01:31.744Z] Archiving artifacts
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (check space before build)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] dir
[2022-01-26T09:01:32.432Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[Pipeline] {
[Pipeline] echo
[2022-01-26T09:01:32.472Z] [INFO] space left on the machine
[Pipeline] sh
[2022-01-26T09:01:32.787Z] + df -h
[2022-01-26T09:01:32.787Z] Filesystem      Size  Used Avail Use% Mounted on
[2022-01-26T09:01:32.787Z] devtmpfs        7.8G     0  7.8G   0% /dev
[2022-01-26T09:01:32.787Z] tmpfs           7.8G     0  7.8G   0% /dev/shm
[2022-01-26T09:01:32.787Z] tmpfs           7.8G   17M  7.8G   1% /run
[2022-01-26T09:01:32.787Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
[2022-01-26T09:01:32.787Z] /dev/vda1        60G   18G   43G  30% /
[2022-01-26T09:01:32.787Z] tmpfs           1.6G     0  1.6G   0% /run/user/0
[2022-01-26T09:01:32.787Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000
[Pipeline] echo
[2022-01-26T09:01:32.804Z] [INFO] space of /home/jenkins
[Pipeline] sh
[2022-01-26T09:01:33.096Z] + du -h -d1 /home/jenkins
[2022-01-26T09:01:33.097Z] 4.0K	/home/jenkins/.ssh
[2022-01-26T09:01:33.097Z] 0	/home/jenkins/go
[2022-01-26T09:01:33.097Z] 8.0K	/home/jenkins/.vnc
[2022-01-26T09:01:33.097Z] 8.0K	/home/jenkins/.m2
[2022-01-26T09:01:33.097Z] 2.1G	/home/jenkins/git-repos
[2022-01-26T09:01:33.097Z] 8.0K	/home/jenkins/.config
[2022-01-26T09:01:33.097Z] 4.0K	/home/jenkins/.cekit
[2022-01-26T09:01:33.097Z] 76M	/home/jenkins/virtenvs
[2022-01-26T09:01:33.097Z] 30M	/home/jenkins/remoting
[2022-01-26T09:01:33.097Z] 0	/home/jenkins/.cache
[2022-01-26T09:01:33.097Z] 2.0M	/home/jenkins/workspace
[2022-01-26T09:01:33.097Z] 0	/home/jenkins/.pki
[2022-01-26T09:01:33.097Z] 81M	/home/jenkins/tools
[2022-01-26T09:01:33.097Z] 0	/home/jenkins/caches
[2022-01-26T09:01:33.097Z] 2.3G	/home/jenkins
[Pipeline] echo
[2022-01-26T09:01:33.115Z] [INFO] space of workspace
[Pipeline] sh
[2022-01-26T09:01:33.406Z] + du -h -d3 /home/jenkins/workspace
[2022-01-26T09:01:33.406Z] 2.0M	/home/jenkins/workspace/KIE/kogito/main
[2022-01-26T09:01:33.406Z] 2.0M	/home/jenkins/workspace/KIE/kogito
[2022-01-26T09:01:33.406Z] 2.0M	/home/jenkins/workspace/KIE
[2022-01-26T09:01:33.406Z] 2.0M	/home/jenkins/workspace
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Install build-chain tool)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] echo
[2022-01-26T09:01:33.758Z] [INFO] Getting build-chain version from composite action file
[Pipeline] readFile
[Pipeline] echo
[2022-01-26T09: [...]

2022-01-26 09:20 UTC, evacchi commented on api/kogito-api/src/main/java/org/kie/kogito/rules/DataHandle.java
> +public interface DataHandle extends org.drools.ruleunits.api.DataHandle {
we should probably mark all these interfaces as `@Deprecated` 

```suggestion
/**
 * @deprecated use org.drools.ruleunits.api.DataHandle
 */
 @Deprecated
public interface DataHandle extends org.drools.ruleunits.api.DataHandle {
```

2022-01-26 09:28 UTC, evacchi requested changes
left some comments, mostly related to add deprecation warnings. I think we can add them everywhere there is a "bridge" class for backwards compatibility. At the next sprint(s) we should probably updated tests/examples to use the new interface and remove the leftovers.

2022-01-26 09:28 UTC, evacchi commented on api/kogito-api/src/main/java/org/kie/kogito/rules/DataObserver.java
> +public interface DataObserver extends org.drools.ruleunits.api.DataObserver {
IIRC this is only an utility to provide the static method, we don't really need this pattern, we can just duplicate it -- i.e. you can probably leave it as it is and duplicate in the Drools codebase if it is useful

2022-01-26 09:28 UTC, evacchi commented on api/kogito-api/src/main/java/org/kie/kogito/rules/DataSource.java
> +public interface DataSource<T> extends org.drools.ruleunits.api.DataSource<T> {
add deprecation

2022-01-26 09:28 UTC, evacchi commented on api/kogito-api/src/main/java/org/kie/kogito/rules/DataStore.java
> +public interface DataStore<T> extends org.drools.ruleunits.api.DataStore<T> {
add deprecation

2022-01-26 09:28 UTC, evacchi commented on api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnit.java
> +public interface RuleUnit<T extends org.drools.ruleunits.api.RuleUnitData> extends org.drools.ruleunits.api.RuleUnit<T> {
deprecate

2022-01-26 09:28 UTC, evacchi commented on api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnitData.java
> +public interface RuleUnitData extends org.drools.ruleunits.api.RuleUnitData {
even more worth deprecating because we most likely want to collapse onto `DataContext` or `ReferenceContext`

2022-01-26 09:28 UTC, evacchi commented on api/kogito-api/src/main/java/org/kie/kogito/rules/RuleUnitInstance.java
> +public interface RuleUnitInstance<T extends RuleUnitData> extends org.drools.ruleunits.api.RuleUnitInstance<T> {
deprecate

2022-01-26 09:28 UTC, evacchi commented on drools/kogito-drools/src/main/java/org/kie/kogito/drools/core/data/FieldDataStore.java
> +public class FieldDataStore<T> extends org.drools.ruleunits.impl.FieldDataStore<T> implements SingletonStore<T> {
deprecate

2022-01-26 09:28 UTC, evacchi commented on jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateNodeInstance.java
> +                boolean isActive = ((InternalAgenda) getProcessInstance().getKnowledgeRuntime().getAgenda())
memo: these are the kind of places where we need to eliminate the references to Drools /cc FYI @tiagodolphine @cristianonicolai @fjtirado

2022-01-26 09:28 UTC, evacchi commented on kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/unit/AnnotatedRules.java
> +import org.drools.ruleunits.impl.annotations.When;
FYI This was part of the experiment to support Java rules with annotations

2022-01-26 10:10 UTC, kie-ci1 commented
**PR job** #861 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.optaplanner-quickstarts/861/display/redirect or see console log:
```spoiler Console Logs
 > git rev-list --no-walk 512c0a79a281c6f6d5b20965ec289b4f3d7a38c0 # timeout=10
Loading library jenkins-pipeline-shared-libraries@main
Attempting to resolve main from remote references...
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space
[INFO] Currently running in a labeled security context
 > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh3159631059941679294.key
 > git ls-remote -h https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10
Found match: refs/heads/main revision d0108f3f4d1eff17009a35026b2ab080b0ef6c17
The recommended git tool is: NONE
using credential kie-ci-user-key
 > git rev-parse --resolve-git-dir /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries/.git # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries
 > git --version # timeout=10
 > git --version # 'git version 1.8.3.1'
using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space
[INFO] Currently running in a labeled security context
 > /usr/bin/chcon --type=ssh_home_t /var/lib/jenkins/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.optaplanner-quickstarts/workspace@libs/jenkins-pipeline-shared-libraries@tmp/jenkins-gitclient-ssh2048997859582520992.key
 > git fetch --no-tags --progress https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision d0108f3f4d1eff17009a35026b2ab080b0ef6c17 (main)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f d0108f3f4d1eff17009a35026b2ab080b0ef6c17 # timeout=10
Commit message: "KOGITO-6599 Markdown notification (#183)"
 > git rev-list --no-walk d0108f3f4d1eff17009a35026b2ab080b0ef6c17 # timeout=10
[Pipeline] Start of Pipeline
[Pipeline] node
Still waiting to schedule task
Waiting for next available executor on ‘kie-rhel7&&kie-mem16g&&!master’
Running on rhos-d-kie-rhel7-xlarge-1037 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
The recommended git tool is: NONE
using credential kie-ci
Cloning the remote Git repository
Cloning repository https://github.com/kiegroup/kogito-pipelines.git
 > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts # timeout=10
Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git
 > git --version # timeout=10
 > git --version # 'git version 2.34.1'
using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space
 > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10
Avoid second fetch
Checking out Revision 512c0a79a281c6f6d5b20965ec289b4f3d7a38c0 (origin/main)
 > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10
 > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
 > git rev-parse origin/main^{commit} # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 512c0a79a281c6f6d5b20965ec289b4f3d7a38c0 # timeout=10
Commit message: "Update Jenkinsfile.buildchain (#361)"
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] timestamps
[Pipeline] {
[Pipeline] timeout
[2022-01-26T10:09:58.212Z] Timeout set to expire in 3 hr 0 min
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Tool Install)
[Pipeline] tool
[2022-01-26T10:09:58.347Z] Unpacking https://nodejs.org/dist/v12.16.3/node-v12.16.3-linux-x64.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-12.16.3 on rhos-d-kie-rhel7-xlarge-1037
[Pipeline] envVarsForTool
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Initialize)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] sh
[2022-01-26T10:10:02.749Z] + printenv
[Pipeline] archiveArtifacts
[2022-01-26T10:10:02.842Z] Archiving artifacts
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (check space before build)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] dir
[2022-01-26T10:10:03.432Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.optaplanner-quickstarts
[Pipeline] {
[Pipeline] echo
[2022-01-26T10:10:03.458Z] [INFO] space left on the machine
[Pipeline] sh
[2022-01-26T10:10:03.758Z] + df -h
[2022-01-26T10:10:03.758Z] Filesystem      Size  Used Avail Use% Mounted on
[2022-01-26T10:10:03.758Z] devtmpfs        7.8G     0  7.8G   0% /dev
[2022-01-26T10:10:03.758Z] tmpfs           7.8G     0  7.8G   0% /dev/shm
[2022-01-26T10:10:03.758Z] tmpfs           7.8G   17M  7.8G   1% /run
[2022-01-26T10:10:03.758Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
[2022-01-26T10:10:03.758Z] /dev/vda1        60G   18G   43G  30% /
[2022-01-26T10:10:03.758Z] tmpfs           1.6G     0  1.6G   0% /run/user/0
[2022-01-26T10:10:03.758Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000
[Pipeline] echo
[2022-01-26T10:10:03.797Z] [INFO] space of /home/jenkins
[Pipeline] sh
[2022-01-26T10:10:04.083Z] + du -h -d1 /home/jenkins
[2022-01-26T10:10:04.083Z] 4.0K	/home/jenkins/.ssh
[2022-01-26T10:10:04.083Z] 0	/home/jenkins/go
[2022-01-26T10:10:04.083Z] 8.0K	/home/jenkins/.vnc
[2022-01-26T10:10:04.083Z] 8.0K	/home/jenkins/.m2
[2022-01-26T10:10:04.341Z] 2.1G	/home/jenkins/git-repos
[2022-01-26T10:10:04.341Z] 8.0K	/home/jenkins/.config
[2022-01-26T10:10:04.341Z] 4.0K	/home/jenkins/.cekit
[2022-01-26T10:10:04.598Z] 76M	/home/jenkins/virtenvs
[2022-01-26T10:10:04.598Z] 30M	/home/jenkins/remoting
[2022-01-26T10:10:04.598Z] 0	/home/jenkins/.cache
[2022-01-26T10:10:04.598Z] 2.0M	/home/jenkins/workspace
[2022-01-26T10:10:04.598Z] 0	/home/jenkins/.pki
[2022-01-26T10:10:04.598Z] 81M	/home/jenkins/tools
[2022-01-26T10:10:04.598Z] 0	/home/jenkins/caches
[2022-01-26T10:10:04.598Z] 2.3G	/home/jenkins
[Pipeline] echo
[2022-01-26T10:10:04.616Z] [INFO] space of workspace
[Pipeline] sh
[2022-01-26T10:10:04.903Z] + du -h -d3 /home/jenkins/workspace
[2022-01-26T10:10:04.904Z] 2.0M	/home/jenkins/workspace/KIE/kogito/main
[2022-01-26T10:10:04.904Z] 2.0M	/home/jenkins/workspace/KIE/kogito
[2022-01-26T10:10:04.904Z] 2.0M	/home/jenkins/workspace/KIE
[2022-01-26T10:10:04.904Z] 2.0M	/home/jenkins/workspace
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Install build-chain tool)
[Pipeline] tool
[Pipeline] envVarsForTool
[Pipeline] withEnv
[Pipeline] {
[Pipeline] script
[Pipeline] {
[Pipeline] echo
[2022-01-26T10:10:05.173Z] [INFO] Getting build-chain version from composite action file
[Pipeline] readFile
[Pipeline] echo
[2022-01-26T10: [...]

2022-01-26 10:13 UTC, kie-ci1 commented
**PR job** #886 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2463
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/886/testReport/org.kie.kogito.quarkus.drools/StatefulRuleUnitServiceTest/testQueryDsService/">org.kie.kogito.quarkus.drools.StatefulRuleUnitServiceTest.testQueryDsService</a></summary>
java.lang.ClassCastException: class org.kie.kogito.drools.core.data.ListDataStore cannot be cast to class org.kie.kogito.rules.DataSource (org.kie.kogito.drools.core.data.ListDataStore and org.kie.kogito.rules.DataSource are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @62c72490)
	at org.kie.kogito.core.rules.incubation.quarkus.support.DataSourceServiceImpl.getDataSource(DataSourceServiceImpl.java:116)
	at org.kie.kogito.core.rules.incubation.quarkus.support.DataSourceServiceImpl.add(DataSourceServiceImpl.java:65)
	at org.kie.kogito.core.rules.incubation.quarkus.support.QuarkusDataSourceService.add(QuarkusDataSourceService.java:47)
	at org.kie.kogito.core.rules.incubation.quarkus.support.QuarkusDataSourceService_ClientProxy.add(Unknown Source)
	at org.kie.kogito.quarkus.drools.StatefulRuleUnitServiceTest.testQueryDsService(StatefulRuleUnitServiceTest.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:956)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:776)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestra [...]

2022-01-26 12:02 UTC, tiagodolphine commented on jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateNodeInstance.java
> +                boolean isActive = ((InternalAgenda) getProcessInstance().getKnowledgeRuntime().getAgenda())
+1 do we already have a jira to track this refactoring, I mean to remove these dependencies, we can try to do it in steps to avoid a huge PR... but at some point, we need to tackle this...

2022-01-26 12:17 UTC, danielezonca commented on api/kogito-api/src/main/java/org/kie/kogito/rules/DataHandle.java
> +public interface DataHandle extends org.drools.ruleunits.api.DataHandle {
I agree, we can also add a note in the release note 👍

2022-01-26 15:17 UTC, evacchi commented
jenkins run native

2022-01-26 15:27 UTC, evacchi approved these changes

2022-01-26 15:27 UTC, evacchi commented on jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/StateNodeInstance.java
> +                boolean isActive = ((InternalAgenda) getProcessInstance().getKnowledgeRuntime().getAgenda())
there are:

https://issues.redhat.com/browse/KOGITO-2972
https://issues.redhat.com/browse/KOGITO-5812

2022-01-26 16:42 UTC, kie-ci1 commented
**PR job** #10 was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 1891
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-apps/10/display/redirect or see console log:
```spoiler Console Logs
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Storage Infinispan ....... SUCCESS [  2.904 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Storage MongoDB .......... SUCCESS [  2.162 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Storage PostgreSQL ....... SUCCESS [  3.740 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Storage Oracle DB ........ SUCCESS [  3.635 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Service .................. SUCCESS [  0.032 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Service Common ........... SUCCESS [  9.523 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Service with Infinispan .. SUCCESS [02:25 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Service with MongoDB ..... SUCCESS [02:21 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Service with Oracle ...... SUCCESS [03:12 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Service with PostgreSQL .. SUCCESS [02:49 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Data Index Service with In-memory persistence SUCCESS [02:38 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: UI Packages ......................... SUCCESS [  0.542 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Security Commons .................... SUCCESS [01:16 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Management Console .................. SUCCESS [01:27 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty UI ........................... SUCCESS [02:27 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Task Console ........................ SUCCESS [01:17 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability ...................... SUCCESS [  0.031 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability Api .................. SUCCESS [  1.563 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability Core ................. SUCCESS [04:00 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability Integration Tests .... SUCCESS [  0.033 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability Integration Tests DMN  SUCCESS [03:14 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability Integration Tests OpenNLP SUCCESS [  8.099 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability Integration Tests PMML SUCCESS [04:39 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability Service .............. SUCCESS [  4.315 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability Service Messaging .... FAILURE [ 13.477 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Explainability Service Rest ......... SUCCESS [02:03 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty .............................. SUCCESS [  0.039 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Storage ...................... SUCCESS [  0.056 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Storage API .................. SUCCESS [  1.604 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Storage Common ............... SUCCESS [  0.301 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Storage Infinispan ........... SUCCESS [  2.597 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Storage Redis ................ SUCCESS [  1.754 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Storage PostgreSQL ........... SUCCESS [  2.163 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Service ...................... SUCCESS [  0.046 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Service :: API ............... SUCCESS [  0.315 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Service Common ............... SUCCESS [01:36 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Service Infinispan ........... SUCCESS [02:47 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Service Redis ................ SUCCESS [02:10 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Trusty Service PostgreSQL ........... SUCCESS [02:48 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Task Assigning ...................... SUCCESS [  0.046 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Task Assigning Core ................. SUCCESS [ 10.267 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Task Assigning Process Service Client SUCCESS [ 10.963 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Task Assigning :: Integration API ... SUCCESS [  0.229 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Task Assigning :: User Service ...... SUCCESS [  0.032 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Task Assigning :: User Service Properties SUCCESS [  1.635 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Task Assigning Service .............. SUCCESS [02:54 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: JIT Executor ........................ SUCCESS [  0.031 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: JIT Executor DMN .................... SUCCESS [ 12.397 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: JIT Executor Runner ................. SUCCESS [02:32 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests ................... SUCCESS [  0.029 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service ... SUCCESS [  0.042 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Common SUCCESS [  0.311 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Quarkus SUCCESS [02:08 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Jobs Service :: Spring Boot SUCCESS [ 11.434 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service . SKIPPED
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Common SKIPPED
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Quarkus SKIPPED
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Trusty Service :: Spring Boot SKIPPED
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Data Index ..... SUCCESS [  0.039 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Common SUCCESS [  0.527 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Quarkus SUCCESS [03:45 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Data Index :: Spring Boot SUCCESS [  6.058 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service SUCCESS [  0.037 s]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Processes SUCCESS [02:25 min]
[2022-01-26T16:42:11.627Z] [INFO] Kogito Apps :: Integration Tests :: Task Assigning Service :: Quarkus SUCCESS [01:09 min]
[2022-01-26T16:42:11.627Z] [INFO] Runtime Tools Quarkus Extension - Parent ........... SUCCESS [  0.038 s]
[2022-01-26T16:42:11.627Z] [INFO] Runtime Tools Quarkus Extension - Runtime .......... SUCCESS [  8.761 s]
[2022-01-26T16:42:11.627Z] [INFO] Runtime Tools Quarkus Extension - Deployment ....... SUCCESS [  0.933 s]
[2022-01-26T16:42:11.627Z] [INFO] ------------------------------------------------------------------------
[2022-01-26T16:42:11.627Z] [INFO] BUILD FAILURE
[2022-01-26T16:42:11.627Z] [INFO] ----------------------- [...]

2022-01-26 16:43 UTC, kie-ci1 commented
**PR job** #16 was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2455
- FAILED: 6

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.kogito-runtimes/16/testReport/org.kie.kogito.it/NativeInfinispanPersistenceIT/testMultipleEmbeddedInstance/">org.kie.kogito.it.NativeInfinispanPersistenceIT.testMultipleEmbeddedInstance</a></summary>
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.


</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.kogito-runtimes/16/testReport/org.kie.kogito.it/NativeJDBCPersistenceIT/testMultipleEmbeddedInstance/">org.kie.kogito.it.NativeJDBCPersistenceIT.testMultipleEmbeddedInstance</a></summary>
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.


</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.kogito-runtimes/16/testReport/org.kie.kogito.it/NativeKafkaPersistenceIT/testMultipleEmbeddedInstance/">org.kie.kogito.it.NativeKafkaPersistenceIT.testMultipleEmbeddedInstance</a></summary>
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.


</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.kogito-runtimes/16/testReport/org.kie.kogito.it/NativeMongoDBPersistenceIT/testMultipleEmbeddedInstance/">org.kie.kogito.it.NativeMongoDBPersistenceIT.testMultipleEmbeddedInstance</a></summary>
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.


</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.kogito-runtimes/16/testReport/org.kie.kogito.it/NativePostgreSQLPersistenceIT/testMultipleEmbeddedInstance/">org.kie.kogito.it.NativePostgreSQLPersistenceIT.testMultipleEmbeddedInstance</a></summary>
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.


</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.kogito-runtimes/16/testReport/org.kie.kogito.quarkus.dmn/CustomEndpointIT/testHelloEndpoint/">org.kie.kogito.quarkus.dmn.CustomEndpointIT.testHelloEndpoint</a></summary>
java.lang.AssertionError: 
1 expectation failed.
JSON path data.d.Hello doesn't match.
Expected: is "Certidão Hello Luca"
  Actual: null

	at org.kie.kogito.quarkus.dmn.CustomEndpointIT.testHelloEndpoint(CustomEndpointIT.java:39)

</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.kogito-runtimes/16/display/redirect

2022-01-27 03:21 UTC, kie-ci1 commented
**PR job** #9 was: **ABORTED**
Possible explanation: Most probably a timeout, please review


**Test results:**
- PASSED: 472
- FAILED: 10

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.kie.kogito.dmn.quarkus.tracing/NativeLoanEligibilityIT/Build_projects___testEvaluateDMNModel/">Build projects / org.kie.kogito.dmn.quarkus.tracing.NativeLoanEligibilityIT.testEvaluateDMNModel</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>

</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.kie.kogito.dmn.quarkus.tracing/NativeLoanEligibilityIT/Build_projects___testEvaluateLoanEligibility/">Build projects / org.kie.kogito.dmn.quarkus.tracing.NativeLoanEligibilityIT.testEvaluateLoanEligibility</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>

</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.kie.kogito.dmn.quarkus.tracing/NativeLoanEligibilityIT/Build_projects___testEvaluateDMNModel/">Build projects / org.kie.kogito.dmn.quarkus.tracing.NativeLoanEligibilityIT.testEvaluateDMNModel</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>

</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.kie.kogito.dmn.quarkus.tracing/NativeLoanEligibilityIT/Build_projects___testEvaluateLoanEligibility/">Build projects / org.kie.kogito.dmn.quarkus.tracing.NativeLoanEligibilityIT.testEvaluateLoanEligibility</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>

</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.kie.kogito.dmn.quarkus.tracing/NativeLoanEligibilityIT/Build_projects___testEvaluateDMNModel/">Build projects / org.kie.kogito.dmn.quarkus.tracing.NativeLoanEligibilityIT.testEvaluateDMNModel</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>

</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.kie.kogito.dmn.quarkus.tracing/NativeLoanEligibilityIT/Build_projects___testEvaluateLoanEligibility/">Build projects / org.kie.kogito.dmn.quarkus.tracing.NativeLoanEligibilityIT.testEvaluateLoanEligibility</a></summary>
org.opentest4j.AssertionFailedError: expected: <0> but was: <1>

</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.acme.numbers/NativeForRestExampleTestIT/Build_projects___testRestExample/">Build projects / org.acme.numbers.NativeForRestExampleTestIT.testRestExample</a></summary>
java.lang.AssertionError: 
1 expectation failed.
Expected status code <201> but was <500>.


</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.acme.numbers/NativeForRestExampleTestIT/Build_projects___testRestExample/">Build projects / org.acme.numbers.NativeForRestExampleTestIT.testRestExample</a></summary>
java.lang.AssertionError: 
1 expectation failed.
Expected status code <201> but was <500>.


</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.acme.sw.onboarding.queries/AssignmentUnitIT/Build_projects___verifyNeurologyAssignmentCollection/">Build projects / org.acme.sw.onboarding.queries.AssignmentUnitIT.verifyNeurologyAssignmentCollection</a></summary>
java.lang.RuntimeException: java.lang.RuntimeException: Unable to successfully launch process '27881'. Exit code is: '1'.
Caused by: java.lang.RuntimeException: Unable to successfully launch process '27881'. Exit code is: '1'.

</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/testReport/org.acme.sw.onboarding.queries/AssignmentUnitIT/Build_projects___verifyNeurologyAssignmentCollection/">Build projects / org.acme.sw.onboarding.queries.AssignmentUnitIT.verifyNeurologyAssignmentCollection</a></summary>
java.lang.RuntimeException: java.lang.RuntimeException: Unable to successfully launch process '32747'. Exit code is: '1'.
Caused by: java.lang.RuntimeException: Unable to successfully launch process '32747'. Exit code is: '1'.

</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.native.downstream.kogito-examples/9/display/redirect or see console log:
```spoiler Console Logs
[2022-01-26T21:51:17.497Z] # /project/hs_err_pid25.log
[2022-01-26T21:51:17.497Z] Compiled method (JVMCI)  123815 29554       4       jdk.internal.misc.Unsafe::copyMemory (33 bytes)
[2022-01-26T21:51:17.497Z]  total in heap  [0x00007f1fae560a10,0x00007f1fae560f20] = 1296
[2022-01-26T21:51:17.497Z]  relocation     [0x00007f1fae560b78,0x00007f1fae560b90] = 24
[2022-01-26T21:51:17.497Z]  main code      [0x00007f1fae560ba0,0x00007f1fae560d92] = 498
[2022-01-26T21:51:17.497Z]  stub code      [0x00007f1fae560d92,0x00007f1fae560d98] = 6
[2022-01-26T21:51:17.497Z]  metadata       [0x00007f1fae560d98,0x00007f1fae560db8] = 32
[2022-01-26T21:51:17.497Z]  scopes data    [0x00007f1fae560db8,0x00007f1fae560e50] = 152
[2022-01-26T21:51:17.497Z]  scopes pcs     [0x00007f1fae560e50,0x00007f1fae560ef0] = 160
[2022-01-26T21:51:17.497Z]  dependencies   [0x00007f1fae560ef0,0x00007f1fae560ef8] = 8
[2022-01-26T21:51:17.497Z]  nul chk table  [0x00007f1fae560ef8,0x00007f1fae560f10] = 24
[2022-01-26T21:51:17.497Z]  JVMCI data     [0x00007f1fae560f10,0x00007f1fae560f20] = 16
[2022-01-26T21:51:17.497Z] Compiled method (JVMCI)  123817 29554       4       jdk.internal.misc.Unsafe::copyMemory (33 bytes)
[2022-01-26T21:51:17.497Z]  total in heap  [0x00007f1fae560a10,0x00007f1fae560f20] = 1296
[2022-01-26T21:51:17.497Z]  relocation     [0x00007f1fae560b78,0x00007f1fae560b90] = 24
[2022-01-26T21:51:17.497Z]  main code      [0x00007f1fae560ba0,0x00007f1fae560d92] = 498
[2022-01-26T21:51:17.497Z]  stub code      [0x00007f1fae560d92,0x00007f1fae560d98] = 6
[2022-01-26T21:51:17.497Z]  metadata       [0x00007f1fae560d98,0x00007f1fae560db8] = 32
[2022-01-26T21:51:17.497Z]  scopes data    [0x00007f1fae560db8,0x00007f1fae560e50] = 152
[2022-01-26T21:51:17.497Z]  scopes pcs     [0x00007f1fae560e50,0x00007f1fae560ef0] = 160
[2022-01-26T21:51:17.498Z]  dependencies   [0x00007f1fae560ef0,0x00007f1fae560ef8] = 8
[2022-01-26T21:51:17.498Z]  nul chk table  [0x00007f1fae560ef8,0x00007f1fae560f10] = 24
[2022-01-26T21:51:17.498Z]  JVMCI data     [0x00007f1fae560f10,0x00007f1fae560f20] = 16
[2022-01-26T21:51:17.498Z] Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
[2022-01-26T21:51:17.49 [...]

2022-01-27 09:37 UTC, merged