[KOGITO-6699]-Drop Spring Boot support from Serverless Workflow
kiegroup/kogito-runtimes pull request #2053
Opened 2022-03-02 17:37 UTC by VaniHaripriya

Jira- https://issues.redhat.com/browse/KOGITO-6699

1. Removed SB Serverless Workflow Starter
2. Updated  kogito-serverless-workflow module README Document that Quarkus is the only supported runtime.

2022-03-03 13:39 UTC, ricardozanini approved these changes

2022-03-03 13:39 UTC, ricardozanini commented on kogito-serverless-workflow/README.md
> +Quarkus is the only supported runtime for Kogito Serverless Workflow.
```suggestion
> ⚠️ Quarkus is the only supported runtime for Kogito Serverless Workflow.
```

2022-03-03 15:02 UTC, kie-ci1 commented
**(tests) - kogito-examples job** `#1318` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 450
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1318/testReport/org.kie.kogito.springboot.outbox/OutboxIT/___/">org.kie.kogito.springboot.outbox.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49237] should be listening)<br/>	at org.kie.kogito.springboot.outbox.OutboxIT.before(OutboxIT.java:83)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49237] should be listening)<br/>
</details>

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1318/display/redirect

2022-03-04 17:03 UTC, fjtirado approved these changes

2022-03-04 17:23 UTC, fjtirado commented
jenkins rerun kogito-examples tests

2022-03-07 11:40 UTC, MarianMacik requested changes

2022-03-07 11:40 UTC, MarianMacik commented on springboot/starters/pom.xml
> -        <module>kogito-serverless-workflow-spring-boot-starter</module>
In that case we need to exclude if from the Spring Boot archetype:
https://github.com/kiegroup/kogito-runtimes/blob/800f88595d92b507d61b7a20976e58afee7b6571/springboot/archetype/src/main/resources/META-INF/archetype-post-generate.groovy#L32-L40

2022-03-08 09:47 UTC, VaniHaripriya commented on springboot/starters/pom.xml
> -        <module>kogito-serverless-workflow-spring-boot-starter</module>
Thank you for the info @MarianMacik . Will update accordingly.

2022-03-08 12:17 UTC, MarianMacik requested changes

2022-03-08 12:17 UTC, MarianMacik commented on springboot/archetype/src/main/resources/META-INF/archetype-post-generate.groovy
> -            [id: "serverless-workflows", starter: "kogito-serverless-workflows-spring-boot-starter"],
There's also a README.md entry:
https://github.com/kiegroup/kogito-runtimes/blob/831205275412e386237552436006f7093c7fa5c1/springboot/archetype/README.md?plain=1#L35-L42

That should be all I hope :)

2022-03-08 18:56 UTC, kie-ci1 commented
**(tests) - kogito-apps job** `#1250` was: **UNSTABLE**
Possible explanation: This should be test failures


**Test results:**
- PASSED: 2696
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1250/testReport/org.kie.kogito.explainability.local.counterfactual/CounterfactualExplainerTest/testFinalUniqueIds(int)[2]/">org.kie.kogito.explainability.local.counterfactual.CounterfactualExplainerTest.testFinalUniqueIds(int)[2]</a></summary>
org.opentest4j.AssertionFailedError: expected: <19> but was: <20><br/>	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)<br/>	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)<br/>	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)<br/>	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)<br/>	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)<br/>	at org.kie.kogito.explainability.local.counterfactual.CounterfactualExplainerTest.testFinalUniqueIds(CounterfactualExplainerTest.java:794)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)<br/>	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:92)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)<br/>	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:139)<br/>	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:107)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)<br/>	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)<br/>	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)<br/>	at java.base/java.util.ArrayList$ArrayListSpliter [...]

2022-03-09 14:50 UTC, MarianMacik approved these changes
Thanks!

2022-03-10 01:07 UTC, cristianonicolai commented
Jenkins rerun kogito-apps tests

2022-03-10 02:25 UTC, kie-ci1 commented
**(tests) - kogito-apps job** `#1251` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1251/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-10T02:24:32.683Z] [INFO] |  \- io.quarkus:quarkus-resteasy-jackson:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     +- org.jboss.resteasy:resteasy-jackson2-provider:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.13.1:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.13.1:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.13.1:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     |  \- com.github.java-json-tools:json-patch:jar:1.13:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     |     +- com.github.java-json-tools:msg-simple:jar:1.2:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     |     |  \- com.github.java-json-tools:btf:jar:1.3:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     |     \- com.github.java-json-tools:jackson-coreutils:jar:2.0:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     \- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] +- io.quarkus:quarkus-rest-client-deployment:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  +- io.quarkus:quarkus-resteasy-common-deployment:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  +- io.quarkus:quarkus-resteasy-common:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |  +- org.jboss.resteasy:resteasy-core:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |  |  \- com.ibm.async:asyncutil:jar:0.1.0:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |  \- com.sun.activation:jakarta.activation:jar:1.2.1:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  \- io.quarkus:quarkus-resteasy-common-spi:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  +- io.quarkus:quarkus-apache-httpclient-deployment:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  \- io.quarkus:quarkus-apache-httpclient:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  +- io.quarkus:quarkus-rest-client:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  +- io.quarkus:quarkus-rest-client-config:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |  \- org.eclipse.microprofile.rest.client:microprofile-rest-client-api:jar:2.0:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  +- org.jboss.resteasy:resteasy-client-microprofile:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |  \- org.jboss.resteasy:resteasy-client-microprofile-base:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |     +- org.jboss.resteasy:resteasy-client:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |     |  \- org.jboss.resteasy:resteasy-client-api:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |     \- org.jboss.resteasy:resteasy-cdi:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  +- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.5:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.15:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  \- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  \- io.quarkus:quarkus-rest-client-config-deployment:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] +- io.quarkus:quarkus-resteasy-multipart-deployment:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  \- io.quarkus:quarkus-resteasy-multipart:jar:2.7.3.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |     \- org.jboss.resteasy:resteasy-multipart-provider:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |        +- org.jboss.resteasy:resteasy-core-spi:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |        +- org.jboss.resteasy:resteasy-jaxb-provider:jar:4.7.5.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |        |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |        |     +- org.glassfish.jaxb:txw2:jar:2.3.3-b02:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |        |     \- com.sun.istack:istack-commons-runtime:jar:3.0.10:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |        +- com.sun.mail:jakarta.mail:jar:1.6.5:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |        +- org.apache.james:apache-mime4j-dom:jar:0.8.3:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |        |  \- org.apache.james:apache-mime4j-core:jar:0.8.3:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |        \- org.apache.james:apache-mime4j-storage:jar:0.8.3:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |           \- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] +- org.kie.kogito:kogito-addons-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] +- org.kie.kogito:kogito-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  +- org.kie.kogito:kogito-quarkus-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-application:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |  \- org.kie.kogito:kogito-api-incubation-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-common-objectmapper:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  +- org.mvel:mvel2:jar:2.4.12.Final:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  +- com.jayway.jsonpath:json-path:jar:2.6.0:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |  \- net.minidev:json-smart:jar:2.4.7:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  |     \- net.minidev:accessors-smart:jar:2.4.7:compile<br/>[2022-03-10T02:24:32.683Z] [INFO] |  |  \- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |     +- org.kie:kie-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |     +- org.drools:drools-ruleunits-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |     +- org.kie:kie-dmn-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |     |  \- org.kie:kie-dmn-model:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |     +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |     \- org.kie.kogito:kogito-pmml-api-dependencies:pom:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |        +- org.kie:kie-pmml-evaluator-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |        |  \- org.kie:kie-pmml-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |        |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |        \- org.kie:kie-pmml-commons:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |           \- org.apache.commons:commons-text:jar:1.9:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  +- org.kie.kogito:kogito-drools:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |  +- org.drools:drools-compiler:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-10T02:24:32.684Z] [INFO] |  |  |  +- org.d [...]

2022-03-11 01:52 UTC, cristianonicolai commented
Jenkins rerun kogito-apps tests

2022-03-11 03:03 UTC, kie-ci1 commented
**(tests) - kogito-apps job** `#1258` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1258/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-11T03:02:55.268Z] [INFO] |  \- io.quarkus:quarkus-resteasy-jackson:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     +- org.jboss.resteasy:resteasy-jackson2-provider:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.13.1:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.13.1:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.13.1:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     |  \- com.github.java-json-tools:json-patch:jar:1.13:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     |     +- com.github.java-json-tools:msg-simple:jar:1.2:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     |     |  \- com.github.java-json-tools:btf:jar:1.3:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     |     \- com.github.java-json-tools:jackson-coreutils:jar:2.0:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     \- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] +- io.quarkus:quarkus-rest-client-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  +- io.quarkus:quarkus-resteasy-common-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  +- io.quarkus:quarkus-resteasy-common:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |  +- org.jboss.resteasy:resteasy-core:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |  |  \- com.ibm.async:asyncutil:jar:0.1.0:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |  \- com.sun.activation:jakarta.activation:jar:1.2.1:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  \- io.quarkus:quarkus-resteasy-common-spi:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  +- io.quarkus:quarkus-apache-httpclient-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  \- io.quarkus:quarkus-apache-httpclient:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  +- io.quarkus:quarkus-rest-client:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  +- io.quarkus:quarkus-rest-client-config:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |  \- org.eclipse.microprofile.rest.client:microprofile-rest-client-api:jar:2.0:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  +- org.jboss.resteasy:resteasy-client-microprofile:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |  \- org.jboss.resteasy:resteasy-client-microprofile-base:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |     +- org.jboss.resteasy:resteasy-client:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |     |  \- org.jboss.resteasy:resteasy-client-api:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |     \- org.jboss.resteasy:resteasy-cdi:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  +- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.5:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.15:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  \- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  \- io.quarkus:quarkus-rest-client-config-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] +- io.quarkus:quarkus-resteasy-multipart-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  \- io.quarkus:quarkus-resteasy-multipart:jar:2.7.3.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |     \- org.jboss.resteasy:resteasy-multipart-provider:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |        +- org.jboss.resteasy:resteasy-core-spi:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |        +- org.jboss.resteasy:resteasy-jaxb-provider:jar:4.7.5.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |        |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |        |     +- org.glassfish.jaxb:txw2:jar:2.3.3-b02:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |        |     \- com.sun.istack:istack-commons-runtime:jar:3.0.10:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |        +- com.sun.mail:jakarta.mail:jar:1.6.5:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |        +- org.apache.james:apache-mime4j-dom:jar:0.8.3:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |        |  \- org.apache.james:apache-mime4j-core:jar:0.8.3:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |        \- org.apache.james:apache-mime4j-storage:jar:0.8.3:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |           \- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] +- org.kie.kogito:kogito-addons-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] +- org.kie.kogito:kogito-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  +- org.kie.kogito:kogito-quarkus-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-application:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |  \- org.kie.kogito:kogito-api-incubation-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-common-objectmapper:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  +- org.mvel:mvel2:jar:2.4.12.Final:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  +- com.jayway.jsonpath:json-path:jar:2.6.0:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |  \- net.minidev:json-smart:jar:2.4.7:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  |     \- net.minidev:accessors-smart:jar:2.4.7:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |  \- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |     +- org.kie:kie-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |     +- org.drools:drools-ruleunits-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.268Z] [INFO] |  |     +- org.kie:kie-dmn-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |     |  \- org.kie:kie-dmn-model:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |     +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |     \- org.kie.kogito:kogito-pmml-api-dependencies:pom:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |        +- org.kie:kie-pmml-evaluator-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |        |  \- org.kie:kie-pmml-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |        |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |        \- org.kie:kie-pmml-commons:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |           \- org.apache.commons:commons-text:jar:1.9:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  +- org.kie.kogito:kogito-drools:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |  +- org.drools:drools-compiler:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T03:02:55.269Z] [INFO] |  |  |  +- org.d [...]

2022-03-11 03:48 UTC, cristianonicolai commented
Jenkins rerun kogito-apps tests

2022-03-11 05:03 UTC, kie-ci1 commented
**(tests) - kogito-apps job** `#1259` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1259/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-11T05:02:57.127Z] [INFO] |  \- io.quarkus:quarkus-resteasy-jackson:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     +- org.jboss.resteasy:resteasy-jackson2-provider:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.13.1:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.13.1:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.13.1:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     |  \- com.github.java-json-tools:json-patch:jar:1.13:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     |     +- com.github.java-json-tools:msg-simple:jar:1.2:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     |     |  \- com.github.java-json-tools:btf:jar:1.3:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     |     \- com.github.java-json-tools:jackson-coreutils:jar:2.0:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     \- org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec:jar:2.0.0.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] +- io.quarkus:quarkus-rest-client-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  +- io.quarkus:quarkus-resteasy-common-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- io.quarkus:quarkus-resteasy-common:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |  +- org.jboss.resteasy:resteasy-core:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |  |  \- com.ibm.async:asyncutil:jar:0.1.0:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |  \- com.sun.activation:jakarta.activation:jar:1.2.1:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  \- io.quarkus:quarkus-resteasy-common-spi:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  +- io.quarkus:quarkus-apache-httpclient-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  \- io.quarkus:quarkus-apache-httpclient:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  +- io.quarkus:quarkus-rest-client:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- io.quarkus:quarkus-rest-client-config:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |  \- org.eclipse.microprofile.rest.client:microprofile-rest-client-api:jar:2.0:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- org.jboss.resteasy:resteasy-client-microprofile:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |  \- org.jboss.resteasy:resteasy-client-microprofile-base:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |     +- org.jboss.resteasy:resteasy-client:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |     |  \- org.jboss.resteasy:resteasy-client-api:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |     \- org.jboss.resteasy:resteasy-cdi:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- jakarta.interceptor:jakarta.interceptor-api:jar:1.2.5:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.5:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |  \- org.apache.httpcomponents:httpcore-nio:jar:4.4.15:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  \- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  \- io.quarkus:quarkus-rest-client-config-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] +- io.quarkus:quarkus-resteasy-multipart-deployment:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  \- io.quarkus:quarkus-resteasy-multipart:jar:2.7.3.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |     \- org.jboss.resteasy:resteasy-multipart-provider:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |        +- org.jboss.resteasy:resteasy-core-spi:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |        +- org.jboss.resteasy:resteasy-jaxb-provider:jar:4.7.5.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |        |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3-b02:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |        |     +- org.glassfish.jaxb:txw2:jar:2.3.3-b02:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |        |     \- com.sun.istack:istack-commons-runtime:jar:3.0.10:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |        +- com.sun.mail:jakarta.mail:jar:1.6.5:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |        +- org.apache.james:apache-mime4j-dom:jar:0.8.3:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |        |  \- org.apache.james:apache-mime4j-core:jar:0.8.3:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |        \- org.apache.james:apache-mime4j-storage:jar:0.8.3:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |           \- commons-io:commons-io:jar:2.11.0:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] +- org.kie.kogito:kogito-addons-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] +- org.kie.kogito:kogito-quarkus-common-deployment:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  +- org.kie.kogito:kogito-quarkus-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-application:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |  \- org.kie.kogito:kogito-api-incubation-common:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- org.kie.kogito:kogito-api-incubation-common-objectmapper:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- org.mvel:mvel2:jar:2.4.12.Final:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- com.jayway.jsonpath:json-path:jar:2.6.0:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |  \- net.minidev:json-smart:jar:2.4.7:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |     \- net.minidev:accessors-smart:jar:2.4.7:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  \- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |     +- org.kie:kie-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |     +- org.drools:drools-ruleunits-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |     +- org.kie:kie-dmn-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |     |  \- org.kie:kie-dmn-model:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |     +- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |     \- org.kie.kogito:kogito-pmml-api-dependencies:pom:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |        +- org.kie:kie-pmml-evaluator-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |        |  \- org.kie:kie-pmml-api:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |        |     \- org.apache.commons:commons-math3:jar:3.4.1:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |        \- org.kie:kie-pmml-commons:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |           \- org.apache.commons:commons-text:jar:1.9:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  +- org.kie.kogito:kogito-drools:jar:2.0.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  +- org.drools:drools-compiler:jar:8.19.0-SNAPSHOT:compile<br/>[2022-03-11T05:02:57.127Z] [INFO] |  |  |  +- org.d [...]

2022-03-11 06:05 UTC, cristianonicolai commented
Jenkins rerun kogito-apps tests

2022-03-11 08:11 UTC, merged