[KOGITO-6853] Fixing error with default condition
kiegroup/kogito-runtimes pull request #2078
Opened 2022-03-10 16:04 UTC by fjtirado

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>Run all builds</b>  
  Please add comment: <b>Jenkins retest this</b>

* <b>Run (or rerun) specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] tests</b>
 
* <b>Quarkus LTS checks</b>  
  Please add comment: <b>Jenkins run LTS</b>

* <b>Run (or rerun) LTS specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] LTS</b>

* <b>Native checks</b>  
  Please add comment: <b>Jenkins run native</b>

* <b>Run (or rerun) native specific test(s)</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|optaplanner|kogito-apps|kogito-examples|optaplanner-quickstarts|optaweb-employee-rostering|optaweb-vehicle-routing] native</b>

* <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2022-03-10 16:33 UTC, fjtirado commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/parser/handlers/StateHandler.java
> +    private Collection<Long> incomingConnections = new LinkedHashSet<>();
This should has been a set since the beginning to handle redundant paths. It needs to preserver order of insertion (the reason was originalle a list). So LinkedHashSet is the way to go

2022-03-10 17:14 UTC, kie-ci1 commented
**(tests) - kogito-examples job** `#1347` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


**Test results:**
- PASSED: 356
- FAILED: 0

Those are the test failures: none

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1347/display/redirect or see console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-03-10T17:14:40.137Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>[2022-03-10T17:14:40.137Z] 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)<br/>[2022-03-10T17:14:40.137Z] 	at org.kie.kogito.codegen.core.ApplicationGenerator.generateComponents(ApplicationGenerator.java:99)<br/>[2022-03-10T17:14:40.137Z] 	at org.kie.kogito.codegen.core.ApplicationGenerator.generate(ApplicationGenerator.java:74)<br/>[2022-03-10T17:14:40.137Z] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateFiles(KogitoAssetsProcessor.java:196)<br/>[2022-03-10T17:14:40.137Z] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateSources(KogitoAssetsProcessor.java:109)<br/>[2022-03-10T17:14:40.137Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>[2022-03-10T17:14:40.137Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>[2022-03-10T17:14:40.137Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>[2022-03-10T17:14:40.137Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>[2022-03-10T17:14:40.137Z] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:882)<br/>[2022-03-10T17:14:40.137Z] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)<br/>[2022-03-10T17:14:40.137Z] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>[2022-03-10T17:14:40.137Z] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>[2022-03-10T17:14:40.137Z] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>[2022-03-10T17:14:40.137Z] 	at java.base/java.lang.Thread.run(Thread.java:829)<br/>[2022-03-10T17:14:40.137Z] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>[2022-03-10T17:14:40.137Z] Caused by: java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.<br/>[2022-03-10T17:14:40.137Z] 	at com.github.javaparser.ast.Node.getData(Node.java:505)<br/>[2022-03-10T17:14:40.137Z] 	at com.github.javaparser.ast.CompilationUnit.getPrinter(CompilationUnit.java:154)<br/>[2022-03-10T17:14:40.137Z] 	at com.github.javaparser.ast.Node.lambda$getPrinter$1(Node.java:199)<br/>[2022-03-10T17:14:40.137Z] 	at java.base/java.util.Optional.map(Optional.java:265)<br/>[2022-03-10T17:14:40.137Z] 	at com.github.javaparser.ast.Node.getPrinter(Node.java:199)<br/>[2022-03-10T17:14:40.138Z] 	at com.github.javaparser.ast.Node.toString(Node.java:322)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2890)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:952)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:926)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:919)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:496)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:459)<br/>[2022-03-10T17:14:40.138Z] 	at org.drools.modelcompiler.builder.PackageModel.generateRulesInUnit(PackageModel.java:703)<br/>[2022-03-10T17:14:40.138Z] 	at org.drools.modelcompiler.builder.PackageModel.lambda$getRulesSource$6(PackageModel.java:591)<br/>[2022-03-10T17:14:40.138Z] 	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4698)<br/>[2022-03-10T17:14:40.138Z] 	at org.drools.modelcompiler.builder.PackageModel.getRulesSource(PackageModel.java:582)<br/>[2022-03-10T17:14:40.138Z] 	at org.drools.modelcompiler.builder.PackageModelWriter.<init>(PackageModelWriter.java:37)<br/>[2022-03-10T17:14:40.138Z] 	at org.kie.kogito.codegen.rules.KogitoPackageSources.dumpSources(KogitoPackageSources.java:68)<br/>[2022-03-10T17:14:40.138Z] 	at org.drools.modelcompiler.builder.ModelBuilderImpl.buildRules(ModelBuilderImpl.java:228)<br/>[2022-03-10T17:14:40.138Z] 	at org.drools.modelcompiler.builder.ModelBuilderImpl.doSecondBuildStep(ModelBuilderImpl.java:119)<br/>[2022-03-10T17:14:40.138Z] 	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.build(CompositeKnowledgeBuilderImpl.java:116)<br/>[2022-03-10T17:14:40.138Z] 	at org.drools.compiler.builder.impl.CompositeKnowledgeBuilderImpl.build(CompositeKnowledgeBuilderImpl.java:100)<br/>[2022-03-10T17:14:40.138Z] 	at org.kie.kogito.codegen.rules.DroolsModelBuilder.build(DroolsModelBuilder.java:70)<br/>[2022-03-10T17:14:40.138Z] 	... 25 more<br/>[2022-03-10T17:14:40.138Z] <br/>[2022-03-10T17:14:40.138Z]     at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment (AugmentActionImpl.java:330)<br/>[2022-03-10T17:14:40.138Z]     at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication (AugmentActionImpl.java:175)<br/>[2022-03-10T17:14:40.138Z]     at io.quarkus.maven.BuildMojo.doExecute (BuildMojo.java:132)<br/>[2022-03-10T17:14:40.138Z]     at io.quarkus.maven.QuarkusBootstrapMojo.execute (QuarkusBootstrapMojo.java:131)<br/>[2022-03-10T17:14:40.138Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2022-03-10T17:14:40.138Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)<br/>[2022-03-10T17:14:40.138Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)<br/>[2022-03-10T17:14:40.138Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)<br/>[2022-03-10T17:14:40.138Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2022-03-10T17:14:40.138Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2022-03-10T17:14:40.138Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2022-03-10T17:14:40.138Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2022-03-10T17:14:40.138Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)<br/>[2022-03-10 [...]

2022-03-10 18:41 UTC, hbelmiro approved these changes
Great work @fjtirado.
I just left one minor suggestion.

2022-03-10 18:41 UTC, hbelmiro commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/greetUnknown.sw.json
> +      }
We don't have to set `"terminate": true` on end definition in SW unless we have `"keepActive"` top-level prop set to true.

```suggestion
      ]
```

2022-03-10 18:49 UTC, hbelmiro commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/greetUnknown.sw.json
> +      }
We don't have to set "terminate": true on end definition in SW unless we have "keepActive" top-level prop set to true.

```suggestion
      "end": true
```

2022-03-10 18:50 UTC, hbelmiro approved these changes

2022-03-10 19:14 UTC, fjtirado commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/greetUnknown.sw.json
> +      }
Indeed, a copy paste thing, thanks for pointing out

2022-03-11 08:19 UTC, wmedvede approved these changes

2022-03-11 08:29 UTC, wmedvede requested changes
If you plan to do a kind of all in one PR and fix https://issues.redhat.com/browse/KOGITO-6853 as part of this PR, then we need an integration test to be sure the issue with the data conditions in the switch test is fixed.

Take a look at the https://issues.redhat.com/browse/KOGITO-6853 please, it'll take 5 mins to add the integration test.

2022-03-11 11:05 UTC, fjtirado commented
@wmedvede I did not use the original description because it was too large for a summry, in my opinion, but anyway I copy paste it here now
 I checked the JIRA attachment and use the bpmn to debug and find the issue, thanks a lot for that. 
The integration test is this one (a variation of the currenlty existing one) 
https://github.com/kiegroup/kogito-runtimes/pull/2078/files#diff-95a0b0cd69c7aaf437c71507a7e642fff56ba8190ef16fec8ae8e805bdfdcdecR36

2022-03-11 11:05 UTC, merged