[KOGITO-6687] Improving property naming strategy
kiegroup/kogito-runtimes pull request #2293
Opened 2022-06-24 12:37 UTC by fjtirado

This adds:
- A new SWF extension to allow user to set their own config key property
for every URI
- The possibility to choose between certain predefined strategies for
this config key resolution: FILE_NAME (current default), SPEC_TITLE
(Take the config key from the spec file title) or FULL_URI (use the full
URI to generate the name)

2022-06-24 16:55 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#367` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/367/display/redirect

**Test results:**
- PASSED: 2792
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/367/testReport/org.jbpm.bpmn2/ProcessFactoryTest/testBoundaryTimerTimeCycle/">org.jbpm.bpmn2.ProcessFactoryTest.testBoundaryTimerTimeCycle</a></summary>
java.util.ConcurrentModificationException<br/>	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1661)<br/>	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)<br/>	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)<br/>	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)<br/>	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)<br/>	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)<br/>	at org.jbpm.bpmn2.JbpmBpmn2TestCase.getNotTriggeredNodes(JbpmBpmn2TestCase.java:280)<br/>	at org.jbpm.bpmn2.JbpmBpmn2TestCase.assertNodeTriggered(JbpmBpmn2TestCase.java:242)<br/>	at org.jbpm.bpmn2.ProcessFactoryTest.testBoundaryTimerTimeCycle(ProcessFactoryTest.java:193)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)<br/>	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)<br/>	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.j [...]

2022-06-24 20:14 UTC, hbelmiro reviewed
Great work, @fjtirado!
I left a few comments about typos and minor enhancements. The rest looks good.

2022-06-24 20:14 UTC, hbelmiro commented on kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/ResourceCacheFactory.java
> +    private static AtomicReference<ResourceCache> cache = new AtomicReference<>(new LocalResourceCache());
```suggestion
    private static final AtomicReference<ResourceCache> cache = new AtomicReference<>(new LocalResourceCache());
```

2022-06-24 20:14 UTC, hbelmiro commented on kogito-serverless-workflow/kogito-serverless-workflow-runtime/src/main/java/org/kie/kogito/serverless/workflow/io/ResourceCacheFactory.java
> +        private Map<URI, byte[]> map = Collections.synchronizedMap(new WeakHashMap<>());
```suggestion
        private final Map<URI, byte[]> map = Collections.synchronizedMap(new WeakHashMap<>());
```

2022-06-24 21:30 UTC, martinweiler requested changes
@fjtirado great work! I ran into two issues, see my comments:
1. Config parameter not read from application.properties
2. Build issue when using FULL_URI due to slashes in the filename

2022-06-24 21:30 UTC, martinweiler commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/operationid/URIWorkflowOperationIdFactory.java
> +        return Path.of(uri.getPath()).toString();
The slashes need to be converted to underscores, otherwise the codegen step fails:
```
Caused by: java.io.FileNotFoundException: /data/jboss/github/kiegroup/kogito/kogito-examples/kogito-quarkus-examples/serverless-workflow-temperature-conversion/conversion-workflow-updated/target/generated-sources/open-api-stream/api/multiplication/document (No such file or directory)
    at java.io.FileOutputStream.open0 (Native Method)
    at java.io.FileOutputStream.open (FileOutputStream.java:298)
    at java.io.FileOutputStream.<init> (FileOutputStream.java:237)
    at java.io.FileOutputStream.<init> (FileOutputStream.java:126)
    at io.quarkiverse.openapi.generator.deployment.codegen.OpenApiGeneratorStreamCodeGen.trigger (OpenApiGeneratorStreamCodeGen.java:72)
```

Something like the following should work:
```
+        return Path.of(uri.getPath()).toString().replaceFirst("/", "").replaceAll("/", "_");
```

2022-06-24 21:30 UTC, martinweiler commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowCodeGenUtils.java
> +    }
Only works with system property (eg. `-Dkogito.sw.operationIdStrategy=FULL_URI`), config is not picked up from application.properties. Is this an issue?

2022-06-27 07:48 UTC, fjtirado commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/operationid/AbstractWorkflowOperationIdFactory.java
> +            uri = URI.create(convertedUri.get());
Hmmmm, actually I do not like that proposal ;), specially, when like in this case, there is no change an exception will be thrown.

2022-06-27 07:49 UTC, fjtirado commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/operationid/WorkflowOperationIdFactoryType.java
> +    private WorkflowOperationIdFactoryType(WorkflowOperationIdFactory factory) {
well, like the final you suggest in the previous comment, but it is more clear this way

2022-06-27 07:52 UTC, fjtirado commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/operationid/URIWorkflowOperationIdFactory.java
> +        return Path.of(uri.getPath()).toString();
hmmmmmmmm
I think this is actually a failure in the extension

2022-06-27 07:54 UTC, fjtirado commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowCodeGenUtils.java
> +    }
hmmmm, 
Since ConfigProvider is the quarkus API, Im afraid there is no much we can do and has to document it.

2022-06-27 08:06 UTC, fjtirado commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/main/java/org/kie/kogito/serverless/workflow/operationid/URIWorkflowOperationIdFactory.java
> +        return Path.of(uri.getPath()).toString();
This code should be 
```

  try (ReadableByteChannel inChannel = Channels.newChannel(inputModel.getInputStream());
                        FileChannel outChannel = FileChannel.open(openApiFilePath)) {
                    outChannel.transferFrom(inChannel, 0, Integer.MAX_VALUE);
                    LOGGER.debug("Saved OpenAPI spec input model in {}", openApiFilePath);
                    this.generate(this.mergeConfig(context, inputModel), openApiFilePath, outDir);
                    generated = true;
                } catch (IOException e) {
                    throw new UncheckedIOException("Failed to save InputStream from provider " + provider + " into location ",
                            e);
                }
```

2022-06-27 11:39 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#428` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/428/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2348.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2349.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2350.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2351.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2352.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2353.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2354.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2355.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2356.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] du: cannot access ‘/home/jenkins/workspace/KIE/kogito/main/pullrequest/drools.tests.drools_ws-cleanup_1656329974301/bc/kiegroup_drools/drools/target/sonar/ucfg2/java/ucfg_2357.proto’: No such file or directory<br/>[2022-06-27T11:39:39.555Z] 260M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-06-27T11:39:39.555Z] 260M	/home/jenkins/workspace/KIE/kogito<br/>[2022-06-27T11:39:39.555Z] 260M	/home/jenkins/workspace/KIE<br/>[2022-06-27T11:39:39.555Z] 260M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>Stage "Install build-chain tool" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>Stage "Build projects" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Sonar analysis)<br/>Stage "Sonar analysis" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space after build)<br/>Stage "check space after build" skipped due to earlier failure(s)<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Post Actions)<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-06-27T11:39:40.462Z] + wget --no-check-certificate -qO - https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/428/api/json<br/>[Pipeline] readJSON<br/>[Pipeline] sh<br/>
</details>

2022-06-27 12:44 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#513` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/513/display/redirect

**Test results:**
- PASSED: 2741
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/513/testReport/org.kie.kogito.explainability.local.shap/ShapKernelExplainerTest/testManyFeatureRegularization/">org.kie.kogito.explainability.local.shap.ShapKernelExplainerTest.testManyFeatureRegularization</a></summary>
org.opentest4j.AssertionFailedError: expected: <true> but was: <false><br/>	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)<br/>	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)<br/>	at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)<br/>	at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:179)<br/>	at org.kie.kogito.explainability.local.shap.ShapKernelExplainerTest.testManyFeatureRegularization(ShapKernelExplainerTest.java:686)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)<br/>	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)<br/>	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.Defau [...]

2022-06-27 18:51 UTC, ricardozanini approved these changes

2022-06-27 18:51 UTC, ricardozanini commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/SpecTitleOperationIdTest.java
> +        assertEquals("javibetico", id.getPackageName());
Please, don't use your name.

2022-06-27 18:51 UTC, ricardozanini commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowCodeGenUtils.java
> +    }
For this to work, the property must start with `quarkus` and be a configuration source for the Quarkus SW Extension.

2022-06-28 06:10 UTC, fjtirado commented on kogito-serverless-workflow/kogito-serverless-workflow-builder/src/test/java/org/kie/kogito/serverless/workflow/operationid/SpecTitleOperationIdTest.java
> +        assertEquals("javibetico", id.getPackageName());
I do not see why I cannot use my name in test, but ok, changed

2022-06-28 07:00 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#382` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/382/display/redirect

**Test results:**
- PASSED: 2789
- FAILED: 8

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/382/testReport/org.kie.kogito.quarkus.workflows/CallbackStateIT/callbackStateSuccessful/">org.kie.kogito.quarkus.workflows.CallbackStateIT.callbackStateSuccessful</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.workflows.CallbackStateIT.callbackStateSuccessful(CallbackStateIT.java:38)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/382/testReport/org.kie.kogito.quarkus.workflows/CallbackStateTimeoutsIT/callbackStateTimeoutsSuccessful/">org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsSuccessful</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsSuccessful(CallbackStateTimeoutsIT.java:43)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/382/testReport/org.kie.kogito.quarkus.workflows/CallbackStateTimeoutsIT/callbackStateTimeoutsExceeded/">org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded(CallbackStateTimeoutsIT.java:56)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/382/testReport/org.kie.kogito.quarkus.workflows/ConversationFlowIT/sanityVerification/">org.kie.kogito.quarkus.workflows.ConversationFlowIT.sanityVerification</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.workflows.ConversationFlowIT.sanityVerification(ConversationFlowIT.java:53)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/382/testReport/org.kie.kogito.quarkus.workflows/CorrelationIT/correlationEventTest/">org.kie.kogito.quarkus.workflows.CorrelationIT.correlationEventTest</a></summary>
org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.WorkflowTestUtils that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/> within 3 minutes.<br/>	at org.kie.kogito.quarkus.workflows.CorrelationIT.correlationEventTest(CorrelationIT.java:117)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/382/testReport/org.kie.kogito.quarkus.workflows/TokenPropagationIT/tokenPropagations/">org.kie.kogito.quarkus.workflows.TokenPropagationIT.tokenPropagations</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.workflows.TokenPropagationIT.tokenPropagations(TokenPropagationIT.java:57)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/382/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi2_0/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0(ApiWithSecurityContextIT.java:62)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/382/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi3_0/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi3_0</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi3_0(ApiWithSecurityContextIT.java:83)<br/>
</details>

2022-06-28 07:12 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#430` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/430/display/redirect

**Test results:**
- PASSED: 420
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/430/testReport/org.acme.newsletter.subscription.flow/SubscriptionFlowIT/Build_projects___verifySubscription/">Build projects / org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription(SubscriptionFlowIT.java:97)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/430/testReport/org.acme.newsletter.subscription.flow/SubscriptionFlowIT/Build_projects___verifySubscription/">Build projects / org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription(SubscriptionFlowIT.java:97)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/430/testReport/org.acme.it/QueryAnswerServiceIT/Build_projects___queryAnswerProcessCycle/">Build projects / org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle(QueryAnswerServiceIT.java:87)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/430/testReport/org.acme.it/QueryAnswerServiceIT/Build_projects___queryAnswerProcessCycle/">Build projects / org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle(QueryAnswerServiceIT.java:87)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/430/testReport/org.kie.kogito.serverless/ConversationFlowIT/sanityVerification/">org.kie.kogito.serverless.ConversationFlowIT.sanityVerification</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.serverless.ConversationFlowIT.sanityVerification(ConversationFlowIT.java:53)<br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-28T07:12:38.701Z] 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)<br/>[2022-06-28T07:12:38.701Z] 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:590)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)<br/>[2022-06-28T07:12:38.701Z] 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:119)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)<br/>[2022-06-28T07:12:38.701Z] 	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)<br/>[2022-06-28T07:12:38.701Z] 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:412)<br/>[2022-06-28T07:12:38.701Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)<br/>[2022-06-28T07:12:38.701Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>[2022-06-28T07:12:38.701Z] 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:554)<br/>[2022-06-28T07:12:38.701Z] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>[2022-06-28T07:12:38.701Z] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>[2022-06-28T07:12:38.701Z] 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)<br/>[2022-06-28T07:12:38.701Z] 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)<br/>[2022-06-28T07:12:38.701Z] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>[2022-06-28T07:12:38.701Z] 	at java.base/java.lang.Thread.run(Thread.java:829)<br/>[2022-06-28T07:12:38.701Z] Caused by: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:80<br/>[2022-06-28T07:12:38.701Z] 	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)<br/>[2022-06-28T07:12:38.701Z] 	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)<br/>[2022-06-28T07:12:38.701Z] 	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)<br/>[2022-06-28T07:12:38.701Z] 	at io.v [...]

2022-06-28 07:16 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#384` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/384/display/redirect

**Test results:**
- PASSED: 2790
- FAILED: 7

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/384/testReport/org.kie.kogito.quarkus.workflows/CallbackStateIT/callbackStateSuccessful/">org.kie.kogito.quarkus.workflows.CallbackStateIT.callbackStateSuccessful</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.workflows.CallbackStateIT.callbackStateSuccessful(CallbackStateIT.java:38)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/384/testReport/org.kie.kogito.quarkus.workflows/CallbackStateTimeoutsIT/callbackStateTimeoutsSuccessful/">org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsSuccessful</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsSuccessful(CallbackStateTimeoutsIT.java:43)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/384/testReport/org.kie.kogito.quarkus.workflows/CallbackStateTimeoutsIT/callbackStateTimeoutsExceeded/">org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded(CallbackStateTimeoutsIT.java:56)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/384/testReport/org.kie.kogito.quarkus.workflows/ConversationFlowIT/sanityVerification/">org.kie.kogito.quarkus.workflows.ConversationFlowIT.sanityVerification</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.workflows.ConversationFlowIT.sanityVerification(ConversationFlowIT.java:53)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/384/testReport/org.kie.kogito.quarkus.workflows/TokenPropagationIT/tokenPropagations/">org.kie.kogito.quarkus.workflows.TokenPropagationIT.tokenPropagations</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.workflows.TokenPropagationIT.tokenPropagations(TokenPropagationIT.java:57)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/384/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi2_0/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0(ApiWithSecurityContextIT.java:62)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/384/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi3_0/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi3_0</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi3_0(ApiWithSecurityContextIT.java:83)<br/>
</details>

2022-06-28 07:20 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#383` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/383/display/redirect

**Test results:**
- PASSED: 2789
- FAILED: 8

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/383/testReport/org.kie.kogito.quarkus.workflows/CallbackStateIT/callbackStateSuccessful/">org.kie.kogito.quarkus.workflows.CallbackStateIT.callbackStateSuccessful</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.workflows.CallbackStateIT.callbackStateSuccessful(CallbackStateIT.java:38)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/383/testReport/org.kie.kogito.quarkus.workflows/CallbackStateTimeoutsIT/callbackStateTimeoutsSuccessful/">org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsSuccessful</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsSuccessful(CallbackStateTimeoutsIT.java:43)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/383/testReport/org.kie.kogito.quarkus.workflows/CallbackStateTimeoutsIT/callbackStateTimeoutsExceeded/">org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <200> but was <404>.<br/><br/>	at org.kie.kogito.quarkus.workflows.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded(CallbackStateTimeoutsIT.java:56)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/383/testReport/org.kie.kogito.quarkus.workflows/ConversationFlowIT/sanityVerification/">org.kie.kogito.quarkus.workflows.ConversationFlowIT.sanityVerification</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.workflows.ConversationFlowIT.sanityVerification(ConversationFlowIT.java:53)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/383/testReport/org.kie.kogito.quarkus.workflows/CorrelationIT/correlationEventTest/">org.kie.kogito.quarkus.workflows.CorrelationIT.correlationEventTest</a></summary>
org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.quarkus.workflows.WorkflowTestUtils that uses java.lang.String, java.lang.Stringjava.lang.String 1 expectation failed.<br/>Expected status code <404> but was <200>.<br/> within 3 minutes.<br/>	at org.kie.kogito.quarkus.workflows.CorrelationIT.correlationEventTest(CorrelationIT.java:117)<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <404> but was <200>.<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/383/testReport/org.kie.kogito.quarkus.workflows/TokenPropagationIT/tokenPropagations/">org.kie.kogito.quarkus.workflows.TokenPropagationIT.tokenPropagations</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.workflows.TokenPropagationIT.tokenPropagations(TokenPropagationIT.java:57)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/383/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi2_0/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0(ApiWithSecurityContextIT.java:62)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/383/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi3_0/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi3_0</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi3_0(ApiWithSecurityContextIT.java:83)<br/>
</details>

2022-06-28 07:32 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#432` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/432/display/redirect

**Test results:**
- PASSED: 420
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/432/testReport/org.acme.newsletter.subscription.flow/SubscriptionFlowIT/Build_projects___verifySubscription/">Build projects / org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription(SubscriptionFlowIT.java:97)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/432/testReport/org.acme.newsletter.subscription.flow/SubscriptionFlowIT/Build_projects___verifySubscription/">Build projects / org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.acme.newsletter.subscription.flow.SubscriptionFlowIT.verifySubscription(SubscriptionFlowIT.java:97)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/432/testReport/org.acme.it/QueryAnswerServiceIT/Build_projects___queryAnswerProcessCycle/">Build projects / org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle(QueryAnswerServiceIT.java:87)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/432/testReport/org.acme.it/QueryAnswerServiceIT/Build_projects___queryAnswerProcessCycle/">Build projects / org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.acme.it.QueryAnswerServiceIT.queryAnswerProcessCycle(QueryAnswerServiceIT.java:87)<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/432/testReport/org.kie.kogito.serverless/ConversationFlowIT/sanityVerification/">org.kie.kogito.serverless.ConversationFlowIT.sanityVerification</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>Expected status code <201> but was <500>.<br/><br/>	at org.kie.kogito.serverless.ConversationFlowIT.sanityVerification(ConversationFlowIT.java:53)<br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-28T07:32:15.393Z] 	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)<br/>[2022-06-28T07:32:15.393Z] 	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)<br/>[2022-06-28T07:32:15.394Z] 	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)<br/>[2022-06-28T07:32:15.394Z] 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:590)<br/>[2022-06-28T07:32:15.394Z] 	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)<br/>[2022-06-28T07:32:15.394Z] 	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)<br/>[2022-06-28T07:32:15.394Z] 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:119)<br/>[2022-06-28T07:32:15.394Z] 	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)<br/>[2022-06-28T07:32:15.394Z] 	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)<br/>[2022-06-28T07:32:15.394Z] 	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:412)<br/>[2022-06-28T07:32:15.394Z] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)<br/>[2022-06-28T07:32:15.394Z] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)<br/>[2022-06-28T07:32:15.394Z] 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:554)<br/>[2022-06-28T07:32:15.394Z] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>[2022-06-28T07:32:15.394Z] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>[2022-06-28T07:32:15.394Z] 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)<br/>[2022-06-28T07:32:15.394Z] 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)<br/>[2022-06-28T07:32:15.394Z] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)<br/>[2022-06-28T07:32:15.394Z] 	at java.base/java.lang.Thread.run(Thread.java:829)<br/>[2022-06-28T07:32:15.394Z] Caused by: java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:80<br/>[2022-06-28T07:32:15.394Z] 	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)<br/>[2022-06-28T07:32:15.394Z] 	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)<br/>[2022-06-28T07:32:15.394Z] 	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)<br/>[2022-06-28T07:32:15.394Z] 	at io.v [...]

2022-06-28 16:28 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#436` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/436/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Mail ................................. SUCCESS [  1.239 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Mail - Deployment .................... SUCCESS [  0.431 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Monitoring .................... SUCCESS [  0.021 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Monitoring Core ............... SUCCESS [  0.378 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Monitoring - Parent .................. SUCCESS [  0.021 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Monitoring Core ...................... SUCCESS [  0.360 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Monitoring Prometheus Common .. SUCCESS [  0.307 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Monitoring Prometheus - Parent ....... SUCCESS [  0.022 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Monitoring Prometheus ................ SUCCESS [  1.358 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Monitoring Prometheus - Deployment ... SUCCESS [  0.478 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Monitoring Elastic Common ..... SUCCESS [  0.252 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Monitoring Elastic - Parent .......... SUCCESS [  0.021 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Monitoring Elastic ................... SUCCESS [  0.399 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Monitoring Elastic - Deployment ...... SUCCESS [  0.439 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Task Notification - Parent ........... SUCCESS [  0.024 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Task Notification .................... SUCCESS [  0.356 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Task Notification - Deployment ....... SUCCESS [  0.296 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Tracing ....................... SUCCESS [  0.021 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: TypedValue API ................ SUCCESS [  0.149 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Tracing :: API ................ SUCCESS [  0.369 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Tracing :: Common ............. SUCCESS [  0.493 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Tracing Decision - Parent ............ SUCCESS [  0.023 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Tracing Decision ..................... SUCCESS [  1.118 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Tracing Decision - Deployment ........ SUCCESS [  0.571 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Tracing Decision - Integration tests . SUCCESS [  0.348 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Task Management :: Common ..... SUCCESS [  0.158 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Task Management - Parent ............. SUCCESS [  0.023 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Task Management ...................... SUCCESS [  1.179 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito Add-On Task Management - Deployment ......... SUCCESS [  0.334 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus ............. SUCCESS [  0.020 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: OpenAPI Client Codegen SKIPPED<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Rules .... SUCCESS [  0.463 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Decisions  SUCCESS [  0.666 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Predictions SUCCESS [  0.592 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Classic SUCCESS [  0.342 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Reactive SUCCESS [  0.619 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Maven Plugin ............................. SUCCESS [  4.947 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Maven Plugin ........ SUCCESS [  1.528 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Without REST SUCCESS [  0.538 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes  SUCCESS [  0.974 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence SUCCESS [  0.024 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Processes :: Persistence :: Common SUCCESS [  0.574 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: PostgreSQL SUCCESS [  3.978 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Infinispan SUCCESS [  3.824 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: MongoDB SUCCESS [  3.662 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Kafka SUCCESS [  3.715 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: JDBC SUCCESS [  4.002 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: File System SUCCESS [  3.348 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Source Files SKIPPED<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Gradle ... SUCCESS [  0.165 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: DB Scripts Collection .................... SUCCESS [  0.199 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Predictions ................... SUCCESS [  0.019 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Predictions :: API ............ SUCCESS [  0.277 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Predictions :: SMILE .......... SUCCESS [  0.373 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Spring Boot .............................. SUCCESS [  0.018 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Spring Boot :: BOM ....................... SUCCESS [  0.019 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Spring Boot ................... SUCCESS [  0.019 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: CloudEvents :: Spring Boot .... SUCCESS [  0.020 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Messaging :: Spring Boot ...... SUCCESS [  1.059 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Spring Boot :: Events - Parent  SUCCESS [  0.020 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Decisions :: Spring Boot SUCCESS [  0.144 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Predictions :: Spring Boot SUCCESS [  0.113 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Rules :: Spring Boot SUCCESS [  0.110 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Events :: SprintBoot :: Process :: Kafka SUCCESS [  0.095 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Add-Ons :: Events ::  MongoDB :: SprintBoot SUCCESS [  0.950 s]<br/>[2022-06-28T16:28:27.527Z] [INFO] Kogito :: Spring Boot :: Starters Parent ........... SUCCESS [  0.680 s]<br/>[2022-06-28T16:2 [...]

2022-06-28 16:33 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#520` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/520/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Mail ................................. SUCCESS [  1.147 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Mail - Deployment .................... SUCCESS [  0.395 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Monitoring .................... SUCCESS [  0.022 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Monitoring Core ............... SUCCESS [  0.377 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Monitoring - Parent .................. SUCCESS [  0.023 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Monitoring Core ...................... SUCCESS [  0.359 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Monitoring Prometheus Common .. SUCCESS [  0.301 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Monitoring Prometheus - Parent ....... SUCCESS [  0.022 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Monitoring Prometheus ................ SUCCESS [  1.258 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Monitoring Prometheus - Deployment ... SUCCESS [  0.445 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Monitoring Elastic Common ..... SUCCESS [  0.282 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Monitoring Elastic - Parent .......... SUCCESS [  0.022 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Monitoring Elastic ................... SUCCESS [  0.510 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Monitoring Elastic - Deployment ...... SUCCESS [  0.359 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Task Notification - Parent ........... SUCCESS [  0.022 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Task Notification .................... SUCCESS [  0.323 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Task Notification - Deployment ....... SUCCESS [  0.285 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Tracing ....................... SUCCESS [  0.018 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: TypedValue API ................ SUCCESS [  0.145 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Tracing :: API ................ SUCCESS [  0.303 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Tracing :: Common ............. SUCCESS [  0.459 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Tracing Decision - Parent ............ SUCCESS [  0.020 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Tracing Decision ..................... SUCCESS [  0.892 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Tracing Decision - Deployment ........ SUCCESS [  0.598 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Tracing Decision - Integration tests . SUCCESS [  0.347 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Task Management :: Common ..... SUCCESS [  0.144 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Task Management - Parent ............. SUCCESS [  0.021 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Task Management ...................... SUCCESS [  1.111 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito Add-On Task Management - Deployment ......... SUCCESS [  0.324 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus ............. SUCCESS [  0.018 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: OpenAPI Client Codegen SKIPPED<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Rules .... SUCCESS [  0.445 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Decisions  SUCCESS [  0.586 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Predictions SUCCESS [  0.429 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Classic SUCCESS [  0.312 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Reactive SUCCESS [  0.547 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Maven Plugin ............................. SUCCESS [  4.856 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Maven Plugin ........ SUCCESS [  1.465 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Without REST SUCCESS [  0.497 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes  SUCCESS [  0.861 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence SUCCESS [  0.022 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Processes :: Persistence :: Common SUCCESS [  0.535 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: PostgreSQL SUCCESS [  3.672 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Infinispan SUCCESS [  3.458 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: MongoDB SUCCESS [  3.272 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Kafka SUCCESS [  3.628 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: JDBC SUCCESS [  4.010 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: File System SUCCESS [  3.445 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Source Files SKIPPED<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Gradle ... SUCCESS [  0.182 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: DB Scripts Collection .................... SUCCESS [  0.196 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Predictions ................... SUCCESS [  0.019 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Predictions :: API ............ SUCCESS [  0.213 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Predictions :: SMILE .......... SUCCESS [  0.338 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Spring Boot .............................. SUCCESS [  0.017 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Spring Boot :: BOM ....................... SUCCESS [  0.050 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Spring Boot ................... SUCCESS [  0.019 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: CloudEvents :: Spring Boot .... SUCCESS [  0.019 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Messaging :: Spring Boot ...... SUCCESS [  1.021 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Spring Boot :: Events - Parent  SUCCESS [  0.019 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Decisions :: Spring Boot SUCCESS [  0.131 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Predictions :: Spring Boot SUCCESS [  0.100 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Rules :: Spring Boot SUCCESS [  0.104 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Events :: SprintBoot :: Process :: Kafka SUCCESS [  0.097 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Add-Ons :: Events ::  MongoDB :: SprintBoot SUCCESS [  0.795 s]<br/>[2022-06-28T16:33:02.290Z] [INFO] Kogito :: Spring Boot :: Starters Parent ........... SUCCESS [  0.633 s]<br/>[2022-06-28T16:33:02.290 [...]

2022-06-28 16:52 UTC, martinweiler approved these changes
great work @fjtirado I successfully tested all three strategies:
quarkus.kogito.sw.operationIdStrategy=FILE_NAME|SPEC_TITLE|FULL_URI

2022-06-28 16:52 UTC, martinweiler commented on quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-deployment/src/main/java/org/kie/kogito/quarkus/serverless/workflow/WorkflowCodeGenUtils.java
> +    }
this works now, property value is obtained from application.properties

2022-06-28 16:59 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#388` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/388/display/redirect

**Test results:**
- PASSED: 2748
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-28T16:59:35.480Z] [INFO] Kogito Add-On Events MongoDB - Deployment .......... SUCCESS [  0.363 s]<br/>[2022-06-28T16:59:35.480Z] [INFO] Kogito :: Add-Ons :: Explainability ................ SUCCESS [  2.686 s]<br/>[2022-06-28T16:59:35.480Z] [INFO] Kogito Add-On Explainability - Parent .............. SUCCESS [  0.124 s]<br/>[2022-06-28T16:59:35.480Z] [INFO] Kogito Add-On Explainability ....................... SUCCESS [  0.467 s]<br/>[2022-06-28T16:59:35.480Z] [INFO] Kogito Add-On Explainability - Deployment .......... SUCCESS [  0.401 s]<br/>[2022-06-28T16:59:35.480Z] [INFO] Kogito Add-On Explainability - Integration tests ... SUCCESS [ 11.513 s]<br/>[2022-06-28T16:59:35.480Z] [INFO] Kogito :: Add-Ons :: Jobs .......................... SUCCESS [  0.022 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Jobs :: API ................... SUCCESS [  2.004 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-Ons Quarkus Jobs Parent ................. SUCCESS [  0.028 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-Ons Quarkus Jobs Common - Parent ........ SUCCESS [  0.026 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-Ons Quarkus - Rest Callback ............. SUCCESS [  2.506 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Jobs :: Management Common ..... SUCCESS [  1.101 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-Ons Quarkus Jobs Management - Parent .... SUCCESS [  0.023 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-Ons Quarkus Jobs - Management ........... SUCCESS [  3.102 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-Ons Quarkus Jobs Management - Deployment  SUCCESS [  0.384 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-Ons Quarkus Jobs Messaging - Parent ..... SUCCESS [  0.026 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-Ons Quarkus Jobs - Messaging ............ SUCCESS [  3.633 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-Ons Quarkus Jobs Messaging - Deployment . SUCCESS [  0.354 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Kubernetes .................... SUCCESS [  4.531 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Knative Eventing - Parent ............ SUCCESS [  0.024 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Kubernetes ........................... SUCCESS [ 11.551 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Kubernetes - Deployment .............. SUCCESS [  9.115 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: E-Mail :: Common .............. SUCCESS [  1.175 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Mail - Parent ........................ SUCCESS [  0.024 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Mail ................................. SUCCESS [ 12.176 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Mail - Deployment .................... SUCCESS [  0.361 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Monitoring .................... SUCCESS [  0.021 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Monitoring Core ............... SUCCESS [  4.014 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Monitoring - Parent .................. SUCCESS [  0.025 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Monitoring Core ...................... SUCCESS [  3.352 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Monitoring Prometheus Common .. SUCCESS [  0.276 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Monitoring Prometheus - Parent ....... SUCCESS [  0.024 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Monitoring Prometheus ................ SUCCESS [  1.366 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Monitoring Prometheus - Deployment ... SUCCESS [  0.460 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Monitoring Elastic Common ..... SUCCESS [  1.238 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Monitoring Elastic - Parent .......... SUCCESS [  0.022 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Monitoring Elastic ................... SUCCESS [  0.398 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Monitoring Elastic - Deployment ...... SUCCESS [  0.361 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Task Notification - Parent ........... SUCCESS [  0.025 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Task Notification .................... SUCCESS [  0.333 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Task Notification - Deployment ....... SUCCESS [  0.295 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Tracing ....................... SUCCESS [  0.023 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: TypedValue API ................ SUCCESS [  1.529 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Tracing :: API ................ SUCCESS [  1.762 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Tracing :: Common ............. SUCCESS [  4.042 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Tracing Decision - Parent ............ SUCCESS [  0.026 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Tracing Decision ..................... SUCCESS [  4.789 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Tracing Decision - Deployment ........ SUCCESS [  0.747 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Tracing Decision - Integration tests . SUCCESS [ 38.782 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Add-Ons :: Task Management :: Common ..... SUCCESS [  0.169 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Task Management - Parent ............. SUCCESS [  0.023 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Task Management ...................... SUCCESS [  1.052 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito Add-On Task Management - Deployment ......... SUCCESS [  0.355 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus ............. SUCCESS [  0.025 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: OpenAPI Client Codegen SKIPPED<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Rules .... SUCCESS [ 11.752 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Decisions  SUCCESS [ 14.170 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Predictions SUCCESS [ 11.792 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Classic SUCCESS [ 12.018 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Reactive SUCCESS [ 12.944 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Maven Plugin ............................. SUCCESS [  5.268 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Maven Plugin ........ SUCCESS [ 23.750 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Without REST SUCCESS [ 28.454 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes  SUCCESS [ 27.606 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence SUCCESS [  0.027 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Processes :: Persistence :: Common SUCCESS [  1.610 s]<br/>[2022-06-28T16:59:35.481Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: PostgreSQL SUCCESS [ 24.794 s]<br/>[2022-06-28T16:59:35 [...]

2022-06-28 17:13 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#389` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/389/display/redirect

**Test results:**
- PASSED: 2748
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Events MongoDB - Deployment .......... SUCCESS [  0.453 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Explainability ................ SUCCESS [  2.582 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Explainability - Parent .............. SUCCESS [  0.024 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Explainability ....................... SUCCESS [  0.419 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Explainability - Deployment .......... SUCCESS [  0.357 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Explainability - Integration tests ... SUCCESS [ 10.549 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Jobs .......................... SUCCESS [  0.022 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Jobs :: API ................... SUCCESS [  1.897 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-Ons Quarkus Jobs Parent ................. SUCCESS [  0.024 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-Ons Quarkus Jobs Common - Parent ........ SUCCESS [  0.024 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-Ons Quarkus - Rest Callback ............. SUCCESS [  2.393 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Jobs :: Management Common ..... SUCCESS [  1.196 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-Ons Quarkus Jobs Management - Parent .... SUCCESS [  0.024 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-Ons Quarkus Jobs - Management ........... SUCCESS [  3.073 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-Ons Quarkus Jobs Management - Deployment  SUCCESS [  0.334 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-Ons Quarkus Jobs Messaging - Parent ..... SUCCESS [  0.023 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-Ons Quarkus Jobs - Messaging ............ SUCCESS [  3.541 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-Ons Quarkus Jobs Messaging - Deployment . SUCCESS [  0.340 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Kubernetes .................... SUCCESS [  4.248 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Knative Eventing - Parent ............ SUCCESS [  0.023 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Kubernetes ........................... SUCCESS [ 11.135 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Kubernetes - Deployment .............. SUCCESS [  8.439 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: E-Mail :: Common .............. SUCCESS [  1.152 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Mail - Parent ........................ SUCCESS [  0.023 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Mail ................................. SUCCESS [ 12.039 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Mail - Deployment .................... SUCCESS [  0.372 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Monitoring .................... SUCCESS [  0.023 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Monitoring Core ............... SUCCESS [  3.960 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Monitoring - Parent .................. SUCCESS [  0.022 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Monitoring Core ...................... SUCCESS [  3.365 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Monitoring Prometheus Common .. SUCCESS [  0.276 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Monitoring Prometheus - Parent ....... SUCCESS [  0.023 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Monitoring Prometheus ................ SUCCESS [  1.340 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Monitoring Prometheus - Deployment ... SUCCESS [  0.494 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Monitoring Elastic Common ..... SUCCESS [  1.589 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Monitoring Elastic - Parent .......... SUCCESS [  0.023 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Monitoring Elastic ................... SUCCESS [  0.391 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Monitoring Elastic - Deployment ...... SUCCESS [  0.374 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Task Notification - Parent ........... SUCCESS [  0.024 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Task Notification .................... SUCCESS [  0.330 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Task Notification - Deployment ....... SUCCESS [  0.309 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Tracing ....................... SUCCESS [  0.021 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: TypedValue API ................ SUCCESS [  1.420 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Tracing :: API ................ SUCCESS [  1.753 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Tracing :: Common ............. SUCCESS [  3.912 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Tracing Decision - Parent ............ SUCCESS [  0.024 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Tracing Decision ..................... SUCCESS [  4.527 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Tracing Decision - Deployment ........ SUCCESS [  0.711 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Tracing Decision - Integration tests . SUCCESS [ 39.170 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Add-Ons :: Task Management :: Common ..... SUCCESS [  0.164 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Task Management - Parent ............. SUCCESS [  0.023 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Task Management ...................... SUCCESS [  1.099 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito Add-On Task Management - Deployment ......... SUCCESS [  0.369 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus ............. SUCCESS [  0.023 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: OpenAPI Client Codegen SKIPPED<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Rules .... SUCCESS [ 11.566 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Decisions  SUCCESS [ 14.428 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Predictions SUCCESS [ 11.784 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Classic SUCCESS [ 10.973 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Reactive SUCCESS [ 11.413 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Maven Plugin ............................. SUCCESS [  4.919 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Maven Plugin ........ SUCCESS [ 22.550 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Without REST SUCCESS [ 28.757 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes  SUCCESS [ 28.481 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence SUCCESS [  0.026 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Processes :: Persistence :: Common SUCCESS [  1.605 s]<br/>[2022-06-28T17:13:31.341Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: PostgreSQL SUCCESS [ 24.334 s]<br/>[2022-06-28T17:13:31 [...]

2022-06-29 07:54 UTC, fjtirado commented
jenkins retest this

2022-06-29 08:00 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#438` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/438/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Mail ................................. SUCCESS [  1.050 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Mail - Deployment .................... SUCCESS [  0.402 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Add-Ons :: Monitoring .................... SUCCESS [  0.019 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Add-Ons :: Monitoring Core ............... SUCCESS [  0.338 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Monitoring - Parent .................. SUCCESS [  0.018 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Monitoring Core ...................... SUCCESS [  0.321 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Add-Ons :: Monitoring Prometheus Common .. SUCCESS [  0.259 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Monitoring Prometheus - Parent ....... SUCCESS [  0.019 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Monitoring Prometheus ................ SUCCESS [  1.262 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Monitoring Prometheus - Deployment ... SUCCESS [  0.423 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Add-Ons :: Monitoring Elastic Common ..... SUCCESS [  0.216 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Monitoring Elastic - Parent .......... SUCCESS [  0.019 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Monitoring Elastic ................... SUCCESS [  0.365 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Monitoring Elastic - Deployment ...... SUCCESS [  0.361 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Task Notification - Parent ........... SUCCESS [  0.019 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Task Notification .................... SUCCESS [  0.293 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Task Notification - Deployment ....... SUCCESS [  0.268 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Add-Ons :: Tracing ....................... SUCCESS [  0.017 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Add-Ons :: TypedValue API ................ SUCCESS [  0.131 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Add-Ons :: Tracing :: API ................ SUCCESS [  0.306 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Add-Ons :: Tracing :: Common ............. SUCCESS [  0.459 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Tracing Decision - Parent ............ SUCCESS [  0.018 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Tracing Decision ..................... SUCCESS [  0.824 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Tracing Decision - Deployment ........ SUCCESS [  0.543 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Tracing Decision - Integration tests . SUCCESS [  0.389 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Add-Ons :: Task Management :: Common ..... SUCCESS [  0.147 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Task Management - Parent ............. SUCCESS [  0.018 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Task Management ...................... SUCCESS [  0.962 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito Add-On Task Management - Deployment ......... SUCCESS [  0.298 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Integration Tests :: Quarkus ............. SUCCESS [  0.016 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Integration Tests :: Quarkus :: OpenAPI Client Codegen SKIPPED<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Rules .... SUCCESS [  0.410 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Decisions  SUCCESS [  0.489 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Predictions SUCCESS [  0.449 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Classic SUCCESS [  0.300 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Reactive SUCCESS [  0.490 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Maven Plugin ............................. SUCCESS [  4.755 s]<br/>[2022-06-29T08:00:07.690Z] [INFO] Kogito :: Integration Tests :: Maven Plugin ........ SUCCESS [  1.295 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Without REST SUCCESS [  0.479 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes  SUCCESS [  0.859 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence SUCCESS [  0.020 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Processes :: Persistence :: Common SUCCESS [  0.516 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: PostgreSQL SUCCESS [  3.505 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Infinispan SUCCESS [  3.235 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: MongoDB SUCCESS [  3.246 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Kafka SUCCESS [  3.443 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: JDBC SUCCESS [  3.806 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: File System SUCCESS [  3.166 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Source Files SKIPPED<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Gradle ... SUCCESS [  0.158 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: DB Scripts Collection .................... SUCCESS [  0.192 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Add-Ons :: Predictions ................... SUCCESS [  0.018 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Add-Ons :: Predictions :: API ............ SUCCESS [  0.214 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Add-Ons :: Predictions :: SMILE .......... SUCCESS [  0.332 s]<br/>[2022-06-29T08:00:07.691Z] [INFO] Kogito :: Spring Boot .............................. SUCCESS [  0.018 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Spring Boot :: BOM ....................... SUCCESS [  0.018 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Add-Ons :: Spring Boot ................... SUCCESS [  0.070 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Add-Ons :: CloudEvents :: Spring Boot .... SUCCESS [  0.018 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Add-Ons :: Messaging :: Spring Boot ...... SUCCESS [  1.030 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Add-Ons :: Spring Boot :: Events - Parent  SUCCESS [  0.019 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Decisions :: Spring Boot SUCCESS [  0.131 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Predictions :: Spring Boot SUCCESS [  0.101 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Rules :: Spring Boot SUCCESS [  0.102 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Add-Ons :: Events :: SprintBoot :: Process :: Kafka SUCCESS [  0.084 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Add-Ons :: Events ::  MongoDB :: SprintBoot SUCCESS [  0.831 s]<br/>[2022-06-29T08:00:07.948Z] [INFO] Kogito :: Spring Boot :: Starters Parent ........... SUCCESS [  0.824 s]<br/>[2022-06-29T08:0 [...]

2022-06-29 08:05 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#522` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/522/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-29T08:05:18.982Z] [INFO] Kogito Add-On Mail ................................. SUCCESS [  1.163 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Mail - Deployment .................... SUCCESS [  0.471 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Monitoring .................... SUCCESS [  0.022 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Monitoring Core ............... SUCCESS [  0.452 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Monitoring - Parent .................. SUCCESS [  0.019 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Monitoring Core ...................... SUCCESS [  0.310 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Monitoring Prometheus Common .. SUCCESS [  0.264 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Monitoring Prometheus - Parent ....... SUCCESS [  0.019 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Monitoring Prometheus ................ SUCCESS [  1.368 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Monitoring Prometheus - Deployment ... SUCCESS [  0.426 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Monitoring Elastic Common ..... SUCCESS [  0.254 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Monitoring Elastic - Parent .......... SUCCESS [  0.026 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Monitoring Elastic ................... SUCCESS [  0.435 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Monitoring Elastic - Deployment ...... SUCCESS [  0.472 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Task Notification - Parent ........... SUCCESS [  0.026 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Task Notification .................... SUCCESS [  0.347 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Task Notification - Deployment ....... SUCCESS [  0.295 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Tracing ....................... SUCCESS [  0.018 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: TypedValue API ................ SUCCESS [  0.143 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Tracing :: API ................ SUCCESS [  0.335 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Tracing :: Common ............. SUCCESS [  0.475 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Tracing Decision - Parent ............ SUCCESS [  0.023 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Tracing Decision ..................... SUCCESS [  0.908 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Tracing Decision - Deployment ........ SUCCESS [  0.650 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Tracing Decision - Integration tests . SUCCESS [  0.339 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Task Management :: Common ..... SUCCESS [  0.147 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Task Management - Parent ............. SUCCESS [  0.020 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Task Management ...................... SUCCESS [  1.032 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito Add-On Task Management - Deployment ......... SUCCESS [  0.292 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus ............. SUCCESS [  0.016 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: OpenAPI Client Codegen SKIPPED<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Rules .... SUCCESS [  0.423 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Decisions  SUCCESS [  0.621 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Predictions SUCCESS [  0.429 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Classic SUCCESS [  0.313 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Reactive SUCCESS [  0.535 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Maven Plugin ............................. SUCCESS [  4.945 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Maven Plugin ........ SUCCESS [  1.519 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Without REST SUCCESS [  0.510 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes  SUCCESS [  0.876 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence SUCCESS [  0.022 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Processes :: Persistence :: Common SUCCESS [  0.596 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: PostgreSQL SUCCESS [  3.667 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Infinispan SUCCESS [  3.496 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: MongoDB SUCCESS [  3.283 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Kafka SUCCESS [  3.463 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: JDBC SUCCESS [  3.906 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: File System SUCCESS [  3.199 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Source Files SKIPPED<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Gradle ... SUCCESS [  0.182 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: DB Scripts Collection .................... SUCCESS [  0.196 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Predictions ................... SUCCESS [  0.019 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Predictions :: API ............ SUCCESS [  0.222 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Predictions :: SMILE .......... SUCCESS [  0.329 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Spring Boot .............................. SUCCESS [  0.019 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Spring Boot :: BOM ....................... SUCCESS [  0.020 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Spring Boot ................... SUCCESS [  0.020 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: CloudEvents :: Spring Boot .... SUCCESS [  0.021 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Messaging :: Spring Boot ...... SUCCESS [  1.105 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Spring Boot :: Events - Parent  SUCCESS [  0.020 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Decisions :: Spring Boot SUCCESS [  0.134 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Predictions :: Spring Boot SUCCESS [  0.154 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Rules :: Spring Boot SUCCESS [  0.114 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Events :: SprintBoot :: Process :: Kafka SUCCESS [  0.095 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Add-Ons :: Events ::  MongoDB :: SprintBoot SUCCESS [  1.069 s]<br/>[2022-06-29T08:05:18.983Z] [INFO] Kogito :: Spring Boot :: Starters Parent ........... SUCCESS [  0.672 s]<br/>[2022-06-29T08:05:18.983 [...]

2022-06-29 08:32 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#390` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/390/display/redirect

**Test results:**
- PASSED: 2748
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-On Events MongoDB - Deployment .......... SUCCESS [  0.390 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito :: Add-Ons :: Explainability ................ SUCCESS [  2.792 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-On Explainability - Parent .............. SUCCESS [  0.026 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-On Explainability ....................... SUCCESS [  0.451 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-On Explainability - Deployment .......... SUCCESS [  0.381 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-On Explainability - Integration tests ... SUCCESS [ 11.695 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito :: Add-Ons :: Jobs .......................... SUCCESS [  0.025 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito :: Add-Ons :: Jobs :: API ................... SUCCESS [  2.093 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-Ons Quarkus Jobs Parent ................. SUCCESS [  0.028 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-Ons Quarkus Jobs Common - Parent ........ SUCCESS [  0.024 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-Ons Quarkus - Rest Callback ............. SUCCESS [  2.545 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito :: Add-Ons :: Jobs :: Management Common ..... SUCCESS [  1.196 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-Ons Quarkus Jobs Management - Parent .... SUCCESS [  0.027 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-Ons Quarkus Jobs - Management ........... SUCCESS [  3.372 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-Ons Quarkus Jobs Management - Deployment  SUCCESS [  0.375 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-Ons Quarkus Jobs Messaging - Parent ..... SUCCESS [  0.031 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-Ons Quarkus Jobs - Messaging ............ SUCCESS [  3.958 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-Ons Quarkus Jobs Messaging - Deployment . SUCCESS [  0.484 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito :: Add-Ons :: Kubernetes .................... SUCCESS [  4.991 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-On Knative Eventing - Parent ............ SUCCESS [  0.027 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-On Kubernetes ........................... SUCCESS [ 11.625 s]<br/>[2022-06-29T08:31:59.594Z] [INFO] Kogito Add-On Kubernetes - Deployment .............. SUCCESS [  9.029 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: E-Mail :: Common .............. SUCCESS [  1.172 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Mail - Parent ........................ SUCCESS [  0.025 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Mail ................................. SUCCESS [ 12.779 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Mail - Deployment .................... SUCCESS [  0.379 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: Monitoring .................... SUCCESS [  0.021 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: Monitoring Core ............... SUCCESS [  4.275 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Monitoring - Parent .................. SUCCESS [  0.024 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Monitoring Core ...................... SUCCESS [  3.661 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: Monitoring Prometheus Common .. SUCCESS [  0.300 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Monitoring Prometheus - Parent ....... SUCCESS [  0.023 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Monitoring Prometheus ................ SUCCESS [  1.543 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Monitoring Prometheus - Deployment ... SUCCESS [  0.581 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: Monitoring Elastic Common ..... SUCCESS [  1.977 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Monitoring Elastic - Parent .......... SUCCESS [  0.025 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Monitoring Elastic ................... SUCCESS [  0.433 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Monitoring Elastic - Deployment ...... SUCCESS [  0.374 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Task Notification - Parent ........... SUCCESS [  0.024 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Task Notification .................... SUCCESS [  0.345 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Task Notification - Deployment ....... SUCCESS [  0.301 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: Tracing ....................... SUCCESS [  0.020 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: TypedValue API ................ SUCCESS [  1.473 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: Tracing :: API ................ SUCCESS [  1.886 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: Tracing :: Common ............. SUCCESS [  3.917 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Tracing Decision - Parent ............ SUCCESS [  0.025 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Tracing Decision ..................... SUCCESS [  4.768 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Tracing Decision - Deployment ........ SUCCESS [  0.746 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Tracing Decision - Integration tests . SUCCESS [ 39.477 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Add-Ons :: Task Management :: Common ..... SUCCESS [  0.158 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Task Management - Parent ............. SUCCESS [  0.022 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Task Management ...................... SUCCESS [  0.974 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito Add-On Task Management - Deployment ......... SUCCESS [  0.420 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus ............. SUCCESS [  0.026 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: OpenAPI Client Codegen SKIPPED<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Rules .... SUCCESS [ 12.089 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Decisions  SUCCESS [ 14.452 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Predictions SUCCESS [ 11.653 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Classic SUCCESS [ 11.311 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Reactive SUCCESS [ 12.667 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Maven Plugin ............................. SUCCESS [  5.422 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Maven Plugin ........ SUCCESS [ 24.809 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Without REST SUCCESS [ 30.319 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes  SUCCESS [ 29.375 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence SUCCESS [  0.029 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Processes :: Persistence :: Common SUCCESS [  1.692 s]<br/>[2022-06-29T08:31:59.595Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: PostgreSQL SUCCESS [ 25.767 s]<br/>[2022-06-29T08:31:59 [...]

2022-06-29 10:59 UTC, merged