KOGITO-7461 - Add event dispatcher listener to make for the possibility of throttling the message consumer
kiegroup/kogito-runtimes pull request #2318
Opened 2022-07-07 11:30 UTC by iurybakov

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

- <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2022-07-07 11:40 UTC, iurybakov commented
This functionality allowed us to register listeners of the event handler execution, which allows us to have metrics of worker thread loading during execution and thereby be able to control the intensity of the event flow. In simple words, this functionality allows you to implement throttling of the event flow. As a result, we were able to solve the 'thread blocked' problem.

2022-07-07 22:58 UTC, fjtirado commented
> Therefore, our idea is to be able to control the intensity of the flow of events from outside. For example suspending the kafka consumer. And for control, an indication of the exhaustion of the pool of worker threads on the event dispatcher is needed.

Ok, but I think there are better alternatives to achieve that
For example, to give users the possibility of changing the executor, which will be as easy as adding a defaultbean annoation to  @Inject
    @javax.inject.Named(KogitoEventExecutor.BEAN_NAME)
    ExecutorService executorService;
in the generated TravelersMessageConsumer, so you can provide a different executor with a differen rejectionhandler. 

Alternatively, we can change scope for consume method from private to protected, so generated consumer  can be inherited, and consume method override this way

protected CompletionStage<?> consume(Object payload)  {
   super.consume(payload).whenComplete (dosomething);
}

2022-07-08 06:39 UTC, iurybakov commented
@fjtirado great, I have understood you. I will try all your options and prepare a PR(s). I'll keep you posted on the results. Thanks!

2022-07-13 13:33 UTC, fjtirado requested changes
@iurybakov is working on alternative approach. Thanks!

2022-07-26 12:09 UTC, iurybakov commented
In the process of researching the proposed ideas, another alternative solution was found https://github.com/kiegroup/kogito-runtimes/pull/2361

2022-07-26 12:10 UTC, closed without merging