quarkus-devtools-testing to version.io.quarkus.quarkus-test-maven
kiegroup/kogito-runtimes pull request #2389
Opened 2022-08-10 05:13 UTC by Ginxo

The kogito-runtimes prod nightly build is failing due to `io.quarkus:quarkus-devtools-testing` is not productized by throwing
```
[ERROR] Failed to execute goal on project kogito-quarkus-serverless-workflow-integration-test: Could not resolve dependencies for project org.kie.kogito:kogito-quarkus-serverless-workflow-integration-test:jar:2.0.0.redhat-2022080923: Failure to find io.quarkus:quarkus-devtools-testing:jar:2.7.5.Final-redhat-00011 in REPO_URL was cached in the local repository, resolution will not be reattempted until the update interval of qe-repository has elapsed or updates are forced -> [Help 1]
```
I suggest to use `version.io.quarkus.quarkus-test-maven` property for `io.quarkus:quarkus-devtools-testing` dependency, this way community libraries for this particular dependency will be taken.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

- <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2022-08-10 06:17 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#748` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/748/display/redirect

**Test results:**
- PASSED: 1892
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/748/testReport/org.kie.kogito.index/ProcessDataIndexMongoDBIT/testProcessInstanceEvents/">org.kie.kogito.index.ProcessDataIndexMongoDBIT.testProcessInstanceEvents</a></summary>
java.lang.IllegalStateException: Failed to load ApplicationContext<br/>Caused by: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is org.springframework.boot.web.server.PortInUseException: Port 53504 is already in use<br/>Caused by: org.springframework.boot.web.server.PortInUseException: Port 53504 is already in use<br/>Caused by: java.lang.IllegalArgumentException: standardService.connector.startFailed<br/>Caused by: org.apache.catalina.LifecycleException: Protocol handler start failed<br/>Caused by: java.net.BindException: Address already in use<br/>
</details>

2022-08-10 07:03 UTC, rgdoliveira approved these changes

2022-08-10 07:39 UTC, mareknovotny commented
Jenkins run kogito-apps

2022-08-10 08:38 UTC, Ginxo commented
kogito-apps unstable due to `ProcessDataIndexMongoDBIT.testProcessInstanceEvents` failture
```
[2022-08-10T06:15:29.321Z] Caused by: java.net.BindException: Address already in use
[2022-08-10T06:15:29.321Z] 	at java.base/sun.nio.ch.Net.bind0(Native Method) ~[na:na]
[2022-08-10T06:15:29.321Z] 	at java.base/sun.nio.ch.Net.bind(Net.java:459) ~[na:na]
[2022-08-10T06:15:29.321Z] 	at java.base/sun.nio.ch.Net.bind(Net.java:448) ~[na:na]
[2022-08-10T06:15:29.321Z] 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227) ~[na:na]
[2022-08-10T06:15:29.321Z] 	at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:274) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
[2022-08-10T06:15:29.321Z] 	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:229) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
[2022-08-10T06:15:29.321Z] 	at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1227) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
[2022-08-10T06:15:29.321Z] 	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:1313) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
[2022-08-10T06:15:29.321Z] 	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:614) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
[2022-08-10T06:15:29.321Z] 	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1072) ~[tomcat-embed-core-9.0.60.jar:9.0.60]
[2022-08-10T06:15:29.321Z] 	... 93 common frames omitted
```
I guess not related with this change

2022-08-10 08:55 UTC, mareknovotny commented
still it seems my comment about retest is not triggering the new build?

2022-08-10 09:58 UTC, Ginxo commented
Jenkins run kogito-apps tests

2022-08-10 09:59 UTC, Ginxo commented
> still it seems my comment about retest is not triggering the new build?
according to documentation `tests` is required, see my previous comment @mareknovotny (it launched the test)

2022-08-10 13:21 UTC, AntStephenson requested changes

2022-08-10 13:21 UTC, AntStephenson commented on quarkus/bom/pom.xml
> +        <version>${version.io.quarkus.quarkus-test-maven}</version>
```suggestion
        <version>${version.io.quarkus.quarkus-devtools-testing}</version>
```

If we are to follow our own guidelines we should introduce a new property specific to this artifactId like the above suggestion. The above property you've proposed is used for io.quarkus:quarkus-test-maven for example.

2022-08-11 06:41 UTC, Ginxo commented on quarkus/bom/pom.xml
> +        <version>${version.io.quarkus.quarkus-test-maven}</version>
and what about renaming already existing `version.io.quarkus.quarkus-test-maven` to something more generic like `version.io.quarkus.quarkus-test`? :thinking:

2022-08-11 07:05 UTC, fjtirado approved these changes

2022-08-11 07:51 UTC, mariofusco approved these changes

2022-08-11 09:39 UTC, mareknovotny commented on quarkus/bom/pom.xml
> +        <version>${version.io.quarkus.quarkus-test-maven}</version>
well, we can probably share the property value, but please keep it in the semantic of version properties we get to use -> version.groupid.artifactId to have clear usage

2022-08-11 11:01 UTC, AntStephenson approved these changes

2022-08-11 11:20 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#686` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/686/display/redirect

**Test results:**
- PASSED: 550
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/686/testReport/org.kie.kogito.quarkus.outbox/OutboxIT/___/">org.kie.kogito.quarkus.outbox.OutboxIT.(?)</a></summary>
java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49183] should be listening)<br/>	at org.kie.kogito.quarkus.outbox.OutboxIT.before(OutboxIT.java:86)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Timed out waiting for container port to open (localhost ports: [8080, 49183] should be listening)<br/>
</details>

2022-08-11 11:20 UTC, MarianMacik approved these changes

2022-08-11 12:29 UTC, merged