Kogito-7938 Fixing code smells related to simplifying and ordering Assertj assertions
kiegroup/kogito-runtimes pull request #2493
Opened 2022-09-23 08:44 UTC by Kbowers-redhat

https://issues.redhat.com/browse/KOGITO-7938

Goal here is to reduce the number of code smells in Kogito-runtimes.

Addressed in this PR are the code smells, "Chained AssertJ assertions should be simplified to the corresponding dedicated assertion." And "Assertion arguments should be passed in the correct order."

I have remedied the first set of code smells by simplifying the assertions to dedicated assertions.

I have remedied the second set of code smells by swapping the assertions from "expected value" followed by "actual value", to "actual value" followed by "expected value."

Related PR in Kogito-apps:
https://github.com/kiegroup/kogito-apps/pull/1468

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

- for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] mandrel-lts</b>
 
- <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2022-09-23 15:56 UTC, mariofusco approved these changes

2022-09-26 13:34 UTC, pibizza requested changes
Two main points
1) assertions inside the assertThat have no effect. Be careful with parentheses. I have marked all the cases I have found
2) withFailMessage has to go before the assertion, not after, or it has no effect.
3) some changes to assertions to use simpler forms.

2022-09-26 13:34 UTC, pibizza commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
> +            assertThat(e.getMessage().contains("has no incoming connection"));
This is wrong. Correct form is assertThat(e.getMessage()).contains("has no incoming connection");
Check the parentheses.

2022-09-26 13:34 UTC, pibizza commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
> +        assertThat(messageContent.toString()).hasToString("MYVALUE");
Remove the toString()

2022-09-26 13:34 UTC, pibizza commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
> +            assertThat(e.getMessage().contains("Could not parse date 'abcdef'"));
Correct form is assertThat(e.getMessage()).contains("Could not parse date 'abcdef'");
Check the parentheses.

2022-09-26 13:34 UTC, pibizza commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
> +            assertThat(e.getMessage().contains("Could not parse delay 'abcdef'"));
Correct form is assertThat(e.getMessage()).contains("Could not parse delay 'abcdef'");
Check the parentheses.

2022-09-26 13:34 UTC, pibizza commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
> +            assertThat(e.getMessage().contains("Could not parse delay 'abcdef'"));
Correct form is assertThat(e.getMessage()).contains("Could not parse delay 'abcdef'");
Check the parentheses.

2022-09-26 13:34 UTC, pibizza commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/IntermediateEventTest.java
> +        assertThat(processInstances.size()).isZero();
Simpler form is assertThat(processInstances).isEmpty(); or assertThat(processInstances.size()).isZero(0);

2022-09-26 13:34 UTC, pibizza commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
> +        assertThat(throwObj).isInstanceOf(Throwable.class).withFailMessage("KogitoWorkItem doesn't contain Throwable.");
withFailMessage has to go before the assertion.

2022-09-26 13:34 UTC, pibizza commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/StandaloneBPMNProcessTest.java
> +        assertThat(((Throwable) throwObj).getMessage().endsWith(input)).withFailMessage("Exception message does not match service input.");
See above. WithFailMessage, no assertion. 
Correct form:
assertThat(((Throwable) throwObj).getMessage()).withFailMessage("Exception message does not match service input.").endsWith(input);

2022-09-26 13:34 UTC, pibizza commented on kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/rules/RuleCodegenTest.java
> +        assertThat(emptyGeneratedFiles.size()).isZero();
```suggestion
        assertThat(emptyGeneratedFiles).isEmpty();
```

2022-09-26 13:34 UTC, pibizza commented on kogito-codegen-modules/kogito-codegen-rules/src/test/java/org/kie/kogito/codegen/rules/RuleCodegenTest.java
> +        assertThat(generatedFiles.size()).isPositive();
```suggestion
        assertThat(generatedFiles).hasSizeGreaterThanZero();
```

2022-09-26 13:34 UTC, pibizza commented on kogito-codegen-modules/kogito-codegen-sample/kogito-codegen-sample-generator/src/test/java/org/kie/kogito/codegen/sample/generator/SampleCodegenTest.java
> +        assertThat(emptyGeneratedFiles.size()).isZero();
```suggestion
        assertThat(emptyGeneratedFiles).isEmpty();
```

2022-09-26 13:34 UTC, pibizza commented on quarkus/addons/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/quarkus/QuarkusMetricsFilterRegisterTest.java
> +            assertThat(values).isNotEmpty();
This assertion is redundant with the next one. Remove this and keep the next.

2022-09-26 13:34 UTC, pibizza commented on quarkus/addons/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/quarkus/QuarkusMetricsInterceptorTest.java
> +        assertThat(endpoints).isNotEmpty();
This assertion is redundant with the next one. Remove this and keep the next.

2022-09-26 13:34 UTC, pibizza commented on quarkus/addons/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/quarkus/QuarkusMetricsInterceptorTest.java
> +        assertThat(statusCodes).isNotEmpty();
This assertion is redundant with the next one. Remove this and keep the next.

2022-09-26 13:34 UTC, pibizza commented on springboot/addons/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/springboot/SpringMetricsFilterRegisterTest.java
> +            assertThat(values).isNotEmpty();
This assertion is redundant with the next one. Remove this and keep the next.

2022-09-26 13:34 UTC, pibizza commented on springboot/addons/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/springboot/SpringMetricsInterceptorTest.java
> +        assertThat(endpoints).isNotEmpty();
This assertion is redundant with the next one. Remove this and keep the next.

2022-09-26 13:34 UTC, pibizza commented on springboot/addons/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/springboot/SpringMetricsInterceptorTest.java
> +        assertThat(statusCodes).isNotEmpty();
This assertion is redundant with the next one. Remove this and keep the next.

2022-09-27 08:39 UTC, Kbowers-redhat commented
Many thanks for your detailed feedback Paolo; I've addressed all the points you made.

2022-09-27 08:42 UTC, Kbowers-redhat commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java
> +        assertEquals(KogitoProcessInstance.STATE_COMPLETED, processInstance.getState());
Will keep as assertEquals if that's okay, to keep it consistent with the rest of the class

2022-09-27 08:55 UTC, pibizza commented on jbpm/jbpm-bpmn2/src/test/java/org/jbpm/bpmn2/ErrorEventTest.java
> +        assertEquals(KogitoProcessInstance.STATE_COMPLETED, processInstance.getState());
No problem. There is a general idea to migrate to assertj assertions, but I agree that it is something that should be addressed in general.

2022-09-27 09:52 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1156` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1156/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.6:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-interpolation:jar:1.26:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.8.6:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.8.6:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.6.3:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.6.3:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-utils:jar:3.3.0:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.3:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.6.3:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.5.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.5.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.5.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:2.12.2.Final:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.13.0:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.5:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  +- io.quarkus:quarkus-test-common:jar:2.12.2.Final:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:2.12.2.Final:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.aesh:readline:jar:2.2:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  \- org.fusesource.jansi:jansi:jar:1.18:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.aesh:aesh:jar:2.6:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.ow2.asm:asm:jar:9.3:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:9.3:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  +- org.ow2.asm:asm-tree:jar:9.3:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  |  \- org.ow2.asm:asm-analysis:jar:9.3:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- io.quarkus:quarkus-class-change-agent:jar:2.12.2.Final:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:2.12.2.Final:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- io.quarkus:quarkus-builder:jar:2.12.2.Final:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  \- org.junit.platform:junit-platform-launcher:jar:1.9.0:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  \- org.jboss:jandex:jar:2.4.3.Final:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  +- io.quarkus:quarkus-junit5-properties:jar:2.12.2.Final:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.9.0:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.9.0:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.0:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.0:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.9.0:test<br/>[2022-09-27T09:52:00.539Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.12.2.Final:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.12.2.Final:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.12.2.Final:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.0:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.0:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.0:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.0:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  |     \- io.smallrye.common:smallrye-common-classloader:jar:1.13.0:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.1.0.Final:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.2.0:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.12.2.Final:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] \- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO]    +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-09-27T09:52:00.539Z] [INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-09-27T09:52:00.539Z] [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-09-27T09:52:00.539Z] [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-09-27T09:52:00.539Z] [INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-09-27T09:52:00.539Z] [INFO]    +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO]    +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-09-27T09:52:00.539Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-09-27T09:52:00.539Z] [INFO]       \- org.apache.commons:commons-lang3:jar:3.12.0:compile<br/>[2022-09-27T09:52:00.539Z] [INFO] <br/>[2022-09-27T09:52:00.539 [...]

2022-09-30 13:05 UTC, pibizza requested changes
Some small changes to make better use of Assertj assertions. Good otherwise.

2022-09-30 13:05 UTC, pibizza commented on api/kogito-services/src/test/java/org/kie/kogito/services/uow/DefaultUnitOfWorkManagerTest.java
> +        assertThat(counter.get()).isZero();
```suggestion
        assertThat(counter).hasValue(0);
```

2022-09-30 13:05 UTC, pibizza commented on api/kogito-services/src/test/java/org/kie/kogito/services/uow/DefaultUnitOfWorkManagerTest.java
> +        assertThat(counter.get()).isZero();
```suggestion
        assertThat(counter).hasValue(0);
```

2022-09-30 13:05 UTC, pibizza commented on api/kogito-services/src/test/java/org/kie/kogito/services/uow/DefaultUnitOfWorkManagerTest.java
> +        assertThat(counter.get()).isZero();
```suggestion
        assertThat(counter).hasValue(0);
```

2022-09-30 13:05 UTC, pibizza commented on api/kogito-services/src/test/java/org/kie/kogito/services/uow/DefaultUnitOfWorkManagerTest.java
> +        assertThat(counter.get()).isZero();
```suggestion
        assertThat(counter).hasValue(0);
```

2022-09-30 13:05 UTC, pibizza commented on api/kogito-services/src/test/java/org/kie/kogito/services/uow/DefaultUnitOfWorkManagerTest.java
> +        assertThat(counter.get()).isZero();
```suggestion
        assertThat(counter).hasValue(0);
```

2022-09-30 13:05 UTC, pibizza commented on api/kogito-services/src/test/java/org/kie/kogito/services/uow/DefaultUnitOfWorkManagerTest.java
>          assertThat(counter.get()).isEqualTo(1);
```suggestion
        assertThat(counter).hasValue(1);
```

2022-09-30 13:05 UTC, pibizza commented on api/kogito-services/src/test/java/org/kie/kogito/services/uow/DefaultUnitOfWorkManagerTest.java
> +        assertThat(picounter.get()).isZero();
```suggestion
        assertThat(picounter).hasValue(0);
```

2022-09-30 13:05 UTC, pibizza commented on addons/common/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/common/system/interceptor/MetricsInterceptorTest.java
>          assertThat(endpoints.get(0)).isEqualTo(expectedEndpoint);
```suggestion
        assertThat(endpoints).containsExactly(expectedEndpoint);
```

2022-09-30 13:05 UTC, pibizza commented on addons/common/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/common/system/interceptor/MetricsInterceptorTest.java
>          assertThat(statusCodes.get(0)).isEqualTo(statusCodeString);
```suggestion
        assertThat(statusCodes).containsExactly(statusCodeString);
```

2022-09-30 13:11 UTC, pibizza requested changes
Some extra changes. I suggest using sonarcloud as a reference.

2022-09-30 13:11 UTC, pibizza commented on addons/common/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/common/system/interceptor/MetricsInterceptorTest.java
> +        assertThat(endpoints).hasSize(1);
assertThat(endpoints).isNotEmpty().hasSize(1);

2022-09-30 13:11 UTC, pibizza commented on addons/common/monitoring/core/src/test/java/org/kie/kogito/monitoring/core/common/system/interceptor/MetricsInterceptorTest.java
> +        assertThat(statusCodes).hasSize(1);
Join assertions, see sonarcloud points.

2022-09-30 13:11 UTC, pibizza commented on api/kogito-services/src/test/java/org/kie/kogito/services/event/impl/ProcessEventDispatcherTest.java
> +        assertThat(correlations.contains(new SimpleCorrelation<>(userId, userValue)));
```suggestion
        assertThat(correlations).contains(new SimpleCorrelation<>(userId, userValue));
```

2022-09-30 13:11 UTC, pibizza commented on api/kogito-services/src/test/java/org/kie/kogito/services/event/impl/ProcessEventDispatcherTest.java
> +        assertThat(correlations.contains(new SimpleCorrelation<>(name, nameValue)));
```suggestion
        assertThat(correlations).contains(new SimpleCorrelation<>(name, nameValue));
```

2022-10-03 14:38 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1289` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1289/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-03T14:37:41.507Z] [INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.8.6:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  |  +- org.apache.maven:maven-artifact:jar:3.8.6:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:2.1.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.8.6:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven:maven-model:jar:3.8.6:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven:maven-model-builder:jar:3.8.6:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven:maven-builder-support:jar:3.8.6:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.6.3:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.6.3:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.3.4:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.2:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-sec-dispatcher:jar:2.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-cipher:jar:2.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.6:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-interpolation:jar:1.26:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.8.6:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.8.6:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.6.3:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.6.3:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-utils:jar:3.3.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.3:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.6.3:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.5.1:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.5.1:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.5.1:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:2.13.0.Final:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  \- org.jboss:jandex:jar:2.4.3.Final:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  +- io.quarkus:quarkus-junit5-properties:jar:2.13.0.Final:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.9.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.9.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.9.0:test<br/>[2022-10-03T14:37:41.508Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.13.0.Final:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.13.0.Final:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.13.0.Final:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.0:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.0:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.1:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.1:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  |     \- io.smallrye.common:smallrye-common-classloader:jar:1.13.1:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.2.0:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.13.0.Final:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-10-03T14:37:41.508Z] [INFO] \- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-10-03T14:37:41.508Z] [INFO]    +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-10-03T14:37:41.508Z] [INFO]    +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-10-03T14:37:41.508Z] [INFO]    +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-10-03T14:37:41.508Z] [INFO]    |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-10-03T14:37:41.508Z] [INFO]    +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-10-03T14:37:41.508Z] [INFO]    +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-10-03T14:37:41.508Z] [INFO]    +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-10-03T14:37:41.508Z] [INFO]    +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-10-03T14:37:41.508Z] [INFO]    |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-10-03T14:37:41.508Z] [INFO]    |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-10-03T14:37:41.508Z] [INFO]    \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-10-03T14:37:41.508Z]  [...]

2022-10-04 05:47 UTC, Kbowers-redhat commented
Made all recommended changes, and addressed the Sonarcloud Code Smells.

2022-10-05 12:39 UTC, merged