KOGITO-7946 Sonarcloud - (Java) Unused method parameters should be removed (50)
kiegroup/kogito-runtimes pull request #2519
Opened 2022-09-29 08:52 UTC by Kbowers-redhat

https://issues.redhat.com/browse/KOGITO-7946

Goal here is to reduce the number of code smells in Kogito-runtimes.

Addressed in this PR is the code smell, (Java) Unused method parameters should be removed (50).
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1172&id=org.kie.kogito%3Akogito-runtimes

I have remedied this by removing unused method parameters.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

<b>Jenkins retest this</b>

</details>

2022-09-29 09:56 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1210` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1210/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-09-29T09:56:04.286Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2022-09-29T09:56:04.286Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2022-09-29T09:56:04.286Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2022-09-29T09:56:04.286Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2022-09-29T09:56:04.286Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2022-09-29T09:56:04.286Z] Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to build quarkus application<br/>[2022-09-29T09:56:04.286Z]     at io.quarkus.maven.BuildMojo.doExecute (BuildMojo.java:165)<br/>[2022-09-29T09:56:04.286Z]     at io.quarkus.maven.QuarkusBootstrapMojo.execute (QuarkusBootstrapMojo.java:154)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2022-09-29T09:56:04.286Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2022-09-29T09:56:04.286Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2022-09-29T09:56:04.286Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2022-09-29T09:56:04.286Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2022-09-29T09:56:04.286Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2022-09-29T09:56:04.286Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2022-09-29T09:56:04.286Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2022-09-29T09:56:04.286Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2022-09-29T09:56:04.287Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2022-09-29T09:56:04.287Z] Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/>[2022-09-29T09:56:04.287Z] 	[error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateModel threw an exception: org.kie.memorycompiler.KieMemoryCompilerException: [org/kie/kogito/queries/LoanUnitQueryFindAllApplicationAmountsEventDrivenExecutor.java (22:40) : cannot find symbol<br/>[2022-09-29T09:56:04.287Z]   symbol:   class AbstractEventDrivenQueryExecutor<br/>[2022-09-29T09:56:04.287Z]   location: package org.kie.kogito.eventdriven.rules, org/kie/kogito/queries/LoanUnitQueryFindAllApplicationAmountsEventDrivenExecutor.java (26:80) : cannot find symbol<br/>[2022-09-29T09:56:04.287Z]   symbol: class AbstractEventDrivenQueryExecutor, org/kie/kogito/queries/LoanUnitQueryFindNotApprovedIdAndAmountEventDrivenExecutor.java (22:40) : cannot find symbol<br/>[2022-09-29T09:56:04.287Z]   symbol:   class AbstractEventDrivenQueryExecutor<br/>[2022-09-29T09:56:04.287Z]   location: package org.kie.kogito.eventdriven.rules, org/kie/kogito/queries/LoanUnitQueryFindNotApprovedIdAndAmountEventDrivenExecutor.java (26:81) : cannot find symbol<br/>[2022-09-29T09:56:04.287Z]   symbol: class AbstractEventDrivenQueryExecutor, org/kie/kogito/queries/LoanUnitQueryFindApprovedEventDrivenExecutor.java (22:40) : cannot find symbol<br/>[2022-09-29T09:56:04.287Z]   symbol:   class AbstractEventDrivenQueryExecutor<br/>[2022-09-29T09:56:04.287Z]   location: package org.kie.kogito.eventdriven.rules, org/kie/kogito/queries/LoanUnitQueryFindApprovedEventDrivenExecutor.java (26:67) : cannot find symbol<br/>[2022-09-29T09:56:04.287Z]   symbol: class AbstractEventDrivenQueryExecutor, org/kie/kogito/queries/LoanUnitQueryFindAllApplicationAmountsEventDrivenExecutor.java (36:9) : cannot find symbol<br/>[2022-09-29T09:56:04.287Z]   symbol:   method setup(org.drools.ruleunits.api.RuleUnit<org.kie.kogito.queries.LoanUnit>,java.lang.String,java.lang.Class<org.kie.kogito.queries.LoanUnitQueryFindAllApplicationAmounts>,java.lang.Class<org.kie.kogito.queries.LoanUnit>,com.fasterxml.jackson.databind.ObjectMapper)<br/>[2022-09-29T09:56:04.287Z]   location: class org.kie.kogito.queries.LoanUnitQueryFindAllApplicationAmountsEventDrivenExecutor, org/kie/kogito/queries/LoanUnitQueryFindNotApprovedIdAndAmountEventDrivenExecutor.java (36:9) : cannot find symbol<br/>[2022-09-29T09:56:04.287Z]   symbol:   method setup(org.drools.ruleunits.api.RuleUnit<org.kie.kogito.queries.LoanUnit>,java.lang.String,java.lang.Class<org.kie.kogito.queries.LoanUnitQueryFindNotApprovedIdAndAmount>,java.lang.Class<org.kie.kogito.queries.LoanUnit>,com.fasterxml.jackson.databind.ObjectMapper)<br/>[2022-09-29T09:56:04.287Z]   location: class org.kie.kogito.queries.LoanUnitQueryFindNotApprovedIdAndAmountEventDrivenExecutor, org/kie/kogito/queries/LoanUnitQueryFindApprovedEventDrivenExecutor.java (36:9) : cannot find symbol<br/>[2022-09-29T09:56:04.287Z]   symbol:   method setup(org.drools.ruleunits.api.RuleUnit<org.kie.kogito.queries.LoanUnit>,java.lang.String,java.lang.Class<org.kie.kogito.queries.LoanUnitQueryFindApproved>,java.lang.Class<org.kie.kogito.queries.LoanUnit>,com.fasterxml.jackson.databind.ObjectMapper)<br/>[2022-09-29T09:56:04.287Z]   location: class org.kie.kogito.queries.LoanUnitQueryFindApprovedEventDrivenExecutor]<br/>[2022-09-29T09:56:04.287Z] 	at org.kie.memorycompiler.KieMemoryCompiler.compileNoLoad(KieMemoryCompiler.java:137)<br/>[2022-09-29T09:56:04.287Z] 	at org.kie.memorycompiler.KieMemoryCompiler.compileNoLoad(KieMemoryCompiler.java:105)<br/>[2022-09-29T09:56:04.287Z] 	at org.drools.drl.quarkus.util.deployment.DroolsQuarkusResourceUtils.compileGeneratedSources(DroolsQuarkusResourceUtils.java:141)<br/>[2022-09-29T09:56:04.287Z] 	at org.kie.kogito.quarkus.common.deployment.K [...]

2022-10-03 10:26 UTC, Kbowers-redhat commented
Jenkins retest this

2022-10-03 11:29 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1277` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1277/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-03T11:29:26.550Z] [INFO] You have 0 Checkstyle violations.<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- impsort-maven-plugin:1.5.0:check (default) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] Using compiler compliance level: JAVA_11<br/>[2022-10-03T11:29:26.550Z] [INFO]  Total Files Processed: 0 in 00:00.000<br/>[2022-10-03T11:29:26.550Z] [INFO]         Already Sorted: 0<br/>[2022-10-03T11:29:26.550Z] [INFO]         Needed Sorting: 0<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] Skipping packaging of the test-jar<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] No tests to run.<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] No tests to run.<br/>[2022-10-03T11:29:26.550Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/serverless-workflow-examples/target/failsafe-reports<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/serverless-workflow-examples/target/failsafe-reports<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples/bc/kiegroup_kogito_examples/kogito-examples/serverless-workflow-examples/pom.xml to /home/jenkins/.m2/repository/org/kie/kogito/examples/serverless-workflow-examples/2.0.0-SNAPSHOT/serverless-workflow-examples-2.0.0-SNAPSHOT.pom<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ serverless-workflow-examples ---<br/>[2022-10-03T11:29:26.550Z] [INFO] org.kie.kogito.examples:serverless-workflow-examples:pom:2.0.0-SNAPSHOT<br/>[2022-10-03T11:29:26.550Z] [INFO] ------------------------------------------------------------------------<br/>[2022-10-03T11:29:26.550Z] [INFO] Reactor Summary:<br/>[2022-10-03T11:29:26.550Z] [INFO] <br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example 2.0.0-SNAPSHOT ...................... SUCCESS [  1.583 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Quarkus 2.0.0-SNAPSHOT ........... SUCCESS [  0.053 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Decision Table - Quarkus 2.0.0-SNAPSHOT SUCCESS [ 20.116 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: DMN Metrics Quarkus 2.0.0-SNAPSHOT SUCCESS [01:12 min]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: DMN Event-Driven :: Quarkus 2.0.0-SNAPSHOT SUCCESS [01:08 min]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: DMN Incubation API With Quarkus 2.0.0-SNAPSHOT SUCCESS [ 13.537 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: DMN with Knative Eventing and Quarkus 2.0.0-SNAPSHOT SUCCESS [ 18.159 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: DMN with listeners - Quarkus 2.0.0-SNAPSHOT SUCCESS [ 14.497 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: DMN :: PMML - QUARKUS 2.0.0-SNAPSHOT SUCCESS [ 26.855 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: DMN 2.0.0-SNAPSHOT ............... SUCCESS [ 15.428 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: DMN Tracing - Quarkus 2.0.0-SNAPSHOT SUCCESS [ 24.929 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Flexible Process - Quarkus 2.0.0-SNAPSHOT SUCCESS [ 19.312 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Travel Agency 2.0.0-SNAPSHOT ..... SUCCESS [  0.076 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Travel Agency :: Basic 2.0.0-SNAPSHOT SUCCESS [ 17.941 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Travel Agency :: Extended 2.0.0-SNAPSHOT SUCCESS [  0.059 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Travel Agency :: Travels 2.0.0-SNAPSHOT SUCCESS [ 41.113 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Travel Agency :: Visas 2.0.0-SNAPSHOT SUCCESS [  6.413 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Onboarding Example 2.0.0-SNAPSHOT  SUCCESS [  0.031 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Onboarding Example :: HR with Drools 2.0.0-SNAPSHOT SUCCESS [ 19.993 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Onboarding Example :: Payroll with DMN 2.0.0-SNAPSHOT SUCCESS [ 18.111 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Onboarding Example :: Onboarding with Business Process Quarkus 2.0.0-SNAPSHOT SUCCESS [ 22.633 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: PMML Event-Driven - Quarkus 2.0.0-SNAPSHOT SUCCESS [01:11 min]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: PMML Incubation API With Quarkus 2.0.0-SNAPSHOT SUCCESS [ 15.259 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: PMML - Quarkus 2.0.0-SNAPSHOT .... SUCCESS [ 23.311 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Process Business Rules Quarkus 2.0.0-SNAPSHOT SUCCESS [ 16.418 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Process :: Decisions :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 20.279 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Process :: Decisions :: REST Quarkus 2.0.0-SNAPSHOT SUCCESS [ 22.128 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Process Scripts With Quarkus 2.0.0-SNAPSHOT SUCCESS [ 14.456 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Process Incubation API With Quarkus 2.0.0-SNAPSHOT SUCCESS [ 14.343 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Process Infinispan Persistence Quarkus 2.0.0-SNAPSHOT SUCCESS [ 26.363 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Process with Kafka and Quarkus, multiple channels, avro serialization 2.0.0-SNAPSHOT SUCCESS [ 26.939 s]<br/>[2022-10-03T11:29:26.550Z] [INFO] Kogito Example :: Process with Kafka and Quarkus, multiple [...]

2022-10-03 13:48 UTC, Kbowers-redhat commented
Jenkins (re)run kogito-examples tests

2022-10-04 07:33 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1311` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1311/display/redirect

**Test results:**
- PASSED: 384
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.141 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [ 23.300 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.719 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.705 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Functions And Events :: Quarkus 1.0-SNAPSHOT SUCCESS [ 30.146 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [ 17.457 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Services 1.0-SNAPSHOT SUCCESS [  8.475 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Workflow 1.0-SNAPSHOT SUCCESS [ 20.392 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: PR Checker Workflow 1.0-SNAPSHOT SUCCESS [ 25.904 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: GitHub Service 1.0-SNAPSHOT SUCCESS [  9.484 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: Notification Service 1.0-SNAPSHOT SUCCESS [  5.042 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.015 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow grpc example 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Server:: Quarkus 1.0-SNAPSHOT SUCCESS [  3.829 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Client:: Quarkus 1.0-SNAPSHOT SUCCESS [ 20.958 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Hello World :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 17.658 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Order Processing 1.0-SNAPSHOT SUCCESS [ 19.803 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Parallel Execution :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 19.047 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Order Saga :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.963 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Service Calls :: Quarkus 1.0-SNAPSHOT SUCCESS [ 21.341 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Stock Profit :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.008 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] stock-profit 2.0.0-SNAPSHOT ........................ SUCCESS [ 21.475 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] stock-portfolio-service 2.0.0-SNAPSHOT ............. SUCCESS [  3.000 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] real-stock-service 2.0.0-SNAPSHOT .................. SUCCESS [  2.223 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] fake-stock-service 2.0.0-SNAPSHOT .................. SUCCESS [  2.750 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Subtraction Service 1.0-SNAPSHOT SUCCESS [  8.874 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Multiplication Service 1.0-SNAPSHOT SUCCESS [  9.944 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Service 1.0-SNAPSHOT SUCCESS [ 20.703 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Full Service 1.0-SNAPSHOT SUCCESS [ 21.219 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Function Service 1.0-SNAPSHOT SUCCESS [ 19.982 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Spec Service 1.0-SNAPSHOT SUCCESS [ 20.883 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Testing with REST Assured :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 18.291 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer Showcase 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer :: Workflow Service 1.0-SNAPSHOT SUCCESS [ 26.551 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer :: Query Service 1.0-SNAPSHOT SUCCESS [ 14.449 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription Showcase 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription :: Subscription Service 1.0-SNAPSHOT SUCCESS [ 12.529 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription :: Subscription Flow 1.0-SNAPSHOT SUCCESS [ 24.033 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example :: ACME Financial Service 1.0-SNAPSHOT SUCCESS [ 30.986 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example :: Currency Exchange 1.0-SNAPSHOT SUCCESS [  9.578 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Timeouts Showcase 1.0-SNAPSHOT SUCCESS [01:17 min]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.009 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.239 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 2.0.0-SNAPSHOT SUCCESS [  1.822 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 2.0.0-SNAPSHOT SUCCESS [  0.630 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 15.852 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT SUCCESS [  0.038 s]<br/>[2022-10-04T07:33:25.019Z] [INFO] ------------------------------------------------------------------------<br/>[2022-10-04T07:33:25.019Z] [INFO] BUILD FAILURE<br/>[2022-10-04T07:33:25.019Z] [INFO] ------------------------------------------------------------------------<br/>[2022-10-04T07:33:25.019Z] [INFO] Total time:  49:50 min<br/>[2022-10-04T07:33:25.019Z] [INFO] Finished at: 2022-10-04T03:33:24-04:00<br/>[2022-10-04T07:33:25.019Z] [INFO] ------------------------------------------------------------------------<br/> [...]

2022-10-04 09:12 UTC, Kbowers-redhat commented
Jenkins (re)run kogito-examples tests

2022-10-04 10:11 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1315` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1315/display/redirect

**Test results:**
- PASSED: 384
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.842 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [ 22.617 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.450 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.206 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Functions And Events :: Quarkus 1.0-SNAPSHOT SUCCESS [ 30.049 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.971 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Services 1.0-SNAPSHOT SUCCESS [  8.119 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Workflow 1.0-SNAPSHOT SUCCESS [ 19.503 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: PR Checker Workflow 1.0-SNAPSHOT SUCCESS [ 24.999 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: GitHub Service 1.0-SNAPSHOT SUCCESS [  9.414 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: Notification Service 1.0-SNAPSHOT SUCCESS [  4.981 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.663 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow grpc example 1.0-SNAPSHOT SUCCESS [  0.003 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Server:: Quarkus 1.0-SNAPSHOT SUCCESS [  4.084 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Client:: Quarkus 1.0-SNAPSHOT SUCCESS [ 19.993 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Hello World :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 17.664 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Order Processing 1.0-SNAPSHOT SUCCESS [ 20.166 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Parallel Execution :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 18.543 s]<br/>[2022-10-04T10:10:40.164Z] [INFO] Kogito Example :: Serverless Workflow Order Saga :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.272 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Service Calls :: Quarkus 1.0-SNAPSHOT SUCCESS [ 20.996 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Stock Profit :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.006 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] stock-profit 2.0.0-SNAPSHOT ........................ SUCCESS [ 20.816 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] stock-portfolio-service 2.0.0-SNAPSHOT ............. SUCCESS [  2.987 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] real-stock-service 2.0.0-SNAPSHOT .................. SUCCESS [  2.685 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] fake-stock-service 2.0.0-SNAPSHOT .................. SUCCESS [  2.167 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Subtraction Service 1.0-SNAPSHOT SUCCESS [  9.142 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Multiplication Service 1.0-SNAPSHOT SUCCESS [  9.511 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Service 1.0-SNAPSHOT SUCCESS [ 20.124 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Full Service 1.0-SNAPSHOT SUCCESS [ 21.398 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Function Service 1.0-SNAPSHOT SUCCESS [ 20.045 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Spec Service 1.0-SNAPSHOT SUCCESS [ 19.974 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Testing with REST Assured :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 16.753 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer Showcase 1.0-SNAPSHOT SUCCESS [  0.003 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer :: Workflow Service 1.0-SNAPSHOT SUCCESS [ 25.854 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer :: Query Service 1.0-SNAPSHOT SUCCESS [ 14.200 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription Showcase 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription :: Subscription Service 1.0-SNAPSHOT SUCCESS [ 12.081 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription :: Subscription Flow 1.0-SNAPSHOT SUCCESS [ 23.936 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example :: ACME Financial Service 1.0-SNAPSHOT SUCCESS [ 30.934 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example :: Currency Exchange 1.0-SNAPSHOT SUCCESS [  8.519 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Timeouts Showcase 1.0-SNAPSHOT SUCCESS [01:16 min]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.255 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 2.0.0-SNAPSHOT SUCCESS [  2.286 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 2.0.0-SNAPSHOT SUCCESS [  0.853 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 15.525 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT SUCCESS [  0.056 s]<br/>[2022-10-04T10:10:40.165Z] [INFO] ------------------------------------------------------------------------<br/>[2022-10-04T10:10:40.165Z] [INFO] BUILD FAILURE<br/>[2022-10-04T10:10:40.165Z] [INFO] ------------------------------------------------------------------------<br/>[2022-10-04T10:10:40.165Z] [INFO] Total time:  48:47 min<br/>[2022-10-04T10:10:40.165Z] [INFO] Finished at: 2022-10-04T06:10:39-04:00<br/>[2022-10-04T10:10:40.165Z] [INFO] ------------------------------------------------------------------------<br/> [...]

2022-10-05 06:12 UTC, Kbowers-redhat commented
Jenkins (re)run kogito-examples tests

2022-10-05 06:13 UTC, Kbowers-redhat commented
Jenkins (re)run kogito-examples tests

2022-10-05 07:29 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1322` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1322/display/redirect

**Test results:**
- PASSED: 384
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-05T07:29:18.032Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.273 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [ 21.684 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.877 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.745 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Functions And Events :: Quarkus 1.0-SNAPSHOT SUCCESS [ 30.862 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [ 17.050 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Services 1.0-SNAPSHOT SUCCESS [  8.731 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Workflow 1.0-SNAPSHOT SUCCESS [ 19.966 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: PR Checker Workflow 1.0-SNAPSHOT SUCCESS [ 25.968 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: GitHub Service 1.0-SNAPSHOT SUCCESS [  9.521 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: Notification Service 1.0-SNAPSHOT SUCCESS [  5.027 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.076 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow grpc example 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Server:: Quarkus 1.0-SNAPSHOT SUCCESS [  4.243 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Client:: Quarkus 1.0-SNAPSHOT SUCCESS [ 20.844 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Hello World :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 19.515 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Order Processing 1.0-SNAPSHOT SUCCESS [ 20.582 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Parallel Execution :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 19.074 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Order Saga :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.975 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Service Calls :: Quarkus 1.0-SNAPSHOT SUCCESS [ 22.540 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Stock Profit :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.008 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] stock-profit 2.0.0-SNAPSHOT ........................ SUCCESS [ 22.247 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] stock-portfolio-service 2.0.0-SNAPSHOT ............. SUCCESS [  3.152 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] real-stock-service 2.0.0-SNAPSHOT .................. SUCCESS [  2.447 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] fake-stock-service 2.0.0-SNAPSHOT .................. SUCCESS [  2.599 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Subtraction Service 1.0-SNAPSHOT SUCCESS [  9.538 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Multiplication Service 1.0-SNAPSHOT SUCCESS [  9.870 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Service 1.0-SNAPSHOT SUCCESS [ 20.666 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Full Service 1.0-SNAPSHOT SUCCESS [ 20.610 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Function Service 1.0-SNAPSHOT SUCCESS [ 20.497 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Spec Service 1.0-SNAPSHOT SUCCESS [ 21.021 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Testing with REST Assured :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 18.047 s]<br/>[2022-10-05T07:29:18.033Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer Showcase 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer :: Workflow Service 1.0-SNAPSHOT SUCCESS [ 26.454 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer :: Query Service 1.0-SNAPSHOT SUCCESS [ 14.527 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription Showcase 1.0-SNAPSHOT SUCCESS [  0.006 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription :: Subscription Service 1.0-SNAPSHOT SUCCESS [ 13.450 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription :: Subscription Flow 1.0-SNAPSHOT SUCCESS [ 25.649 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example :: ACME Financial Service 1.0-SNAPSHOT SUCCESS [ 31.809 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example :: Currency Exchange 1.0-SNAPSHOT SUCCESS [  8.972 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Timeouts Showcase 1.0-SNAPSHOT SUCCESS [01:19 min]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.007 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.246 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 2.0.0-SNAPSHOT SUCCESS [  2.174 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 2.0.0-SNAPSHOT SUCCESS [  0.741 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 16.098 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT SUCCESS [  0.048 s]<br/>[2022-10-05T07:29:18.034Z] [INFO] ------------------------------------------------------------------------<br/>[2022-10-05T07:29:18.034Z] [INFO] BUILD FAILURE<br/>[2022-10-05T07:29:18.034Z] [INFO] ------------------------------------------------------------------------<br/>[2022-10-05T07:29:18.034Z] [INFO] Total time:  52:03 min<br/>[2022-10-05T07:29:18.034Z] [INFO] Finished at: 2022-10-05T03:29:17-04:00<br/>[2022-10-05T07:29:18.034Z] [INFO] ------------------------------------------------------------------------<br/> [...]

2022-10-05 09:26 UTC, Kbowers-redhat commented
Jenkins (re)run kogito-examples tests

2022-10-05 10:26 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1326` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1326/display/redirect

**Test results:**
- PASSED: 384
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-05T10:25:47.428Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.475 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [ 24.438 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.661 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.161 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Functions And Events :: Quarkus 1.0-SNAPSHOT SUCCESS [ 29.063 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.546 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Services 1.0-SNAPSHOT SUCCESS [  8.240 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Workflow 1.0-SNAPSHOT SUCCESS [ 19.284 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: PR Checker Workflow 1.0-SNAPSHOT SUCCESS [ 25.069 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: GitHub Service 1.0-SNAPSHOT SUCCESS [  9.217 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Github Showcase :: Notification Service 1.0-SNAPSHOT SUCCESS [  4.786 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.647 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow grpc example 1.0-SNAPSHOT SUCCESS [  0.006 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Server:: Quarkus 1.0-SNAPSHOT SUCCESS [  4.544 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Client:: Quarkus 1.0-SNAPSHOT SUCCESS [ 19.398 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Hello World :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 17.208 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Order Processing 1.0-SNAPSHOT SUCCESS [ 19.776 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Parallel Execution :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 18.192 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Order Saga :: Quarkus 1.0-SNAPSHOT SUCCESS [ 15.627 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Service Calls :: Quarkus 1.0-SNAPSHOT SUCCESS [ 20.694 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Stock Profit :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.008 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] stock-profit 2.0.0-SNAPSHOT ........................ SUCCESS [ 20.433 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] stock-portfolio-service 2.0.0-SNAPSHOT ............. SUCCESS [  2.859 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] real-stock-service 2.0.0-SNAPSHOT .................. SUCCESS [  2.399 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] fake-stock-service 2.0.0-SNAPSHOT .................. SUCCESS [  2.584 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Subtraction Service 1.0-SNAPSHOT SUCCESS [  9.196 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Multiplication Service 1.0-SNAPSHOT SUCCESS [  9.074 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Service 1.0-SNAPSHOT SUCCESS [ 20.596 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Full Service 1.0-SNAPSHOT SUCCESS [ 20.538 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Function Service 1.0-SNAPSHOT SUCCESS [ 19.877 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Temperature Conversion :: Conversion Spec Service 1.0-SNAPSHOT SUCCESS [ 19.936 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Testing with REST Assured :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 17.250 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer Showcase 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer :: Workflow Service 1.0-SNAPSHOT SUCCESS [ 26.161 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Query and Answer :: Query Service 1.0-SNAPSHOT SUCCESS [ 14.750 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription Showcase 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription :: Subscription Service 1.0-SNAPSHOT SUCCESS [ 12.641 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription :: Subscription Flow 1.0-SNAPSHOT SUCCESS [ 22.575 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example :: ACME Financial Service 1.0-SNAPSHOT SUCCESS [ 28.989 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Oauth2 Orchestration Example :: Currency Exchange 1.0-SNAPSHOT SUCCESS [  8.114 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Timeouts Showcase 1.0-SNAPSHOT SUCCESS [01:17 min]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.008 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 2.0.0-SNAPSHOT SUCCESS [  0.255 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 2.0.0-SNAPSHOT SUCCESS [  2.272 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 2.0.0-SNAPSHOT SUCCESS [  0.728 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 2.0.0-SNAPSHOT SUCCESS [ 16.226 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT SUCCESS [  0.045 s]<br/>[2022-10-05T10:25:47.429Z] [INFO] ------------------------------------------------------------------------<br/>[2022-10-05T10:25:47.429Z] [INFO] BUILD FAILURE<br/>[2022-10-05T10:25:47.429Z] [INFO] ------------------------------------------------------------------------<br/>[2022-10-05T10:25:47.429Z] [INFO] Total time:  49:46 min<br/>[2022-10-05T10:25:47.429Z] [INFO] Finished at: 2022-10-05T06:25:46-04:00<br/>[2022-10-05T10:25:47.429Z] [INFO] ------------------------------------------------------------------------<br/> [...]

2022-10-07 04:23 UTC, Kbowers-redhat commented
Jenkins (re)run kogito-examples tests

2022-10-07 04:24 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1360` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1360/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-07T04:23:32.968Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-10-07T04:23:33.094Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-psi-rhel7-xlarge-383<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.37.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 2f7de4d8b0e5bc3425890a5d1979353b8cb1452e # timeout=10<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-10-07T04:23:35.246Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-10-07T04:23:35.272Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-10-07T04:23:35.667Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-07T04:23:35.702Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-10-07T04:23:35.982Z] + df -h<br/>[2022-10-07T04:23:35.982Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-10-07T04:23:35.982Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-10-07T04:23:35.982Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-10-07T04:23:35.982Z] tmpfs           7.8G   25M  7.8G   1% /run<br/>[2022-10-07T04:23:35.982Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-10-07T04:23:35.982Z] /dev/vda1        80G   20G   61G  25% /<br/>[2022-10-07T04:23:35.982Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-10-07T04:23:36.002Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-10-07T04:23:36.284Z] + du -h -d1 /home/jenkins<br/>[2022-10-07T04:23:36.284Z] 4.0K	/home/jenkins/.ssh<br/>[2022-10-07T04:23:36.284Z] 0	/home/jenkins/go<br/>[2022-10-07T04:23:36.284Z] 8.0K	/home/jenkins/.vnc<br/>[2022-10-07T04:23:36.284Z] 38M	/home/jenkins/.m2<br/>[2022-10-07T04:23:36.284Z] 2.1G	/home/jenkins/git-repos<br/>[2022-10-07T04:23:36.284Z] 8.0K	/home/jenkins/.config<br/>[2022-10-07T04:23:36.284Z] 4.0K	/home/jenkins/.cekit<br/>[2022-10-07T04:23:36.284Z] 82M	/home/jenkins/virtenvs<br/>[2022-10-07T04:23:36.284Z] 33M	/home/jenkins/remoting<br/>[2022-10-07T04:23:36.284Z] 0	/home/jenkins/.cache<br/>[2022-10-07T04:23:36.284Z] 3.0M	/home/jenkins/workspace<br/>[2022-10-07T04:23:36.284Z] 0	/home/jenkins/.pki<br/>[2022-10-07T04:23:36.284Z] 0	/home/jenkins/caches<br/>[2022-10-07T04:23:36.284Z] 8.0K	/home/jenkins/.java<br/>[2022-10-07T04:23:36.540Z] 671M	/home/jenkins/.gradle<br/>[2022-10-07T04:23:36.540Z] 100M	/home/jenkins/tools<br/>[2022-10-07T04:23:36.540Z] 3.0G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-10-07T04:23:36.560Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-10-07T04:23:36.842Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-10-07T04:23:36.842Z] 0	/home/jenkins/workspace/KIE/optaplanner/main<br/>[2022-10-07T04:23:36.842Z] 0	/home/jenkins/workspace/KIE/optaplanner<br/>[2022-10-07T04:23:36.842Z] 0	/home/jenkins/workspace/KIE/kogito/1.28.x<br/>[2022-10-07T04:23:36.842Z] 3.0M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-10-07T04:23:36.842Z] 3.0M	/home/jenkins/workspace/KIE/kogito<br/>[2022-10-07T04:23:36.842Z] 3.0M	/home/jenkins/workspace/KIE<br/>[2022-10-07T04:23:36.842Z] 3.0M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-07T04:23:37.165Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-10-07T04:23:37.377Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-10-07T04:23:37.657Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-10-07T04:23:39.546Z] npm WARN ERESOLVE overriding peer dependency<br/>[2022-10-07T04:23:39.546Z] npm WARN Found: @octokit/core@2.5.4<br/>[2022-10-07T04:23:39.546Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2022-10-07T04:23:39.546Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2022-10-07T04:23:39.546Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-07T04:23:39.546Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2022-10-07T04:23:39.546Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2022-10-07T04:23:39.546Z] npm WARN     1 more (@kie/build-chain-configuration-reader)<br/>[2022-10-07T04:23:39.546Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2022-10-07T04:23:39.546Z] npm WARN <br/>[2022-10-07T04:23:39.546Z] npm WARN Could not resolve dependency:<br/>[2022-10-07T04:23:39.547Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2022-10-07T04:23:39.547Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2022-10-07T04:23:39.547Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2022-10-07T04:23:39.547Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-07T04:23:42.814Z] <br/>[2022-10-07T04:23:42.814Z] added 111 packages, and audited 112 packages in 5s<br/>[2022-10-07T04:23:42.814Z] <br/>[2022-10-07T04:23:42.814Z] 5 packages are looking for funding<br/>[2022-10-07T04:23:42.814Z]   run `npm fund` for details<br/>[2022-10-07T04:23:42.814Z] <br/>[2022-10-07T04:23:42.814Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTo [...]

2022-10-07 06:57 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1362` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1362/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Avoid second fetch<br/>Checking out Revision 2f7de4d8b0e5bc3425890a5d1979353b8cb1452e (origin/main)<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 2f7de4d8b0e5bc3425890a5d1979353b8cb1452e # timeout=10<br/>Commit message: "Remove `dependency:tree` from quarkus check (#648)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-10-07T06:57:04.284Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-10-07T06:57:04.376Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-psi-rhel7-xlarge-406<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-10-07T06:57:06.649Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-10-07T06:57:06.730Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-10-07T06:57:07.247Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-07T06:57:07.279Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-10-07T06:57:07.562Z] + df -h<br/>[2022-10-07T06:57:07.563Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-10-07T06:57:07.563Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-10-07T06:57:07.563Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-10-07T06:57:07.563Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-10-07T06:57:07.563Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-10-07T06:57:07.563Z] /dev/vda1        80G   20G   61G  24% /<br/>[2022-10-07T06:57:07.563Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-10-07T06:57:07.584Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-10-07T06:57:07.864Z] + du -h -d1 /home/jenkins<br/>[2022-10-07T06:57:07.864Z] 4.0K	/home/jenkins/.ssh<br/>[2022-10-07T06:57:07.864Z] 0	/home/jenkins/go<br/>[2022-10-07T06:57:07.864Z] 8.0K	/home/jenkins/.vnc<br/>[2022-10-07T06:57:07.864Z] 8.0K	/home/jenkins/.m2<br/>[2022-10-07T06:57:07.864Z] 2.1G	/home/jenkins/git-repos<br/>[2022-10-07T06:57:07.864Z] 8.0K	/home/jenkins/.config<br/>[2022-10-07T06:57:07.864Z] 4.0K	/home/jenkins/.cekit<br/>[2022-10-07T06:57:07.864Z] 82M	/home/jenkins/virtenvs<br/>[2022-10-07T06:57:07.864Z] 32M	/home/jenkins/remoting<br/>[2022-10-07T06:57:07.864Z] 0	/home/jenkins/.cache<br/>[2022-10-07T06:57:07.864Z] 3.0M	/home/jenkins/workspace<br/>[2022-10-07T06:57:07.864Z] 0	/home/jenkins/.pki<br/>[2022-10-07T06:57:07.864Z] 100M	/home/jenkins/tools<br/>[2022-10-07T06:57:07.864Z] 0	/home/jenkins/caches<br/>[2022-10-07T06:57:07.864Z] 2.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-10-07T06:57:07.884Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-10-07T06:57:08.166Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-10-07T06:57:08.167Z] 3.0M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-10-07T06:57:08.167Z] 3.0M	/home/jenkins/workspace/KIE/kogito<br/>[2022-10-07T06:57:08.167Z] 3.0M	/home/jenkins/workspace/KIE<br/>[2022-10-07T06:57:08.167Z] 3.0M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-07T06:57:08.485Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-10-07T06:57:08.689Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-10-07T06:57:08.972Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-10-07T06:57:10.337Z] npm WARN ERESOLVE overriding peer dependency<br/>[2022-10-07T06:57:10.337Z] npm WARN Found: @octokit/core@2.5.4<br/>[2022-10-07T06:57:10.337Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2022-10-07T06:57:10.337Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2022-10-07T06:57:10.337Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-07T06:57:10.337Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2022-10-07T06:57:10.337Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2022-10-07T06:57:10.337Z] npm WARN     1 more (@kie/build-chain-configuration-reader)<br/>[2022-10-07T06:57:10.337Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2022-10-07T06:57:10.337Z] npm WARN <br/>[2022-10-07T06:57:10.337Z] npm WARN Could not resolve dependency:<br/>[2022-10-07T06:57:10.337Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2022-10-07T06:57:10.337Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2022-10-07T06:57:10.337Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2022-10-07T06:57:10.337Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-07T06:57:12.856Z] <br/>[2022-10-07T06:57:12.856Z] added 111 packages, and audited 112 packages in 4s<br/>[2022-10-07T06:57:12.856Z] <br/>[2022-10-07T06:57:12.856Z] 5 packages are looking for funding<br/>[2022-10-07T06:57:12.856Z]   run `npm fund` for details<br/>[2022-10-07T06:57:12.856Z] <br/>[2022-10-07T06:57:12.856Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-07T06:57:13.276Z] BUILD_MVN_OPTS_CURRENT = <br/>[Pipeline] configFileProvider<br/>[2022-10-07T06:57:13.291Z] provisioning config files...<br/>[2022-10-07T06:57:13.299Z] copy managed file [kogito_pr_settings] to file:/home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-examples@tmp/config4684639672079679856tmp<br/>[Pipeline] {<br/>[Pipeline] withCredentials<br/>[2022-10-07T06:57:13.333Z] Masking supported pattern matches of $GITHUB_TOKEN<br/>[Pipeline [...]

2022-10-07 06:58 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1404` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1404/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
Cloning the remote Git repository<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.37.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Avoid second fetch<br/>Checking out Revision 2f7de4d8b0e5bc3425890a5d1979353b8cb1452e (origin/main)<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 2f7de4d8b0e5bc3425890a5d1979353b8cb1452e # timeout=10<br/>Commit message: "Remove `dependency:tree` from quarkus check (#648)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-10-07T06:57:34.257Z] Timeout set to expire in 3 hr 30 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[2022-10-07T06:57:34.347Z] Installing NodeJS from /var/jenkins_home/caches/nodejs/LINUX/amd64/16.2.0.tar.gz to /home/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-16.2.0 on rhos-01-kie-psi-rhel7-xlarge-407<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-10-07T06:57:36.555Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-10-07T06:57:36.655Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-10-07T06:57:37.176Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-apps<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-07T06:57:37.208Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-10-07T06:57:37.489Z] + df -h<br/>[2022-10-07T06:57:37.490Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-10-07T06:57:37.490Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-10-07T06:57:37.490Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-10-07T06:57:37.490Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-10-07T06:57:37.490Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-10-07T06:57:37.490Z] /dev/vda1        80G   20G   61G  24% /<br/>[2022-10-07T06:57:37.490Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-10-07T06:57:37.510Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-10-07T06:57:37.793Z] + du -h -d1 /home/jenkins<br/>[2022-10-07T06:57:37.793Z] 4.0K	/home/jenkins/.ssh<br/>[2022-10-07T06:57:37.793Z] 0	/home/jenkins/go<br/>[2022-10-07T06:57:37.793Z] 8.0K	/home/jenkins/.vnc<br/>[2022-10-07T06:57:37.793Z] 8.0K	/home/jenkins/.m2<br/>[2022-10-07T06:57:37.793Z] 2.1G	/home/jenkins/git-repos<br/>[2022-10-07T06:57:37.793Z] 8.0K	/home/jenkins/.config<br/>[2022-10-07T06:57:37.793Z] 4.0K	/home/jenkins/.cekit<br/>[2022-10-07T06:57:37.793Z] 82M	/home/jenkins/virtenvs<br/>[2022-10-07T06:57:37.793Z] 32M	/home/jenkins/remoting<br/>[2022-10-07T06:57:37.793Z] 0	/home/jenkins/.cache<br/>[2022-10-07T06:57:37.793Z] 3.0M	/home/jenkins/workspace<br/>[2022-10-07T06:57:37.793Z] 0	/home/jenkins/.pki<br/>[2022-10-07T06:57:37.793Z] 100M	/home/jenkins/tools<br/>[2022-10-07T06:57:37.793Z] 0	/home/jenkins/caches<br/>[2022-10-07T06:57:37.793Z] 2.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-10-07T06:57:37.813Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-10-07T06:57:38.097Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-10-07T06:57:38.097Z] 3.0M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-10-07T06:57:38.097Z] 3.0M	/home/jenkins/workspace/KIE/kogito<br/>[2022-10-07T06:57:38.097Z] 3.0M	/home/jenkins/workspace/KIE<br/>[2022-10-07T06:57:38.097Z] 3.0M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-07T06:57:38.411Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-10-07T06:57:38.585Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-10-07T06:57:38.870Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-10-07T06:57:39.799Z] npm WARN ERESOLVE overriding peer dependency<br/>[2022-10-07T06:57:39.800Z] npm WARN Found: @octokit/core@2.5.4<br/>[2022-10-07T06:57:39.800Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2022-10-07T06:57:39.800Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2022-10-07T06:57:39.800Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-07T06:57:39.800Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2022-10-07T06:57:39.800Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2022-10-07T06:57:39.800Z] npm WARN     1 more (@kie/build-chain-configuration-reader)<br/>[2022-10-07T06:57:39.800Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2022-10-07T06:57:39.800Z] npm WARN <br/>[2022-10-07T06:57:39.800Z] npm WARN Could not resolve dependency:<br/>[2022-10-07T06:57:39.800Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2022-10-07T06:57:39.800Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2022-10-07T06:57:39.800Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2022-10-07T06:57:39.800Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-07T06:57:42.321Z] <br/>[2022-10-07T06:57:42.321Z] added 111 packages, and audited 112 packages in 3s<br/>[2022-10-07T06:57:42.321Z] <br/>[2022-10-07T06:57:42.321Z] 5 packages are looking for funding<br/>[2022-10-07T06:57:42.321Z]   run `npm fund` for details<br/>[2022-10-07T06:57:42.321Z] <br/>[2022-10-07T06:57:42.321Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool [...]

2022-10-07 06:58 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#1259` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1259/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision 2f7de4d8b0e5bc3425890a5d1979353b8cb1452e (origin/main)<br/>Commit message: "Remove `dependency:tree` from quarkus check (#648)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2022-10-07T06:57:53.925Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.37.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci service account with access to jboss-integration private github space<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 2f7de4d8b0e5bc3425890a5d1979353b8cb1452e # timeout=10<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2022-10-07T06:57:54.516Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2022-10-07T06:57:54.540Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2022-10-07T06:57:54.901Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-07T06:57:54.931Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2022-10-07T06:57:55.211Z] + df -h<br/>[2022-10-07T06:57:55.211Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2022-10-07T06:57:55.211Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2022-10-07T06:57:55.211Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2022-10-07T06:57:55.211Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2022-10-07T06:57:55.211Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2022-10-07T06:57:55.211Z] /dev/vda1        80G   20G   61G  24% /<br/>[2022-10-07T06:57:55.211Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2022-10-07T06:57:55.231Z] [INFO] space of /home/jenkins<br/>[Pipeline] sh<br/>[2022-10-07T06:57:55.509Z] + du -h -d1 /home/jenkins<br/>[2022-10-07T06:57:55.509Z] 4.0K	/home/jenkins/.ssh<br/>[2022-10-07T06:57:55.509Z] 0	/home/jenkins/go<br/>[2022-10-07T06:57:55.509Z] 8.0K	/home/jenkins/.vnc<br/>[2022-10-07T06:57:55.509Z] 8.0K	/home/jenkins/.m2<br/>[2022-10-07T06:57:55.509Z] 2.1G	/home/jenkins/git-repos<br/>[2022-10-07T06:57:55.509Z] 8.0K	/home/jenkins/.config<br/>[2022-10-07T06:57:55.509Z] 4.0K	/home/jenkins/.cekit<br/>[2022-10-07T06:57:55.509Z] 82M	/home/jenkins/virtenvs<br/>[2022-10-07T06:57:55.509Z] 32M	/home/jenkins/remoting<br/>[2022-10-07T06:57:55.509Z] 0	/home/jenkins/.cache<br/>[2022-10-07T06:57:55.509Z] 3.0M	/home/jenkins/workspace<br/>[2022-10-07T06:57:55.509Z] 0	/home/jenkins/.pki<br/>[2022-10-07T06:57:55.509Z] 139M	/home/jenkins/tools<br/>[2022-10-07T06:57:55.509Z] 0	/home/jenkins/caches<br/>[2022-10-07T06:57:55.509Z] 27M	/home/jenkins/.npm<br/>[2022-10-07T06:57:55.509Z] 2.4G	/home/jenkins<br/>[Pipeline] echo<br/>[2022-10-07T06:57:55.528Z] [INFO] space of workspace<br/>[Pipeline] sh<br/>[2022-10-07T06:57:55.806Z] + du -h -d3 /home/jenkins/workspace<br/>[2022-10-07T06:57:55.806Z] 3.0M	/home/jenkins/workspace/KIE/kogito/main<br/>[2022-10-07T06:57:55.806Z] 3.0M	/home/jenkins/workspace/KIE/kogito<br/>[2022-10-07T06:57:55.806Z] 3.0M	/home/jenkins/workspace/KIE<br/>[2022-10-07T06:57:55.806Z] 3.0M	/home/jenkins/workspace<br/>[Pipeline] }<br/>[Pipeline] // dir<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Install build-chain tool)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2022-10-07T06:57:56.094Z] [INFO] Getting build-chain version from composite action file<br/>[Pipeline] readFile<br/>[Pipeline] echo<br/>[2022-10-07T06:57:56.193Z] [INFO] build-chain version recovered '2.3.36'<br/>[Pipeline] sh<br/>[2022-10-07T06:57:56.474Z] + npm install -g @kie/build-chain-action@2.3.36 -registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/<br/>[2022-10-07T06:57:57.035Z] npm WARN ERESOLVE overriding peer dependency<br/>[2022-10-07T06:57:57.035Z] npm WARN Found: @octokit/core@2.5.4<br/>[2022-10-07T06:57:57.035Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/core<br/>[2022-10-07T06:57:57.035Z] npm WARN   @octokit/core@"^2.4.3" from @octokit/rest@17.11.2<br/>[2022-10-07T06:57:57.035Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-07T06:57:57.035Z] npm WARN     @octokit/rest@"^17.6.0" from @kie/build-chain-action@2.3.36<br/>[2022-10-07T06:57:57.035Z] npm WARN     node_modules/@kie/build-chain-action<br/>[2022-10-07T06:57:57.035Z] npm WARN     1 more (@kie/build-chain-configuration-reader)<br/>[2022-10-07T06:57:57.035Z] npm WARN   1 more (@octokit/plugin-paginate-rest)<br/>[2022-10-07T06:57:57.035Z] npm WARN <br/>[2022-10-07T06:57:57.035Z] npm WARN Could not resolve dependency:<br/>[2022-10-07T06:57:57.035Z] npm WARN peer @octokit/core@">=3" from @octokit/plugin-request-log@1.0.4<br/>[2022-10-07T06:57:57.035Z] npm WARN node_modules/@kie/build-chain-action/node_modules/@octokit/plugin-request-log<br/>[2022-10-07T06:57:57.035Z] npm WARN   @octokit/plugin-request-log@"^1.0.0" from @octokit/rest@17.11.2<br/>[2022-10-07T06:57:57.035Z] npm WARN   node_modules/@kie/build-chain-action/node_modules/@octokit/rest<br/>[2022-10-07T06:57:58.400Z] <br/>[2022-10-07T06:57:58.400Z] changed 111 packages, and audited 112 packages in 2s<br/>[2022-10-07T06:57:58.400Z] <br/>[2022-10-07T06:57:58.400Z] 5 packages are looking for funding<br/>[2022-10-07T06:57:58.400Z]   run `npm fund` for details<br/>[2022-10-07T06:57:58.400Z] <br/>[2022-10-07T06:57:58.400Z] found 0 vulnerabilities<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (Build projects)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] tool<b [...]

2022-10-11 12:58 UTC, fjtirado commented on api/kogito-timer/src/main/java/org/kie/kogito/timer/impl/CronExpression.java
> +    protected Date getTimeBefore() {
I do not think you should change the signature of fhis protected method.

2022-10-11 12:59 UTC, fjtirado commented on api/kogito-services/src/main/java/org/kie/kogito/services/uow/DefaultUnitOfWorkManager.java
> +    protected void dissociate() {
This protected method signature sohuld not be changed, another implementation will need the parameter

2022-10-11 13:01 UTC, fjtirado commented on drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogitoCallbacks.java
> +    public static void beforeAbstractDecisionModelsInit() {
@gitgabrio @tarilabs 
I think this class should be removed, or the name changed to Logger, 
Also the code is weird, a warning to just see if a method has been invoked?

2022-10-11 13:03 UTC, tarilabs commented on drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogitoCallbacks.java
> +    public static void beforeAbstractDecisionModelsInit() {
I am pretty positive it was called "callback" on architectural/tech lead decision, at the time.

2022-10-11 13:05 UTC, fjtirado commented on jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/AbstractNodeHandler.java
> +    protected Optional<DataAssociation> readDataAssociation(org.w3c.dom.Element element, Function<String, DataDefinition> sourceResolver,
I think we need a real good reason (not just a warning from sonar) to change the signature of a protected method. The two cases I mentioned before crearly should not be change, because without the removed parameter, the semantic does not longer makes sense)
And if we verify that the parameter can be safely removed, because no class is overriding this method, then the right thing to do is to also change the scope to private.

2022-10-11 13:12 UTC, gitgabrio commented on drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogitoCallbacks.java
> +    public static void beforeAbstractDecisionModelsInit() {
I agree that the name is misleading: I do not know why a logger helper/utility should be called "Callback".
IMO the behavior could be kept (I guess that there was a reason to write that) but I also would prefer a more meaningfull name

2022-10-11 13:13 UTC, fjtirado commented on jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/BoundaryEventHandler.java
> +            final String localName, final Parser parser, final String attachedTo) throws SAXException {
I do not think any method of this class should be changed. The clear intention of the writter is all the protected method to have the same set of attributes, even if some of them are not used in the default implementation. By removing unused parameters you are breaking the simmetry.
This change only makes sense if you make the methods private.

2022-10-11 13:13 UTC, fjtirado commented on jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/EndEventHandler.java
> +                handleTerminateNode(node, element);
Same, all protected methods has the same signature, which is fine, even if some parameters are not used

2022-10-11 13:14 UTC, fjtirado commented on jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/IntermediateThrowEventHandler.java
>      public void handleMessageNode(final Node node, final Element element,
Changing the signature of a public method because of a sonar warning should be an antipattern.

2022-10-11 13:15 UTC, fjtirado commented on jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/xml/XmlBPMNProcessDumper.java
> +    protected void visitHeader(WorkflowProcess process, StringBuilder xmlDump) {
Same, this protected method should not be changed

2022-10-11 13:18 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/descriptors/AbstractServiceTaskDescriptor.java
> +    protected Expression handleServiceCallResult(final MethodCallExpr callService) {
In this particular case, as author of the class I intentionally introduce the body parameter knowing that is not used by the default implementation, but it will be for sure used for any future implementation, so this should be reverted

2022-10-11 13:20 UTC, fjtirado requested changes
I think this PR is well intended but ill conceived. 
In order to avoid sonar warnings, we should NOT change public and protected methods signature globally. 
So I would only change protected final in self evident cases and all private methods as you did. 
I mentioned in the comments, the cases I know for sure the protected method should not be changed.  Other cases should be carefully reviewed one by one.
For example, probably most of code gen protected methods should be private, not protected, but for that I think a different PR should be opened.

2022-10-11 13:26 UTC, fjtirado commented on drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogitoCallbacks.java
> +    public static void beforeAbstractDecisionModelsInit() {
@gitgabrio I guess that warning is there to indicate the fact that this method should not called when the native mode is enabled, isnt it?

2022-10-11 13:35 UTC, gitgabrio commented on drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/DMNKogitoCallbacks.java
> +    public static void beforeAbstractDecisionModelsInit() {
@fjtirado 
I am mentioned in that class only because for some reason, in one of my PR, I slightly changed the signature of those methods (maybe just formatting ? Or  removal of an unused parameter ?); but all those methods, and their implementations, existed before, so I can not tell why `WARN`  for `GraalVMNIRuntime` and `DEBUG` in the other case. Anyway, I would think that, if it was an unexpected/unwanted/error condition, something like error or exception should have be put in place, though.

2022-10-12 09:20 UTC, Kbowers-redhat commented
Thanks @fjtirado, I really appreciate the feedback and want to apologize for my over-zealousness at following Sonarclouds recommendations. I've reverted the changes you mentioned as well as some additional ones, that upon review seemed ill-considered. Regarding the DMNKogitoCallbacks.java class, I've reverted it back to its original state for now, but I am happy to rename it in this PR if you'd like.

2022-10-12 10:26 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1400` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1400/display/redirect

**Test results:**
- PASSED: 426
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1400/testReport/org.kie.kogito.examples.hr/DepartmentTest/Build_projects___testDepartmentUK/">Build projects / org.kie.kogito.examples.hr.DepartmentTest.testDepartmentUK</a></summary>
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito.examples:hr::jar:2.0.0-SNAPSHOTnull<br/>	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:714)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestClassConstructor(QuarkusTestExtension.java:785)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.api.extension.InvocationInterceptor.interceptTestClassConstructor(InvocationInterceptor.java:73)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:62)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestClassConstructor(ClassBasedTestDescriptor.java:363)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateTestClass(ClassBasedTestDescriptor.java:310)<br/>	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateTestClass(ClassTestDescriptor.java:79)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:286)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:278)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:277)<br/>	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:105)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:104)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:68)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatfor [...]

2022-10-12 10:34 UTC, kie-ci3 commented
**(tests) - kogito-examples job** `#1401` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1401/display/redirect

**Test results:**
- PASSED: 428
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-examples/1401/testReport/org.kie.kogito.examples/CompensationRestIT/Build_projects___testErrorRest/">Build projects / org.kie.kogito.examples.CompensationRestIT.testErrorRest</a></summary>
io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito.examples:serverless-workflow-compensation-quarkus::jar:1.0-SNAPSHOTnull
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.apache.maven:maven-model-builder:jar:3.8.6:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.apache.maven:maven-builder-support:jar:3.8.6:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.6.3:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.6.3:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.3.4:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.2:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-sec-dispatcher:jar:2.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-cipher:jar:2.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.6:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-interpolation:jar:1.26:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  +- org.apache.maven:maven-resolver-provider:jar:3.8.6:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.apache.maven:maven-repository-metadata:jar:3.8.6:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-spi:jar:1.6.3:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-impl:jar:1.6.3:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-utils:jar:3.3.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.3:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  +- org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.6.3:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  +- org.apache.maven.wagon:wagon-http:jar:3.5.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  +- org.apache.maven.wagon:wagon-http-shared:jar:3.5.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  |  \- org.apache.maven.wagon:wagon-provider-api:jar:3.5.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  \- org.apache.maven.wagon:wagon-file:jar:3.5.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  \- io.quarkus:quarkus-bootstrap-gradle-resolver:jar:2.13.0.Final:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- io.quarkus:quarkus-junit5-properties:jar:2.13.0.Final:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.9.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.9.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.9.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  \- com.thoughtworks.xstream:xstream:jar:1.4.19:compile<br/>[2022-10-12T10:34:19.632Z] [INFO] |     \- io.github.x-stream:mxparser:jar:1.2.2:compile<br/>[2022-10-12T10:34:19.632Z] [INFO] |        \- xmlpull:xmlpull:jar:1.1.3.1:compile<br/>[2022-10-12T10:34:19.632Z] [INFO] +- io.rest-assured:rest-assured:jar:4.5.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.codehaus.groovy:groovy:jar:3.0.9:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.codehaus.groovy:groovy-xml:jar:3.0.9:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.15:compile<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.13:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.hamcrest:hamcrest:jar:2.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- io.rest-assured:json-path:jar:4.5.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  +- org.codehaus.groovy:groovy-json:jar:3.0.9:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  \- io.rest-assured:rest-assured-common:jar:4.5.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  \- io.rest-assured:xml-path:jar:4.5.1:test<br/>[2022-10-12T10:34:19.632Z] [INFO] +- org.assertj:assertj-core:jar:3.22.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] +- com.github.tomakehurst:wiremock-jre8:jar:2.33.2:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.eclipse.jetty:jetty-server:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  +- javax.servlet:javax.servlet-api:jar:3.1.0:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  +- org.eclipse.jetty:jetty-http:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.eclipse.jetty:jetty-servlet:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  +- org.eclipse.jetty:jetty-security:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  \- org.eclipse.jetty:jetty-util-ajax:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.eclipse.jetty:jetty-servlets:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  +- org.eclipse.jetty:jetty-continuation:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.eclipse.jetty:jetty-webapp:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  \- org.eclipse.jetty:jetty-xml:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  +- org.eclipse.jetty:jetty-proxy:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.632Z] [INFO] |  |  \- org.eclipse.jetty:jetty-client:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.633Z] [INFO] |  +- org.eclipse.jetty.http2:http2-server:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.633Z] [INFO] |  |  \- org.eclipse.jetty.http2:http2-common:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.633Z] [INFO] |  |     \- org.eclipse.jetty.http2:http2-hpack:jar:9.4.46.v20220331:test<br/>[2022-10-12T10:34:19.633Z] [INFO] |  +- org.eclipse.jetty:jetty-alpn- [...]

2022-10-13 08:01 UTC, Kbowers-redhat commented
Jenkins (re)run kogito-examples tests

2022-10-21 19:03 UTC, fjtirado approved these changes
Good to go, thanks @Kbowers-redhat

2022-10-21 19:04 UTC, fjtirado commented
> Thanks @fjtirado, I really appreciate the feedback and want to apologize for my over-zealousness at following Sonarclouds recommendations. I've reverted the changes you mentioned as well as some additional ones, that upon review seemed ill-considered. Regarding the DMNKogitoCallbacks.java class, I've reverted it back to its original state for now, but I am happy to rename it in this PR if you'd like.

@Kbowers-redhat Sometimes we focus so much on something that we lost perspective, happens to me twice a day ;)
Thanks lot for your understanding, regarding DMNKogitoCallbacks.java, lets open a different PR

2022-10-21 19:05 UTC, merged