Kogito-8066 Sonarcloud - (Java) Exception classes should be immutable (15)
kiegroup/kogito-runtimes pull request #2538
Opened 2022-10-05 06:31 UTC by Kbowers-redhat

https://issues.redhat.com/browse/KOGITO-8066

Goal here is to reduce the number of code smells in Kogito-runtimes.

Addressed in this PR is the code smell, (Java) Exception classes should be immutable (15).
https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1165&id=org.kie.kogito%3Akogito-runtimes

I have addressed this by declaring all fields in exception classes as final.

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>mandrel checks</b>  
  Run native checks against Mandrel image
  Please add comment: <b>Jenkins run mandrel</b>

- for a <b>specific mandrel check</b>  
  Run native checks against Mandrel image  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] mandrel</b>

- for <b>mandrel lts checks</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins run mandrel-lts</b>

- for a <b>specific mandrel lts check</b>  
  Run native checks against Mandrel image and quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] mandrel-lts</b>
 
- <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

2022-10-05 07:48 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1367` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1367/display/redirect

**Test results:**
- PASSED: 1923
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1367/testReport/org.kie.kogito.it.jobs/ProcessAsyncIT/Build_projects___testAsync/">Build projects / org.kie.kogito.it.jobs.ProcessAsyncIT.testAsync</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path hello doesn't match.<br/>Expected: null<br/>  Actual: Hello Tiago<br/><br/>
</details>

2022-11-11 16:13 UTC, fjtirado commented on jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/WorkItemHandlerRuntimeException.java
> +    private final HashMap<String, Object> info = new HashMap<>();
hmmmm. it is funny to find out that we have a not inmutable exception class at all. 
This [method](https://github.com/kiegroup/kogito-runtimes/blob/ef11a51cf8aae3d569413b6f11bd9f7daa5f80fe/jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/WorkItemHandlerRuntimeException.java#L43) should be removed to achieve that goal.

2022-11-11 16:21 UTC, fjtirado requested changes
Please see pending change on my comment

2022-11-14 18:29 UTC, Kbowers-redhat commented on jbpm/jbpm-bpmn2/src/main/java/org/jbpm/bpmn2/handler/WorkItemHandlerRuntimeException.java
> +    private final HashMap<String, Object> info = new HashMap<>();
Moved the map constructor from wihRE to the ServiceTaskHandler itself.

2022-11-14 19:02 UTC, fjtirado commented
@Kbowers-redhat I created PR https://github.com/Kbowers-redhat/kogito-runtimes/pull/1, please take a look

2022-11-14 19:33 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#1608` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1608/display/redirect

**Test results:**
- PASSED: 1929
- FAILED: 5

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1608/testReport/org.kie.kogito.it.jobs/ProcessAsyncIT/Build_projects___testAsync/">Build projects / org.kie.kogito.it.jobs.ProcessAsyncIT.testAsync</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path hello doesn't match.<br/>Expected: null<br/>  Actual: Hello Tiago<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1608/testReport/org.kie.kogito.index.service/InfinispanDomainIndexingServiceIT/testIndexingDomainParallelEvents/">org.kie.kogito.index.service.InfinispanDomainIndexingServiceIT.testIndexingDomainParallelEvents</a></summary>
java.lang.IllegalArgumentException: Cannot invoke method size() on null object<br/>Caused by: java.lang.NullPointerException: Cannot invoke method size() on null object<br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1608/testReport/org.kie.kogito.index.service/InfinispanDomainIndexingServiceIT/testAddProtoFile/">org.kie.kogito.index.service.InfinispanDomainIndexingServiceIT.testAddProtoFile</a></summary>
org.awaitility.core.ConditionTimeoutException: <br/>Assertion condition defined as a lambda expression in org.kie.kogito.index.service.AbstractIndexingServiceIT that uses java.lang.String, java.lang.Stringorg.kie.kogito.event.process.UserTaskInstanceDataEvent 1 expectation failed.<br/>JSON path data.UserTaskInstances[0].id doesn't match.<br/>Expected: is "3596df3b-7038-467a-9b32-858c63a059b3"<br/>  Actual: null<br/> within 30 seconds.<br/>Caused by: java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].id doesn't match.<br/>Expected: is "3596df3b-7038-467a-9b32-858c63a059b3"<br/>  Actual: null<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1608/testReport/org.kie.kogito.index.service/InfinispanDomainIndexingServiceIT/testIndexingDomainUsingUserTaskEventFirst/">org.kie.kogito.index.service.InfinispanDomainIndexingServiceIT.testIndexingDomainUsingUserTaskEventFirst</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.Travels[0].id doesn't match.<br/>Expected: is "cb0bc300-5626-4244-b256-8741db867f61"<br/>  Actual: null<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/1608/testReport/org.kie.kogito.index.service/InfinispanDomainIndexingServiceIT/testIndexingDomainUsingProcessEventFirst/">org.kie.kogito.index.service.InfinispanDomainIndexingServiceIT.testIndexingDomainUsingProcessEventFirst</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.Travels[0].id doesn't match.<br/>Expected: is "228184ea-47fc-4903-8c06-a3f83dd44f35"<br/>  Actual: null<br/><br/>
</details>

2022-11-15 07:46 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#1463` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1463/display/redirect

**Test results:**
- PASSED: 3110
- FAILED: 6

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1463/testReport/org.jbpm.bpmn2/ErrorEventTest/testErrorBoundaryEventOnServiceTask/">org.jbpm.bpmn2.ErrorEventTest.testErrorBoundaryEventOnServiceTask</a></summary>
org.opentest4j.AssertionFailedError: <br/>[Process instance has not been finished.] <br/>expected: null<br/> but was: WorkflowProcessInstance [Id=ca56408b-488b-4b2e-912d-f6b314c65960,processId=BPMN2-ErrorBoundaryEventOnServiceTask,state=5]<br/>	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br/>	at org.jbpm.bpmn2.JbpmBpmn2TestCase.assertProcessInstanceFinished(JbpmBpmn2TestCase.java:198)<br/>	at org.jbpm.bpmn2.ErrorEventTest.testErrorBoundaryEventOnServiceTask(ErrorEventTest.java:224)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)<br/>	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)<br/>	at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:45)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.exec [...]

2022-11-15 13:38 UTC, fjtirado commented
@Kbowers-redhat I manager to break some test with my pr
Opening a new one that fixed this https://github.com/Kbowers-redhat/kogito-runtimes/pull/2
Sorry about that, should be good now

2022-11-16 10:34 UTC, Kbowers-redhat commented
@fjtirado Merged, thanks for sorting that out! :)

2022-11-16 11:18 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#1470` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1470/display/redirect

**Test results:**
- PASSED: 3115
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1470/testReport/io.quarkus.it.kogito.devmode/DevMojoIT/testDMNHotReload/">io.quarkus.it.kogito.devmode.DevMojoIT.testDMNHotReload</a></summary>
org.awaitility.core.ConditionTimeoutException: Condition with lambda expression in io.quarkus.it.kogito.devmode.DevMojoIT was not fulfilled within 15 minutes.<br/>	at io.quarkus.it.kogito.devmode.DevMojoIT.testDMNHotReload(DevMojoIT.java:223)<br/>Caused by: java.util.concurrent.TimeoutException<br/>	at io.quarkus.it.kogito.devmode.DevMojoIT.testDMNHotReload(DevMojoIT.java:223)<br/>
</details>

2022-11-16 17:43 UTC, merged