[KOGITO-7982] - End state not terminating the process when there are pending event nodes and keepActive is false
kiegroup/kogito-runtimes pull request #2722
Opened 2023-01-09 16:21 UTC by VaniHaripriya

Jira - https://issues.redhat.com/browse/KOGITO-7982

Removing all the non-executed event nodes pointing to the join, so that there are no active node instances are present while executing the End node.

2023-01-09 16:56 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#1666` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1666/display/redirect

**Test results:**
- PASSED: 3147
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1666/testReport/org.kie.kogito.integrationtests.springboot/PingPongMessageTest/verifyTopicsInformation/">org.kie.kogito.integrationtests.springboot.PingPongMessageTest.verifyTopicsInformation</a></summary>
java.lang.IllegalStateException: Failed to load ApplicationContext<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>Caused by: java.lang.IllegalStateException: Container exited with code 126<br/>
</details>

2023-01-10 13:12 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
> +                    if (nodeInstance.getNode() instanceof EventNode) {
1)  I do not think we need to check if the contained node is an event
2) I think we should call cancel besided removing the instance
My doubt is if this will break bpmn (probably the fact that Join does not cancel other nodes leads to the introduction of Xand)
Im unsure, @krisv whats your view?

2023-01-10 13:26 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
> +                    if (nodeInstance.getNode() instanceof EventNode) {
Take into account that the real issue is that an XOR Join, when reached, is not cancelling the other branches. To test this is working you can just remove the exclusive;true from here 
https://github.com/kiegroup/kogito-runtimes/blob/main/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/src/main/resources/eventMultipleExclusive.sw.json#L88

2023-01-11 20:11 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#1695` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1695/display/redirect

**Test results:**
- PASSED: 1036
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Processes Extension :: Integration Tests (Hot Reload) SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons .................................. SUCCESS [  0.041 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Common ........................ SUCCESS [  0.052 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Rest Exception Handler :: Common ......... SUCCESS [  7.922 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Quarkus ....................... SUCCESS [  1.290 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Rest Exception Handler :: Quarkus ........ SUCCESS [  5.769 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Messaging ..................... SUCCESS [ 12.952 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Messaging - Parent ................... SUCCESS [  0.027 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Messaging - Common ................... SUCCESS [ 48.906 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Messaging ............................ SUCCESS [  3.157 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Kubernetes .................... SUCCESS [ 24.384 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Kubernetes - Parent .................. SUCCESS [  0.035 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Kubernetes ........................... SUCCESS [02:45 min]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Serverless Workflow Extension .... SUCCESS [  0.366 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Serverless Workflow Extension :: Runtime SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Quarkus Common - Parent .............. SUCCESS [  0.037 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Common - Deployment .................. SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Kubernetes - Deployment .............. SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Messaging - Deployment ............... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Workflows Extension :: Deployment  SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Persistence :: Parent ......... SUCCESS [  0.948 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Persistence :: JDBC ........... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Quarkus Persistence .................. SUCCESS [  0.046 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence JDBC - Parent ............ SUCCESS [  0.445 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence JDBC ..................... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Quarkus :: Events ............. SUCCESS [  0.044 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Events Process - Parent .............. SUCCESS [  0.065 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Events Process ....................... SUCCESS [  1.664 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Test Utilities :: Quarkus ................ SUCCESS [ 17.535 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence JDBC - Deployment ........ SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Events Process - Deployment .......... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Workflows Extension :: Integration Tests SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Workflows Extension :: Image Integration Tests SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Rules Extension :: Integration Tests SUCCESS [01:05 min]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Rules Extension :: Integration Tests (Hot Reload) SUCCESS [01:16 min]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Decisions Extension :: Integration Tests SUCCESS [02:08 min]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Decicions Extension :: Integration Tests (Hot Reload) SUCCESS [01:50 min]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Predictions Extension :: Integration Tests SUCCESS [ 17.654 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Quarkus Test List ........................ SUCCESS [  1.762 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Persistence :: Infinispan ..... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence Infinispan - Parent ...... SUCCESS [  0.083 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence Infinispan ............... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence Infinispan - Deployment .. SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence Infinispan Health Check .. SUCCESS [01:36 min]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence Kafka Streams - Parent ... SUCCESS [  0.068 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence Kafka Streams ............ SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence Kafka Streams - Deployment SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Persistence :: File System .... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence FileSystem - Parent ...... SUCCESS [  0.035 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence FileSystem ............... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence FileSystem - Deployment .. SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Persistence :: MongoDB ........ SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence MongoDB - Parent ......... SUCCESS [  0.028 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence MongoDB .................. SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence MongoDB - Deployment ..... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Persistence :: PostgreSQL ..... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence PostgreSQL - Parent ...... SUCCESS [  0.057 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence PostgreSQL ............... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Persistence PostgreSQL - Deployment .. SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Process SVG :: Common ......... SUCCESS [ 10.949 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Process SVG - Parent ................. SUCCESS [  0.039 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Process SVG .......................... SUCCESS [ 16.654 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Process SVG - Deployment ............. SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Process Management :: Common .. SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Process Management - Parent .......... SUCCESS [  0.031 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Process Management ................... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Process Management - Deployment ...... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito :: Add-Ons :: Source Files :: Common ........ SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Source Files - Parent ................ SUCCESS [  0.101 s]<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On Source Files ......................... SKIPPED<br/>[2023-01-11T20:11:19.668Z] [INFO] Kogito Add-On [...]

2023-01-12 23:14 UTC, VaniHaripriya commented on jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
> +                    if (nodeInstance.getNode() instanceof EventNode) {
@fjtirado Thank you Francisco.
As we don't have cancel to remove the instance from NodeInstanceContainer, I am removing the instance.

The integration test works fine after removing terminate true from the above mentioned SW.

2023-01-12 23:25 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#1705` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1705/display/redirect

**Test results:**
- PASSED: 1036
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Add-Ons :: Common ........................ SUCCESS [  0.157 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Rest Exception Handler :: Common ......... SUCCESS [  6.902 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Add-Ons :: Quarkus ....................... SUCCESS [  1.371 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Rest Exception Handler :: Quarkus ........ SUCCESS [  6.931 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Add-Ons :: Messaging ..................... SUCCESS [  9.391 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Messaging - Parent ................... SUCCESS [  0.064 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Messaging - Common ................... SUCCESS [ 47.297 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Messaging ............................ SUCCESS [  2.908 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Add-Ons :: Kubernetes .................... SUCCESS [ 24.830 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Kubernetes - Parent .................. SUCCESS [  0.071 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Kubernetes ........................... SUCCESS [02:44 min]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Serverless Workflow Extension .... SUCCESS [  0.117 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Serverless Workflow Extension :: Runtime SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Quarkus Common - Parent .............. SUCCESS [  0.047 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Common - Deployment .................. SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Kubernetes - Deployment .............. SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Messaging - Deployment ............... SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Workflows Extension :: Deployment  SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Add-Ons :: Persistence :: Parent ......... SUCCESS [  0.028 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Add-Ons :: Persistence :: JDBC ........... SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Quarkus Persistence .................. SUCCESS [  0.043 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence JDBC - Parent ............ SUCCESS [  0.070 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence JDBC ..................... SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Add-Ons :: Quarkus :: Events ............. SUCCESS [  0.031 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Events Process - Parent .............. SUCCESS [  0.051 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Events Process ....................... SUCCESS [  1.230 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Test Utilities :: Quarkus ................ SUCCESS [ 24.603 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence JDBC - Deployment ........ SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Events Process - Deployment .......... SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Workflows Extension :: Integration Tests SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Workflows Extension :: Image Integration Tests SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Rules Extension :: Integration Tests SUCCESS [01:26 min]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Rules Extension :: Integration Tests (Hot Reload) SUCCESS [01:59 min]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Decisions Extension :: Integration Tests SUCCESS [01:56 min]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Decicions Extension :: Integration Tests (Hot Reload) SUCCESS [01:31 min]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Predictions Extension :: Integration Tests SUCCESS [ 16.104 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Quarkus Test List ........................ SUCCESS [  1.683 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Add-Ons :: Persistence :: Infinispan ..... SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence Infinispan - Parent ...... SUCCESS [  0.032 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence Infinispan ............... SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence Infinispan - Deployment .. SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence Infinispan Health Check .. SUCCESS [01:53 min]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence Kafka Streams - Parent ... SUCCESS [  0.029 s]<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence Kafka Streams ............ SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence Kafka Streams - Deployment SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito :: Add-Ons :: Persistence :: File System .... SKIPPED<br/>[2023-01-12T23:24:59.449Z] [INFO] Kogito Add-On Persistence FileSystem - Parent ...... SUCCESS [  0.030 s]<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Persistence FileSystem ............... SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Persistence FileSystem - Deployment .. SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito :: Add-Ons :: Persistence :: MongoDB ........ SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Persistence MongoDB - Parent ......... SUCCESS [  0.032 s]<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Persistence MongoDB .................. SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Persistence MongoDB - Deployment ..... SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito :: Add-Ons :: Persistence :: PostgreSQL ..... SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Persistence PostgreSQL - Parent ...... SUCCESS [  0.027 s]<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Persistence PostgreSQL ............... SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Persistence PostgreSQL - Deployment .. SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito :: Add-Ons :: Process SVG :: Common ......... SUCCESS [ 10.667 s]<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Process SVG - Parent ................. SUCCESS [  0.063 s]<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Process SVG .......................... SUCCESS [ 20.647 s]<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Process SVG - Deployment ............. SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito :: Add-Ons :: Process Management :: Common .. SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Process Management - Parent .......... SUCCESS [  0.037 s]<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Process Management ................... SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Process Management - Deployment ...... SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito :: Add-Ons :: Source Files :: Common ........ SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Source Files - Parent ................ SUCCESS [  0.033 s]<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Source Files ......................... SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito Add-On Source Files - Deployment ............ SKIPPED<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito :: Add-Ons :: Knative :: Parent ............. SUCCESS [  0.027 s]<br/>[2023-01-12T23:24:59.450Z] [INFO] Kogito :: Add-Ons :: Knative ::  [...]

2023-01-13 00:39 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#1708` was: **UNSTABLE**
Possible explanation: This should be test failures

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1708/display/redirect

**Test results:**
- PASSED: 3145
- FAILED: 7

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/1708/testReport/org.jbpm.bpmn2/FlowTest/testInclusiveSplitAndJoinWithEnd/">org.jbpm.bpmn2.FlowTest.testInclusiveSplitAndJoinWithEnd</a></summary>
org.opentest4j.AssertionFailedError: <br/>[Process instance is not active.] <br/>Expecting value to be true but was false<br/>	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)<br/>	at org.jbpm.bpmn2.JbpmBpmn2TestCase.assertProcessInstanceActive(JbpmBpmn2TestCase.java:193)<br/>	at org.jbpm.bpmn2.FlowTest.testInclusiveSplitAndJoinWithEnd(FlowTest.java:408)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)<br/>	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)<br/>	at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:45)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)<br/>	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrato [...]

2023-01-13 13:01 UTC, krisv requested changes

2023-01-13 13:01 UTC, krisv commented on jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java
> +        if (node instanceof Join) {
I don't think you can just remove all other node instances, because they might be from other completely unrelated paths.  If you have a split and then when you join for the first one arriving you want to cancel all other waiting paths, you need to keep track of which other node instances were actually related to this split/join.  This can be done through an ExclusiveGroup that is created when the split of type XAND is executed (https://github.com/kiegroup/kogito-runtimes/blob/main/jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/node/SplitInstance.java#L177).  This will cancel all others automatically when one is completed already, as shown here: https://github.com/kiegroup/kogito-runtimes/blob/main/jbpm/jbpm-flow/src/main/java/org/jbpm/workflow/instance/impl/NodeInstanceImpl.java#L391

Is XAND used for event-based node when keepActive is false?

2023-01-18 11:21 UTC, fjtirado commented
Closing because we are going to use a different approach. 
Right now, we are using AND-split and XOR-join for exclusive, while we should be using XAND-split and XOR-join. 
For non exclusive the current approach should be preserved AND-split and AND-join.

2023-01-18 11:21 UTC, closed without merging