[KOGITO-8990] Removing pmml from kogito-api
kiegroup/kogito-runtimes pull request #2928
Opened 2023-04-12 12:05 UTC by fjtirado

PMML interfaces  are moved to pmml module.
Lets see how CI for examples goes

2023-04-12 12:16 UTC, baldimir approved these changes

2023-04-12 12:35 UTC, tiagodolphine approved these changes
LGTM

2023-04-12 12:38 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#703` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-springboot-examples/703/display/redirect

**Test results:**
- PASSED: 130
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-12T12:37:55.258Z] 08:37:49.341 [main] INFO  org.apache.juli.logging.DirectJDKLog.log:173 - Initializing Spring embedded WebApplicationContext<br/>[2023-04-12T12:37:55.258Z] 08:37:49.341 [main] INFO  o.s.b.w.s.c.ServletWebServerApplicationContext.prepareWebApplicationContext:290 - Root WebApplicationContext: initialization completed in 1803 ms<br/>[2023-04-12T12:37:55.258Z] 08:37:52.320 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver.<init>:58 - Exposing 1 endpoint(s) beneath base path '/actuator'<br/>[2023-04-12T12:37:55.258Z] 08:37:52.692 [main] INFO  org.apache.juli.logging.DirectJDKLog.log:173 - Starting ProtocolHandler ["http-nio-0.0.0.0-auto-1"]<br/>[2023-04-12T12:37:55.258Z] 08:37:52.709 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer.start:220 - Tomcat started on port(s): 42219 (http) with context path ''<br/>[2023-04-12T12:37:55.258Z] 08:37:53.134 [main] INFO  o.s.boot.StartupInfoLogger.logStarted:61 - Started RestQueryTest in 6.301 seconds (JVM running for 7.49)<br/>[2023-04-12T12:37:56.773Z] 08:37:54.605 [http-nio-0.0.0.0-auto-1-exec-1] INFO  org.apache.juli.logging.DirectJDKLog.log:173 - Initializing Spring DispatcherServlet 'dispatcherServlet'<br/>[2023-04-12T12:37:56.773Z] 08:37:54.606 [http-nio-0.0.0.0-auto-1-exec-1] INFO  o.s.web.servlet.FrameworkServlet.initServletBean:525 - Initializing Servlet 'dispatcherServlet'<br/>[2023-04-12T12:37:56.773Z] 08:37:54.608 [http-nio-0.0.0.0-auto-1-exec-1] INFO  o.s.web.servlet.FrameworkServlet.initServletBean:547 - Completed initialization in 2 ms<br/>[2023-04-12T12:37:56.773Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.379 s - in org.kie.kogito.decisiontable.springboot.ruleunit.RestQueryTest<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] Results:<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-jar-plugin:3.1.0:jar (default-jar) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example.jar<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-jar-plugin:3.1.0:test-jar (test-jar) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-tests.jar<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-sources.jar<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-source-plugin:3.0.1:test-jar-no-fork (attach-test-sources) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] Building jar: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-test-sources.jar<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- spring-boot-maven-plugin:2.6.6:repackage (default) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] Replacing main artifact with repackaged archive<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-resources-plugin:2.5:copy-resources (add-it-resources) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [debug] execute contextualize<br/>[2023-04-12T12:37:56.773Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.<br/>[2023-04-12T12:37:56.773Z] [INFO] Copying 2 resources<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (integration-test) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/failsafe-reports<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/failsafe-reports<br/>[2023-04-12T12:37:56.773Z] [INFO] <br/>[2023-04-12T12:37:56.773Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ ruleunit-springboot-example ---<br/>[2023-04-12T12:37:56.773Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT.jar<br/>[2023-04-12T12:37:56.773Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/pom.xml to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT.pom<br/>[2023-04-12T12:37:56.773Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/target/ruleunit-springboot-example-tests.jar to /home/jenkins/.m2/repository/org/kie/kogito/examples/ruleunit-springboot-example/2.0.0-SNAPSHOT/ruleunit-springboot-example-2.0.0-SNAPSHOT-tests.jar<br/>[2023-04-12T12:37:56.773Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-springboot-examples/bc/kiegroup_kogito-examples/kogito-springboot-examples/ruleunit-springboot-example/ta [...]

2023-04-12 12:40 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#672` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/672/display/redirect

**Test results:**
- PASSED: 78
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-12T12:40:01.238Z] [INFO] |  +- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- org.kie:kie-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- io.cloudevents:cloudevents-api:jar:2.3.0:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- org.drools:drools-ruleunits-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  \- org.kie:kie-internal:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- org.kie:kie-dmn-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  \- org.kie:kie-dmn-model:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  \- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  \- org.drools:drools-io:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |     \- org.drools:drools-util:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  +- io.quarkus:quarkus-elytron-security-properties-file:jar:2.16.5.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- io.quarkus:quarkus-elytron-security:jar:2.16.5.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  \- io.quarkus:quarkus-elytron-security-common:jar:2.16.5.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-auth-server:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-auth:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-base:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-credential:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-asn1:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-keystore:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  |  |  \- org.wildfly.security:wildfly-elytron-x500-cert:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  |  |     +- org.wildfly.security:wildfly-elytron-x500-cert-util:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  |  |     \- org.apache.sshd:sshd-common:jar:2.9.2:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  |  \- org.wildfly.security:wildfly-elytron-provider-util:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-permission:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-util:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-x500:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-password-impl:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-realm:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-encryption:jar:1.20.1.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- io.quarkus:quarkus-security:jar:2.16.5.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- jakarta.security.jacc:jakarta.security.jacc-api:jar:1.6.1:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  \- jakarta.security.auth.message:jakarta.security.auth.message-api:jar:1.1.3:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |     |  \- org.kie:kie-memory-compiler:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |     \- org.assertj:assertj-core:jar:3.23.1:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |        \- net.bytebuddy:byte-buddy:jar:1.12.18:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] +- io.quarkus:quarkus-webjars-locator:jar:2.16.5.Final:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] +- org.webjars:bootstrap:jar:5.1.3:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  \- org.webjars:popper.js:jar:2.9.3:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] +- org.webjars:jquery:jar:3.6.0:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] +- io.quarkus:quarkus-junit5:jar:2.16.5.Final:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:2.16.5.Final:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-app-model:jar:2.16.5.Final:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.13.2:compile<br/>[2023-04-12T12:40:01.238Z] [INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.5:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  +- io.quarkus:quarkus-test-common:jar:2.16.5.Final:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:2.16.5.Final:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- org.aesh:readline:jar:2.2:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  |  \- org.fusesource.jansi:jansi:jar:1.18:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- org.aesh:aesh:jar:2.7:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:9.4:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- io.quarkus:quarkus-class-change-agent:jar:2.16.5.Final:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:2.16.5.Final:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- io.quarkus:quarkus-builder:jar:2.16.5.Final:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  \- org.junit.platform:junit-platform-launcher:jar:1.9.2:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:2.16.5.Final:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.8.6:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.8.6:test<br/>[2023-04-12T12:40:01.238Z] [INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3 [...]

2023-04-12 12:51 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#687` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/687/display/redirect

**Test results:**
- PASSED: 167
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-12T12:51:07.907Z] [INFO] |  |  \- io.quarkus:quarkus-credentials:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  +- io.quarkus:quarkus-jdbc-postgresql:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  \- org.postgresql:postgresql:jar:42.5.4:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  +- io.quarkus:quarkus-vertx:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.quarkus:quarkus-netty:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  +- io.netty:netty-codec:jar:4.1.86.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.86.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  +- io.netty:netty-codec-http2:jar:4.1.86.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  +- io.netty:netty-handler:jar:4.1.86.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  |  \- io.netty:netty-transport-native-unix-common:jar:4.1.86.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  \- com.aayushatharva.brotli4j:brotli4j:jar:1.8.0:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |     \- com.aayushatharva.brotli4j:native-linux-x86_64:jar:1.8.0:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.netty:netty-codec-haproxy:jar:4.1.86.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.86.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  \- io.netty:netty-transport:jar:4.1.86.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.smallrye.common:smallrye-common-annotation:jar:1.13.2:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.smallrye.common:smallrye-common-vertx-context:jar:1.13.2:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  \- io.smallrye.common:smallrye-common-constraint:jar:1.13.2:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.quarkus:quarkus-mutiny:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  +- io.quarkus:quarkus-smallrye-context-propagation:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  |  \- io.smallrye:smallrye-context-propagation:jar:1.2.2:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  |     +- io.smallrye:smallrye-context-propagation-api:jar:1.2.2:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  |     \- io.smallrye:smallrye-context-propagation-storage:jar:1.2.2:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  \- io.smallrye.reactive:mutiny-smallrye-context-propagation:jar:1.9.0:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.quarkus:quarkus-vertx-latebound-mdc-provider:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.30.1:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-runtime:jar:2.30.1:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  \- io.smallrye.reactive:vertx-mutiny-generator:jar:2.30.1:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |     \- io.vertx:vertx-codegen:jar:4.3.7:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  \- io.smallrye:smallrye-fault-tolerance-vertx:jar:5.6.0:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  +- org.kie.kogito:kogito-addons-tracing-decision-common:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- org.kie.kogito:kogito-events-core:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  \- org.kie.kogito:kogito-jackson-utils:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- org.kie.kogito:kogito-addons-tracing-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  \- org.kie.kogito:kogito-addons-tracing-typedvalue-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  \- org.kie.kogito:kogito-addons-explainability:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  \- org.kie.kogito:kogito-addons-quarkus-explainability:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] +- org.kie.kogito:runtime-tools-quarkus-extension:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.13.3:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.13.3:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.2:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.2:compile<br/>[2023-04-12T12:51:07.907Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-classloader:jar:1.13.2:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  |     \- io.smallrye.config:smallrye-config-common:jar:2.13.3:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.5.0.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.11:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.36:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.3.0:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  |  \- io.smallrye.common:smallrye-common-io:jar:1.13.2:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  +- io.quarkus:quarkus-rest-client:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- io.quarkus:quarkus-resteasy-common:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  |  \- org.jboss.resteasy:resteasy-core:jar:4.7.7.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  |     +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  |     \- com.ibm.async:asyncutil:jar:0.1.0:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  +- io.quarkus:quarkus-apache-httpclient:jar:2.16.5.Final:compile<br/>[2023-04-12T12:51:07.908Z] [INFO] |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.14:compile<br/>[2023-04-12T12:51: [...]

2023-04-12 13:58 UTC, fjtirado commented
> Hi @fjtirado what's the reason behind that PR ? It potentially break stuff downward, and introduce a certain unconsistency with other engines.

PMML dependencies are included in serverless workflow extension, where they are not really needed.

2023-04-12 14:08 UTC, gitgabrio commented
> > Hi @fjtirado what's the reason behind that PR ? It potentially break stuff downward, and introduce a certain unconsistency with other engines.
> 
> PMML dependencies are included in serverless workflow extension, where they are not really needed. I do not think the classes I moved to PMLM belonged to Kogito API, but I kept the package to maintain backward compatibility

OK, this is really strange. Your modification does not touch DMN nor any other engine, so I'm expecting all of them to ends up in the `serverless workflow extension`. BUT (again, e.g.) DMN may need them (since DMN may invoke PMML behind the scenes)

2023-04-12 14:15 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#2322` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2322/display/redirect

**Test results:**
- PASSED: 1692
- FAILED: 20

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2322/testReport/org.kie.kogito.it.jobs/JobServiceLeaderIT/___/">org.kie.kogito.it.jobs.JobServiceLeaderIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at org.kie.kogito.it.jobs.JobServiceLeaderIT.init(JobServiceLeaderIT.java:53)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@2cf3d63b)<br/>	at org.kie.kogito.it.jobs.JobServiceLeaderIT.init(JobServiceLeaderIT.java:53)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT<br/>	at org.kie.kogito.it.jobs.JobServiceLeaderIT.init(JobServiceLeaderIT.java:53)<br/>Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: <br/>Status 500: {"message":"Get \"https://org.kie.kogito/v2/\": dial tcp: lookup org.kie.kogito on 10.11.5.160:53: no such host"}<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2322/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/Build_projects___callbackStateTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@7a5f9483)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT<br/>Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: <br/>Status 500: {"message":"Get \"https://org.kie.kogito/v2/\": dial tcp: lookup org.kie.kogito on 10.11.5.160:53: no such host"}<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2322/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/Build_projects___callbackStateTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@41ad342e)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT<br/>Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: <br/>Status 500: {"message":"Get \"https://org.kie.kogito/v2/\": dial tcp: lookup org.kie.kogito on 10.11.5.160:53: no such host"}<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2322/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/Build_projects___callbackStateTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@520795b7)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT<br/>Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: <br/>Status 500: {"message":"Get \"https://org.kie.kogito/v2/\": dial tcp: lookup org.kie.kogito on 10.11.5.160:53: no such host"}<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2322/testReport/org.kie.kogito.it.jobs/ProcessAsyncIT/Build_projects___testAsync/">Build projects / org.kie.kogito.it.jobs.ProcessAsyncIT.testAsync</a></summary>
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuar [...]

2023-04-12 14:21 UTC, gitgabrio requested changes
@fjtirado 
Sorry, but I think this can't be merged. I do not see a real good reason to introduce such potentially breaking change.
Cleaning up a dependency tree, by itself, is not a valid enough reason for such modifications.
As far as I know, there was no issue until now.
If there is a real problem (again, clean up a dependency tree by itself is not) please let me know and, before submitting another PR, let's discuss the issue

2023-04-12 14:35 UTC, fjtirado commented
> 

@gitgabrio Yes, I missed DMN, I should took the same approach for that.

2023-04-12 14:37 UTC, fjtirado commented
> . I do not see a real good reason to introduce such potentially breaking change.
> Cleaning up a dependency tree, by itself, is not a valid enough reason for such modifications.
> As far as I know, there was no issue until now.
> If there is a real problem (again, clean up a dependency tree by itself is not) please let me know and, before submitting another PR, let's discuss the issue

The issue is both DMN and PMML interfaces in kogito-api requires extra dependencies that should not be there (DMNResult, PMMLResult ....). The consequence of that is that any module using kogito-api will include all dmn and pmml dependencies, which is an issue is, as we are trying to do, we want to produce compact images.

2023-04-12 14:41 UTC, fjtirado commented
@gitgabrio which is the potential breaking change? The classes are the same, they are just moved to a different module. And it is very likely that all modulues using dmn or pmml already include the target module (dmn and pmml). 
I  think the benefit worth the small risk.

2023-04-12 14:49 UTC, gitgabrio commented
@fjtirado 
If you are going to do a consistent refactoring, i.e. moving ALL the engine-specif code from kogito-api
namely:

decision
prediction
process
rules

I would agree, because it would make kogito-api "clean" and clear how to use and inherit it.
What I'm strongly against is to have a patchworked situation where some engines are kept inside `kogito-api` and some not. 
About potentially breaking changes: this PR changes the `kogito-api `pom removing the `kogito-pmml-dependencies`: noone can foresee if this could break dependency tree in some "distant" projects, that's what I'm worried about.
Again: if you are going to do the full clean up, moving eveything in due place and clean up kogito-api from all engine-specif dependencies, I would be extremely happy :)

2023-04-12 14:59 UTC, fjtirado commented
@gitgabrio Thats the final target. Im starting with dmn and pmml. Process does not have anything already. And the only remaining is drools-units

2023-04-12 15:03 UTC, fjtirado commented
When I say none, Im referring to dependencies to other projects. The key is the pom. I want to remove dependencies from the pom

2023-04-12 15:05 UTC, tiagodolphine commented
@gitgabrio @fjtirado I think the idea is to keep kogito-api as small and generic as possible, removing dependencies from the specific engines (domains) we currently have, let's take the pom https://github.com/kiegroup/kogito-runtimes/blob/9d569122f534f30739caa2eee884e9eef6f44241/api/kogito-api/pom.xml#L35-L77.
If we try to clean up and remove incrementally the dependencies for dmn, pmml, rule units, it would be a step forward making the module lighter let's say, in this way, each engine would add the specific API they need. For instance, in the pom we don't have jbpm, serverless workflow...  direct dependency. 
This prevents each specific engine to have unnecessary classes in the classpath.
Let's see how CI goes, but it seems the classes were just moved from one place to another, it should not be that harmful.

2023-04-12 15:13 UTC, fjtirado commented
DecissionModel will require anohter PR because there is strong dependency between bpmn engine and dmn. 
But PMML can be easily removed with this PR

2023-04-12 15:26 UTC, fjtirado commented
We already have an inconsistent situation because there are engines adding extra dependencies (rules, dmn and pmml) and others that does not add extra dependencies (bmpn, serverless workflow)
Removin PMML dependency from Kogito-api is easy because pmml is not used directly in the process engine, while rules and dmn are directly referenced by jbmp-flow. 
Thats why this PR just focused on PMML (to be honest I have the hope to remove DMN too, but it was not possible without touching the engine)  to remove an unnededed dependency from kogito-api
Obviously is not the final state, which achievement will require substantial changes in the engine, which is out of the question right now. 
The reason Im trying to is to reduce the maven dependencies is strategical and cannot be disccused here.

2023-04-12 15:28 UTC, fjtirado commented
jenkins retest this

2023-04-12 15:58 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#676` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/676/display/redirect

**Test results:**
- PASSED: 78
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-12T15:58:10.571Z] [INFO] |  +- org.kie.kogito:kogito-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- org.kie:kie-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- io.cloudevents:cloudevents-api:jar:2.3.0:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- org.drools:drools-ruleunits-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  \- org.kie:kie-internal:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- org.kie:kie-dmn-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  \- org.kie:kie-dmn-model:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  \- org.kie.kogito:kogito-timer:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  +- org.kie.kogito:kogito-codegen-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- com.github.javaparser:javaparser-core:jar:3.24.2:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  \- org.drools:drools-codegen-common:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  +- org.kie.kogito:kogito-codegen-core:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  \- org.drools:drools-io:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |     \- org.drools:drools-util:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  +- io.quarkus:quarkus-elytron-security-properties-file:jar:2.16.5.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- io.quarkus:quarkus-elytron-security:jar:2.16.5.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  \- io.quarkus:quarkus-elytron-security-common:jar:2.16.5.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-auth-server:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-auth:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-base:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-credential:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-asn1:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  |  +- org.wildfly.security:wildfly-elytron-keystore:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  |  |  \- org.wildfly.security:wildfly-elytron-x500-cert:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  |  |     +- org.wildfly.security:wildfly-elytron-x500-cert-util:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  |  |     \- org.apache.sshd:sshd-common:jar:2.9.2:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  |  \- org.wildfly.security:wildfly-elytron-provider-util:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-permission:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- org.wildfly.security:wildfly-elytron-util:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-x500:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-password-impl:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- org.wildfly.security:wildfly-elytron-realm:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  \- org.wildfly.security:wildfly-elytron-encryption:jar:1.20.1.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- io.quarkus:quarkus-security:jar:2.16.5.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- jakarta.security.jacc:jakarta.security.jacc-api:jar:1.6.1:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  \- jakarta.security.auth.message:jakarta.security.auth.message-api:jar:1.1.3:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  \- org.kie:efesto-dependencies:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |     +- org.kie:efesto-common-utils:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |     +- org.kie:efesto-common-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |     |  \- org.kie:kie-memory-compiler:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |     +- org.kie:efesto-common-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |     +- org.kie:efesto-compilation-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |     +- org.kie:efesto-compilation-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |     +- org.kie:efesto-runtime-manager-api:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |     +- org.kie:efesto-runtime-manager-core:jar:8.38.0-SNAPSHOT:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |     \- org.assertj:assertj-core:jar:3.23.1:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |        \- net.bytebuddy:byte-buddy:jar:1.12.18:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] +- io.quarkus:quarkus-webjars-locator:jar:2.16.5.Final:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] +- org.webjars:bootstrap:jar:5.1.3:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  \- org.webjars:popper.js:jar:2.9.3:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] +- org.webjars:jquery:jar:3.6.0:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] +- io.quarkus:quarkus-junit5:jar:2.16.5.Final:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  +- io.quarkus:quarkus-bootstrap-core:jar:2.16.5.Final:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-app-model:jar:2.16.5.Final:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  \- io.smallrye.common:smallrye-common-io:jar:1.13.2:compile<br/>[2023-04-12T15:58:10.571Z] [INFO] |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.5:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  +- io.quarkus:quarkus-test-common:jar:2.16.5.Final:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- io.quarkus:quarkus-core-deployment:jar:2.16.5.Final:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- org.aesh:readline:jar:2.2:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  |  \- org.fusesource.jansi:jansi:jar:1.18:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- org.aesh:aesh:jar:2.7:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- org.ow2.asm:asm-commons:jar:9.4:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- io.quarkus:quarkus-class-change-agent:jar:2.16.5.Final:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- io.quarkus:quarkus-devtools-utilities:jar:2.16.5.Final:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- io.quarkus:quarkus-builder:jar:2.16.5.Final:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  \- org.junit.platform:junit-platform-launcher:jar:1.9.2:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:2.16.5.Final:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.8.6:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.8.6:test<br/>[2023-04-12T15:58:10.571Z] [INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3 [...]

2023-04-12 16:11 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#691` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/691/display/redirect

**Test results:**
- PASSED: 167
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-12T16:11:16.691Z] [INFO] |  |  \- io.quarkus:quarkus-credentials:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  +- io.quarkus:quarkus-jdbc-postgresql:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  \- org.postgresql:postgresql:jar:42.5.4:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  +- io.quarkus:quarkus-vertx:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.quarkus:quarkus-netty:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  +- io.netty:netty-codec:jar:4.1.86.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  +- io.netty:netty-codec-http:jar:4.1.86.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  +- io.netty:netty-codec-http2:jar:4.1.86.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  +- io.netty:netty-handler:jar:4.1.86.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  |  \- io.netty:netty-transport-native-unix-common:jar:4.1.86.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- com.aayushatharva.brotli4j:brotli4j:jar:1.8.0:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |     \- com.aayushatharva.brotli4j:native-linux-x86_64:jar:1.8.0:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.netty:netty-codec-haproxy:jar:4.1.86.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  +- io.netty:netty-buffer:jar:4.1.86.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- io.netty:netty-transport:jar:4.1.86.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.smallrye.common:smallrye-common-annotation:jar:1.13.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.smallrye.common:smallrye-common-vertx-context:jar:1.13.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- io.smallrye.common:smallrye-common-constraint:jar:1.13.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.quarkus:quarkus-mutiny:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  +- io.quarkus:quarkus-smallrye-context-propagation:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  |  \- io.smallrye:smallrye-context-propagation:jar:1.2.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  |     +- io.smallrye:smallrye-context-propagation-api:jar:1.2.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  |     \- io.smallrye:smallrye-context-propagation-storage:jar:1.2.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- io.smallrye.reactive:mutiny-smallrye-context-propagation:jar:1.9.0:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.quarkus:quarkus-vertx-latebound-mdc-provider:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.30.1:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  +- io.smallrye.reactive:smallrye-mutiny-vertx-runtime:jar:2.30.1:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- io.smallrye.reactive:vertx-mutiny-generator:jar:2.30.1:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |     \- io.vertx:vertx-codegen:jar:4.3.7:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  \- io.smallrye:smallrye-fault-tolerance-vertx:jar:5.6.0:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  +- org.kie.kogito:kogito-addons-tracing-decision-common:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.kie.kogito:kogito-events-core:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  +- org.kie.kogito:kogito-events-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- org.kie.kogito:kogito-jackson-utils:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.kie.kogito:kogito-addons-tracing-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- org.kie.kogito:kogito-addons-tracing-typedvalue-api:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  \- org.kie.kogito:kogito-addons-explainability:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  \- org.kie.kogito:kogito-addons-quarkus-explainability:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] +- org.kie.kogito:runtime-tools-quarkus-extension:jar:2.0.0-SNAPSHOT:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  +- io.quarkus:quarkus-core:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- jakarta.enterprise:jakarta.enterprise.cdi-api:jar:2.0.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- jakarta.el:jakarta.el-api:jar:3.0.3:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- jakarta.inject:jakarta.inject-api:jar:1.0:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.quarkus:quarkus-development-mode-spi:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.13.3:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.13.3:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-classloader:jar:1.13.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |     \- io.smallrye.config:smallrye-config-common:jar:2.13.3:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.5.0.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.11:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.slf4j:slf4j-api:jar:1.7.36:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.graalvm.sdk:graal-sdk:jar:22.3.0:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- io.smallrye.common:smallrye-common-io:jar:1.13.2:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  +- io.quarkus:quarkus-rest-client:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.quarkus:quarkus-resteasy-common:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- org.jboss.resteasy:resteasy-core:jar:4.7.7.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |     +- org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:2.0.1.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |     \- com.ibm.async:asyncutil:jar:0.1.0:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  +- io.quarkus:quarkus-apache-httpclient:jar:2.16.5.Final:compile<br/>[2023-04-12T16:11:16.691Z] [INFO] |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.14:compile<br/>[2023-04-12T16:11: [...]

2023-04-12 17:31 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#2326` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2326/display/redirect

**Test results:**
- PASSED: 1692
- FAILED: 20

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2326/testReport/org.kie.kogito.it.jobs/JobServiceLeaderIT/___/">org.kie.kogito.it.jobs.JobServiceLeaderIT.(?)</a></summary>
org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at org.kie.kogito.it.jobs.JobServiceLeaderIT.init(JobServiceLeaderIT.java:53)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@2cf3d63b)<br/>	at org.kie.kogito.it.jobs.JobServiceLeaderIT.init(JobServiceLeaderIT.java:53)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT<br/>	at org.kie.kogito.it.jobs.JobServiceLeaderIT.init(JobServiceLeaderIT.java:53)<br/>Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: <br/>Status 500: {"message":"Get \"https://org.kie.kogito/v2/\": dial tcp: lookup org.kie.kogito on 10.11.5.160:53: no such host"}<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2326/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/Build_projects___callbackStateTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@58459cad)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT<br/>Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: <br/>Status 500: {"message":"Get \"https://org.kie.kogito/v2/\": dial tcp: lookup org.kie.kogito on 10.11.5.160:53: no such host"}<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2326/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/Build_projects___callbackStateTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@655629b3)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT<br/>Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: <br/>Status 500: {"message":"Get \"https://org.kie.kogito/v2/\": dial tcp: lookup org.kie.kogito on 10.11.5.160:53: no such host"}<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2326/testReport/org.kie.kogito.it.jobs/CallbackStateTimeoutsIT/Build_projects___callbackStateTimeoutsExceeded/">Build projects / org.kie.kogito.it.jobs.CallbackStateTimeoutsIT.callbackStateTimeoutsExceeded</a></summary>
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$ChainedImageNameSubstitutor@e408168)<br/>Caused by: org.testcontainers.containers.ContainerFetchException: Failed to pull image: org.kie.kogito/jobs-service-postgresql:2.0.0-SNAPSHOT<br/>Caused by: com.github.dockerjava.api.exception.InternalServerErrorException: <br/>Status 500: {"message":"Get \"https://org.kie.kogito/v2/\": dial tcp: lookup org.kie.kogito on 10.11.5.160:53: no such host"}<br/><br/>
</details>
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2326/testReport/org.kie.kogito.it.jobs/ProcessAsyncIT/Build_projects___testAsync/">Build projects / org.kie.kogito.it.jobs.ProcessAsyncIT.testAsync</a></summary>
java.lang.RuntimeException: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuarkusTestResource<br/>Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource class org.kie.kogito.test.resources.JobServiceCompositeQuark [...]

2023-04-13 09:56 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#709` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-springboot-examples/709/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T09:56:13.590Z] Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.kie.kogito:kogito-maven-plugin:2.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:234)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T09:56:13.590Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T09:56:13.591Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T09:56:13.591Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T09:56:13.591Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T09:56:13.591Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T09:56:13.591Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T09:56:13.591Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T09:56:13.591Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T09:56:13.591Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T09:56:13.591Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T09:56:13.591Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T09:56:13.591Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T09:56:13.591Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:226)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T09:56:13.591Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[202 [...]

2023-04-13 09:57 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#2328` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2328/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T09:57:30.899Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T09:57:30.899Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T09:57:30.899Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T09:57:30.899Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T09:57:30.899Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T09:57:30.899Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T09:57:30.899Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T09:57:30.899Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T09:57:30.899Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T09:57:30.899Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T09:57:30.899Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T09:57:30.899Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T09:57:30.899Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:226)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T09:57:30.899Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T09:57:30.900Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T09:57:30.900Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T09:57:30.900Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T09:57:30.900Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T09:57:30.900Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T09:57:30.900Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T09:57:30.900Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launc [...]

2023-04-13 09:59 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#693` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/693/display/redirect

**Test results:**
- PASSED: 18
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/693/testReport/org.kie.kogito.examples/CloudEventListenerTest/___/">org.kie.kogito.examples.CloudEventListenerTest.(?)</a></summary>
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito.examples:dmn-knative-quickstart-quarkus::jar:2.0.0-SNAPSHOTnull<br/>	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:625)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:680)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:128)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:70)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$13(ClassBasedTestDescriptor.java:411)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:409)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:215)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)<br/>	Suppressed: java.lang.NullPointerException<br/>		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:904)<br/>		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:896)<br/>		at io.quarkus.test.junit.QuarkusTestExtension.interceptA [...]

2023-04-13 10:00 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#678` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/678/display/redirect

**Test results:**
- PASSED: 21
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T10:00:10.719Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T10:00:10.719Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T10:00:10.719Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T10:00:10.719Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T10:00:10.719Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T10:00:10.719Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T10:00:10.719Z] Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-addons-quarkus-source-files:jar:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T10:00:10.719Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:357)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-13T10:00:10.719Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T10:00:10.720Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T10:00:10.720Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T10:00:10.720Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T10:00:10.720Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T10:00:10.720Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T10:00:10.720Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T10:00:10.720Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T10:00:10.720Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T10:00:10.720Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-addons-quarkus-source-files:jar:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T10:00:10.720Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T10:00:10.720Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T10:00:10.720Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T10:00:10.720Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T10:00:10.720Z]     at org.ap [...]

2023-04-13 10:08 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#2329` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2329/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T10:08:14.999Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T10:08:14.999Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T10:08:14.999Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T10:08:14.999Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T10:08:14.999Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T10:08:14.999Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T10:08:14.999Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T10:08:14.999Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T10:08:14.999Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T10:08:15.000Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T10:08:15.000Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T10:08:15.000Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T10:08:15.000Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T10:08:15.000Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T10:08:15.000Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T10:08:15.000Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T10:08:15.000Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T10:08:15.000Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T10:08:15.000Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T10:08:15.000Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T10:08:15.000Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:226)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T10:08:15.000Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T10:08:15.000Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T10:08:15.000Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T10:08:15.000Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java: [...]

2023-04-13 10:11 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#679` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/679/display/redirect

**Test results:**
- PASSED: 21
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T10:11:07.296Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T10:11:07.296Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T10:11:07.296Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T10:11:07.296Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T10:11:07.296Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T10:11:07.296Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T10:11:07.296Z] Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-addons-quarkus-source-files:jar:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T10:11:07.296Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:357)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T10:11:07.296Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T10:11:07.297Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T10:11:07.297Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T10:11:07.297Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T10:11:07.297Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T10:11:07.297Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T10:11:07.297Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T10:11:07.297Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T10:11:07.297Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T10:11:07.297Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-addons-quarkus-source-files:jar:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T10:11:07.297Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T10:11:07.297Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T10:11:07.297Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T10:11:07.297Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T10:11:07.297Z]     at org.ap [...]

2023-04-13 10:58 UTC, gitgabrio reviewed
Hi @fjtirado , thanks for the effort! I left one comment, but I think there is still something else going on

2023-04-13 10:58 UTC, gitgabrio commented on jbpm/jbpm-flow/pom.xml
> +    <dependency>
One thing: dmn needs pmml, otherwise dmn models may not work. So, maybe, also pmml should be included here.
It could be that this case (dmn -> pmml) is not covered in any test, but this should be checked out because it could be broken in real usage

2023-04-13 10:59 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#696` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/696/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
 > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.kogito-quarkus-examples/workspace@script/ee10b829cbd0ac763d0be6f0356db3418b2d4469e9daa1842e842313521cde92/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/>Cleaning workspace<br/> > git rev-parse --verify HEAD # timeout=10<br/>Resetting working tree<br/> > git reset --hard # timeout=10<br/> > git clean -fdx # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/>Checking out Revision f0de32225f0dba64e2d32072be76bf288194c207 (origin/main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f f0de32225f0dba64e2d32072be76bf288194c207 # timeout=10<br/>Commit message: "KOGITO-8981 Fix Kogito setup branch job (#933)"<br/> > git rev-list --no-walk f0de32225f0dba64e2d32072be76bf288194c207 # timeout=10<br/>Loading library jenkins-pipeline-shared-libraries@main<br/>Attempting to resolve main from remote references...<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /tmp/jenkins-gitclient-ssh14566941001371394252.key<br/>Verifying host key using manually-configured host key entries<br/> > git ls-remote -h -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Found match: refs/heads/main revision 928fa1ccfce5990c91a751f074d5207b7a0505eb<br/>Selected Git installation does not exist. Using Default<br/>The recommended git tool is: NONE<br/>using credential kie-ci-user-key<br/> > git rev-parse --resolve-git-dir /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.kogito-quarkus-examples/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb/.git # timeout=10<br/>Fetching changes from the remote Git repository<br/> > git config remote.origin.url https://github.com/kiegroup/jenkins-pipeline-shared-libraries # timeout=10<br/>Fetching without tags<br/>Fetching upstream changes from https://github.com/kiegroup/jenkins-pipeline-shared-libraries<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.31.1'<br/>using GIT_SSH to set credentials SSH: kie-ci service account with access to jboss-integration private github space<br/>[INFO] Currently running in a labeled security context<br/> > /usr/bin/chcon --type=ssh_home_t /var/jenkins_home/jobs/KIE/jobs/kogito/jobs/main/jobs/pullrequest/jobs/kogito-runtimes.tests.downstream.kogito-quarkus-examples/workspace@libs/d03f8b53ef89e88ec2b15428a250a4b1fb7910bfcdd3e1c33e4e95c3adb758bb@tmp/jenkins-gitclient-ssh2046490313845386364.key<br/>Verifying host key using manually-configured host key entries<br/> > git fetch --no-tags --force --progress -- https://github.com/kiegroup/jenkins-pipeline-shared-libraries +refs/heads/*:refs/remotes/origin/* # timeout=10<br/>Checking out Revision 928fa1ccfce5990c91a751f074d5207b7a0505eb (main)<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f 928fa1ccfce5990c91a751f074d5207b7a0505eb # timeout=10<br/>Commit message: "[BXMSPROD-2011] Added withKerberos utility method (#270)"<br/> > git rev-list --no-walk 928fa1ccfce5990c91a751f074d5207b7a0505eb # timeout=10<br/>[Pipeline] Start of Pipeline<br/>[Pipeline] node<br/>Running on rhos-01-kie-psi-rhel7-xlarge-3 in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-quarkus-examples<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Checkout SCM)<br/>[Pipeline] checkout<br/>The recommended git tool is: NONE<br/>using credential kie-ci3<br/>Cloning the remote Git repository<br/>Avoid second fetch<br/>Checking out Revision f0de32225f0dba64e2d32072be76bf288194c207 (origin/main)<br/>Commit message: "KOGITO-8981 Fix Kogito setup branch job (#933)"<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] timestamps<br/>[Pipeline] {<br/>[Pipeline] timeout<br/>[2023-04-13T10:57:01.373Z] Timeout set to expire in 3 hr 0 min<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Declarative: Tool Install)<br/>Cloning repository https://github.com/kiegroup/kogito-pipelines.git<br/> > git init /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-quarkus-examples # timeout=10<br/>Fetching upstream changes from https://github.com/kiegroup/kogito-pipelines.git<br/> > git --version # timeout=10<br/> > git --version # 'git version 2.39.2'<br/>using GIT_ASKPASS to set credentials PSSWD: kie-ci3 account to access GitHub via token<br/> > git fetch --tags --force --progress -- https://github.com/kiegroup/kogito-pipelines.git +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git config remote.origin.url https://github.com/kiegroup/kogito-pipelines.git # timeout=10<br/> > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10<br/> > git rev-parse origin/main^{commit} # timeout=10<br/> > git config core.sparsecheckout # timeout=10<br/> > git checkout -f f0de32225f0dba64e2d32072be76bf288194c207 # timeout=10<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] stage<br/>[Pipeline] { (Initialize)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] sh<br/>[2023-04-13T10:57:02.077Z] + printenv<br/>[Pipeline] archiveArtifacts<br/>[2023-04-13T10:57:02.111Z] Archiving artifacts<br/>[Pipeline] }<br/>[Pipeline] // script<br/>[Pipeline] }<br/>[Pipeline] // withEnv<br/>[Pipeline] }<br/>[Pipeline] // stage<br/>[Pipeline] stage<br/>[Pipeline] { (check space before build)<br/>[Pipeline] tool<br/>[Pipeline] envVarsForTool<br/>[Pipeline] withEnv<br/>[Pipeline] {<br/>[Pipeline] script<br/>[Pipeline] {<br/>[Pipeline] dir<br/>[2023-04-13T10:57:02.577Z] Running in /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-quarkus-examples<br/>[Pipeline] {<br/>[Pipeline] echo<br/>[2023-04-13T10:57:02.615Z] [INFO] space left on the machine<br/>[Pipeline] sh<br/>[2023-04-13T10:57:02.897Z] + df -h<br/>[2023-04-13T10:57:02.897Z] Filesystem      Size  Used Avail Use% Mounted on<br/>[2023-04-13T10:57:02.897Z] devtmpfs        7.8G     0  7.8G   0% /dev<br/>[2023-04-13T10:57:02.897Z] tmpfs           7.8G     0  7.8G   0% /dev/shm<br/>[2023-04-13T10:57:02.897Z] tmpfs           7.8G   17M  7.8G   1% /run<br/>[2023-04-13T10:57:02.897Z] tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup<br/>[2023-04-13T10:57:02.897Z] /dev/vda1        80G   20G   61G  25% /<br/>[2023-04-13T10:57:02.897Z] tmpfs           1.6G     0  1.6G   0% /run/user/1000<br/>[Pipeline] echo<br/>[2023-04-13T10:57:02.921Z] [INFO] space of /home/jenkins< [...]

2023-04-13 11:02 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#712` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-springboot-examples/712/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:02:06.919Z] Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.kie.kogito:kogito-maven-plugin:2.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:234)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:02:06.919Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:02:06.919Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:02:06.919Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T11:02:06.919Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T11:02:06.919Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T11:02:06.919Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T11:02:06.919Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T11:02:06.919Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T11:02:06.919Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:02:06.919Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T11:02:06.919Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T11:02:06.919Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:226)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:02:06.919Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[202 [...]

2023-04-13 11:03 UTC, fjtirado commented on jbpm/jbpm-flow/pom.xml
> +    <dependency>
DMN is included here temporarily (I think the target should be to make it conditional rather than strong dependency) because there are some engine classes using the DMN interface. 
Those classes are not using PMML interface directly, so the dependency is not needed here, but in the example that uses DMN&PMML (which I also suspect does not exist)

2023-04-13 11:04 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#2331` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2331/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:04:17.812Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:04:17.812Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:04:17.812Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T11:04:17.812Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T11:04:17.812Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T11:04:17.812Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T11:04:17.812Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T11:04:17.812Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T11:04:17.812Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:04:17.812Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T11:04:17.812Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T11:04:17.812Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:226)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:04:17.812Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:04:17.812Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:04:17.812Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:04:17.812Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java: [...]

2023-04-13 11:05 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#2332` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2332/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:05:13.607Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:05:13.607Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:05:13.607Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:05:13.607Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:05:13.607Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T11:05:13.607Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T11:05:13.607Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T11:05:13.607Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T11:05:13.608Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T11:05:13.608Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T11:05:13.608Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:05:13.608Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T11:05:13.608Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T11:05:13.608Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:226)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:05:13.608Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:05:13.608Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:05:13.608Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:05:13.608Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java: [...]

2023-04-13 11:06 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#681` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/681/display/redirect

**Test results:**
- PASSED: 21
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:05:56.493Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:05:56.493Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:05:56.493Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T11:05:56.493Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T11:05:56.493Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T11:05:56.493Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T11:05:56.493Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T11:05:56.493Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T11:05:56.493Z] Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-addons-quarkus-source-files:jar:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:05:56.493Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:357)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:05:56.493Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:05:56.493Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:05:56.493Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T11:05:56.493Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T11:05:56.493Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T11:05:56.493Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T11:05:56.493Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T11:05:56.493Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T11:05:56.493Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-addons-quarkus-source-files:jar:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:05:56.493Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T11:05:56.493Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T11:05:56.493Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-13T11:05:56.493Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2 [...]

2023-04-13 11:07 UTC, kie-ci3 commented
**(tests) - serverless-workflow-examples job** `#682` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.serverless-workflow-examples/682/display/redirect

**Test results:**
- PASSED: 21
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:07:38.558Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:07:38.558Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:07:38.558Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T11:07:38.558Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T11:07:38.558Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T11:07:38.558Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T11:07:38.558Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T11:07:38.558Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T11:07:38.558Z] Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-addons-quarkus-source-files:jar:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:07:38.558Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:357)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:07:38.558Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:07:38.558Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:07:38.558Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T11:07:38.558Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T11:07:38.558Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T11:07:38.558Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T11:07:38.558Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T11:07:38.558Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T11:07:38.558Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-quarkus-serverless-workflow-devui:jar:2.0.0-SNAPSHOT, org.kie.kogito:kogito-addons-quarkus-source-files:jar:2.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:kogito-quarkus-serverless-workflow:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:07:38.558Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T11:07:38.558Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T11:07:38.558Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve (DefaultProjectDependenciesResolver.java:207)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies (LifecycleDependencyResolver.java:243)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies (LifecycleDependencyResolver.java:147)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved (MojoExecutor.java:401)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:347)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-04-13T11:07:38.558Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2 [...]

2023-04-13 11:08 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#2266` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/2266/display/redirect

**Test results:**
- PASSED: 954
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Spring Boot :: Starter ................... SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Jobs :: Management SprintBoot Addon SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: E-Mail :: Spring Boot Addon ... SUCCESS [  1.676 s]<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Task notification :: Spring Boot Addon SUCCESS [  1.177 s]<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Tracing :: Spring Boot ........ SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Rest Exception Handler:: Spring Boot ..... SUCCESS [ 10.505 s]<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Process SVG :: Spring Boot Addon SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Process Management :: Spring Boot Addon SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Task Management :: Spring Boot Addon SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Spring Boot :: Kubernetes ..... SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Spring Boot :: Persistence :: Parent SUCCESS [  0.051 s]<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Persistence File System :: Springboot SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Persistence Infinispan :: Springboot SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Persistence JDBC :: Springboot  SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Persistence MongoDB :: Springboot SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Add-Ons :: Persistence PostgreSQL :: Springboot SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Spring Boot :: Maven Archetype ........... SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Test Utilities :: Spring Boot ............ SUCCESS [ 20.672 s]<br/>[2023-04-13T11:07:57.410Z] [INFO] Kogito :: Integration Tests :: Spring Boot ......... SKIPPED<br/>[2023-04-13T11:07:57.410Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-13T11:07:57.410Z] [INFO] BUILD FAILURE<br/>[2023-04-13T11:07:57.410Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-13T11:07:57.410Z] [INFO] Total time:  04:22 min (Wall Clock)<br/>[2023-04-13T11:07:57.410Z] [INFO] Finished at: 2023-04-13T07:07:54-04:00<br/>[2023-04-13T11:07:57.410Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-13T11:07:57.410Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project process-workitems: Compilation failure: Compilation failure: <br/>[2023-04-13T11:07:57.410Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[24,35] package org.assertj.core.api does not exist<br/>[2023-04-13T11:07:57.410Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[24,1] static import only from classes and interfaces<br/>[2023-04-13T11:07:57.410Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[69,9] cannot find symbol<br/>[2023-04-13T11:07:57.410Z] [ERROR]   symbol:   method assertThat(java.lang.Object)<br/>[2023-04-13T11:07:57.410Z] [ERROR]   location: class org.kie.kogito.process.workitems.impl.KogitoWorkItemImplTest<br/>[2023-04-13T11:07:57.410Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[72,9] cannot find symbol<br/>[2023-04-13T11:07:57.410Z] [ERROR]   symbol:   method assertThat(java.util.Map<java.lang.String,java.lang.Object>)<br/>[2023-04-13T11:07:57.410Z] [ERROR]   location: class org.kie.kogito.process.workitems.impl.KogitoWorkItemImplTest<br/>[2023-04-13T11:07:57.410Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[73,9] cannot find symbol<br/>[2023-04-13T11:07:57.410Z] [ERROR]   symbol:   method assertThat(java.lang.Object)<br/>[2023-04-13T11:07:57.410Z] [ERROR]   location: class org.kie.kogito.process.workitems.impl.KogitoWorkItemImplTest<br/>[2023-04-13T11:07:57.410Z] [ERROR] -> [Help 1]<br/>[2023-04-13T11:07:57.410Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project process-workitems: Compilation failure<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)<br/>[2023-04-13T11:07:57.410Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:264)<br/>[2023-04-13T11:07:57.410Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)<br/>[2023-04-13T11:07:57.410Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:264)<br/>[2023-04-13T11:07:57.410Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)<br/>[2023-04-13T11:07:57.410Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)<br/>[2023-04-13T11:07:57.410Z]     at java.lang.Thread.run (Thread.java:829)<br/>[2023-04-13T11:07:57.410Z] Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:180)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-04-13T11:07:57.410Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-04-13T11:07:57.410Z]     at org [...]

2023-04-13 11:08 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#2267` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/2267/display/redirect

**Test results:**
- PASSED: 954
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Spring Boot :: Starter ................... SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Jobs :: Management SprintBoot Addon SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: E-Mail :: Spring Boot Addon ... SUCCESS [  0.929 s]<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Task notification :: Spring Boot Addon SUCCESS [  3.124 s]<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Tracing :: Spring Boot ........ SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Rest Exception Handler:: Spring Boot ..... SUCCESS [ 10.727 s]<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Process SVG :: Spring Boot Addon SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Process Management :: Spring Boot Addon SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Task Management :: Spring Boot Addon SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Spring Boot :: Kubernetes ..... SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Spring Boot :: Persistence :: Parent SUCCESS [  0.072 s]<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Persistence File System :: Springboot SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Persistence Infinispan :: Springboot SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Persistence JDBC :: Springboot  SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Persistence MongoDB :: Springboot SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Add-Ons :: Persistence PostgreSQL :: Springboot SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Spring Boot :: Maven Archetype ........... SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Test Utilities :: Spring Boot ............ SUCCESS [ 21.101 s]<br/>[2023-04-13T11:07:58.284Z] [INFO] Kogito :: Integration Tests :: Spring Boot ......... SKIPPED<br/>[2023-04-13T11:07:58.284Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-13T11:07:58.284Z] [INFO] BUILD FAILURE<br/>[2023-04-13T11:07:58.284Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-13T11:07:58.284Z] [INFO] Total time:  04:17 min (Wall Clock)<br/>[2023-04-13T11:07:58.284Z] [INFO] Finished at: 2023-04-13T07:07:56-04:00<br/>[2023-04-13T11:07:58.284Z] [INFO] ------------------------------------------------------------------------<br/>[2023-04-13T11:07:58.284Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project process-workitems: Compilation failure: Compilation failure: <br/>[2023-04-13T11:07:58.285Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[24,35] package org.assertj.core.api does not exist<br/>[2023-04-13T11:07:58.285Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[24,1] static import only from classes and interfaces<br/>[2023-04-13T11:07:58.285Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[69,9] cannot find symbol<br/>[2023-04-13T11:07:58.285Z] [ERROR]   symbol:   method assertThat(java.lang.Object)<br/>[2023-04-13T11:07:58.285Z] [ERROR]   location: class org.kie.kogito.process.workitems.impl.KogitoWorkItemImplTest<br/>[2023-04-13T11:07:58.285Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[72,9] cannot find symbol<br/>[2023-04-13T11:07:58.285Z] [ERROR]   symbol:   method assertThat(java.util.Map<java.lang.String,java.lang.Object>)<br/>[2023-04-13T11:07:58.285Z] [ERROR]   location: class org.kie.kogito.process.workitems.impl.KogitoWorkItemImplTest<br/>[2023-04-13T11:07:58.285Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.kogito-runtimes/bc/kiegroup_kogito-runtimes/jbpm/process-workitems/src/test/java/org/kie/kogito/process/workitems/impl/KogitoWorkItemImplTest.java:[73,9] cannot find symbol<br/>[2023-04-13T11:07:58.285Z] [ERROR]   symbol:   method assertThat(java.lang.Object)<br/>[2023-04-13T11:07:58.285Z] [ERROR]   location: class org.kie.kogito.process.workitems.impl.KogitoWorkItemImplTest<br/>[2023-04-13T11:07:58.285Z] [ERROR] -> [Help 1]<br/>[2023-04-13T11:07:58.285Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project process-workitems: Compilation failure<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:210)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:195)<br/>[2023-04-13T11:07:58.285Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:264)<br/>[2023-04-13T11:07:58.285Z]     at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)<br/>[2023-04-13T11:07:58.285Z]     at java.util.concurrent.FutureTask.run (FutureTask.java:264)<br/>[2023-04-13T11:07:58.285Z]     at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)<br/>[2023-04-13T11:07:58.285Z]     at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)<br/>[2023-04-13T11:07:58.285Z]     at java.lang.Thread.run (Thread.java:829)<br/>[2023-04-13T11:07:58.285Z] Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:180)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-04-13T11:07:58.285Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-04-13T11:07:58.285Z]     at org [...]

2023-04-13 11:08 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#697` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/697/display/redirect

**Test results:**
- PASSED: 18
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/697/testReport/org.kie.kogito.examples/CloudEventListenerTest/___/">org.kie.kogito.examples.CloudEventListenerTest.(?)</a></summary>
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito.examples:dmn-knative-quickstart-quarkus::jar:2.0.0-SNAPSHOTnull<br/>	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:625)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:680)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:128)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:70)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$13(ClassBasedTestDescriptor.java:411)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:409)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:215)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)<br/>	Suppressed: java.lang.NullPointerException<br/>		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:904)<br/>		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:896)<br/>		at io.quarkus.test.junit.QuarkusTestExtension.interceptA [...]

2023-04-13 11:20 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#2333` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2333/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:20:19.440Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:20:19.440Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:20:19.440Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T11:20:19.440Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T11:20:19.440Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T11:20:19.440Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T11:20:19.440Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T11:20:19.440Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T11:20:19.440Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:20:19.440Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T11:20:19.440Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T11:20:19.440Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:226)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:20:19.440Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:20:19.440Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:20:19.440Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:20:19.440Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java: [...]

2023-04-13 11:20 UTC, kie-ci3 commented
**(tests) - kogito-springboot-examples job** `#714` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-springboot-examples/714/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:20:25.443Z] Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.kie.kogito:kogito-maven-plugin:2.0.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:234)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-04-13T11:20:25.443Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-04-13T11:20:25.443Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-04-13T11:20:25.443Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-04-13T11:20:25.443Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-04-13T11:20:25.443Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-04-13T11:20:25.443Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-04-13T11:20:25.443Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-04-13T11:20:25.443Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-04-13T11:20:25.443Z] Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.kie.kogito:kogito-maven-plugin:jar:2.0.0-SNAPSHOT<br/>[2023-04-13T11:20:25.443Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve (DefaultArtifactResolver.java:425)<br/>[2023-04-13T11:20:25.443Z]     at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts (DefaultArtifactResolver.java:229)<br/>[2023-04-13T11:20:25.443Z]     at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies (DefaultRepositorySystem.java:340)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal (DefaultPluginDependenciesResolver.java:226)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve (DefaultPluginDependenciesResolver.java:165)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.resolveExtensionArtifacts (DefaultMavenPluginManager.java:911)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupExtensionsRealm (DefaultMavenPluginManager.java:842)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultProjectBuildingHelper.createProjectRealm (DefaultProjectBuildingHelper.java:197)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultModelBuildingListener.buildExtensionsAssembled (DefaultModelBuildingListener.java:101)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.model.building.ModelBuildingEventCatapult$1.fire (ModelBuildingEventCatapult.java:44)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.model.building.DefaultModelBuilder.fireEvent (DefaultModelBuilder.java:1450)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:530)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.model.building.DefaultModelBuilder.build (DefaultModelBuilder.java:510)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:618)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:633)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.project.DefaultProjectBuilder.build (DefaultProjectBuilder.java:387)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.graph.DefaultGraphBuilder.collectProjects (DefaultGraphBuilder.java:414)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.graph.DefaultGraphBuilder.getProjectsForMavenReactor (DefaultGraphBuilder.java:405)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.graph.DefaultGraphBuilder.build (DefaultGraphBuilder.java:82)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.DefaultMaven.buildGraph (DefaultMaven.java:542)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:219)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-04-13T11:20:25.443Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[202 [...]

2023-04-13 11:23 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#2268` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/2268/display/redirect

**Test results:**
- PASSED: 1004
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-Ons Quarkus Jobs - Knative Eventing ..... SUCCESS [ 14.362 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-Ons Quarkus Jobs Knative Eventing - Deployment SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: E-Mail :: Common .............. SUCCESS [  6.919 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Mail - Parent ........................ SUCCESS [  0.023 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Mail ................................. SUCCESS [ 41.865 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Mail - Deployment .................... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Monitoring .................... SUCCESS [  0.052 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Monitoring Core ............... SUCCESS [ 19.598 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Monitoring - Parent .................. SUCCESS [  0.111 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Monitoring Core ...................... SUCCESS [ 16.732 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Monitoring Prometheus Common .. SUCCESS [  1.182 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Monitoring Prometheus - Parent ....... SUCCESS [  0.047 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Monitoring Prometheus ................ SUCCESS [  5.330 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Monitoring Prometheus - Deployment ... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Monitoring Elastic Common ..... SUCCESS [  7.821 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Monitoring Elastic - Parent .......... SUCCESS [  0.085 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Monitoring Elastic ................... SUCCESS [  1.444 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Monitoring Elastic - Deployment ...... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Task Notification - Parent ........... SUCCESS [  0.047 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Task Notification .................... SUCCESS [  2.704 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Task Notification - Deployment ....... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Tracing ....................... SUCCESS [  0.049 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: TypedValue API ................ SUCCESS [  9.435 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Tracing :: API ................ SUCCESS [  9.394 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Tracing :: Common ............. SUCCESS [ 17.866 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Tracing Decision - Parent ............ SUCCESS [  0.064 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Tracing Decision ..................... SUCCESS [ 27.101 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Tracing Decision - Deployment ........ SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Tracing Decision - Integration tests . SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Task Management :: Common ..... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Task Management - Parent ............. SUCCESS [  0.053 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Task Management ...................... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito Add-On Task Management - Deployment ......... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus ............. SUCCESS [  0.031 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: OpenAPI Client Codegen SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Rules .... SUCCESS [ 58.782 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Decisions  SUCCESS [ 57.197 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Classic SUCCESS [ 43.480 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: RESTEasy Reactive SUCCESS [ 32.865 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Maven Plugin ............................. SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Maven Plugin ........ SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Without REST SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes  SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Reactive SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence SUCCESS [  1.354 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Processes :: Persistence :: Common SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: PostgreSQL SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Infinispan SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: MongoDB SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: Kafka SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: JDBC SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Persistence :: File System SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Processes :: Source Files SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Integration Tests :: Quarkus :: Gradle ... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: DB Scripts Collection .................... SUCCESS [  1.905 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Predictions ................... SUCCESS [  0.023 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Predictions :: API ............ SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Predictions :: SMILE .......... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Serverless Workflow :: Executor .......... SKIPPED<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Spring Boot .............................. SUCCESS [  0.089 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Spring Boot :: BOM ....................... SUCCESS [  0.120 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Spring Boot ................... SUCCESS [  0.064 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: CloudEvents :: Spring Boot .... SUCCESS [  0.029 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Messaging :: Spring Boot ...... SUCCESS [  1.000 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Spring Boot :: Events - Parent  SUCCESS [  0.041 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Decisions :: Spring Boot SUCCESS [  0.540 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Predictions :: Spring Boot SUCCESS [  0.608 s]<br/>[2023-04-13T11:23:32.336Z] [INFO] Kogito :: Add-Ons :: Events :: Event-Driven Rules :: Spring Boot SUCCESS [  0.553 s]<br/>[2023-04-13T11:23:32.336Z] [ [...]

2023-04-13 11:23 UTC, kie-ci3 commented
**(tests) - kogito-quarkus-examples job** `#698` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure

Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/698/display/redirect

**Test results:**
- PASSED: 18
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-quarkus-examples/698/testReport/org.kie.kogito.examples/CloudEventListenerTest/___/">org.kie.kogito.examples.CloudEventListenerTest.(?)</a></summary>
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for org.kie.kogito.examples:dmn-knative-quickstart-quarkus::jar:2.0.0-SNAPSHOTnull<br/>	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:625)<br/>	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:680)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:128)<br/>	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptBeforeAllMethod(TimeoutExtension.java:70)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)<br/>	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)<br/>	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllMethods$13(ClassBasedTestDescriptor.java:411)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllMethods(ClassBasedTestDescriptor.java:409)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:215)<br/>	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)<br/>	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)<br/>	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)<br/>	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)<br/>	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)<br/>	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)<br/>	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)<br/>	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)<br/>	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)<br/>	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)<br/>	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)<br/>	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)<br/>	Suppressed: java.lang.NullPointerException<br/>		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:904)<br/>		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:896)<br/>		at io.quarkus.test.junit.QuarkusTestExtension.interceptA [...]

2023-04-13 14:33 UTC, fjtirado commented
jenkins run kogito-apps tests

2023-04-13 18:32 UTC, merged