Updating references to the new kie-ci actions folder.
kiegroup/kogito-runtimes pull request #2965
Opened 2023-05-02 13:44 UTC by bacciotti

Related PR:
- https://github.com/kiegroup/kie-ci/pull/1495

2023-05-03 12:03 UTC, lampajr requested changes
@bacciotti  Meanwhile we decide if we want to keep `dsl-tests` action on `kogito-pipelines` or move it in `kie-ci`, in both cases the main and branch config file repo is still `kogito-pipelines` as this would remain the repo containing DSL configuration.

The same applies to all other repos that use dsl-tests as well

2023-05-03 12:03 UTC, lampajr commented on .github/workflows/pr-jenkins.yml
> +        main-config-file-repo: kiegroup/kie-ci
```suggestion
        main-config-file-repo: kiegroup/kogito-pipelines
```

2023-05-03 12:03 UTC, lampajr commented on .github/workflows/pr-jenkins.yml
> +        branch-config-file-repo: kiegroup/kie-ci
```suggestion
        branch-config-file-repo: kiegroup/kogito-pipelines
```

2023-05-24 06:45 UTC, lampajr approved these changes

2023-05-30 12:35 UTC, Ginxo approved these changes
LGTM

2023-05-31 08:29 UTC, merged