[BXMSPROD-2055] include jobs in prod profile
kiegroup/kogito-runtimes pull request #3003
Opened 2023-05-23 09:14 UTC by lampajr

Many thanks for submitting your Pull Request :heart:! 

**JIRA:** https://issues.redhat.com/browse/BXMSPROD-2055

**Referenced Pull Requests:**

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
 
- <b>Full Kogito testing</b> (with cloud images and operator BDD testing)  
  Please add comment: <b>Jenkins run BDD</b>  
  <b>This check should be used only if a big change is done as it takes time to run, need resources and one full BDD tests check can be done at a time ...</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

<details>
<summary>
Quarkus-3 PR check is failing ... what to do ?
</summary>
The Quarkus 3 check is applying patches from the `.ci/environments/quarkus-3/patches`.

The first patch, called `0001_before_sh.patch`, is generated from Openrewrite `.ci/environments/quarkus-3/quarkus3.yml` recipe. The patch is created to speed up the check. But it may be that some changes in the PR broke this patch.  
No panic, there is an easy way to regenerate it. You just need to comment on the PR:
```
jenkins rewrite quarkus-3
```
and it should, after some minutes (~20/30min) apply a commit on the PR with the patch regenerated.

Other patches were generated manually. If any of it fails, you will need to manually update it... and push your changes.
</details>

2023-05-23 09:27 UTC, radtriste commented
jenkins run quarkus-lts

2023-05-23 09:28 UTC, radtriste requested changes

2023-05-23 09:28 UTC, radtriste commented on addons/common/pom.xml
> +    <module>jobs</module>
please remove from default profile as well

2023-05-23 09:30 UTC, lampajr commented on addons/common/pom.xml
> +    <module>jobs</module>
good catch

2023-05-23 09:32 UTC, lampajr commented
jenkins run quarkus-lts

2023-05-23 09:48 UTC, kie-ci3 commented
**(tests) - kogito-runtimes job** `#2559` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT=-T 1C -Dvalidate-formatting -Prun-code-coverage
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-runtimes -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/2559/display/redirect

**Test results:**
- PASSED: 3330
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.kogito-runtimes/2559/testReport/org.kie.kogito.quarkus.it.openapi.client/ApiWithSecurityContextIT/verifyAuthHeadersOpenApi2_0/">org.kie.kogito.quarkus.it.openapi.client.ApiWithSecurityContextIT.verifyAuthHeadersOpenApi2_0</a></summary>
java.lang.RuntimeException: <br/>java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/>	[error]: Build step io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor#setupKubernetesDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.setupKubernetesDevService(DevServicesKubernetesProcessor.java:119)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/>	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/>	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/>	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/>	at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.lambda$startKubernetes$7(DevServicesKubernetesProcessor.java:227)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.startKubernetes(DevServicesKubernetesProcessor.java:241)<br/>	at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.setupKubernetesDevService(DevServicesKubernetesProcessor.java:109)<br/>	... 11 more<br/>Caused by: org.rnorth.ducttape.RetryCountExceededException: Retry limit hit with exception<br/>	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:88)<br/>	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:334)<br/>	... 16 more<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container<br/>	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:542)<br/>	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:344)<br/>	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)<br/>	... 17 more<br/>Caused by: org.testcontainers.shaded.org.awaitility.core.ConditionTimeoutException: Lambda expression in com.dajudge.kindcontainer.ApiServerContainer: expected the predicate to return <true> but it returned <false> for input of <Optional.empty> within 10 seconds.<br/>	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:167)<br/>	at org.testcontainers.shaded.org.awaitility.core.AbstractHamcrestCondition.await(AbstractHamcrestCondition.java:86)<br/>	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:985)<br/>	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:691)<br/>	at org.testcontainers.shaded.org.awaitility.core.ConditionFactory.until(ConditionFactory.java:708)<br/>	at com.dajudge.kindcontainer.ApiServerContainer.waitForDefaultNamespace(ApiServerContainer.java:150)<br/>	at com.dajudge.kindcontainer.ApiServerContainer.containerIsStarting(ApiServerContainer.java:144)<br/>	at org.testcontainers.containers.GenericContainer.containerIsStarting(GenericContainer.java:692)<br/>	at com.dajudge.kindcontainer.KubernetesContainer.containerIsStarting(KubernetesContainer.java:151)<br/>	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:474)<br/>	... 19 more<br/>Caused by: java.util.concurrent.TimeoutException<br/>	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)<br/>	at org.testcontainers.shaded.org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:101)<br/>	at org.testcontainers.shaded.org.awaitility.core.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:81)<br/>	at org.testcontainers.shaded.org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:103)<br/>	... 28 more<br/><br/>Caused by: java.lang.RuntimeException: <br/>io.quarkus.builder.BuildException: Build failure: Build failed due to errors<br/>	[error]: Build step io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor#setupKubernetesDevService threw an exception: java.lang.RuntimeException: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.setupKubernetesDevService(DevServicesKubernetesProcessor.java:119)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br/>	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br/>	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br/>	at java.base/java.lang.reflect.Method.invoke(Method.java:566)<br/>	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)<br/>	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)<br/>	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)<br/>	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)<br/>	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)<br/>	at java.base/java.lang.Thread.run(Thread.java:829)<br/>	at org.jboss.threads.JBossThread.run(JBossThread.java:501)<br/>Caused by: org.testcontainers.containers.ContainerLaunchException: Container startup failed<br/>	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:349)<br/>	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)<br/>	at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.lambda$startKubernetes$7(DevServicesKubernetesProcessor.java:227)<br/>	at java.base/java.util.Optional.orElseGet(Optional.java:369)<br/>	at io.quarkus.kubernetes.client.deployment.De [...]

2023-05-23 09:49 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-springboot-examples job** `#56` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-springboot-examples/56/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T09:48:54.778Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-embedded ---<br/>[2023-05-23T09:48:54.778Z] [INFO] <br/>[2023-05-23T09:48:54.778Z] [INFO] --< org.kie.kogito.examples:serverless-workflow-timeouts-showcase-extended >--<br/>[2023-05-23T09:48:54.778Z] [INFO] Building Kogito Example :: Serverless Workflow Timeouts Showcase Extended 1.0-SNAPSHOT [59/61]<br/>[2023-05-23T09:48:54.778Z] [INFO] --------------------------------[ jar ]---------------------------------<br/>[2023-05-23T09:48:54.778Z] [INFO] <br/>[2023-05-23T09:48:54.778Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-extended ---<br/>[2023-05-23T09:48:54.778Z] [INFO] <br/>[2023-05-23T09:48:54.778Z] [INFO] --------------< org.kie.kogito.examples:kogito-examples >---------------<br/>[2023-05-23T09:48:54.778Z] [INFO] Building Kogito Example 2.0.0-SNAPSHOT                           [60/61]<br/>[2023-05-23T09:48:54.778Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T09:48:54.778Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T09:48:54.778Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T09:48:54.778Z] [WARNING] The artifact org.codehaus.mojo:sonar-maven-plugin:jar:3.6.1.1688 has been relocated to org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.6.1.1688: SonarQube plugin was moved to SonarSource organisation<br/>[2023-05-23T09:48:54.778Z] [INFO] <br/>[2023-05-23T09:48:54.778Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ kogito-examples ---<br/>[2023-05-23T09:48:55.032Z] [INFO] <br/>[2023-05-23T09:48:55.032Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2023-05-23T09:48:55.032Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [61/61]<br/>[2023-05-23T09:48:55.032Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T09:48:55.032Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T09:48:55.032Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T09:48:55.032Z] [INFO] <br/>[2023-05-23T09:48:55.032Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ serverless-workflow-examples ---<br/>[2023-05-23T09:48:55.032Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-23T09:48:55.032Z] [INFO] Reactor Summary:<br/>[2023-05-23T09:48:55.032Z] [INFO] <br/>[2023-05-23T09:48:55.032Z] [INFO] Kogito Example :: Serverless Workflow Annotations and Description:: Quarkus 1.0-SNAPSHOT SUCCESS [  0.531 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.139 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Callback Event Service 1.0-SNAPSHOT SUCCESS [  0.048 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Service 1.0-SNAPSHOT SUCCESS [  0.025 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Callback :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.018 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Compensation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.017 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Consuming Events Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.017 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Correlation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.023 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Custom Function :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Service 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Workflow 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.006 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 1.0-SNAPSHOT SUCCESS [  0.936 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 1.0-SNAPSHOT SUCCESS [  0.008 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Data Index :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.010 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.011 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPSHOT SUCCESS [  0.003 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Services 1.0-SNAPSHOT SUCCESS [  0.011 s]<br/>[2023-05-23T09:48:55.033Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Workflow 1.0-SNAPSHOT SUCCESS [  0. [...]

2023-05-23 09:49 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-quarkus-examples job** `#55` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-quarkus-examples/55/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T09:48:54.646Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-embedded ---<br/>[2023-05-23T09:48:54.646Z] [INFO] <br/>[2023-05-23T09:48:54.646Z] [INFO] --< org.kie.kogito.examples:serverless-workflow-timeouts-showcase-extended >--<br/>[2023-05-23T09:48:54.647Z] [INFO] Building Kogito Example :: Serverless Workflow Timeouts Showcase Extended 1.0-SNAPSHOT [59/61]<br/>[2023-05-23T09:48:54.647Z] [INFO] --------------------------------[ jar ]---------------------------------<br/>[2023-05-23T09:48:54.647Z] [INFO] <br/>[2023-05-23T09:48:54.647Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-extended ---<br/>[2023-05-23T09:48:54.647Z] [INFO] <br/>[2023-05-23T09:48:54.647Z] [INFO] --------------< org.kie.kogito.examples:kogito-examples >---------------<br/>[2023-05-23T09:48:54.647Z] [INFO] Building Kogito Example 2.0.0-SNAPSHOT                           [60/61]<br/>[2023-05-23T09:48:54.647Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T09:48:54.902Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T09:48:54.902Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T09:48:54.902Z] [WARNING] The artifact org.codehaus.mojo:sonar-maven-plugin:jar:3.6.1.1688 has been relocated to org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.6.1.1688: SonarQube plugin was moved to SonarSource organisation<br/>[2023-05-23T09:48:54.902Z] [INFO] <br/>[2023-05-23T09:48:54.902Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ kogito-examples ---<br/>[2023-05-23T09:48:55.157Z] [INFO] <br/>[2023-05-23T09:48:55.157Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2023-05-23T09:48:55.157Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [61/61]<br/>[2023-05-23T09:48:55.157Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T09:48:55.157Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T09:48:55.157Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T09:48:55.157Z] [INFO] <br/>[2023-05-23T09:48:55.157Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ serverless-workflow-examples ---<br/>[2023-05-23T09:48:55.157Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-23T09:48:55.157Z] [INFO] Reactor Summary:<br/>[2023-05-23T09:48:55.157Z] [INFO] <br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Annotations and Description:: Quarkus 1.0-SNAPSHOT SUCCESS [  0.481 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.147 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Callback Event Service 1.0-SNAPSHOT SUCCESS [  0.058 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Service 1.0-SNAPSHOT SUCCESS [  0.023 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Callback :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.022 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Compensation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.019 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Consuming Events Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.022 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Correlation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.026 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Custom Function :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Service 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Workflow 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 1.0-SNAPSHOT SUCCESS [  0.842 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 1.0-SNAPSHOT SUCCESS [  0.006 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.012 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Data Index :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.012 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.012 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.010 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.011 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Services 1.0-SNAPSHOT SUCCESS [  0.017 s]<br/>[2023-05-23T09:48:55.157Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Workflow 1.0-SNAPSHOT SUCCESS [  0.012 s] [...]

2023-05-23 09:53 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-runtimes job** `#61` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT=-T 1C 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-runtimes -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.kogito-runtimes/61/display/redirect

**Test results:**
- PASSED: 2260
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:55,928 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-7) [Consumer clientId=kafka-consumer-callback_state_event_type, groupId=kogito-sw-it] Connection to node 0 (localhost/127.0.0.1:32894) could not be established. Broker may not be available.<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:55,928 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-3) [Consumer clientId=kafka-consumer-correlation_event_type, groupId=kogito-sw-it] Connection to node 0 (localhost/127.0.0.1:32894) could not be established. Broker may not be available.<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:55,928 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-kogito_outgoing_stream) [Producer clientId=kafka-producer-kogito_outgoing_stream] Connection to node 0 (localhost/127.0.0.1:32894) could not be established. Broker may not be available.<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:55,929 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-1) [Consumer clientId=kafka-consumer-visa_denied_in_transition2, groupId=kogito-quarkus-serverless-workflow-integration-test] Connection to node 0 (localhost/127.0.0.1:32894) could not be established. Broker may not be available.<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:55,929 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-wait_out) [Producer clientId=kafka-producer-wait_out] Connection to node 0 (localhost/127.0.0.1:32894) could not be established. Broker may not be available.<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:55,930 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-kogito-usertaskinstances-events) [Producer clientId=kafka-producer-kogito-usertaskinstances-events] Connection to node 0 (localhost/127.0.0.1:32894) could not be established. Broker may not be available.<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,001 INFO  [org.ecl.jet.ser.AbstractConnector] (main) Stopped NetworkTrafficServerConnector@7f0f8258{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,001 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@32688a54{/,null,STOPPED}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,002 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@5526ca37{/__admin,null,STOPPED}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,003 INFO  [org.ecl.jet.ser.AbstractConnector] (main) Stopped NetworkTrafficServerConnector@673e5ae4{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,003 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@42c3ff27{/,null,STOPPED}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,003 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@f622120{/__admin,null,STOPPED}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,004 INFO  [org.ecl.jet.ser.AbstractConnector] (main) Stopped NetworkTrafficServerConnector@e87dd35{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,004 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@1edfad9b{/,null,STOPPED}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,004 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@13d220ab{/__admin,null,STOPPED}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,006 INFO  [org.ecl.jet.ser.AbstractConnector] (main) Stopped NetworkTrafficServerConnector@771e5fc5{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,006 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@586db357{/,null,STOPPED}<br/>[2023-05-23T09:53:01.216Z] 2023-05-23 05:52:56,006 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@75ec1841{/__admin,null,STOPPED}<br/>[2023-05-23T09:53:01.775Z] [INFO] <br/>[2023-05-23T09:53:01.775Z] [INFO] Results:<br/>[2023-05-23T09:53:01.775Z] [INFO] <br/>[2023-05-23T09:53:01.775Z] [INFO] Tests run: 72, Failures: 0, Errors: 0, Skipped: 0<br/>[2023-05-23T09:53:01.775Z] [INFO] <br/>[2023-05-23T09:53:01.775Z] [INFO] <br/>[2023-05-23T09:53:01.775Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ kogito-quarkus-serverless-workflow-integration-test ---<br/>[2023-05-23T09:53:01.776Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/target/failsafe-reports<br/>[2023-05-23T09:53:01.776Z] [INFO] <br/>[2023-05-23T09:53:01.776Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ kogito-quarkus-serverless-workflow-integration-test ---<br/>[2023-05-23T09:53:01.776Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/target/kogito-quarkus-serverless-workflow-integration-test-2.0.0-SNAPSHOT.jar to /home/jenkins/.m2/repository/org/kie/kogito/kogito-quarkus-serverless-workflow-integration-test/2.0.0-SNAPSHOT/kogito-quarkus-serverless-workflow-integration-test-2.0.0-SNAPSHOT.jar<br/>[2023-05-23T09:53:01.776Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml to /home/jenkins/.m2/repository/org/kie/kogito/kogito-quarkus-serverless-workflow-integration-test/2.0.0-SNAPSHOT/kogito-quarkus-serverless-workflow-integration-test-2.0.0-SNAPSHOT.pom<br/>[2023-05-23T09:53:01.776Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/target/kogito-quarkus-serverless-workflow-integration-test-2.0.0-SNAPSHOT-tests.jar to /home/jenkins/.m2/repository/org/kie/kogito/kogito-quarkus-serverless-workflow-integration-test/2.0.0-SNAPSHOT/kogito-quarkus-serverless-workflow-integration-test-2.0.0-SNAPSHOT-tests.jar<br/>[2023-05-23T09:53:01.776Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/target/kogito-quarku [...]

2023-05-23 09:53 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-springboot-examples job** `#57` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-springboot-examples/57/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T09:53:04.931Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-embedded ---<br/>[2023-05-23T09:53:04.931Z] [INFO] <br/>[2023-05-23T09:53:04.931Z] [INFO] --< org.kie.kogito.examples:serverless-workflow-timeouts-showcase-extended >--<br/>[2023-05-23T09:53:04.931Z] [INFO] Building Kogito Example :: Serverless Workflow Timeouts Showcase Extended 1.0-SNAPSHOT [59/61]<br/>[2023-05-23T09:53:04.931Z] [INFO] --------------------------------[ jar ]---------------------------------<br/>[2023-05-23T09:53:04.931Z] [INFO] <br/>[2023-05-23T09:53:04.931Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-extended ---<br/>[2023-05-23T09:53:04.931Z] [INFO] <br/>[2023-05-23T09:53:04.931Z] [INFO] --------------< org.kie.kogito.examples:kogito-examples >---------------<br/>[2023-05-23T09:53:04.931Z] [INFO] Building Kogito Example 2.0.0-SNAPSHOT                           [60/61]<br/>[2023-05-23T09:53:04.931Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T09:53:05.186Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T09:53:05.186Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T09:53:05.186Z] [WARNING] The artifact org.codehaus.mojo:sonar-maven-plugin:jar:3.6.1.1688 has been relocated to org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.6.1.1688: SonarQube plugin was moved to SonarSource organisation<br/>[2023-05-23T09:53:05.186Z] [INFO] <br/>[2023-05-23T09:53:05.186Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ kogito-examples ---<br/>[2023-05-23T09:53:05.441Z] [INFO] <br/>[2023-05-23T09:53:05.441Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2023-05-23T09:53:05.441Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [61/61]<br/>[2023-05-23T09:53:05.441Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T09:53:05.441Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T09:53:05.441Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T09:53:05.441Z] [INFO] <br/>[2023-05-23T09:53:05.441Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ serverless-workflow-examples ---<br/>[2023-05-23T09:53:05.441Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-23T09:53:05.441Z] [INFO] Reactor Summary:<br/>[2023-05-23T09:53:05.441Z] [INFO] <br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Annotations and Description:: Quarkus 1.0-SNAPSHOT SUCCESS [  0.473 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.131 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Callback Event Service 1.0-SNAPSHOT SUCCESS [  0.047 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Service 1.0-SNAPSHOT SUCCESS [  0.023 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Callback :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.017 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Compensation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.020 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Consuming Events Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.019 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Correlation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.024 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Custom Function :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Service 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Workflow 1.0-SNAPSHOT SUCCESS [  0.017 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 1.0-SNAPSHOT SUCCESS [  0.587 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 1.0-SNAPSHOT SUCCESS [  0.007 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Data Index :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.052 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.015 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.011 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.010 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Services 1.0-SNAPSHOT SUCCESS [  0.011 s]<br/>[2023-05-23T09:53:05.441Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Workflow 1.0-SNAPSHOT SUCCESS [  0. [...]

2023-05-23 09:54 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-quarkus-examples job** `#56` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-quarkus-examples/56/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T09:54:33.130Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-embedded ---<br/>[2023-05-23T09:54:33.130Z] [INFO] <br/>[2023-05-23T09:54:33.130Z] [INFO] --< org.kie.kogito.examples:serverless-workflow-timeouts-showcase-extended >--<br/>[2023-05-23T09:54:33.130Z] [INFO] Building Kogito Example :: Serverless Workflow Timeouts Showcase Extended 1.0-SNAPSHOT [59/61]<br/>[2023-05-23T09:54:33.130Z] [INFO] --------------------------------[ jar ]---------------------------------<br/>[2023-05-23T09:54:33.130Z] [INFO] <br/>[2023-05-23T09:54:33.130Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-extended ---<br/>[2023-05-23T09:54:33.130Z] [INFO] <br/>[2023-05-23T09:54:33.130Z] [INFO] --------------< org.kie.kogito.examples:kogito-examples >---------------<br/>[2023-05-23T09:54:33.130Z] [INFO] Building Kogito Example 2.0.0-SNAPSHOT                           [60/61]<br/>[2023-05-23T09:54:33.130Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T09:54:33.130Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T09:54:33.130Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T09:54:33.130Z] [WARNING] The artifact org.codehaus.mojo:sonar-maven-plugin:jar:3.6.1.1688 has been relocated to org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.6.1.1688: SonarQube plugin was moved to SonarSource organisation<br/>[2023-05-23T09:54:33.130Z] [INFO] <br/>[2023-05-23T09:54:33.130Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ kogito-examples ---<br/>[2023-05-23T09:54:33.385Z] [INFO] <br/>[2023-05-23T09:54:33.385Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2023-05-23T09:54:33.385Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [61/61]<br/>[2023-05-23T09:54:33.385Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T09:54:33.385Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T09:54:33.385Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T09:54:33.385Z] [INFO] <br/>[2023-05-23T09:54:33.385Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ serverless-workflow-examples ---<br/>[2023-05-23T09:54:33.385Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-23T09:54:33.385Z] [INFO] Reactor Summary:<br/>[2023-05-23T09:54:33.385Z] [INFO] <br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Annotations and Description:: Quarkus 1.0-SNAPSHOT SUCCESS [  0.519 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.156 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Callback Event Service 1.0-SNAPSHOT SUCCESS [  0.056 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Service 1.0-SNAPSHOT SUCCESS [  0.055 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Callback :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.025 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Compensation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.020 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Consuming Events Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.020 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Correlation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.024 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Custom Function :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Service 1.0-SNAPSHOT SUCCESS [  0.017 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Workflow 1.0-SNAPSHOT SUCCESS [  0.018 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.006 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 1.0-SNAPSHOT SUCCESS [  0.567 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 1.0-SNAPSHOT SUCCESS [  0.007 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Data Index :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.017 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.011 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.010 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPSHOT SUCCESS [  0.003 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Services 1.0-SNAPSHOT SUCCESS [  0.011 s]<br/>[2023-05-23T09:54:33.385Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Workflow 1.0-SNAPSHOT SUCCESS [  0.011 s] [...]

2023-05-23 09:59 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-runtimes job** `#62` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT=-T 1C 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-runtimes -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.kogito-runtimes/62/display/redirect

**Test results:**
- PASSED: 2260
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,996 INFO  [org.ecl.jet.ser.AbstractConnector] (main) Stopped NetworkTrafficServerConnector@13419cfb{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0}<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,996 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@70401e5b{/,null,STOPPED}<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,996 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@2f55dc29{/__admin,null,STOPPED}<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,997 INFO  [org.ecl.jet.ser.AbstractConnector] (main) Stopped NetworkTrafficServerConnector@4248980b{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0}<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,997 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@3e5fb35e{/,null,STOPPED}<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,997 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-5) [Consumer clientId=kafka-consumer-visa_denied_in_condition_end, groupId=kogito-quarkus-serverless-workflow-integration-test] Connection to node 0 (localhost/127.0.0.1:32784) could not be established. Broker may not be available.<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,998 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@256c5f20{/__admin,null,STOPPED}<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,998 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-6) [Consumer clientId=kafka-consumer-visa_denied_in_transition2, groupId=kogito-quarkus-serverless-workflow-integration-test] Connection to node 0 (localhost/127.0.0.1:32784) could not be established. Broker may not be available.<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,998 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-7) [Consumer clientId=kafka-consumer-callback_state_event_type, groupId=kogito-sw-it] Connection to node 0 (localhost/127.0.0.1:32784) could not be established. Broker may not be available.<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,998 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-kogito_outgoing_stream) [Producer clientId=kafka-producer-kogito_outgoing_stream] Connection to node 0 (localhost/127.0.0.1:32784) could not be established. Broker may not be available.<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,998 WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-producer-kogito-usertaskinstances-events) [Producer clientId=kafka-producer-kogito-usertaskinstances-events] Connection to node 0 (localhost/127.0.0.1:32784) could not be established. Broker may not be available.<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,999 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-visa_approved_in_condition_end, groupId=kogito-quarkus-serverless-workflow-integration-test] Connection to node 0 (localhost/127.0.0.1:32784) could not be established. Broker may not be available.<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:45,999 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-8) [Consumer clientId=kafka-consumer-correlation_event_type, groupId=kogito-sw-it] Connection to node 0 (localhost/127.0.0.1:32784) could not be established. Broker may not be available.<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:46,000 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-9) [Consumer clientId=kafka-consumer-visa_approved_in_transition, groupId=kogito-quarkus-serverless-workflow-integration-test] Connection to node 0 (localhost/127.0.0.1:32784) could not be established. Broker may not be available.<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:46,000 WARN  [org.apa.kaf.cli.NetworkClient] (smallrye-kafka-consumer-thread-4) [Consumer clientId=kafka-consumer-callback_state_timeouts_event_type, groupId=kogito-sw-it] Connection to node 0 (localhost/127.0.0.1:32784) could not be established. Broker may not be available.<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:46,000 INFO  [org.ecl.jet.ser.AbstractConnector] (main) Stopped NetworkTrafficServerConnector@368f027e{HTTP/1.1, (http/1.1, h2c)}{0.0.0.0:0}<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:46,001 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@46a79fdb{/,null,STOPPED}<br/>[2023-05-23T09:58:52.088Z] 2023-05-23 05:58:46,001 INFO  [org.ecl.jet.ser.han.ContextHandler] (main) Stopped o.e.j.s.ServletContextHandler@195bf3ff{/__admin,null,STOPPED}<br/>[2023-05-23T09:58:52.352Z] [INFO] <br/>[2023-05-23T09:58:52.352Z] [INFO] Results:<br/>[2023-05-23T09:58:52.352Z] [INFO] <br/>[2023-05-23T09:58:52.352Z] [INFO] Tests run: 72, Failures: 0, Errors: 0, Skipped: 0<br/>[2023-05-23T09:58:52.352Z] [INFO] <br/>[2023-05-23T09:58:52.608Z] [INFO] <br/>[2023-05-23T09:58:52.608Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ kogito-quarkus-serverless-workflow-integration-test ---<br/>[2023-05-23T09:58:52.608Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/target/failsafe-reports<br/>[2023-05-23T09:58:52.608Z] [INFO] <br/>[2023-05-23T09:58:52.608Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ kogito-quarkus-serverless-workflow-integration-test ---<br/>[2023-05-23T09:58:52.608Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/target/kogito-quarkus-serverless-workflow-integration-test-2.0.0-SNAPSHOT.jar to /home/jenkins/.m2/repository/org/kie/kogito/kogito-quarkus-serverless-workflow-integration-test/2.0.0-SNAPSHOT/kogito-quarkus-serverless-workflow-integration-test-2.0.0-SNAPSHOT.jar<br/>[2023-05-23T09:58:52.608Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/pom.xml to /home/jenkins/.m2/repository/org/kie/kogito/kogito-quarkus-serverless-workflow-integration-test/2.0.0-SNAPSHOT/kogito-quarkus-serverless-workflow-integration-test-2.0.0-SNAPSHOT.pom<br/>[2023-05-23T09:58:52.608Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/extensions/kogito-quarkus-serverless-workflow-extension/kogito-quarkus-serverless-workflow-integration-test/target/kogito-quarkus-serverl [...]

2023-05-23 10:01 UTC, kie-ci3 commented
**(quarkus-lts) - serverless-workflow-examples job** `#54` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.serverless-workflow-examples/54/display/redirect

**Test results:**
- PASSED: 59
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T10:01:50.980Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-23T10:01:50.980Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-23T10:01:50.980Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-23T10:01:50.980Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-23T10:01:50.980Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-23T10:01:50.980Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-23T10:01:50.980Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-23T10:01:50.980Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-23T10:01:50.980Z] Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to inject extension deployment dependencies for org.kie.kogito.examples:serverless-workflow-order-processing:1.0-SNAPSHOT<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.buildAppModel (BootstrapAppModelResolver.java:324)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel (BootstrapAppModelResolver.java:286)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel (BootstrapAppModelResolver.java:165)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.maven.QuarkusBootstrapProvider$QuarkusMavenAppBootstrap.doBootstrap (QuarkusBootstrapProvider.java:243)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.maven.QuarkusBootstrapProvider$QuarkusMavenAppBootstrap.bootstrapApplication (QuarkusBootstrapProvider.java:294)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.maven.QuarkusBootstrapProvider.bootstrapApplication (QuarkusBootstrapProvider.java:100)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.maven.QuarkusBootstrapMojo.bootstrapApplication (QuarkusBootstrapMojo.java:272)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.maven.QuarkusBootstrapMojo.bootstrapApplication (QuarkusBootstrapMojo.java:268)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.maven.BuildMojo.doExecute (BuildMojo.java:131)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.maven.QuarkusBootstrapMojo.execute (QuarkusBootstrapMojo.java:154)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-23T10:01:50.980Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-23T10:01:50.980Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-23T10:01:50.980Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-23T10:01:50.980Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-23T10:01:50.980Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-23T10:01:50.980Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-23T10:01:50.980Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-23T10:01:50.980Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-23T10:01:50.980Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-23T10:01:50.980Z] Caused by: io.quarkus.bootstrap.BootstrapDependencyProcessingException: Failed to collect dependencies of org.kie.kogito:kogito-addons-quarkus-knative-eventing-deployment:jar:2.0.0-SNAPSHOT: either its POM could not be resolved from the available Maven repositories or the artifact does not have any dependencies while at least a dependency on the runtime artifact org.kie.kogito:kogito-addons-quarkus-knative-eventing:jar:2.0.0-SNAPSHOT is expected<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.injectDeploymentDependencies (ApplicationDependencyTreeResolver.java:496)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.resolve (ApplicationDependencyTreeResolver.java:197)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.buildAppModel (BootstrapAppModelResolver.java:321)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel (BootstrapAppModelResolver.java:286)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel (BootstrapAppModelResolver.java:165)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.maven.QuarkusBootstrapProvider$QuarkusMavenAppBootstrap.doBootstrap (QuarkusBootstrapProvider.java:243)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.maven.QuarkusBootstrapProvider$QuarkusMavenAppBootstrap.bootstrapApplication (QuarkusBootstrapProvider.java:294)<br/>[2023-05-23T10:01:50.980Z]     at io.quarkus.mav [...]

2023-05-23 10:06 UTC, kie-ci3 commented
**(quarkus-lts) - serverless-workflow-examples job** `#55` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.serverless-workflow-examples/55/display/redirect

**Test results:**
- PASSED: 59
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T10:06:15.553Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-23T10:06:15.553Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-23T10:06:15.553Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-23T10:06:15.553Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-23T10:06:15.553Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-23T10:06:15.553Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-23T10:06:15.553Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-23T10:06:15.553Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-23T10:06:15.553Z] Caused by: io.quarkus.bootstrap.resolver.AppModelResolverException: Failed to inject extension deployment dependencies for org.kie.kogito.examples:serverless-workflow-order-processing:1.0-SNAPSHOT<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.buildAppModel (BootstrapAppModelResolver.java:324)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel (BootstrapAppModelResolver.java:286)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel (BootstrapAppModelResolver.java:165)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.maven.QuarkusBootstrapProvider$QuarkusMavenAppBootstrap.doBootstrap (QuarkusBootstrapProvider.java:243)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.maven.QuarkusBootstrapProvider$QuarkusMavenAppBootstrap.bootstrapApplication (QuarkusBootstrapProvider.java:294)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.maven.QuarkusBootstrapProvider.bootstrapApplication (QuarkusBootstrapProvider.java:100)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.maven.QuarkusBootstrapMojo.bootstrapApplication (QuarkusBootstrapMojo.java:272)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.maven.QuarkusBootstrapMojo.bootstrapApplication (QuarkusBootstrapMojo.java:268)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.maven.BuildMojo.doExecute (BuildMojo.java:131)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.maven.QuarkusBootstrapMojo.execute (QuarkusBootstrapMojo.java:154)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)<br/>[2023-05-23T10:06:15.553Z]     at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)<br/>[2023-05-23T10:06:15.553Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)<br/>[2023-05-23T10:06:15.553Z]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)<br/>[2023-05-23T10:06:15.553Z]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)<br/>[2023-05-23T10:06:15.553Z]     at java.lang.reflect.Method.invoke (Method.java:566)<br/>[2023-05-23T10:06:15.553Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)<br/>[2023-05-23T10:06:15.553Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)<br/>[2023-05-23T10:06:15.553Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)<br/>[2023-05-23T10:06:15.553Z]     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)<br/>[2023-05-23T10:06:15.553Z] Caused by: io.quarkus.bootstrap.BootstrapDependencyProcessingException: Failed to collect dependencies of org.kie.kogito:kogito-addons-quarkus-knative-eventing-deployment:jar:2.0.0-SNAPSHOT: either its POM could not be resolved from the available Maven repositories or the artifact does not have any dependencies while at least a dependency on the runtime artifact org.kie.kogito:kogito-addons-quarkus-knative-eventing:jar:2.0.0-SNAPSHOT is expected<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.injectDeploymentDependencies (ApplicationDependencyTreeResolver.java:496)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.bootstrap.resolver.maven.ApplicationDependencyTreeResolver.resolve (ApplicationDependencyTreeResolver.java:197)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.buildAppModel (BootstrapAppModelResolver.java:321)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.doResolveModel (BootstrapAppModelResolver.java:286)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.bootstrap.resolver.BootstrapAppModelResolver.resolveManagedModel (BootstrapAppModelResolver.java:165)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.maven.QuarkusBootstrapProvider$QuarkusMavenAppBootstrap.doBootstrap (QuarkusBootstrapProvider.java:243)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.maven.QuarkusBootstrapProvider$QuarkusMavenAppBootstrap.bootstrapApplication (QuarkusBootstrapProvider.java:294)<br/>[2023-05-23T10:06:15.553Z]     at io.quarkus.mav [...]

2023-05-23 10:11 UTC, lampajr commented
Looks like `quarkus-lts` tests are failing at:
```
[2023-05-23T09:58:52.610Z] [INFO] Kogito Add-On Knative Eventing - Deployment ........ FAILURE [  1.812 s]
```
with this error:
```
[2023-05-23T09:58:52.610Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kogito-addons-quarkus-knative-eventing-deployment: Compilation failure
[2023-05-23T09:58:52.610Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/addons/knative/eventing/deployment/src/main/java/org/kie/kogito/addons/quarkus/knative/eventing/deployment/KogitoAddOnKnativeEventingProcessor.java:[127,54] incompatible types: java.lang.String cannot be converted to org.jboss.jandex.DotName
[2023-05-23T09:58:52.610Z] [ERROR] -> [Help 1]
[2023-05-23T09:58:52.610Z] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kogito-addons-quarkus-knative-eventing-deployment: Compilation failure
[2023-05-23T09:58:52.610Z] /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.kogito-runtimes/bc/kiegroup_kogito-runtimes/quarkus/addons/knative/eventing/deployment/src/main/java/org/kie/kogito/addons/quarkus/knative/eventing/deployment/KogitoAddOnKnativeEventingProcessor.java:[127,54] incompatible types: java.lang.String cannot be converted to org.jboss.jandex.DotName
```

2023-05-23 10:13 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-apps job** `#56` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-apps/56/display/redirect

**Test results:**
- PASSED: 520
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-apps/56/testReport/org.kie.kogito.jobs.service.resource/JobServiceManagementResourceIT/testShutdown/">org.kie.kogito.jobs.service.resource.JobServiceManagementResourceIT.testShutdown</a></summary>
java.lang.RuntimeException: An unexpected situation occurred while trying to instantiate the testing infrastructure. Have you perhaps mixed @QuarkusTest and @QuarkusIntegrationTest in the same test run?<br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T10:13:40.770Z] [INFO] |     +- io.quarkus:quarkus-transaction-annotations:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |     +- io.smallrye:smallrye-context-propagation-jta:jar:1.2.2:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |     +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |     +- io.smallrye.reactive:smallrye-reactive-converter-api:jar:2.7.0:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |     +- io.smallrye.reactive:smallrye-reactive-converter-mutiny:jar:2.7.0:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |     +- org.jboss.narayana.jta:narayana-jta:jar:5.13.1.Final:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |     |  \- org.jboss.spec.javax.resource:jboss-connector-api_1.7_spec:jar:1.0.0.Final:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |     \- org.jboss.narayana.jts:narayana-jts-integration:jar:5.13.1.Final:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] +- io.quarkus:quarkus-jdbc-postgresql-deployment:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |  \- io.quarkus:quarkus-jdbc-postgresql:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] +- io.quarkus:quarkus-junit5-internal:jar:999-SNAPSHOT:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  +- org.jboss.shrinkwrap:shrinkwrap-depchain:pom:1.2.6:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  +- org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  +- org.jboss.shrinkwrap:shrinkwrap-spi:jar:1.2.6:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  \- org.jboss.shrinkwrap:shrinkwrap-impl-base:jar:1.2.6:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.9.1:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.1:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.1:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  +- org.junit.jupiter:junit-jupiter-engine:jar:5.9.1:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  \- org.junit.platform:junit-platform-engine:jar:1.9.1:test<br/>[2023-05-23T10:13:40.770Z] [INFO] |  +- io.quarkus:quarkus-core:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.3:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.3:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.1:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.1:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-classloader:jar:1.13.1:compile<br/>[2023-05-23T10:13:40.770Z] [INFO] |  |  |     \- io.smallrye.config:smallrye-config-common:jar:2.12.3:compile<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2023-05-23T10:13:40.771Z] [INFO] |  +- io.quarkus:quarkus-test-common:jar:999-SNAPSHOT:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:999-SNAPSHOT:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.8.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.8.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.8.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  |  +- org.apache.maven:maven-artifact:jar:3.8.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:1.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.8.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.apache.maven:maven-model:jar:3.8.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.apache.maven:maven-model-builder:jar:3.8.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.apache.maven:maven-builder-support:jar:3.8.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.6.3:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.6.3:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.3.4:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.2:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  |  \- com.google.guava:guava:jar:31.1-jre:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  |     \- com.google.guava:failureaccess:jar:1.0.1:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-sec-dispatcher:jar:2.0:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-cipher:jar:2.0:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.6:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-interpolation:jar:1.26:test<br/>[2023-05-23T10:13:40.771Z] [INFO] |  |  |  +- org [...]

2023-05-23 10:17 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-apps job** `#57` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-apps/57/display/redirect

**Test results:**
- PASSED: 520
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-apps/57/testReport/org.kie.kogito.jobs.service.resource/JobServiceManagementResourceIT/testShutdown/">org.kie.kogito.jobs.service.resource.JobServiceManagementResourceIT.testShutdown</a></summary>
java.lang.RuntimeException: An unexpected situation occurred while trying to instantiate the testing infrastructure. Have you perhaps mixed @QuarkusTest and @QuarkusIntegrationTest in the same test run?<br/>
</details>

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T10:17:21.305Z] [INFO] |     +- io.quarkus:quarkus-transaction-annotations:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] |     +- io.smallrye:smallrye-context-propagation-jta:jar:1.2.2:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] |     +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] |     +- io.smallrye.reactive:smallrye-reactive-converter-api:jar:2.7.0:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] |     +- io.smallrye.reactive:smallrye-reactive-converter-mutiny:jar:2.7.0:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] |     +- org.jboss.narayana.jta:narayana-jta:jar:5.13.1.Final:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] |     |  \- org.jboss.spec.javax.resource:jboss-connector-api_1.7_spec:jar:1.0.0.Final:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] |     \- org.jboss.narayana.jts:narayana-jts-integration:jar:5.13.1.Final:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] +- io.quarkus:quarkus-jdbc-postgresql-deployment:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] |  \- io.quarkus:quarkus-jdbc-postgresql:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] +- io.quarkus:quarkus-junit5-internal:jar:999-SNAPSHOT:test<br/>[2023-05-23T10:17:21.305Z] [INFO] |  +- org.jboss.shrinkwrap:shrinkwrap-depchain:pom:1.2.6:test<br/>[2023-05-23T10:17:21.305Z] [INFO] |  |  +- org.jboss.shrinkwrap:shrinkwrap-api:jar:1.2.6:test<br/>[2023-05-23T10:17:21.305Z] [INFO] |  |  +- org.jboss.shrinkwrap:shrinkwrap-spi:jar:1.2.6:test<br/>[2023-05-23T10:17:21.305Z] [INFO] |  |  \- org.jboss.shrinkwrap:shrinkwrap-impl-base:jar:1.2.6:test<br/>[2023-05-23T10:17:21.305Z] [INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.9.1:test<br/>[2023-05-23T10:17:21.305Z] [INFO] |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test<br/>[2023-05-23T10:17:21.305Z] [INFO] |  |  +- org.junit.platform:junit-platform-commons:jar:1.9.1:test<br/>[2023-05-23T10:17:21.305Z] [INFO] |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:compile<br/>[2023-05-23T10:17:21.305Z] [INFO] |  +- org.junit.jupiter:junit-jupiter-params:jar:5.9.1:test<br/>[2023-05-23T10:17:21.305Z] [INFO] |  +- org.junit.jupiter:junit-jupiter-engine:jar:5.9.1:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  \- org.junit.platform:junit-platform-engine:jar:1.9.1:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  +- io.quarkus:quarkus-core:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  +- io.quarkus:quarkus-ide-launcher:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  +- io.smallrye.config:smallrye-config:jar:2.12.3:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  \- io.smallrye.config:smallrye-config-core:jar:2.12.3:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-expression:jar:1.13.1:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |     |  \- io.smallrye.common:smallrye-common-function:jar:1.13.1:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |     +- io.smallrye.common:smallrye-common-classloader:jar:1.13.1:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |     \- io.smallrye.config:smallrye-config-common:jar:2.12.3:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  +- org.jboss.logmanager:jboss-logmanager-embedded:jar:1.0.10:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.2.1.Final:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  +- org.jboss.threads:jboss-threads:jar:3.4.3.Final:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logmanager:jar:1.2.0.Final:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-runner:jar:999-SNAPSHOT:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  \- io.quarkus:quarkus-fs-util:jar:0.0.9:compile<br/>[2023-05-23T10:17:21.306Z] [INFO] |  +- io.quarkus:quarkus-test-common:jar:999-SNAPSHOT:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  +- io.quarkus:quarkus-bootstrap-maven-resolver:jar:999-SNAPSHOT:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  +- org.apache.maven:maven-embedder:jar:3.8.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.apache.maven:maven-settings:jar:3.8.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.apache.maven:maven-core:jar:3.8.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  |  +- org.apache.maven:maven-artifact:jar:3.8.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  |  \- org.codehaus.plexus:plexus-component-annotations:jar:1.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.apache.maven:maven-plugin-api:jar:3.8.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.apache.maven:maven-model:jar:3.8.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.apache.maven:maven-model-builder:jar:3.8.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.apache.maven:maven-builder-support:jar:3.8.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-api:jar:1.6.3:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.apache.maven.resolver:maven-resolver-util:jar:1.6.3:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.apache.maven.shared:maven-shared-utils:jar:3.3.4:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- com.google.inject:guice:jar:no_aop:4.2.2:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  |  \- com.google.guava:guava:jar:31.1-jre:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  |     \- com.google.guava:failureaccess:jar:1.0.1:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-classworlds:jar:2.6.0:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-sec-dispatcher:jar:2.0:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  +- org.codehaus.plexus:plexus-cipher:jar:2.0:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  \- commons-cli:commons-cli:jar:1.4:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  +- org.apache.maven:maven-settings-builder:jar:3.8.6:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  |  \- org.codehaus.plexus:plexus-interpolation:jar:1.26:test<br/>[2023-05-23T10:17:21.306Z] [INFO] |  |  |  +- org [...]

2023-05-23 11:03 UTC, radtriste commented
lts should be fixed by https://github.com/kiegroup/kogito-runtimes/pull/3004

2023-05-23 11:06 UTC, kie-ci3 commented
**(tests) - kogito-apps job** `#2622` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>


export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2622/display/redirect

**Test results:**
- PASSED: 1669
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest/job/kogito-runtimes.tests.downstream.kogito-apps/2622/testReport/org.kie.kogito.index.oracle/ProcessDataIndexOracleHttpIT/testProcessInstanceEvents/">org.kie.kogito.index.oracle.ProcessDataIndexOracleHttpIT.testProcessInstanceEvents</a></summary>
java.lang.AssertionError: <br/>1 expectation failed.<br/>JSON path data.UserTaskInstances[0].attachments.size() doesn't match.<br/>Expected: is <1><br/>  Actual: <0><br/><br/>
</details>

2023-05-23 12:54 UTC, radtriste commented
jenkins run quarkus-lts

2023-05-23 12:55 UTC, radtriste commented
jenkins rerun kogito-apps tests

2023-05-23 13:17 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-quarkus-examples job** `#58` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-quarkus-examples/58/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T13:17:02.694Z] [INFO] Building Kogito Example :: Serverless Workflow Timeouts Showcase Embedded 1.0-SNAPSHOT [58/61]<br/>[2023-05-23T13:17:02.694Z] [INFO] --------------------------------[ jar ]---------------------------------<br/>[2023-05-23T13:17:02.694Z] [INFO] <br/>[2023-05-23T13:17:02.694Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-embedded ---<br/>[2023-05-23T13:17:02.694Z] [INFO] <br/>[2023-05-23T13:17:02.694Z] [INFO] --< org.kie.kogito.examples:serverless-workflow-timeouts-showcase-extended >--<br/>[2023-05-23T13:17:02.694Z] [INFO] Building Kogito Example :: Serverless Workflow Timeouts Showcase Extended 1.0-SNAPSHOT [59/61]<br/>[2023-05-23T13:17:02.694Z] [INFO] --------------------------------[ jar ]---------------------------------<br/>[2023-05-23T13:17:02.694Z] [INFO] <br/>[2023-05-23T13:17:02.694Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-extended ---<br/>[2023-05-23T13:17:02.694Z] [INFO] <br/>[2023-05-23T13:17:02.694Z] [INFO] --------------< org.kie.kogito.examples:kogito-examples >---------------<br/>[2023-05-23T13:17:02.694Z] [INFO] Building Kogito Example 2.0.0-SNAPSHOT                           [60/61]<br/>[2023-05-23T13:17:02.694Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T13:17:02.951Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T13:17:02.951Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T13:17:02.951Z] [WARNING] The artifact org.codehaus.mojo:sonar-maven-plugin:jar:3.6.1.1688 has been relocated to org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.6.1.1688: SonarQube plugin was moved to SonarSource organisation<br/>[2023-05-23T13:17:02.951Z] [INFO] <br/>[2023-05-23T13:17:02.951Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ kogito-examples ---<br/>[2023-05-23T13:17:03.206Z] [INFO] <br/>[2023-05-23T13:17:03.206Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2023-05-23T13:17:03.206Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [61/61]<br/>[2023-05-23T13:17:03.206Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T13:17:03.206Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T13:17:03.206Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T13:17:03.206Z] [INFO] <br/>[2023-05-23T13:17:03.206Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ serverless-workflow-examples ---<br/>[2023-05-23T13:17:03.206Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-23T13:17:03.206Z] [INFO] Reactor Summary:<br/>[2023-05-23T13:17:03.206Z] [INFO] <br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Annotations and Description:: Quarkus 1.0-SNAPSHOT SUCCESS [  0.524 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.161 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Callback Event Service 1.0-SNAPSHOT SUCCESS [  0.049 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Service 1.0-SNAPSHOT SUCCESS [  0.021 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Callback :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.018 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Compensation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.018 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Consuming Events Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.016 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Correlation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.021 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Custom Function :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Service 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Workflow 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 1.0-SNAPSHOT SUCCESS [  0.605 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 1.0-SNAPSHOT SUCCESS [  0.007 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Data Index :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.012 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.011 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.012 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T13:17:03.206Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPS [...]

2023-05-23 13:18 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-springboot-examples job** `#59` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-springboot-examples/59/display/redirect
See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T13:17:51.045Z] [INFO] Building Kogito Example :: Serverless Workflow Timeouts Showcase Embedded 1.0-SNAPSHOT [58/61]<br/>[2023-05-23T13:17:51.045Z] [INFO] --------------------------------[ jar ]---------------------------------<br/>[2023-05-23T13:17:51.045Z] [INFO] <br/>[2023-05-23T13:17:51.045Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-embedded ---<br/>[2023-05-23T13:17:51.045Z] [INFO] <br/>[2023-05-23T13:17:51.045Z] [INFO] --< org.kie.kogito.examples:serverless-workflow-timeouts-showcase-extended >--<br/>[2023-05-23T13:17:51.045Z] [INFO] Building Kogito Example :: Serverless Workflow Timeouts Showcase Extended 1.0-SNAPSHOT [59/61]<br/>[2023-05-23T13:17:51.045Z] [INFO] --------------------------------[ jar ]---------------------------------<br/>[2023-05-23T13:17:51.045Z] [INFO] <br/>[2023-05-23T13:17:51.045Z] [INFO] --- versions-maven-plugin:2.15.0:set-property (default-cli) @ serverless-workflow-timeouts-showcase-extended ---<br/>[2023-05-23T13:17:51.045Z] [INFO] <br/>[2023-05-23T13:17:51.045Z] [INFO] --------------< org.kie.kogito.examples:kogito-examples >---------------<br/>[2023-05-23T13:17:51.045Z] [INFO] Building Kogito Example 2.0.0-SNAPSHOT                           [60/61]<br/>[2023-05-23T13:17:51.045Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T13:17:51.045Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T13:17:51.045Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T13:17:51.443Z] [WARNING] The artifact org.codehaus.mojo:sonar-maven-plugin:jar:3.6.1.1688 has been relocated to org.sonarsource.scanner.maven:sonar-maven-plugin:jar:3.6.1.1688: SonarQube plugin was moved to SonarSource organisation<br/>[2023-05-23T13:17:51.443Z] [INFO] <br/>[2023-05-23T13:17:51.443Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ kogito-examples ---<br/>[2023-05-23T13:17:51.443Z] [INFO] <br/>[2023-05-23T13:17:51.443Z] [INFO] --------< org.kie.kogito.examples:serverless-workflow-examples >--------<br/>[2023-05-23T13:17:51.443Z] [INFO] Building Kogito Example :: Serverless Workflow 2.0.0-SNAPSHOT    [61/61]<br/>[2023-05-23T13:17:51.443Z] [INFO] --------------------------------[ pom ]---------------------------------<br/>[2023-05-23T13:17:51.443Z] [WARNING] The POM for org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 is missing, no dependency information available<br/>[2023-05-23T13:17:51.443Z] [WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:license-maven-plugin:4.0.rc2: Plugin org.codehaus.mojo:license-maven-plugin:4.0.rc2 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:license-maven-plugin:jar:4.0.rc2 in https://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8443/nexus/content/groups/kogito-runtimes-pr-artifacts-group/ was cached in the local repository, resolution will not be reattempted until the update interval of mirror-central has elapsed or updates are forced<br/>[2023-05-23T13:17:51.443Z] [INFO] <br/>[2023-05-23T13:17:51.443Z] [INFO] --- versions-maven-plugin:2.5:set-property (default-cli) @ serverless-workflow-examples ---<br/>[2023-05-23T13:17:51.443Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-23T13:17:51.443Z] [INFO] Reactor Summary:<br/>[2023-05-23T13:17:51.443Z] [INFO] <br/>[2023-05-23T13:17:51.443Z] [INFO] Kogito Example :: Serverless Workflow Annotations and Description:: Quarkus 1.0-SNAPSHOT SUCCESS [  0.523 s]<br/>[2023-05-23T13:17:51.443Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.139 s]<br/>[2023-05-23T13:17:51.443Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Callback Event Service 1.0-SNAPSHOT SUCCESS [  0.052 s]<br/>[2023-05-23T13:17:51.443Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Service 1.0-SNAPSHOT SUCCESS [  0.023 s]<br/>[2023-05-23T13:17:51.443Z] [INFO] Kogito Example :: Serverless Workflow Callback :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.021 s]<br/>[2023-05-23T13:17:51.443Z] [INFO] Kogito Example :: Serverless Workflow Compensation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.019 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Consuming Events Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.019 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Correlation :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.022 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Custom Function :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Service 1.0-SNAPSHOT SUCCESS [  0.018 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Workflow 1.0-SNAPSHOT SUCCESS [  0.018 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.006 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 1.0-SNAPSHOT SUCCESS [  0.524 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 1.0-SNAPSHOT SUCCESS [  0.007 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Data Index :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.014 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.013 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.012 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.012 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.012 s]<br/>[2023-05-23T13:17:51.444Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0 [...]

2023-05-23 13:29 UTC, kie-ci3 commented
**(quarkus-lts) - serverless-workflow-examples job** `#57` was: **FAILURE**
Possible explanation: Pipeline failure or project build failure


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-examples -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.serverless-workflow-examples/57/display/redirect

**Test results:**
- PASSED: 64
- FAILED: 0

Those are the test failures: none

See console log:
<details>
<summary><b>Console Logs</b></summary>
[2023-05-23T13:29:31.262Z] [INFO] No tests to run.<br/>[2023-05-23T13:29:31.262Z] [INFO] <br/>[2023-05-23T13:29:31.262Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:integration-test (default) @ serverless-workflow-examples ---<br/>[2023-05-23T13:29:31.262Z] [INFO] No tests to run.<br/>[2023-05-23T13:29:31.262Z] [INFO] Skipping execution of surefire because it has already been run for this configuration<br/>[2023-05-23T13:29:31.262Z] [INFO] <br/>[2023-05-23T13:29:31.262Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (integration-test) @ serverless-workflow-examples ---<br/>[2023-05-23T13:29:31.262Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.downstream.serverless-workflow-examples/bc/kiegroup_kogito-examples/serverless-workflow-examples/target/failsafe-reports<br/>[2023-05-23T13:29:31.262Z] [INFO] <br/>[2023-05-23T13:29:31.262Z] [INFO] --- maven-failsafe-plugin:3.0.0-M5:verify (default) @ serverless-workflow-examples ---<br/>[2023-05-23T13:29:31.262Z] [INFO] Failsafe report directory: /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.downstream.serverless-workflow-examples/bc/kiegroup_kogito-examples/serverless-workflow-examples/target/failsafe-reports<br/>[2023-05-23T13:29:31.262Z] [INFO] <br/>[2023-05-23T13:29:31.262Z] [INFO] --- maven-install-plugin:2.5.2:install (default-install) @ serverless-workflow-examples ---<br/>[2023-05-23T13:29:31.262Z] [INFO] Installing /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.downstream.serverless-workflow-examples/bc/kiegroup_kogito-examples/serverless-workflow-examples/pom.xml to /home/jenkins/.m2/repository/org/kie/kogito/examples/serverless-workflow-examples/2.0.0-SNAPSHOT/serverless-workflow-examples-2.0.0-SNAPSHOT.pom<br/>[2023-05-23T13:29:31.262Z] [INFO] ------------------------------------------------------------------------<br/>[2023-05-23T13:29:31.262Z] [INFO] Reactor Summary:<br/>[2023-05-23T13:29:31.262Z] [INFO] <br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Annotations and Description:: Quarkus 1.0-SNAPSHOT SUCCESS [  9.178 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.141 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Callback Event Service 1.0-SNAPSHOT SUCCESS [  2.752 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow CallBack Over HTTP Quarkus :: Service 1.0-SNAPSHOT SUCCESS [ 17.636 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Callback :: Quarkus 1.0-SNAPSHOT SUCCESS [ 31.659 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Compensation :: Quarkus 1.0-SNAPSHOT SUCCESS [ 12.462 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Consuming Events Over HTTP :: Quarkus 1.0-SNAPSHOT SUCCESS [ 13.873 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Correlation :: Quarkus 1.0-SNAPSHOT SUCCESS [ 29.896 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Custom Function :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Service 1.0-SNAPSHOT SUCCESS [  2.533 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Custom Function Knative :: Workflow 1.0-SNAPSHOT SUCCESS [  6.343 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Custom type :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.005 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Server :: Quarkus 1.0-SNAPSHOT SUCCESS [  0.337 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC :: Runtime 1.0-SNAPSHOT SUCCESS [  1.423 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example:: Serverless Workflow Custom RPC:: deployment 1.0-SNAPSHOT SUCCESS [  0.499 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Custom RPC Client :: Quarkus 1.0-SNAPSHOT SUCCESS [ 12.740 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Data Index :: Quarkus 1.0-SNAPSHOT SUCCESS [ 30.478 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Error :: Quarkus 1.0-SNAPSHOT SUCCESS [ 13.831 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Events :: Quarkus 1.0-SNAPSHOT SUCCESS [ 28.111 s]<br/>[2023-05-23T13:29:31.262Z] [INFO] Kogito Example :: Serverless Workflow Expression :: Quarkus 1.0-SNAPSHOT SUCCESS [ 13.183 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow For Each :: Quarkus 1.0-SNAPSHOT SUCCESS [ 12.897 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow Functions :: Quarkus 1.0-SNAPSHOT SUCCESS [ 14.203 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy 1.0-SNAPSHOT SUCCESS [  0.003 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Services 1.0-SNAPSHOT SUCCESS [  7.285 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow :: Funqy :: Workflow 1.0-SNAPSHOT SUCCESS [ 17.514 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: Quarkus 1.0-SNAPSHOT SUCCESS [ 14.755 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow grpc example 1.0-SNAPSHOT SUCCESS [  0.002 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Server:: Quarkus 1.0-SNAPSHOT SUCCESS [  3.922 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow Greeting :: gRPC Client:: Quarkus 1.0-SNAPSHOT SUCCESS [ 17.394 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow Hello World :: Quarkus 1.0-SNAPSHOT SUCCESS [ 16.441 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow Loan Broker Showcase 1.0-SNAPSHOT SUCCESS [  0.003 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Examples :: Serverless Workflow Loan Broker Showcase :: Aggregator 1.0-SNAPSHOT SUCCESS [ 27.069 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow Loan Broker Showcase :: Flow 1.0-SNAPSHOT SUCCESS [ 23.790 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Examples :: Serverless Workflow Loan Broker Showcase :: UI 1.0-SNAPSHOT SUCCESS [ 10.200 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription Showcase 1.0-SNAPSHOT SUCCESS [  0.004 s]<br/>[2023-05-23T13:29:31.263Z] [INFO] Kogito Example :: Serverless Workflow Newsletter Subscription :: Subscription Service 1.0-SNAPSHOT SUCCESS [ 13.132 s]<br/>[2023-05-23 [...]

2023-05-23 13:32 UTC, lampajr commented
It seems on `kogito-apps` there is an issue similar to  https://github.com/kiegroup/kogito-runtimes/pull/3004:
```
[2023-05-23T13:16:35.410Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project kogito-addons-quarkus-jobs-service-embedded-deployment: Compilation failure: Compilation failure: 
[2023-05-23T13:16:35.410Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.downstream.kogito-quarkus-examples/bc/kiegroup_kogito-apps/jobs-service/kogito-addons-jobs-service/kogito-addons-quarkus-jobs-service-embedded/deployment/src/main/java/org/kie/kogito/addons/quarkus/jobs/service/embedded/deployment/KogitoAddonsQuarkusJobsServiceEmbeddedProcessor.java:[74,114] incompatible types: java.lang.String cannot be converted to org.jboss.jandex.DotName
[2023-05-23T13:16:35.410Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.downstream.kogito-quarkus-examples/bc/kiegroup_kogito-apps/jobs-service/kogito-addons-jobs-service/kogito-addons-quarkus-jobs-service-embedded/deployment/src/main/java/org/kie/kogito/addons/quarkus/jobs/service/embedded/deployment/KogitoAddonsQuarkusJobsServiceEmbeddedProcessor.java:[78,124] incompatible types: java.lang.Class<io.vertx.mutiny.pgclient.PgPool> cannot be converted to java.lang.String
[2023-05-23T13:16:35.410Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.downstream.kogito-quarkus-examples/bc/kiegroup_kogito-apps/jobs-service/kogito-addons-jobs-service/kogito-addons-quarkus-jobs-service-embedded/deployment/src/main/java/org/kie/kogito/addons/quarkus/jobs/service/embedded/deployment/KogitoAddonsQuarkusJobsServiceEmbeddedProcessor.java:[80,116] incompatible types: java.lang.Class<io.agroal.api.AgroalDataSource> cannot be converted to java.lang.String
[2023-05-23T13:16:35.410Z] [ERROR] /home/jenkins/workspace/KIE/kogito/main/pullrequest.quarkus-lts/kogito-runtimes.quarkus-lts.downstream.kogito-quarkus-examples/bc/kiegroup_kogito-apps/jobs-service/kogito-addons-jobs-service/kogito-addons-quarkus-jobs-service-embedded/deployment/src/main/java/org/kie/kogito/addons/quarkus/jobs/service/embedded/deployment/KogitoAddonsQuarkusJobsServiceEmbeddedProcessor.java:[95,54] incompatible types: java.lang.String cannot be converted to org.jboss.jandex.DotName
```

2023-05-23 13:55 UTC, cristianonicolai commented
@lampajr @radtriste fix for Job Service related LTS https://github.com/kiegroup/kogito-apps/pull/1725

2023-05-24 02:53 UTC, cristianonicolai commented
jenkins run quarkus-lts

2023-05-24 03:37 UTC, kie-ci3 commented
**(quarkus-lts) - kogito-apps job** `#60` was: **UNSTABLE**
Possible explanation: This should be test failures


<details>
<summary><b>Reproducer</b></summary>

export QUARKUS_BRANCH=2.13
export BUILD_MVN_OPTS_CURRENT= 
build-chain build cross_pr -f 'https://raw.githubusercontent.com/kiegroup/kogito-pipelines/main/.ci/pull-request-config.yaml' -o 'bc' -p kiegroup/kogito-apps -u https://github.com/kiegroup/kogito-runtimes/pull/3003 --skipParallelCheckout

NOTE: To install the build-chain tool, please refer to https://github.com/kiegroup/github-action-build-chain#local-execution

</details>


Please look here: https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-apps/60/display/redirect

**Test results:**
- PASSED: 523
- FAILED: 1

Those are the test failures: 
<details>
<summary><a href="https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/KIE/job/kogito/job/main/job/pullrequest.quarkus-lts/job/kogito-runtimes.quarkus-lts.downstream.kogito-apps/60/testReport/org.kie.kogito.jobs.service.resource/JobServiceManagementResourceIT/testShutdown/">org.kie.kogito.jobs.service.resource.JobServiceManagementResourceIT.testShutdown</a></summary>
java.lang.RuntimeException: An unexpected situation occurred while trying to instantiate the testing infrastructure. Have you perhaps mixed @QuarkusTest and @QuarkusIntegrationTest in the same test run?<br/>
</details>

2023-05-24 18:29 UTC, wmedvede commented
jenkins run quarkus-lts

2023-05-25 08:32 UTC, merged