kie-issues#532: create REST endpoint to start process instances using signals
kiegroup/kogito-runtimes pull request #3221
Opened 2023-09-08 09:59 UTC by pefernan

Closes https://github.com/kiegroup/kie-issues/issues/532

Adds a new REST endpoint to create Process Instances using signals

Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [ ] You have read the [contributors guide](CONTRIBUTING.md)
- [ ] Your code is properly formatted according to [this configuration](https://github.com/kiegroup/kogito-runtimes/tree/main/kogito-build/kogito-ide-config)
- [ ] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ ] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains link to any dependent or related Pull Request
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

<details>
<summary>
How to replicate CI configuration locally?
</summary>

Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the code for each repository.
 
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to change multiple repositories and send multiple dependent pull requests related with a change you can easily reproduce the same build by executing it on Github hosted environment or locally in your development environment. See [local execution](https://github.com/kiegroup/github-action-build-chain#local-execution) details to get more information about it.
</details>

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

- for <b>pull request checks</b>  
  Please add comment: <b>Jenkins retest this</b>

- for a <b>specific pull request check</b>  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] tests</b>

- for <b>quarkus branch checks</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins run quarkus-branch</b>

- for a <b>quarkus branch specific check</b>  
  Run checks against Quarkus current used branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-branch</b>

- for <b>quarkus main checks</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins run quarkus-main</b>

- for a <b>specific quarkus main check</b>  
  Run checks against Quarkus main branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-main</b>

- for <b>quarkus lts checks</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins run quarkus-lts</b>

- for a <b>specific quarkus lts check</b>  
  Run checks against Quarkus lts branch  
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] quarkus-lts</b>

- for <b>native checks</b>  
  Run native checks  
  Please add comment: <b>Jenkins run native</b>

- for a <b>specific native check</b>  
  Run native checks 
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native</b>

- for <b>native lts checks</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins run native-lts</b>

- for a <b>specific native lts check</b>  
  Run native checks against quarkus lts branch
  Please add comment: <b>Jenkins (re)run [kogito-runtimes|kogito-apps|kogito-examples] native-lts</b>
</details>

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

<details>
<summary>
Quarkus-3 PR check is failing ... what to do ?
</summary>
The Quarkus 3 check is applying patches from the `.ci/environments/quarkus-3/patches`.

The first patch, called `0001_before_sh.patch`, is generated from Openrewrite `.ci/environments/quarkus-3/quarkus3.yml` recipe. The patch is created to speed up the check. But it may be that some changes in the PR broke this patch.  
No panic, there is an easy way to regenerate it. You just need to comment on the PR:
```
jenkins rewrite quarkus-3
```
and it should, after some minutes (~20/30min) apply a commit on the PR with the patch regenerated.

Other patches were generated manually. If any of it fails, you will need to manually update it... and push your changes.
</details>

2023-09-08 13:48 UTC, fjtirado requested changes
Please do not merge this one till we discuss the alternative approach
In my opinion, start signals should be handled as start messages, and that in Kogito is not done through an explicit api but as part of the code gen, which finally delegate to external broken to handle the events that start the process.
So, in my view,  this JIRA is not really aligned with Kogito design

2023-09-08 14:15 UTC, elguardian commented
Hi @fjtirado
This is a bug fix. not really a enhacement. The rest call already existed but incorrectly working as the rest endpoint was asking (process instance id).

Regarding the new start signal, it should be there as Process is acting as the façade and that logic was missing in there (design flaw).

Please don't state intermediately to block an issue without proper conversation.

2023-09-12 14:31 UTC, pefernan commented
@elguardian @fjtirado as agreed, we'll enhance the events api in kogito to support Signals in a different task https://github.com/kiegroup/kie-issues/issues/550)

2023-09-12 16:01 UTC, fjtirado commented on api/kogito-api/src/main/java/org/kie/kogito/process/ProcessService.java
> +    <T extends Model> ProcessInstance<T> signalProcess(Process<T> process,
Rather than a new method in ProcessService, I will invoke the already existing one that start a new process instance, which is currently invoked only from ProcessEventDispatcher

2023-09-12 16:06 UTC, fjtirado commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSignalQuarkusTemplate.java
> +        ProcessInstance<$Type$> pi = this.processService.signalProcess(process,
Im wondering if we should check if the header contains values for for business key, start from node and kogito reference id, wdyt?

2023-09-12 16:08 UTC, fjtirado approved these changes

2023-09-12 16:17 UTC, pefernan commented on api/kogito-api/src/main/java/org/kie/kogito/process/ProcessService.java
> +    <T extends Model> ProcessInstance<T> signalProcess(Process<T> process,
ok, I can do that.

2023-09-12 16:19 UTC, pefernan commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSignalQuarkusTemplate.java
> +        ProcessInstance<$Type$> pi = this.processService.signalProcess(process,
@fjtirado I agree with business key and reference id, but in this case in particular that we know that the instance has started due to the signal IDK if the start from node is really needed

2023-09-12 22:19 UTC, tiagodolphine approved these changes

2023-09-13 16:24 UTC, pefernan commented
@fjtirado @tiagodolphine just pushed the changes. Let's see what the if there is any broken IT test.

2023-09-13 17:27 UTC, fjtirado commented on kogito-codegen-modules/kogito-codegen-processes/src/main/resources/class-templates/RestResourceSignalSpringTemplate.java
> +        return ResponseEntity.created(uriComponentsBuilder.path("/$name$/{id}").buildAndExpand(pi.id()).toUri())
@pefernan per our discussion this morning, I just realize this is assuming that well, the engine, when receiving the signal is going to start a process instance always, which is not necessarily true. 
To be honest, I do not have a good solution, the best one is that maybe this REST api should be async and do not return anything.

2023-09-14 10:33 UTC, fjtirado approved these changes

2023-09-14 12:58 UTC, merged