KOGITO-2914: connect Trusty service and Explainability service
kiegroup/kogito-runtimes pull request #720
Opened 2020-08-24 17:25 UTC by kostola

2020-08-24 18:37 UTC, r00ta requested changes
Overall looks good to me, the only major comment I have is about the exception handling. Since with this new changes one of the many requests in the http body can fail we should handle it and do not return a `BAD_REQUEST`: I think that a perturbed request might contain invalid data for the model in many cases.

2020-08-24 18:37 UTC, r00ta commented on addons/explainability/explainability-addon-common/src/test/java/org/kie/kogito/explainability/ExplainabilityServiceTest.java
>      public void testPerturbedExecution() {
Given that with these changes multiple requests are embedded in just one http call, one request might be invalid and raise an uncaught exception. I think we have to handle this case and add a test for that, wdyt?

2020-08-24 18:37 UTC, r00ta commented on addons/explainability/pom.xml
> +
remove newlines

2020-08-24 18:37 UTC, r00ta commented on addons/explainability/explainability-addon-common/pom.xml
> +
remove newline

2020-08-24 18:42 UTC, r00ta commented
Another side comment is that I'm not sure if `typedvalue-api` is a very informative name for a module. Wdyt?

2020-08-25 17:21 UTC, danielezonca commented on addons/explainability/explainability-quarkus-addon/src/test/java/org/kie/kogito/explainability/QuarkusExplainableResourceIT.java
> +    void explainServiceTest() throws JsonProcessingException {
Done, added a test with 2 elements and on with no element

2020-08-25 17:22 UTC, danielezonca commented on addons/explainability/explainability-springboot-addon/pom.xml
> +
Done

2020-08-25 17:22 UTC, danielezonca commented on addons/explainability/pom.xml
> +
Done

2020-08-25 17:22 UTC, danielezonca commented on addons/explainability/explainability-addon-common/pom.xml
> +
Done

2020-08-26 10:24 UTC, kostola commented
> Another side comment is that I'm not sure if `typedvalue-api` is a very informative name for a module. Wdyt?

What is your suggestion?

2020-08-27 09:09 UTC, r00ta commented
> > Another side comment is that I'm not sure if `typedvalue-api` is a very informative name for a module. Wdyt?
> 
> What is your suggestion?

Hi @kostola , what is the purpose of such module? Is it just including the classes for the dto/event? We might go for something like `tracing-messaging-api`

2020-08-27 10:14 UTC, danielezonca commented
@r00ta 
We are trying to avoid `tracing-` in the name because this module is also used by `explainability-service` as DTO for values.
We would like to keep services independent and we cannot have -runtimes -> -apps dependencies so this common module will be probably moved somewhere else inside -runtimes repo.
Btw we can change the name for sure if we find a better one :)

2020-08-27 10:14 UTC, danielezonca commented
jenkins retest this please

2020-08-27 11:08 UTC, danielezonca commented
jenkins retest this please

2020-08-27 14:03 UTC, danielezonca commented
jenkins retest this please

2020-08-28 13:30 UTC, danielezonca commented on addons/explainability/explainability-addon-common/src/test/java/org/kie/kogito/explainability/ExplainabilityServiceTest.java
>      public void testPerturbedExecution() {
Ticket created https://issues.redhat.com/browse/KOGITO-3213

2020-08-28 14:14 UTC, jiripetrlik approved these changes
Looks good to me. Few minor comments.

2020-08-28 16:30 UTC, danielezonca commented on addons/explainability/explainability-addon-common/src/test/java/org/kie/kogito/explainability/ExplainabilityServiceTest.java
> +            throw new RuntimeException("Model not found.");
Done

2020-08-28 16:30 UTC, danielezonca commented on addons/explainability/explainability-quarkus-addon/src/test/java/org/kie/kogito/explainability/ApplicationMock.java
> +            throw new RuntimeException("Model not found.");
Done

2020-08-28 22:26 UTC, danielezonca commented
jenkins retest this please

2020-08-31 08:06 UTC, r00ta approved these changes

2020-08-31 09:27 UTC, merged