[KOGITO-2893] Detach Business Key from ID - follow-up cleaning
kiegroup/kogito-runtimes pull request #730
Opened 2020-08-27 15:57 UTC by MarianMacik

Follow-up of [KOGITO-2893](https://issues.redhat.com/browse/KOGITO-2893) (as it got merged before I had a chance to review it)

As we discussed with @ruromero business key is now just set and used only when querying using data index. This means that methods removed in this PR are no longer needed.

2020-08-27 16:50 UTC, ruromero requested changes
I agree with the changes so far

2020-08-27 16:50 UTC, ruromero commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java
>      public ProcessInstance getProcessInstance(CorrelationKey correlationKey) {
Is it too much refactoring to remove the whole method? Is it even used?
I think you just have to remove it from the CorrelationAwareProcessRuntime interface

2020-08-27 16:50 UTC, ruromero commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/ProcessRuntimeImpl.java
> +        return null; // Querying of correlation keys is no longer supported
Same, I think it can be removed

2020-08-27 17:10 UTC, MarianMacik commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/LightProcessRuntime.java
>      public ProcessInstance getProcessInstance(CorrelationKey correlationKey) {
Yep, was considering it. But then the `CorrelationAwareProcessRuntime` interface would have methods startProcess and createProcessInstance but no query methods. If that's OK, I will remove also those.

2020-08-28 06:35 UTC, MarianMacik commented
Tests were unable to pull Infinispan docker image. Retrying.

jenkins retest this

2020-08-28 06:47 UTC, ruromero approved these changes

2020-08-31 01:55 UTC, cristianonicolai approved these changes

2020-09-03 11:21 UTC, tiagodolphine approved these changes

2020-09-03 12:55 UTC, merged