KOGITO-1031 Run BDD tests from PR
kiegroup/kogito-runtimes pull request #731
Opened 2020-08-28 00:07 UTC by Kevin-Mok

See: https://issues.redhat.com/browse/KOGITO-1031

This is an accompanying PR to [the one opened in kogito-pipelines](https://github.com/kiegroup/kogito-pipelines/pull/46). 

## Changes
- adds parameter to take in the PR's target branch for `ghprb` so that the changes can be merged into it using the shared library's `githubscm.checkoutIfExists`
  - wrote helper function `getDefaultBranch` to determine fallback branch (includes jenkins-spock tests)
- deploys all artifacts locally before zipping them altogether to push to Nexus
  * copied from [kie-jenkins-scripts](https://github.com/kiegroup/kie-jenkins-scripts/blob/56e91745ac98d4529b4414ecca37f5f3e87dedc3/job-dsls/jobs/dailyBuild_pipeline.groovy#L111-L114)
* fixes the post step of saving reports so that the build doesn't fail if the `SKIP_TESTS` parameter is ticked

## Requirements
Many thanks for submitting your Pull Request :heart:! 

Please make sure that your PR meets the following requirements:

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket

2020-09-21 08:52 UTC, Ginxo requested changes
Please check.
I can't tell about business here, only my technical POV

2020-09-21 08:52 UTC, Ginxo commented on Jenkinsfile.deploy
> +                    cd ${env.LOCAL_DEPLOY_DIR}
you should try to avoid browsing folder this way, you can do

```
dir(${env.LOCAL_DEPLOY_DIR}) {
    sh """
    zip -r kiegroup .
    curl --silent --upload-file kiegroup.zip -u ${kieUnpack} -v ${params.MAVEN_DEPLOY_REPOSITORY}/content-compressed
    """
}
```

2020-09-21 08:52 UTC, Ginxo commented on Jenkinsfile.deploy
> +    if (params.PR_TARGET_BRANCH == '') {
`if (!params.PR_TARGET_BRANCH)`

2020-09-21 08:52 UTC, Ginxo commented on Jenkinsfile.deploy
> +    return 'master'
I would suggest to replace 340-346 by
`return repositoryScm ? params.PR_TARGET_BRANCH : 'master'`

2020-09-21 08:52 UTC, Ginxo commented on jenkins-tests/src/test/vars/JenkinsfileDeploy.groovy
> +class JenkinsfileDeploy extends JenkinsPipelineSpecification {
fix indentation problems please

2020-09-24 21:52 UTC, Kevin-Mok commented on jenkins-tests/src/test/vars/JenkinsfileDeploy.groovy
> +class JenkinsfileDeploy extends JenkinsPipelineSpecification {
Same as [comment in pipelines PR](https://github.com/kiegroup/kogito-pipelines/pull/46#discussion_r494627253).

2020-09-29 06:03 UTC, Ginxo approved these changes
LGTM, please check my suggestion.

2020-09-29 06:03 UTC, Ginxo commented on Jenkinsfile.deploy
> +    return repoUrl.replaceAll('/content/', '/service/local/') + 'content-compressed'
I would do
```
String getMavenRepoZipUrl() {
     return "${params.MAVEN_DEPLOY_REPOSITORY.replaceAll('/content/', '/service/local/').replaceFirst('/*$', '')}/content-compressed"
}
```
the $ matches the end of a string and `*` in case there are multiple slashes, so it will remove it in case it exists and you always concatenate `/` after url.
This is just a suggestion.

2020-09-29 07:24 UTC, Kaitou786 approved these changes

2020-09-29 08:46 UTC, radtriste requested changes

2020-09-29 08:46 UTC, radtriste commented on Jenkinsfile.deploy
> +    String repoUrl = params.MAVEN_DEPLOY_REPOSITORY
what happens here if no `MAVEN_DEPLOY_REPOSITORY` is given ?
Usually, if none mentioned, we are using the default one defined into the pom.xml.

2020-11-11 03:24 UTC, Kevin-Mok commented on Jenkinsfile.deploy
> +    String repoUrl = params.MAVEN_DEPLOY_REPOSITORY
I'm not sure how to go about deployment now. I tried just using the [current `mavenDeploy()`](https://github.com/kiegroup/kogito-runtimes/blob/03d1fbecd3cfdb6fccad2114359485479e3f7dd7/Jenkinsfile.deploy#L273-L276) with the parameter of the PR check repository, but this results in a [401 error](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/custom/job/kmok/job/KOGITO-1031-full/job/kogito-runtimes-deploy/23/execution/node/162/log/) when deploying to that repo. 

[This zip and curl method](https://github.com/Kevin-Mok/kogito-runtimes/blob/3b49b28fc332bc1a5c96be31fee9d0799766a59d/Jenkinsfile.deploy#L197-L209) I was using previously uses the `unpacks-zip-on-qa-nexus` credential to authenticate itself to the repo, I'm not sure how to deploy to the default repo in the `pom.xml` in that case.  

I could create 2 different branches of deployment depending on whether or not there is a `MAVEN_DEPLOY_REPOSITORY` parameter, but that seems kind of janky. Also, would the `unpacks-zip-on-qa-nexus` credential even work universally for that?

How would you suggest I go about this?

2020-11-12 13:18 UTC, radtriste commented on Jenkinsfile.deploy
> +    String repoUrl = params.MAVEN_DEPLOY_REPOSITORY
I guess we would also need to retrieve the user/pwd from settings.xml to upload to usual maven as it is a different one...
or have different credentials with this information to do the curl. and so I would have the creds name as optional parameter of the pipeline (if empty get from settings.xml) and the main pipeline would send directly this information (here it would send `unpacks-zip-on-qa-nexus` for this use case).

wdyt ?

2020-11-12 16:36 UTC, Kevin-Mok commented on Jenkinsfile.deploy
> +    String repoUrl = params.MAVEN_DEPLOY_REPOSITORY
Using the zip and curl method if there are artifact repository and credentials parameters passed in requires using a `withCredentials` block, but authenticating with the retrieved credentials from `settings.xml` wouldn't. In this case, would it just be simpler to create two different branches depending on whether artifact repository and credentials parameters are passed in? That is, using a `withCredentials` block if there are and the current `mavenDeploy()` with no repository argument if there isn't. I initially thought this was not ideal, but it may be the simplest implementation after all?

2020-11-12 16:43 UTC, radtriste commented on Jenkinsfile.deploy
> +    String repoUrl = params.MAVEN_DEPLOY_REPOSITORY
yep you could have an if statement and have 2 different behaviors. I have no problem with that ;)

2020-11-18 17:51 UTC, radtriste requested changes

2020-11-18 17:51 UTC, radtriste commented on Jenkinsfile.deploy
> +        string(name: 'PR_TARGET_BRANCH', defaultValue: '', description: 'What is the target branch of the PR? Will be automatically filled out by GitHub Pull Request Builder.')
is that still used ? as far as I can see https://github.com/kiegroup/kogito-pipelines/pull/46, you are checking before calling if the branch exist (which I prefer :))

2020-11-18 17:51 UTC, radtriste commented on Jenkinsfile.deploy
> +
I guess that one could then be deleted

2020-11-18 17:51 UTC, radtriste commented on Jenkinsfile.deploy
> -    extraArgs = params.MAVEN_DEPLOY_REPOSITORY != '' ? "-DaltDeploymentRepository=runtimes-artifacts::default::${params.MAVEN_DEPLOY_REPOSITORY} -Denforcer.skip=true" : ''
This should not be deleted because in case of `MAVEN_DEPLOY_CREDS_ID` not defined we may still need to deploy to `MAVEN_DEPLOY_REPOSITORY`

2020-11-18 23:59 UTC, Kevin-Mok commented on Jenkinsfile.deploy
> +        string(name: 'PR_TARGET_BRANCH', defaultValue: '', description: 'What is the target branch of the PR? Will be automatically filled out by GitHub Pull Request Builder.')
This is still needed because there are 2 repositories being checked out in runtimes. The original pipeline only checks if the branch exists for one of them (the one the PR is for). The other repository will need to fall back to checking out the target branch.

2020-11-19 07:44 UTC, radtriste commented on Jenkinsfile.deploy
> +        string(name: 'PR_TARGET_BRANCH', defaultValue: '', description: 'What is the target branch of the PR? Will be automatically filled out by GitHub Pull Request Builder.')
ah I see, you want to make use of the `checkoutIfExist` and the merge capability in there.
In that case, I think that would need to be added to each deploy pipeline (not only runtimes) and added as param for all call (as you did )
also, 2 small things:
- can you change the comment on that param ? This is confusing as it is not automatic, the main pipeline is setting it
- could you move that param to the `Git information` part ?

2021-01-15 14:07 UTC, radtriste approved these changes
one minor comment

2021-01-15 14:07 UTC, radtriste commented on Jenkinsfile.deploy
> +    if(!directory) {
when do you need to set another directory ?

2021-01-15 14:30 UTC, Kevin-Mok commented on Jenkinsfile.deploy
> +    if(!directory) {
We don't need to. I'll remove it from the other repositories as well.

2021-01-15 16:11 UTC, radtriste approved these changes

2021-01-21 14:19 UTC, radtriste approved these changes

2021-01-22 07:31 UTC, merged