[KOGITO-3297] Bump CloudEvents api to 2.x
kiegroup/kogito-runtimes pull request #750
Opened 2020-09-08 14:43 UTC by ruromero

Fix https://issues.redhat.com/browse/KOGITO-3297

Signed-off-by: ruromero <rromerom@redhat.com>

Upgrade CloudEvents dependencyManagement to 2.0.0-milestone2 that was already being used by the event addon.
Refactor tracing addon to use the new version
Refactor event addon to simplify the use

2020-09-08 14:48 UTC, ricardozanini commented
Depends on: https://github.com/kiegroup/kogito-runtimes/pull/748

2020-09-08 14:56 UTC, ricardozanini approved these changes
LGTM, the example https://github.com/kiegroup/kogito-examples/tree/stable/process-knative-quickstart-quarkus needs to be reviewed.

I'll do the changes as part of https://issues.redhat.com/browse/KOGITO-3294

2020-09-08 17:22 UTC, ruromero commented
I am making sure that any library depending on this addon  doesn't require any additional configuration

2020-09-08 19:43 UTC, ruromero commented
now it should be ready

2020-09-08 20:20 UTC, ricardozanini requested changes
@ruromero since you removed the `HttpRequestConverter` class we need another one to verify if the addon is there:
https://github.com/kiegroup/kogito-runtimes/pull/748/files#diff-b31d1dc9b637fba5701e7c942847842fR107

2020-09-08 20:28 UTC, ruromero commented
done @ricardozanini

2020-09-08 20:49 UTC, ricardozanini requested changes
Sorry, there's one more place to replace the deleted file.

2020-09-08 20:49 UTC, ricardozanini commented on kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
> +    private static final DotName knativeEventingClass = DotName.createSimple("org.kie.kogito.events.knative.ce.extensions.KogitoProcessExtension");
I believe there are one more place:

```shell
kogito-maven-plugin/src/main/java/org/kie/kogito/maven/plugin/GenerateModelMojo.java:235:        boolean useKnativeEventing = hasClassOnClasspath(project, "org.kie.kogito.events.knative.ce.http.HttpRequestConverter");
```
Dammit we need to refactor this ASAP @evacchi

2020-09-09 06:28 UTC, evacchi approved these changes
I think overall it looks good, just left a couple of comments

2020-09-09 06:28 UTC, evacchi commented on addons/events/knative-eventing-addon/src/main/java/org/kie/kogito/events/knative/ce/extensions/KogitoProcessExtension.java
> +    private String kogitoProcessInstanceId;
this is only fixing capitalization, right?

2020-09-09 06:28 UTC, evacchi commented on addons/events/knative-eventing-addon/src/test/java/org/kie/kogito/events/knative/ce/CloudEventConverterTest.java
> +        final String ceJson = new String(cloudEvent.getData());
new String ?

2020-09-09 06:50 UTC, ruromero commented on addons/events/knative-eventing-addon/src/main/java/org/kie/kogito/events/knative/ce/extensions/KogitoProcessExtension.java
> +    private String kogitoProcessInstanceId;
yes

2020-09-09 06:52 UTC, ruromero commented on addons/events/knative-eventing-addon/src/test/java/org/kie/kogito/events/knative/ce/CloudEventConverterTest.java
> +        final String ceJson = new String(cloudEvent.getData());
Yes, the `getData()` method is a byte[] representing the String

2020-09-09 06:53 UTC, ruromero commented on kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
> +    private static final DotName knativeEventingClass = DotName.createSimple("org.kie.kogito.events.knative.ce.extensions.KogitoProcessExtension");
done

2020-09-09 09:07 UTC, mareknovotny commented
Jenkins retest this please

2020-09-09 09:08 UTC, mareknovotny commented
@ricardozanini I triggered CI here to test the new maven mirror settings.xml ;)

2020-09-09 09:40 UTC, winklerm commented
Jenkins retest this please

2020-09-09 10:16 UTC, winklerm commented
Jenkins retest this please

2020-09-11 06:59 UTC, evacchi commented on addons/events/knative-eventing-addon/src/test/java/org/kie/kogito/events/knative/ce/CloudEventConverterTest.java
> +        final String ceJson = new String(cloudEvent.getData());
oh ok. you may want to pass in a charset encoding then

2020-09-11 12:53 UTC, ruromero commented on addons/events/knative-eventing-addon/src/test/java/org/kie/kogito/events/knative/ce/CloudEventConverterTest.java
> +        final String ceJson = new String(cloudEvent.getData());
Actually this doesn't test anything. I have replaced it by a simple Json object

2020-09-14 12:24 UTC, danielezonca commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
>                  .build();
I don't think we should "hide" a serialization exception in an empty result. What about propagate the exception?

2020-09-14 12:24 UTC, danielezonca commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
> +        }
Same as above

2020-09-14 12:24 UTC, danielezonca commented on addons/tracing/tracing-decision-common/pom.xml
> +      <artifactId>jackson-datatype-jdk8</artifactId>
What is this module used for?

2020-09-14 12:31 UTC, ruromero commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
>                  .build();
Propagate the exception up to where? I need advise here

2020-09-14 12:33 UTC, ruromero commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
> +        }
I tried to propagate it but I didn't know up to where or where to really deal with it. Any advise?

2020-09-14 13:16 UTC, ruromero commented on addons/tracing/tracing-decision-common/pom.xml
> +      <artifactId>jackson-datatype-jdk8</artifactId>
It's not needed. I added it by mistake. Thanks

2020-09-14 13:19 UTC, ruromero commented on addons/events/knative-eventing-addon/src/test/resources/application.properties
> +quarkus.index-dependency.cloudevents.artifact-id=cloudevents-http-restful-ws
No, it's not needed. With the service file it's enough to have the provider injected and available in other projects depending on this addon

2020-09-14 13:20 UTC, ruromero commented on addons/events/knative-eventing-addon/src/main/resources/META-INF/services/javax.ws.rs.ext.Providers
> +io.cloudevents.http.restful.ws.CloudEventsProvider
Yes, this code works in native mode. Actually it will allow any other library using the addon to have the CloudEventsProvider injected without any additional configuration.

2020-09-14 13:47 UTC, danielezonca commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
>                  .build();
@kostola 
Can you please support? What if an event is impossible to be serialized? (same question for comment below)

2020-09-14 13:49 UTC, danielezonca commented on addons/events/knative-eventing-addon/src/test/resources/application.properties
> +quarkus.index-dependency.cloudevents.artifact-id=cloudevents-http-restful-ws
Ok so it is not clear to me why you had to add this configuration only for the test. Shouldn't be possible to use service mechanism here too?

2020-09-14 15:07 UTC, ruromero commented on addons/events/knative-eventing-addon/src/test/resources/application.properties
> +quarkus.index-dependency.cloudevents.artifact-id=cloudevents-http-restful-ws
Yes, I deleted it

2020-09-15 10:20 UTC, ruromero commented on addons/events/knative-eventing-addon/src/test/resources/application.properties
> +quarkus.index-dependency.cloudevents.artifact-id=cloudevents-http-restful-ws
I temporarily added it back and can be removed in cloudevents-2.0.0-milestone3
see https://github.com/cloudevents/sdk-java/pull/233

2020-09-16 14:04 UTC, kostola commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
>                  .build();
With the previous API the `data` field was typed, so there's no particular error handling for serialization errors.
Imho sending a `CloudEvent` with `null` data, as I see here, is not very useful. I would avoid that.
I would rather log a more detailed error (possibly with the payload that triggered the error somehow) so that in a production environment it's possible to investigate by grabbing the logs of the services.
Wdyt @danielezonca @ruromero ?

2020-09-16 20:41 UTC, danielezonca commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
>                  .build();
Fine for me a more detailed log but what else? Error propagation until where?

2020-09-17 07:42 UTC, kostola commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
>                  .build();
I would catch the exception, log the message without sending a CloudEvent with `null` data and then that's it in the code. It seems to me a very rare error but correct me if I'm wrong.
Then the best way imho to catch those errors in a prod environment would be to setup a log management system (e.g. [Graylog](https://www.graylog.org/)) that ingests all the logs and allows custom triggers on specific messages to be configured.
Does this seem reasonable to you?

2020-09-17 09:06 UTC, kostola commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
>                  .build();
Probably the best solution for this method would be to return a `Optional<CloudEvent>` and let the caller decide how to handle the serialization failure with something like [ifPresentOrElse](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Optional.html#ifPresentOrElse(java.util.function.Consumer,java.lang.Runnable)) (which in my case would be to simply log the error without sending anything as I wrote above).

2020-09-17 09:08 UTC, danielezonca commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
>                  .build();
@ruromero 
Can you please verify if the proposed approach can be implemented? Return Optional<CloudEvent> and log error in caller if empty

2020-09-18 06:54 UTC, ruromero commented on addons/tracing/tracing-decision-api/src/main/java/org/kie/kogito/tracing/decision/event/CloudEventUtils.java
>                  .build();
@kostola logging the payload won't be of much help as it is an array of bytes representing anything (a Json object, a String, a serialized object in any language, etc.). In this case we expect an object of type E but if decoding failed you don't know how to represent the data content.

I think the log is fine as it is. It's an error saying the CloudEvent data cannot be deserialized with the stacktrace.

Regarding the Optional propagation. There are 2 chains of invocations:
1) BaseModelEventEmitter#publishDecisionModels. In this case it's simple, we decide whether to emit the event or not.
2) DefaultAggregator#aggregate: There are 2 invocations and for these cases the event is always created right before the invocation so it doesn't make sense to expect an error. If for some reason such error occurs I will throw an unchecked exception.

2020-09-18 13:35 UTC, ruromero commented
jenkins retest this

2020-09-21 19:41 UTC, ruromero commented
jenkins retest this

2020-09-21 21:01 UTC, ricardozanini approved these changes

2020-09-23 14:25 UTC, evacchi commented
Let's move this forward for now, we can refine in further PRs @ricardozanini

2020-09-23 14:26 UTC, merged