[KOGITO-2766] Refactoring initialization code
kiegroup/kogito-runtimes pull request #763
Opened 2020-09-14 11:06 UTC by fjtirado

Generated handlers are now passed to constructor explicitly (handlers
fields is
removed), which registers them, both for injection and non injection
paths (which means that when injection is not used, caller of the
constructor will explicitly have to pass it)

Configure and registerListeners methods are only generated if they have
content (if there are listeners)

If injection is not used, activate method will be invoked from
constructor. If it is active, then it is invoked using quarkus start
event or springboot post construct as it is now.

2020-09-15 13:24 UTC, evacchi requested changes
can you paste here an example of the new code that is being generated now? :)
also, I was hoping we were moving away from the `annotator ` mechanism in lieu of a template-based approach. We can do that in a subsequent refactoring, but any particular reason why you can't do that? How much code is still framework-specific?

2020-09-15 13:24 UTC, evacchi commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T witLazyInit(T node) { return node; }
`with`

2020-09-15 13:24 UTC, evacchi commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                // super(module.config().process())
remove comment

2020-09-15 13:35 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T witLazyInit(T node) { return node; }
Thanks

2020-09-15 13:35 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                // super(module.config().process())
This comment is not actually code, but displaying what the code below is generating, are we sure we want to remove it?

2020-09-15 13:40 UTC, fjtirado commented
> ay from the `annotator ` mechanism in lieu of a template-based approach. We can do that in a subsequent refactoring, but any particular reason why you can't do that? How much code is still framework-specific?

We still need to use CDI annotations for Constructor and for initialization.

2020-09-15 15:41 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
As far as I can see this concept only exists in `Spring` and not in `CDI` (even if quarkus impl should be lazy by default).
Why do you need it?

Minor note, can you add a javadoc?

2020-09-15 15:41 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +        return null;
What about return `Optional<MethodDeclaration>`?

2020-09-15 15:41 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +        return null;
What about return `Optional<MethodDeclaration>`?

2020-09-15 15:41 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +    private void forEachField (ClassOrInterfaceDeclaration clazz, FieldDeclaration fd) {
Can you please rename the method to better explain its scope? Something like `initializeField` or similar

2020-09-15 15:41 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +        }
If you make them return `Optional<MethodDeclaration>` you can replace with something like 
```suggestion
        internalConfigure(processMetaData).ifPresent(cls::addMember);
        internalRegisterListeners(processMetaData)::ifPresent(cls::addMember);
```

2020-09-15 15:41 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                                listener.getPackageDeclaration().map(pd -> pd.getName().toString()).orElse("") + "." +clazz.getName()),
If `getPackageDeclaration()` returns an empty `Optional` this will produce an invalid string: `.ClassName`
Can you please verify if `getPackageDeclaration()` can be empty (i.e. default package)?
If not I think it is better to throw an exception like "This should never happen" instead of a empty string.

In general we can probably replace the code with this alternative
```suggestion
                                listener.getPackageDeclaration().map(pd -> pd.getName().toString() + "." + clazz.getName()).orElse(clazz.getName()),
```
Wdyt?

2020-09-15 15:51 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
As you correctly detect, for SpringBoot we need to add lazy annotation to handlers passed as parameters in the constructor. 
SpringBoot has issues with circular dependencies when using construction injection. If, as happens in one of the examples, one of the beans injected into the handler, depends on the Process, SpringBoot wont start unless we include lazy annotation (this issue does not appear in Quarkus)
I use a descriptive name, but we can use a more abstract one for the new method something as constructorParam. wdyt?

2020-09-15 16:00 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
After thinking a while, I think for consistency with the existing interface, the word lazy needs to be there

2020-09-15 16:02 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +        return null;
Ill do it

2020-09-15 16:24 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
:thinking: I'm fine with the name, I have more concern with the need of this annotation: I'm worried that sooner or later this problem (circular dependencies) will appear again if we continue to use construction injection.
What if we generate the constructor with all the parameters (to allow manual instantiation) but then we inject on fields? Does it solve the need to have lazy init?

@evacchi wdyt? If this works I would prefer to do this change instead of have the risk to add `Lazy` annotation "everywhere"

2020-09-15 16:41 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
I think constructor injection is what this JIRA was all about (this allow us to remove fields and remove separate initialization). I do not see a big trouble with lazy if used where it should be (just the constructor parameters). Also, please notice this is a workaroung for SpringBoot, Quakus resolve circular dependencies without any issue.

2020-09-15 16:54 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
What Im trying to say is that annotating something with Lazy is not an issue at all. Which is an issue is to use construction injection on springboot without the lazy. If we use construction injection somewhere else, we need to have this into account (and the annotator will be ready).
Does it make sense to use constructor injection in this particular scenario, I think the answer is yes, so I vote going for it

2020-09-16 09:30 UTC, evacchi commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                // super(module.config().process())
oh ok it looked like older code

2020-09-16 09:54 UTC, evacchi commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
ok, here's what I think

1) I don't love the "Annotator" at all really :P I believe that we should actually move to templates everywhere.
2) We don't necessarily have to introduce templates with this PR but then I would at least wish for a follow-up JIRA where we try; [I am trying to do it for Rules -- the code there is arguably less, though](https://github.com/kiegroup/kogito-runtimes/pull/660)
3) However, the following code could be substituted for the injection of Instance/Collection 
(and in fact IIRC we were injecting a collection, before)


```java
    @javax.inject.Inject()
    public TravellersProcess(org.kie.kogito.app.Application app, org.kie.kogito.handlers.GreetingTravellerService_greetTraveller_3_Handler greetingTravellerService_greetTraveller_3_Handler, org.kie.kogito.handlers.TravellerAuditService_auditTraveller_7_Handler travellerAuditService_auditTraveller_7_Handler, org.kie.kogito.handlers.StoreTravellerService_storeTraveller_2_Handler storeTravellerService_storeTraveller_2_Handler) {
        super(app.config().process());
        this.app = app;
        org.kie.api.runtime.process.WorkItemManager workItemManager = services.getWorkItemManager();
        workItemManager.registerWorkItemHandler("org.acme.travels.services.GreetingTravellerService_greetTraveller_3_Handler", greetingTravellerService_greetTraveller_3_Handler);
        workItemManager.registerWorkItemHandler("org.acme.travels.services.TravellerAuditService_auditTraveller_7_Handler", travellerAuditService_auditTraveller_7_Handler);
        workItemManager.registerWorkItemHandler("org.acme.travels.services.StoreTravellerService_storeTraveller_2_Handler", storeTravellerService_storeTraveller_2_Handler);
        this.activate();
    }
```

in other words:

```java
    @javax.inject.Inject()
    public TravellersProcess(
        org.kie.kogito.app.Application app, 
        // java.util.Collection in the case of Spring
        javax.enterprise.inject.Instance<org.kie.api.runtime.process.WorkItemHandler> handlers) {
        super(app.config().process());
        this.app = app;
        org.kie.api.runtime.process.WorkItemManager workItemManager = services.getWorkItemManager();
        for (WorkItemHandler wih : handlers) {
            workItemManager.registerWorkItemHandler(wih.getClass().getCanonicalName(), wih);
        }
        this.activate();
    }
```

to the point where we can actually move the logic to a super constructor:

```java
protected AbstractProcess(
    org.kie.kogito.app.Application app, 
    // iterable is a common superclass between Instance (CDI) and Collection (Spring)
    Iterable<org.kie.api.runtime.process.WorkItemHandler> handlers) {
        this(app.config().process());
        this.app = app;
        org.kie.api.runtime.process.WorkItemManager workItemManager = services.getWorkItemManager();
        for (WorkItemHandler wih : handlers) {
            workItemManager.registerWorkItemHandler(wih.getClass().getCanonicalName(), wih);
        }
        this.activate();
}
```

thus transforming the code as such:


```java
    @javax.inject.Inject()
    public TravellersProcess(
        org.kie.kogito.app.Application app, 
        // java.util.Collection in the case of Spring
        javax.enterprise.inject.Instance<org.kie.api.runtime.process.WorkItemHandler> handlers) {
        super(app.config().process(), handlers);
    }
```

as you can see, this way we trim down the generated code considerably, we get a much more meaningful and simpler template

4) Now, for the `@Lazy` annotation, first of all I would like to know what's causing the issue, and rather try to solve the issue at its root if possible; IIRC Application gets injected ApplicationProcesses, which contains all of the available processes; this in a CDI/Spring context is _not_ a dependency of this class; however, this could be still cyclic; to resolve the cycle, it may be just enough to annotate the class `kogito-codegen/src/main/resources/class-templates/SpringProcessContainerTemplate.java`with `@Lazy`

5) if there is not way to break the cycle, then I'd rather annotate the constructor rather than the single parameters 

hope this answers all of your questions

2020-09-16 10:04 UTC, evacchi requested changes
see comment on constructor/templates

2020-09-16 10:59 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
Let me try to reply
1) and 2) I think are matter of a different JIRA which completely change the approach we are using and use two different templates rather than annotator (I confess Im not a fan of that approach and do not see the advantage, we are going to duplicate a lot of code in the templates as already happen with resources) 
In any case, place where the annotator is used are now minimized in codegen., 
3) Since we are using a generator, I think is better to restrict the handler to the ones that really makes sense for a particular process, thats why Im using concrete handlers rather than a generic list, so I ensure only those handlers that are part of the process definition are registered. This was my humble aportation to the JIRA description and I think is an improvement.
Also please note that first parameter of register handler is not really equal to class cannonical name
Name is org.acme.travels.services.GreetingTravellerService_greetTraveller_3_Handler
Class name is org.kie.kogito.handlers.GreetingTravellerService_greetTraveller_3_Handler 
If they matched the code I would generate is
```
    @javax.inject.Inject()
    public TravellersProcess(org.kie.kogito.app.Application app, org.kie.kogito.handlers.GreetingTravellerService_greetTraveller_3_Handler greetingTravellerService_greetTraveller_3_Handler, org.kie.kogito.handlers.TravellerAuditService_auditTraveller_7_Handler travellerAuditService_auditTraveller_7_Handler, org.kie.kogito.handlers.StoreTravellerService_storeTraveller_2_Handler storeTravellerService_storeTraveller_2_Handler) {
        super(app.config().process());   registerHandler(greetingTravellerService_greetTraveller_3_Handler,travellerAuditService_auditTraveller_7_Handler,storeTravellerService_storeTraveller_2_Handler);
}
```
But this can simply not be done, neither what you are proposing. 
3a) BTW, do we need app to be a field at all?
4) Circular dependency happens here https://github.com/kiegroup/kogito-examples/blob/stable/process-optaplanner-quarkus/src/main/java/org/kie/kogito/examples/service/FlightSeatingSolveService.java. This is a service injected by the handler that is injecting the process. Since there is not way to prevent that circular depedency, lazy is the solution for spring boot. 
5) I applied a fine grane approach, only annotate with lazy what really needs to be annotated (please note that currently Application bean is not annotated with lazy because we know for sure that there is not circular dependency here), but of course we can switch to coarse approach and lazy initialize all constructor parameters

2020-09-16 11:39 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
@evacchi I updated code according to your point 3) proposal, please review

2020-09-16 11:40 UTC, evacchi commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
2) ok let's file a jira for that
3) we are using the Collection approach for ApplicationConfig and ProcessConfig. I think this is a simpler approach, and although I agree we could be more specific in the way we generate code, I have also come to the conclusion it is better to lean on the side of simplicity to reduce the complexity and amount of code we generate. In this case, I'd rather uniform the codebase with that approach; otherwise we would have to modify ProcessConfig et al. for consistency.

>  Also please note that first parameter of registerhandler method is not really equal to class cannonical name
Name is org.acme.travels.services.GreetingTravellerService_greetTraveller_3_Handler

weird why is that so? How was that solved before? I am pretty sure we were injecting a collection

3a) the app is used inside process definition, that's why it's passed on (Strictly speaking we may not necessarily always need it, it depends on how the process is defined)


4) I'd argue we should make lazy the `Process` field of that service in the example instead, wdyt ? :)

2020-09-16 11:45 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
regarding 3). I think this is simple enough
```
  public TravellersProcess(org.kie.kogito.app.Application app) {
        this(app, new org.kie.kogito.handlers.GreetingTravellerService_greetTraveller_3_Handler(), new org.kie.kogito.handlers.TravellerAuditService_auditTraveller_7_Handler(), new org.kie.kogito.handlers.StoreTravellerService_storeTraveller_2_Handler());
    }

    @javax.inject.Inject()
    public TravellersProcess(org.kie.kogito.app.Application app, org.kie.kogito.handlers.GreetingTravellerService_greetTraveller_3_Handler greetingTravellerService_greetTraveller_3_Handler, org.kie.kogito.handlers.TravellerAuditService_auditTraveller_7_Handler travellerAuditService_auditTraveller_7_Handler, org.kie.kogito.handlers.StoreTravellerService_storeTraveller_2_Handler storeTravellerService_storeTraveller_2_Handler) {
        super(app, java.util.Arrays.asList(greetingTravellerService_greetTraveller_3_Handler, travellerAuditService_auditTraveller_7_Handler, storeTravellerService_storeTraveller_2_Handler));
    }

    public TravellersProcess() {
    }
```

2020-09-16 11:46 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
4) I think we cannot guarantee what the user code will do. I think is better to prevent this issue on runtime side

2020-09-16 11:52 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
> weird why is that so? How was that solved before? I am pretty sure we were injecting a collection
handler.getName

2020-09-16 12:55 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
Regarding lazy, I removed from process parameters and add to handler constructor.

2020-09-16 13:19 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
Please note that activate needs to be invoked from child class constructor, since it relies on abtract method process and this is only avaiable when super() has finished

2020-09-16 13:20 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    default <T extends NodeWithAnnotations<?>> T withLazyInit(T node) { return node; }
Rather than new mthod withLazy, a new parameter lazy has been added to withInjection method, default value being false

2020-09-16 13:37 UTC, evacchi approved these changes
alright let's move this forward

2020-09-16 16:39 UTC, danielezonca approved these changes
Thanks for the PR, adding just a minor commend but LGTM :+1:

2020-09-16 16:39 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    <T extends NodeWithAnnotations<?>> T withInjection(T node, boolean lazy);
What about rename `lazy` to something like `forceLazyInit` or similar? Mainly because lazy=false doesn't mean eager but means "use framework default"

2020-09-16 16:48 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/di/DependencyInjectionAnnotator.java
> +    <T extends NodeWithAnnotations<?>> T withInjection(T node, boolean lazy);
good point, done

2020-09-17 03:01 UTC, cristianonicolai approved these changes

2020-09-17 03:01 UTC, merged