KOGITO-3211 - SW update to latest spec and runtime updates
kiegroup/kogito-runtimes pull request #768
Opened 2020-09-16 05:00 UTC by tsurdilo

Signed-off-by: Tihomir Surdilovic <tsurdilo@redhat.com>

Many thanks for submitting your Pull Request :heart:! 

@ricardozanini 
This PR aligns the kogito SW parsing with the latest of the specification
Updated parsing and generation code to work with the latest Switch state
Updated all examples and tests so the json and yaml use the latest spec definitions

2020-09-16 16:34 UTC, tsurdilo commented
Jenkins retest this please

2020-09-16 19:36 UTC, ricardozanini reviewed
Just a few nitpicks. :)

2020-09-16 19:36 UTC, ricardozanini commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/ServerlessWorkflowParser.java
> +//        }
Can we get rid of the commented code?

2020-09-17 14:17 UTC, tsurdilo commented
@ricardozanini added the missing test for switch state where conditions define end of workflow.

2020-09-21 17:54 UTC, tsurdilo commented
Jenkins retest please

2020-10-13 19:43 UTC, tsurdilo commented
rebased
will do some more updates in additional pushes

2020-10-14 13:52 UTC, ricardozanini commented
Many thanks @tsurdilo please let me know when this is ready for review. So we can get back to the example.

2020-10-15 14:48 UTC, ricardozanini approved these changes

2020-10-20 08:42 UTC, evacchi requested changes
I have seen a refactoring/addition of a WorkflowValidator, but I couldn't find where it is actually used, can you point out where this is applied? there is similar work being done for DMN and I've been thinking at some point we should introduce a common "validation" phase across all components.

Make sure to clean up your imports, I found a few occurrences that are probably outdated.

2020-10-20 08:42 UTC, evacchi commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/serializers/EventStateSerializer.java
> +import java.io.IOException;
I am seeing a few of these imports `java.io.IOException` in these classes, but I don't think the exception is actually thrown, you can probably remove them.

2020-10-20 08:42 UTC, evacchi commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/serializers/ForEachStateSerializer.java
> +import java.io.IOException;
see eg. another here

2020-10-20 08:42 UTC, evacchi commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/serializers/InjectStateSerializer.java
> +import java.io.IOException;
etc. etc. :)

2020-10-20 08:42 UTC, evacchi commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/util/ServerlessWorkflowUtils.java
> +        return "return !((java.util.List<java.lang.String>) com.jayway.jsonpath.JsonPath.parse(((com.fasterxml.jackson.databind.JsonNode)kcontext.getVariable(\"" + processVar + "\")).toString()).read
I wish we will be able to revisit some of this codegen in the near future. String concat is a bit error-prone this way

2020-10-22 13:25 UTC, cristianonicolai reviewed
@tsurdilo overall looks good, only some minor comments. SOme of the file changes could be avoided in my opinion, just moving things around, changing headers, etc...

2020-10-22 13:25 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/util/ServerlessWorkflowUtils.java
> +        return "return !((java.util.List<java.lang.String>) com.jayway.jsonpath.JsonPath.parse(((com.fasterxml.jackson.databind.JsonNode)kcontext.getVariable(\"" + processVar + "\")).toString()).read
+1, would be good to have some way to at least hide this inside a utility method.

2020-10-22 13:25 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow/src/test/java/org/jbpm/serverless/workflow/utils/WorkflowTestUtils.java
> +import java.io.*;
maybe do a more specific import?

2020-10-22 13:25 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/workflow/BaseWorkflow.java
> +            String jsonString = jsonObjectMapper.writeValueAsString(workflow);
I think you can try something like the code below to avoid the roundtrip to String and back.
```suggestion
            JsonNode jsonNode = jsonObjectMapper.valueToTree(workflow)
```

2020-10-23 02:21 UTC, tsurdilo commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/serializers/EventStateSerializer.java
> +import java.io.IOException;
The Serializers "serialize" method throws IOException

2020-10-23 02:22 UTC, tsurdilo commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/serializers/ForEachStateSerializer.java
> +import java.io.IOException;
Yeah BeanSerializerFactory.instance.createSerializer throws it and we just re-throw in serialize method that calls it.

2020-10-23 02:23 UTC, tsurdilo commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/serializers/InjectStateSerializer.java
> +import java.io.IOException;
:)

2020-10-23 02:23 UTC, tsurdilo commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/util/ServerlessWorkflowUtils.java
> +        return "return !((java.util.List<java.lang.String>) com.jayway.jsonpath.JsonPath.parse(((com.fasterxml.jackson.databind.JsonNode)kcontext.getVariable(\"" + processVar + "\")).toString()).read
ok

2020-10-23 02:26 UTC, tsurdilo commented on jbpm/jbpm-serverless-workflow/src/test/java/org/jbpm/serverless/workflow/utils/WorkflowTestUtils.java
> +import java.io.*;
ok

2020-10-23 02:29 UTC, tsurdilo commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/api/workflow/BaseWorkflow.java
> +            String jsonString = jsonObjectMapper.writeValueAsString(workflow);
ok

2020-10-23 12:53 UTC, ricardozanini commented
@evacchi @cristianonicolai could you guys please take a second look? I believe we addressed your concerns.

It's worth mentioning that we will remove most of this code in favor of the [sdk-java](https://github.com/serverlessworkflow/sdk-java) very soon.

2020-10-23 13:02 UTC, evacchi approved these changes

2020-10-23 13:52 UTC, cristianonicolai approved these changes

2020-10-23 19:53 UTC, ricardozanini commented
Error not related:
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.9.1:yarn (yarn test) on project kogito-apps-ui-packages: Failed to run task: 'yarn run test --registry=https://repository.engineering.redhat.com/nexus/repository/registry.npmjs.org/' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

2020-10-23 19:53 UTC, ricardozanini commented
Jenkins test please

2020-10-23 19:56 UTC, ricardozanini commented
jenkins test this please

2020-10-23 21:37 UTC, merged