[KOGITO-3158] Adding RestTaskHandler
kiegroup/kogito-runtimes pull request #778
Opened 2020-09-18 19:26 UTC by fjtirado

Still not working in native mode (Jax-rs client does not work after all, needs to be replaced by a different one, Im going to try vert.x, but Im not 100% confident and honestly believe we need different implementation for Quarkus and Springboot), but anyway I think there are parts that are ready to review (so we can move forward soon when the change of library is done)

"Questionable" decisions I have taken so far:

1. -  New work item handler for Rest invocations (RestTaskHandler) has been added to jbpm-flow and included in the list of default task handlers. The other alternative is to create two implementation, one for Quarkus and another for SpringBoot (I need advice on the location if we took that path)
2. - Since input/output parameters can be Json objects (when serverless) or Pojo (when bpmn), rather than putting that knowledge in the hadnler, I have tried to encapsulate the details using Function, Supplier, Bifunction generated by code generator, but where the runtime part is located at flow (JsonPathResolver):
- Supplier is used when generating code to fill the work iterm parameter with objects (either function or bifunction)
- Function is used to calculate the objects to be used in different parts of the request from the input model
- Bifunction is used to format the ouputs of the task (in case of jsonobject a non deep merge is performed)

2020-09-21 09:31 UTC, fjtirado commented
Currently working on replacing jax-rs by vert.x mutiny client (https://quarkus.io/guides/vertx#using-vert-x-clients). Since vertx uses injection, this requires few changes on codegen, so a similar approach to current service handlers is followed (partially generated, partyally constant)

2020-09-21 14:32 UTC, ricardozanini reviewed
I did not see nothing wrong if this implementation, but I think a demo would be a nice to have. Maybe a call tomorrow morning showing case your example, @fjtirado 
@evacchi @cristianonicolai @tsurdilo what u think?

2020-09-21 14:32 UTC, ricardozanini commented on jbpm/jbpm-flow/pom.xml
> +        <artifactId>json-path</artifactId>
@tsurdilo don't we already have this dependency in your PR? #768

2020-09-21 14:32 UTC, ricardozanini commented on kogito-build-parent/pom.xml
> +    <version.org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec>2.0.1.Final</version.org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec>
This is a big name for a property! :sweat_smile:

2020-09-21 15:02 UTC, fjtirado commented on kogito-build-parent/pom.xml
> +    <version.org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec>2.0.1.Final</version.org.jboss.spec.javax.ws.rs.jboss-jaxrs-api_2.1_spec>
this needs to be removed, since is not longer used

2020-09-21 15:03 UTC, fjtirado commented on jbpm/jbpm-flow/pom.xml
> +        <artifactId>json-path</artifactId>
> I did not see nothing wrong if this implementation, but I think a demo would be a nice to have. Maybe a call tomorrow morning showing case your example, @fjtirado
> @evacchi @cristianonicolai @tsurdilo what u think?

Please check example in this PR https://github.com/kiegroup/kogito-examples/pull/369

2020-09-21 15:04 UTC, fjtirado commented
> I did not see nothing wrong if this implementation, but I think a demo would be a nice to have. Maybe a call tomorrow morning showing case your example, @fjtirado
> @evacchi @cristianonicolai @tsurdilo what u think?

Please check serverless workflow example in https://github.com/kiegroup/kogito-examples/pull/369

2020-09-21 17:31 UTC, tsurdilo commented
Initial reaction is to ask -> How is this better or different than what we have in v7? The jBPM rest workitem handler is pretty much same but more powerful - https://github.com/kiegroup/jbpm/blob/master/jbpm-workitems/jbpm-workitems-rest/src/main/java/org/jbpm/process/workitem/rest/RESTWorkItemHandler.java? Could we align the two so at least they have the same functionalities? 

Also the "type" check on SW markup function def is most likely going away. We will remove the type param from the specification prob soon, so that will need to be all updated. It would be nice if the impl is just concerned with the workitem and not too much worry about the Impl with SW atm. WDYT?

2020-09-21 17:59 UTC, tsurdilo commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JSonPathResultHandler.java
> +public class JSonPathResultHandler implements BiFunction<Object, JsonObject, Object> {
If you are addressing results of a JsonPath query, it will/should always be an array.

2020-09-21 18:05 UTC, tsurdilo commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JsonPathResolver.java
> +public class JsonPathResolver implements UnaryOperator<Object> {
Are we exposing this to users in public api? If so it could also be used insides script expressions which is nice.
I would change it tho so it can be used easier, for example JsonPathResolver.resolve(....). much easier to deal w/ in expressions as such

2020-09-21 18:09 UTC, tsurdilo commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +        int start = endPoint.indexOf('{');
Don't get this:
1) It seems very workflow specific , but then again in new version the queries are enclosed in '{{' and '}}'.
2) Data passed to functions even in SW are not always expressions. It can be custom JSON objects as well. 
3) This seems not useful for BPMN2 scenarios no?
'

2020-09-21 18:12 UTC, tsurdilo commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/core/ServerlessWorkflowFactory.java
> +    public Node restServiceNode(long id,
Wonder since this defines workitem we can have a generic getWorkitemNode(....) method that can handle any future workitems that we might expose in kogito like this one.

2020-09-21 18:12 UTC, tsurdilo commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/core/ServerlessWorkflowFactory.java
> +                // assuming param value is json string path
Yeah, not a very correct assumption :) It can also be custom JSON data.

2020-09-21 18:20 UTC, tsurdilo commented
@ricardozanini I left some small comments, and an overall question :) Will look into more details laster today.

I think that this pr addresses a future demo needs maybe that you are trying to create which is nice.
The thing I was expecting is for a PR like this to only include RestTaskHandler. I think it is pretty obvious that even if we ported the v7 workitem handler to kogito that "rest calls would work" for both bpmn2 and workflow. 
The addition of the SW specific stuff is nice, but again the workflow backend is really moving fast, with spec changes especially that for kogito-runtiomes I would only look at the workitem itself and not the other parts added.

2020-09-21 18:31 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JSonPathResultHandler.java
> +public class JSonPathResultHandler implements BiFunction<Object, JsonObject, Object> {
The resulf of the rest invocation needs to be merged into the json tree, so json queries can be performed over it. 
The point is that defailt of the conversion are hidden into that object, so no serverless no handler needs to be changes, just this object (or invoke a different one in generator)

2020-09-21 18:33 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JsonPathResolver.java
> +public class JsonPathResolver implements UnaryOperator<Object> {
No, this is not a public API. And even if it was, it is implementin a well know interface defined in jdk8, user will expect an apply as publis method (but it does not matter since it is not public)

2020-09-21 18:37 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +        int start = endPoint.indexOf('{');
This code is replacing parameters in the endpoint. JAX-RS convention is to include the path parameters to be replaced between {}. 
This applies both for POJO/Json parameters, both for BPMN/SW.

2020-09-21 18:37 UTC, fjtirado commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/core/ServerlessWorkflowFactory.java
> +    public Node restServiceNode(long id,
I think parameters will be different depending on the work item type, probably some of this code can be moved to a common method, but most parameters names will differ.

2020-09-21 18:41 UTC, fjtirado commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/core/ServerlessWorkflowFactory.java
> +                // assuming param value is json string path
Yes, I introduced that comment to make possible that, when JSON pojo support is added to SW, a new Supplier that deals with POJO can be added here

2020-09-21 18:46 UTC, fjtirado commented
> Also the "type" check on SW markup function def is most likely going away. We will remove the type param from the specification prob soon, so that will need to be all updated. It would be nice if the impl is just concerned with the workitem and not too much worry about the Impl with SW atm. WDYT?

I needed to check that the example worked, also I need to understand the whole scenario to define the interface of the handler (the parameters requested). I do not think any of the changes performed in the SW parser jeopardize any evolution of it, I do not pretend them to be definitive, Im just trying to make the scenario work end to end. As specified in the doc that I took as "requirements" type equal to "rest" is the way to identifiy a function that is going to call a rest interface.

2020-09-21 18:54 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JsonPathResolver.java
> +public class JsonPathResolver implements UnaryOperator<Object> {
Please note that this class is for now specific to SW, since it is dealing with json path resolution

2020-09-21 21:26 UTC, tsurdilo commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JSonPathResultHandler.java
> +public class JSonPathResultHandler implements BiFunction<Object, JsonObject, Object> {
Ok, what I'm thinking is that it would be better for SW to deal with this via a script task that does this, than having this code in /jbpm/process/instance. Reason being is that SW should be able to do this independently of the bpmn2 processes for example. Or allow for SW to overwrite this class if possible, so it can evolve this independently

2020-09-21 21:34 UTC, tsurdilo commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +        int start = endPoint.indexOf('{');
Ok. There are things missing here like accept headers, read timeouts, content type etc etc. Also expecting a hard-coded password in the workflow markup is something noone is going to really use as its pretty much only for demos I assume. 
I hardly think that even for a demo anyone out there that still uses hard-coded passwords in their apps is even thinking about moving to a serverless architectures. wdyt?

2020-09-21 21:35 UTC, tsurdilo commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JsonPathResolver.java
> +public class JsonPathResolver implements UnaryOperator<Object> {
I really do not care if it uses a well or not well known interface or not :) My concern is about usability.

2020-09-21 21:40 UTC, tsurdilo commented
> As specified in the doc that I took as "requirements" , type equal to "rest" is the current way to identify a function that is going to call a rest interface.

Yeah that's why I keep repeating myself to try to do this as generic as possible. I am updating the specification alot so its a moving target. When we started the integration with kogito the type param was the most natural way to distinguish but its really not portable at all. The spec is going to soon remove the type param and replace it completely most likely with forcing an openapi def. Runtimes that want to do something else can use the metadata to define this but it will be noted that its not portable. So we will have to look at this impl anyways alot more and change things in the future.

2020-09-22 06:52 UTC, ruromero requested changes

2020-09-22 07:48 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JSonPathResultHandler.java
> +public class JSonPathResultHandler implements BiFunction<Object, JsonObject, Object> {
SW is specifying that this class should be used when populating the workitem with parameters 
I think this is cleaner that forcing the sw writer to introduce a script task

2020-09-22 07:50 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JsonPathResolver.java
> +public class JsonPathResolver implements UnaryOperator<Object> {
I first put this class in sw project, but it turns out that classes there are not used at runtime, thats the only reason this class was add to flow, but I agree is not the better place. The goal of doing so is that this class should be in classpath at runtime

2020-09-22 07:53 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +        int start = endPoint.indexOf('{');
RestTaskHadled needs evolution (as the SW flow ;)). I think at this stage we should care about the contract (aka how the serverles parser fills the work node item)
Content type is assumed to be json (is going to be different in any case?)
Headers can be specified as a parameter of the workitem (as method, user and password)
I agree that password for basic authentication needs to be at least encrypted (which encryption?)

2020-09-22 07:54 UTC, fjtirado commented
> > As specified in the doc that I took as "requirements" , type equal to "rest" is the current way to identify a function that is going to call a rest interface.
> 
> Yeah that's why I keep repeating myself to try to do this as generic as possible. I am updating the specification alot so its a moving target. When we started the integration with kogito the type param was the most natural way to distinguish but its really not portable at all. The spec is going to soon remove the type param and replace it completely most likely with forcing an openapi def. Runtimes that want to do something else can use the metadata to define this but it will be noted that its not portable. So we will have to look at this impl anyways alot more and change things in the future.

When you update the specification, you will change the way the node factories are invoked by the parser, you can do the same with the new one

2020-09-22 07:57 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JSonPathResultHandler.java
> +        ObjectNode result = (ObjectNode) inputParameter;
Null check is already performed in the Handler (inputModel is taking from parameter, which a mandatory attribute)
If this class in being invoked is because SW fill ResultHander parameter and it did that because the Parameter object is an ObjectNode.

2020-09-22 07:57 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JSonPathResultHandler.java
> +    private void addValue (ArrayNode result, Object value) {
Thanks, I have the formatter disable by default

2020-09-22 07:59 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JSonPathResultHandler.java
> +    private ObjectNode transform (JsonObject src, ObjectNode target) {
Since I have to merge the input with the response, I prefer to avoid encode/decode step and perform the merge programatically

2020-09-22 08:00 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +        @SuppressWarnings("unchecked")
yes, but as a generic rule the annotation should in lowest possible scope to prevent other unchecked casting to be unnoticed

2020-09-22 08:00 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +        HttpResponse<Buffer> response = method.equalsIgnoreCase("POST") || method.equalsIgnoreCase("PUT")
sure, thanks

2020-09-22 12:15 UTC, ricardozanini commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +        int start = endPoint.indexOf('{');
Security constraints should be handled by injected configuration properties, please see: https://docs.google.com/document/d/1GgAEAAoiBWsQ3zDKsW_w_Uml4cg5C5dnG6tlGQZlY0g/edit#heading=h.9qnfgrgjxwzl

2020-09-22 12:16 UTC, ricardozanini commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +        int start = endPoint.indexOf('{');
There's a JIRA for that: https://issues.redhat.com/browse/KOGITO-3160

2020-09-22 12:18 UTC, evacchi reviewed
In general, I am not really fond of the usage of Unary/Function/BiFunction as classes; for instance, they are not easily searchable; e.g. if you're looking for all impls that may be used you'll find a ton of them. 

 Wherever there is a specific usage -- i.e., non-lambda -- I'd rather see a named interface with a descriptive name; otherwise I'll find myself asking "what is BiFunction" doing ? 
 
 For the Supplier<T> I probably don't care that much, but for Function/BiFunciton, if I am understanding correctly, the purpose is to customize the WorkItem implementation; so why not e.g. defining an (possibly abstract, if there are no meaningful defaults) rest workitem impl, and override those at use-sites?

In this case we would probably have at least 2 meaningful sub-classes 1 for plain processes and 1 for serverless workflows.

WDYT?

2020-09-22 12:18 UTC, evacchi commented on jbpm/jbpm-flow/pom.xml
> +        <artifactId>json-path</artifactId>
I wonder if we can make this available as an addon so that we don't pollute the core with external deps (maybe another separate jira)

2020-09-22 12:21 UTC, ricardozanini commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RestTaskDescriptor.java
> +    public static String getClassName(ProcessMetaData processMetadata) {
I asked myself the same thing.

2020-09-22 12:25 UTC, ricardozanini commented
> @ricardozanini I left some small comments, and an overall question :) Will look into more details laster today.
> 
> I think that this pr addresses a future demo needs maybe that you are trying to create which is nice.
> The thing I was expecting is for a PR like this to only include RestTaskHandler. I think it is pretty obvious that even if we ported the v7 workitem handler to kogito that "rest calls would work" for both bpmn2 and workflow.
> The addition of the SW specific stuff is nice, but again the workflow backend is really moving fast, with spec changes especially that for kogito-runtimes I would only look at the workitem itself and not the other parts added.
> 
> The rest of stuff like the integrations with the workflow maybe can be done inside a separate branch you use to create your demos from, until we figure out what exactly to change for specification. Would that work for you ?

Well, I won't run any demos requiring this feature for now, so I'd say that we should agree with an implementation and move forward. After finishing the work in #768, I'll finish the example https://github.com/kiegroup/kogito-examples/pull/351. And then I will circle back to this and update that demo to use `rest` instead of `interface`, manually wrapping the REST calls within the project.

So, whatever you guys decide. I will get back to it to add Kubernetes SVC discovery to the endpoints anyway, so I'm on your hands.

2020-09-22 13:44 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RestTaskDescriptor.java
> +    public static String getClassName(ProcessMetaData processMetadata) {
because the exact same thing is donde for ServiceTaskHander. I can use template, but the code is going to be the same

2020-09-22 13:49 UTC, fjtirado commented
> In general, I am not really fond of the usage of Unary/Function/BiFunction as classes; for instance, they are not easily searchable; e.g. if you're looking for all impls that may be used you'll find a ton of them.
> 
> Wherever there is a specific usage -- i.e., non-lambda -- I'd rather see a named interface with a descriptive name; otherwise I'll find myself asking "what is BiFunction" doing ?
> 
> For the Supplier I probably don't care that much, but for Function/BiFunciton, if I am understanding correctly, the purpose is to customize the WorkItem implementation; so why not e.g. defining an (possibly abstract, if there are no meaningful defaults) rest workitem impl, and override those at use-sites?
> 
> In this case we would probably have at least 2 meaningful sub-classes 1 for plain processes and 1 for serverless workflows.
> 
> WDYT?

I was trying to avoid having specific subclasses for sw or bpmn there, thats why Im using Function. I think the usage is pretty clear, but what we can do is to define a specific interface with a well define name that extends BiFunction and the issue of searching the implementation will not longer be a problem

Regarding the jsonpath dependency, I think is prery clear that JsonPathResolver and that dependency should be outside of flow, but in a place where they are included in runtime classpath (serverles workflow is used only at compilation)

2020-09-22 14:26 UTC, evacchi commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RestTaskDescriptor.java
> +    public static String getClassName(ProcessMetaData processMetadata) {
I'd prefer to move as much code as possible to templates, especially new code :)

2020-09-22 15:25 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RestTaskDescriptor.java
> +    public static String getClassName(ProcessMetaData processMetadata) {
yes, Ill move to template

2020-09-22 15:45 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RestTaskDescriptor.java
> +    public static String getClassName(ProcessMetaData processMetadata) {
done

2020-09-22 15:59 UTC, fjtirado commented
All comments incorporated. 
Since the functional is creating some controversy, let me try to explain my view and why Im using it rather than an OOP approach. 
Im trying to implement a Strategy pattern, the objective is that RestTaskHandler is not aware of the different way to resolve a parameter to be included in the rest invocation. So rather than introduce an if (POJO) then or if (JSONTREE) in the handler itslef (which implies that the Handler is aware of the different invokers and also implies that the handler needs to be modified if a third actor enters into the picture) , the different parameter are evaluated against workitem input using a Function provided by the creator of the work item node (in this case SW parser) 
Thats the overall idea and I think all agree on that. 
Now the details. 
Currently the two function objects, the one to be used for parameter resolution and the one to be used for output merging are located in flow project. This classed depends on a json path library. 
This is not the inteded final location, but the currently simplest one in order to achieve the purpose of these classes being added to classpath on runtime (if located in serverless wf project, they wont be in runtime classpath and an exception will be thrown). These classes, together with the library dependency, should be moved to a module, when available. So, take the current one as a temporary location. The important thing is that they are not directly referenced from the handler, so, when the final location is available, they will be moved there without having to change anything else. 
The other quesiton is why functional interface rather than subclassing the evaluate and the merge abstract functions. The answer, a very subttle one, is to give us more flexibility in case some parameters are resolved from JsonTree and anothers from Pojo (that probably will hardly happen). Since these function objects are instantiated by the generators, we can achieve that flexibility without compromising complexity, since the generator, rather than deciding the name of the subclass base on a global approach, can dedice which function to use to resolve a parameter based on each parameter (it is true that currently, since WF uses only Json Tree, all functions instantiated are of the Json tree type, but the point is that we change that just in the generator, without affecting the RestTaskHandler. 
Hope that now the code is clearer to everyone.

2020-09-23 08:35 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +        String user = (String) parameters.remove(USER);
me neither, but this is what is already happening in v7 version of the rest handler.

2020-09-23 08:37 UTC, fjtirado commented
https://github.com/kiegroup/kogito-runtimes/pull/778#discussion_r493140674
As I said in my last comment, JsonPath will be moved out of flow when we have a better place, but mutiny dependency must stay if we want RestHandler to be part of flow. They has to be together.

2020-09-23 08:41 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JsonPathResolver.java
> +    private Object readValue (JsonNode node) {
formatted

2020-09-23 08:42 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
> +    private Boolean asBoolean (Object value) {
WorkItemNodeVisitor changes has been formatted now

2020-09-23 08:43 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
> +    private Integer asInteger (Object value) {
formatted

2020-09-23 10:47 UTC, fjtirado commented
Added unit test for increasing coverage

2020-09-23 15:52 UTC, fjtirado commented
PR has been updated to solve the dependency issue. 
Rather than in jbpm-flow, RestTaskHandler has been included in a project called jbpm-rest-handler and SW runtime classes (JSonPathResolver and JSonPathResultHandler) has been included in a project called jbpm-serverless-worflow-runtime. 
This way, SW developers can update jbpm-serverless-workflow-runtime when the SE specification evolves and jbpm-flow does not depend on vert.x

2020-09-23 16:12 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JsonPathResolver.java
> +public class JsonPathResolver implements UnaryOperator<Object> {
Class has been moved to serverless-workflow-runtime project (so can be edited by SW developers). It now implementes a well defined interface rather than the generic one

2020-09-23 16:13 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/jbpm/process/instance/impl/rest/JSonPathResultHandler.java
> +public class JSonPathResultHandler implements BiFunction<Object, JsonObject, Object> {
Please read https://github.com/kiegroup/kogito-runtimes/pull/778#issuecomment-697583850

2020-09-23 16:13 UTC, fjtirado commented on jbpm/jbpm-flow/pom.xml
> +        <artifactId>json-path</artifactId>
Classes and dependency moved to a different project than flow

2020-09-23 16:25 UTC, tsurdilo commented on jbpm/jbpm-rest-handler/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +            request.send(handler);
Any reason we are not sending json here as well? For SW at least the content type should always be application/json.

2020-09-23 16:27 UTC, tsurdilo commented
Would it be possible to get tests that call methods from https://petstore.swagger.io/ or something real?

2020-09-23 16:34 UTC, tsurdilo commented
> PR has been updated to solve the dependency issue.
> Rather than in jbpm-flow, RestTaskHandler has been included in a project called jbpm-rest-handler and SW runtime classes (JSonPathResolver and JSonPathResultHandler) has been included in a project called jbpm-serverless-worflow-runtime.
> This way, SW developers can update jbpm-serverless-workflow-runtime when the SE specification evolves and jbpm-flow does not depend on vert.x

@cristianonicolai based on this comment, wouldnt it make more sense to just have this whole thing as an addon then? This seems to be a little bit in-between. WDYT?

2020-09-23 18:29 UTC, fjtirado commented on jbpm/jbpm-rest-handler/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +            request.send(handler);
Line 108 is a GET or DELETE call, so there is not body, unlike POST or PUT call. 
Json output is handled by ResultTaskResultHandler implementation provided In ResultHandler parameter. In the case of the example JsonPathResultHandler

2020-09-24 01:06 UTC, cristianonicolai commented
> > PR has been updated to solve the dependency issue.
> > Rather than in jbpm-flow, RestTaskHandler has been included in a project called jbpm-rest-handler and SW runtime classes (JSonPathResolver and JSonPathResultHandler) has been included in a project called jbpm-serverless-worflow-runtime.
> > This way, SW developers can update jbpm-serverless-workflow-runtime when the SE specification evolves and jbpm-flow does not depend on vert.x
> 
> @cristianonicolai based on this comment, wouldnt it make more sense to just have this whole thing as an addon then? This seems to be a little bit in-between. WDYT?

Yep, that makes sense  to me. But how about the SW specific part, are you ok to have this in the sw runtimes module that @fjtirado  proposed here? Problem was that is introduces dependecy to json path that would not be needed for bpmn projects.

2020-09-24 08:06 UTC, fjtirado commented
> > Would it be possible to get tests that call api from https://petstore.swagger.io/ or something real?
> 
> @tsurdilo @fjtirado perhaps use something like https://quarkus.io/guides/rest-client#using-a-mock-http-server-for-testsor https://www.testcontainers.org/modules/mockserver/ for integration tests so we don't depend on an external system?

Rest calls are tested in the example https://github.com/kiegroup/kogito-examples/pull/369. The example implements a dummy rest server.

2020-09-24 08:08 UTC, fjtirado commented
> se to me. But how about the SW specific part, are you ok to have this in the sw runtimes module that @fjtirado proposed here? Problem was that is introduces dependecy to json path that would not be needed for bpmn projects.

Also in one of his comments, Tihomir was asking about the possibility of chaging those classes (JsonPathResolver and JsonPathResultHander). If they are located in a separate, SW specific project, ha can freely change them without affectig bpmn code

2020-09-24 08:08 UTC, fjtirado commented
jenkins retest this

2020-09-24 09:37 UTC, evacchi approved these changes
looks good, just left 1 minor comment

2020-09-24 09:38 UTC, evacchi commented
there are a few issues with the build @fjtirado

2020-09-24 10:17 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
> +    private Expression getParameterExpr(String type, Object value) {
Checked, returning null literal expr in that case

2020-09-24 10:18 UTC, fjtirado commented
> there are a few issues with the build @fjtirado

they seem unrelated, something corcerning knative-event addon

2020-09-24 12:06 UTC, ruromero commented
jenkins retest this

2020-09-24 12:17 UTC, evacchi commented
with the help of @ricardozanini there are a few issues with the pom

```
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM org.kie.kogito:jbpm-rest-handler:1.0.0-SNAPSHOT (/home/ricferna/dev/github.com/kiegroup/kogito-runtimes/jbpm/jbpm-rest-handler/pom.xml) points at org.kie.kogito:jbpm instead of org.kie.kogito:addons, please verify your project structure @ line 5, column 11
[FATAL] Non-resolvable parent POM for org.kie.kogito:jbpm-rest-handler:1.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:addons:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11
 @
```

this indicating `addons` as a parent but it is not in the `addons` directory so either you move it the right place, or don't make it an addon :)

```
 <parent>
    <groupId>org.kie.kogito</groupId>
    <artifactId>addons</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>jbpm-rest-handler</artifactId>
  <name>RestHandler</name>
Edoardo Vacchi: he added that project so probably it's broken
```

2020-09-24 12:45 UTC, fjtirado commented
> with the help of @ricardozanini there are a few issues with the pom
> 
> ```
> [ERROR] [ERROR] Some problems were encountered while processing the POMs:
> [WARNING] 'parent.relativePath' of POM org.kie.kogito:jbpm-rest-handler:1.0.0-SNAPSHOT (/home/ricferna/dev/github.com/kiegroup/kogito-runtimes/jbpm/jbpm-rest-handler/pom.xml) points at org.kie.kogito:jbpm instead of org.kie.kogito:addons, please verify your project structure @ line 5, column 11
> [FATAL] Non-resolvable parent POM for org.kie.kogito:jbpm-rest-handler:1.0.0-SNAPSHOT: Could not find artifact org.kie.kogito:addons:pom:1.0.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 11
>  @
> ```
> 
> this indicating `addons` as a parent but it is not in the `addons` directory so either you move it the right place, or don't make it an addon :)
> 
> ```
>  <parent>
>     <groupId>org.kie.kogito</groupId>
>     <artifactId>addons</artifactId>
>     <version>1.0.0-SNAPSHOT</version>
>   </parent>
>   <artifactId>jbpm-rest-handler</artifactId>
>   <name>RestHandler</name>
> ```

Thanks guys, I made a mistake while copy pasting. I initially tried to add RestTasKHandler as add-on, but later I change my ming and I think it should be part of bpmn core, but not part of flow, so can be added to classpath on demand. 
Pom is fixed now

2020-09-24 13:16 UTC, evacchi commented
good let's merge as soon as it is green

2020-09-24 13:22 UTC, MarianMacik commented
My review will land in a few minutes as well :)

2020-09-24 13:49 UTC, tsurdilo commented
> @tsurdilo Yep, that makes sense to me. But how about the SW specific part, are you ok to have this in the sw runtimes module that @fjtirado proposed here? Problem was that is introduces dependecy to json path that would not be needed for bpmn projects.

@cristianonicolai I do not think that these "specific" SW parts are something that goes beyond just having it run for a demo, as we havent had the chance to actually implement the "real" solution for data management of SW in Kogito. I feel a little rushed here as this implementation is based on whats there **now** and assumes its right but it may be irrelevant in the near future. 

Also this is a workitem and to bring this back one more time it should be as such a reusable component. I think talking about
a workitem and "sw specific parts" in the same sentence just shows a wrong approach tobegin with. 
I don't think having even a "serverless-workflow-runtime" or whatever package or module  makes sense at all. 

So to answer your question I would really like to see this as an addon workitem that is completely independent and does not include any "specific sw features" and then we will figure out how to incorporate its use when needed.

2020-09-24 13:55 UTC, tsurdilo commented
> good let's merge as soon as it is green

WDYM lets merge...You are the only one that approved this, and it does not fit the SW/Kogito strategy at all. I don't think that forcing this in will benefit anyone here as the right approach would be to
1) MAKE THIS A STANDALONE + REUSABLE workitem..idk how many times I need to write this hehe :) 
2) DO NOT ADD ANY SW SPECIFIC PARTS..just a workitem that can take in a JSON object body and returns a JSON response..again idk how many times I need to say this as well :)

2020-09-24 13:58 UTC, fjtirado commented
> > good let's merge as soon as it is green
> 
> WDYM lets merge...You are the only one that approved this, and it does not fit the SW/Kogito strategy at all. I don't think that forcing this in will benefit anyone here as the right approach would be to
> 
> 1. MAKE THIS A STANDALONE + REUSABLE workitem..idk how many times I need to write this hehe :)
> 2. DO NOT ADD ANY SW SPECIFIC PARTS..just a workitem that can take in a JSON object body and returns a JSON response..again idk how many times I need to say this as well :)

1) RestWorkItemHandler proposed in this PR  is fully reusable and not specific to SW
2) SW specific part is needed for the demo. You can throw it to the bin later if you want.

2020-09-24 14:00 UTC, tsurdilo commented
> > > good let's merge as soon as it is green
> > 
> > 
> > WDYM lets merge...You are the only one that approved this, and it does not fit the SW/Kogito strategy at all. I don't think that forcing this in will benefit anyone here as the right approach would be to
> > 
> > 1. MAKE THIS A STANDALONE + REUSABLE workitem..idk how many times I need to write this hehe :)
> > 2. DO NOT ADD ANY SW SPECIFIC PARTS..just a workitem that can take in a JSON object body and returns a JSON response..again idk how many times I need to say this as well :)
> 
> 1. RestWorkItemHandler proposed in this PR  is fully reusable and not specific to SW
> 2. SW specific part is needed for the demo. You can throw it to the bin later if you want.

1) You can say this as many times as you wish and just force your solution on everyone...but it is not reusable .
2) Then just do the demo in some separate repo and throw it away yourself :)

2020-09-24 14:01 UTC, fjtirado commented
> > > > good let's merge as soon as it is green
> > > 
> > > 
> > > WDYM lets merge...You are the only one that approved this, and it does not fit the SW/Kogito strategy at all. I don't think that forcing this in will benefit anyone here as the right approach would be to
> > > 
> > > 1. MAKE THIS A STANDALONE + REUSABLE workitem..idk how many times I need to write this hehe :)
> > > 2. DO NOT ADD ANY SW SPECIFIC PARTS..just a workitem that can take in a JSON object body and returns a JSON response..again idk how many times I need to say this as well :)
> > 
> > 
> > 
> > 1. RestWorkItemHandler proposed in this PR  is fully reusable and not specific to SW
> > 2. SW specific part is needed for the demo. You can throw it to the bin later if you want.
> 
> 1. You can say this as many times as you wish and just force your solution on everyone...but it is not reusable .
> 2. Then just do the demo in some separate repo and throw it away yourself :)

why is not resusable? Can you justify that assertion?

2020-09-24 14:06 UTC, evacchi commented
> WDYM lets merge...

sorry I got confused by a different PR and thought there were more approvals

2020-09-24 14:06 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RestTaskDescriptor.java
> +        return processMetadata.getProcessId() + "RestTaskHandler";
you are right, I rename it

2020-09-24 14:07 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/resources/class-templates/RestTaskTemplate.java
> +        super(WebClient.create(vertx));
yep

2020-09-24 14:08 UTC, fjtirado commented on jbpm/jbpm-flow/pom.xml
> +
jbpm-flow was edited several times during this PR, thats why there is an uneeded change, Ill revert

2020-09-24 14:09 UTC, fjtirado commented on jbpm/jbpm-rest-handler/pom.xml
> +  </parent>
yes, I think is fine, if the rest agree (It is not my intenttion to impose that on anyone)

2020-09-24 14:09 UTC, fjtirado commented on jbpm/jbpm-rest-handler/src/main/java/org/jbpm/process/instance/impl/rest/RestTaskHandler.java
> +public class RestTaskHandler implements WorkItemHandler {
yes

2020-09-24 14:10 UTC, tsurdilo commented
> > > > > good let's merge as soon as it is green
> > > > 
> > > > 
> > > > WDYM lets merge...You are the only one that approved this, and it does not fit the SW/Kogito strategy at all. I don't think that forcing this in will benefit anyone here as the right approach would be to
> > > > 
> > > > 1. MAKE THIS A STANDALONE + REUSABLE workitem..idk how many times I need to write this hehe :)
> > > > 2. DO NOT ADD ANY SW SPECIFIC PARTS..just a workitem that can take in a JSON object body and returns a JSON response..again idk how many times I need to say this as well :)
> > > 
> > > 
> > > 
> > > 1. RestWorkItemHandler proposed in this PR  is fully reusable and not specific to SW
> > > 2. SW specific part is needed for the demo. You can throw it to the bin later if you want.
> > 
> > 
> > 
> > 1. You can say this as many times as you wish and just force your solution on everyone...but it is not reusable .
> > 2. Then just do the demo in some separate repo and throw it away yourself :)
> 
> why is not resusable? Can you justify that assertion?

Well, the workitem itself is intended for demo purposes. It does not reflect anything that we actually can consider a production usable component. 
The sw specific parts of the pr are also just for demo purposes only as they do not reflect how we might actually end up implementing the data strategy around SW states and workflows.
The PR forces SW code to use it. The decision aroudn that hasnt been made yet and we might as well if we are looking into such simple stuff (just a simple rest call) do this in a script task expression to have the same outcome.
So I am arguing here because I think it's pretty clear now that this is for demo/pr purposes only, but the pr forces itself to be used within the SW code. 
The workitem itself maybe "reusable" in the sense it can be used but if you look at its scope its just again for demo :) 
Idk what else to say about this ....

2020-09-24 14:26 UTC, evacchi commented
> Well, the workitem itself is intended for demo purposes. It does not reflect anything that we actually can consider a production usable component.

@tsurdilo merging on master does not mean anything is "production-ready". If anything this is to move forward with the task. Of course I won't merge with my only approval. I understand that you do not approve of the design, and there aren't any other approving reviews so far, so let's wait for others to chime in.

But please, *everyone*, let's keep the tone friendly; there's no point in arguing over this :)

2020-09-24 14:27 UTC, ricardozanini commented
Let me try to clarify:

1. We need a feature to call REST services for BPMN and SW. I designed that doc to have an alternative based on what we have. You changed the implementation from Camel to Vertx because of technical/roadmap reasons. I'm ok with that, I don't care. I just need the feature.

2. Now I understand that this PR will become a real thing? Because was a PoC at first to try to implement the REST calls via JAX-RS/Vertx/Whatever. If so, I agree that we need a more stable code base and do not have any specifics to SW whatsoever.

3. For the Demo I'm working on, I've already written a wrapper manually and my function look like this:

```
 {
      "name": "AddLabels",
      "type": "service",
      "metadata": {
        "interface": "org.kogito.examples.sw.github.workflow.GitHubService",
        "operation": "addLabels"
      }
    },
```

Whereas whould be nice to have something like:

```
 {
      "name": "AddLabels",
      "type": "rest",
      "resource": "http://openshift/myservice/github/label"
      "metadata": {
        "method": "POST",
      }
    },
```

So people would understand that we have an alternative for calling services in a declarative way.

That's what I was looking for.

2020-09-24 14:28 UTC, fjtirado commented on jbpm/jbpm-rest-handler/src/test/java/org/jbpm/process/instance/impl/rest/TestRestTaskHandler.java
> +class TestRestTaskHandler {
ok, moving test to the end

2020-09-24 14:28 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                                                            "Cannot a find a non empty constructor to annotate in handler class " +
good catch! thanks

2020-09-24 14:31 UTC, tsurdilo commented
> > Well, the workitem itself is intended for demo purposes. It does not reflect anything that we actually can consider a production usable component.
> 
> @tsurdilo merging on master does not mean anything is "production-ready". If anything this is to move forward with the task. Of course I won't merge with my only approval. I understand that you do not approve of the design, and there aren't any other approving reviews so far, so let's wait for others to chime in.
> 
> But please, _everyone_, let's keep the tone friendly; there's no point in arguing over this :)

@evacchi And that is fine if you guys want to merge this, my problem is 
https://github.com/kiegroup/kogito-runtimes/pull/778/files#diff-552bf6d008d02f358c614dd70191c999R445

This **forces** sw implementation to use it. Remove that part and then you guys put anything you want in :)

2020-09-24 14:35 UTC, fjtirado commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/RestTaskDescriptor.java
> +        return compilationUnit;
Yes, and also to reuse the same vertx instance (which is injected)

2020-09-24 14:38 UTC, fjtirado commented
How can we generate the workitemparameters without modifying current SW codebase?

2020-09-24 14:39 UTC, fjtirado commented
> Let me try to clarify:
> 
> 1. We need a feature to call REST services for BPMN and SW. I designed that doc to have an alternative based on what we have. You changed the implementation from Camel to Vertx because of technical/roadmap reasons. I'm ok with that, I don't care. I just need the feature.
> 2. Now I understand that this PR will become a real thing? Because was a PoC at first to try to implement the REST calls via JAX-RS/Vertx/Whatever. If so, I agree that we need a more stable code base and do not have any specifics to SW whatsoever.
> 3. For the Demo I'm working on, I've already written a wrapper manually and my function looks like this:
> 
> ```
>  {
>       "name": "AddLabels",
>       "type": "service",
>       "metadata": {
>         "interface": "org.kogito.examples.sw.github.workflow.GitHubService",
>         "operation": "addLabels"
>       }
>     },
> ```
> 
> Whereas would be nice to have something like:
> 
> ```
>  {
>       "name": "AddLabels",
>       "type": "rest",
>       "resource": "http://openshift/myservice/github/label"
>       "metadata": {
>         "method": "POST",
>       }
>     },
> ```
> 
> So people would understand that we have an alternative for calling services in a declarative way.
> 
> That's what I was looking for.

And this what is impelemented on this PR, in order to do that SW parser needs to be modified to generate the proper workitem.

2020-09-24 19:33 UTC, ricardozanini approved these changes

2020-09-25 10:23 UTC, cristianonicolai commented on kogito-build-parent/pom.xml
> +    </dependency>
please check format

2020-09-25 10:23 UTC, cristianonicolai commented on kogito-bom/pom.xml
> +        <artifactId>jbpm-rest-handler</artifactId>
kogito-rest-workitem

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-workitems/pom.xml
> +    <module>jbpm-rest-handler</module>
kogito-rest-workitem

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
> +
```suggestion

```

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-rest-handler/.gitignore
> +/target
probably not needed to add this file, should be covered by the one at the root level.

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow-runtime/src/test/java/RestTaskHandlerTest.java
> +        WebClient webClient = Mockito.mock(WebClient.class);
in most tests, we end up using import static to most Mockito API calls,

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow-runtime/src/test/java/RestTaskHandlerTest.java
> +                new HashMap<>();
```suggestion
        Map<String, Object> parameters = new HashMap<>();
```

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow-runtime/src/test/java/RestTaskHandlerTest.java
> +                  WorkItem.class);
```suggestion
        WorkItem workItem = mock(WorkItem.class);
```

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/ServerlessWorkflowParser.java
> +                            current = factory.restServiceNode (idCounter.getAndIncrement(), action.getFunctionRef(), actionFunction,embeddedSubProcess);
```suggestion
                            current = factory.restServiceNode(idCounter.getAndIncrement(), action.getFunctionRef(), actionFunction, embeddedSubProcess);
```

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/ServerlessWorkflowParser.java
> +                   current = unsupportedNode(action,embeddedSubProcess);
```suggestion
                   current = unsupportedNode(action, embeddedSubProcess);
```

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/ServerlessWorkflowParser.java
> +    private Node unsupportedNode (Action action, CompositeContextNode embeddedSubProcess) {
```suggestion
    private Node unsupportedNode(Action action, CompositeContextNode embeddedSubProcess) {
```

2020-09-25 10:23 UTC, cristianonicolai commented on jbpm/jbpm-serverless-workflow/src/main/java/org/jbpm/serverless/workflow/parser/core/JsonPathExprSupplier.java
> +    public JsonPathExprSupplier (String jsonPathExpr) {
```suggestion
    public JsonPathExprSupplier(String jsonPathExpr) {
```

2020-09-25 10:25 UTC, cristianonicolai commented on jbpm/jbpm-rest-handler/pom.xml
> +  </parent>
@MarianMacik @fjtirado I think its ok to have the new module, but would prefer to name it kogito-workitems and kogito-rest-workitem, as this is kogito specific.

2020-09-25 10:34 UTC, cristianonicolai commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/ServiceTaskDescriptor.java
> +            .setBody(new BlockStmt().addStatement(new MethodCallExpr("this",new ObjectCreationExpr().setType(serviceType))));
```suggestion
            .setBody(new BlockStmt().addStatement(new MethodCallExpr("this", new ObjectCreationExpr().setType(serviceType))));
```

2020-09-25 10:34 UTC, cristianonicolai commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
> +                .computeIfAbsent(workName,RestTaskDescriptor::generateHandlerClassForService);
```suggestion
                .computeIfAbsent(workName, RestTaskDescriptor::generateHandlerClassForService);
```

2020-09-25 10:48 UTC, cristianonicolai commented
> > @tsurdilo Yep, that makes sense to me. But how about the SW specific part, are you ok to have this in the sw runtimes module that @fjtirado proposed here? Problem was that is introduces dependecy to json path that would not be needed for bpmn projects.
> 
> @cristianonicolai I do not think that these "specific" SW parts are something that goes beyond just having it run for a demo, as we havent had the chance to actually implement the "real" solution for data management of SW in Kogito. I feel a little rushed here as this implementation is based on whats there **now** and assumes its right but it may be irrelevant in the near future.
> 
> Also this is a workitem and to bring this back one more time it should be as such a reusable component. I think talking about
> a workitem and "sw specific parts" in the same sentence just shows a wrong approach tobegin with.
> I don't think having even a "serverless-workflow-runtime" or whatever package or module makes sense at all.
> 
> So to answer your question I would really like to see this as an addon workitem that is completely independent and does not include any "specific sw features" and then we will figure out how to incorporate its use when needed.

@tsurdilo agree that this solution is not final, but rather something for us to start showing some usecases and capabilitties, which will need evolving for sure. As for the SW part, my understanding was that its only the JSON path thing wasnt neded for processes, but I see that this can actually be reused for both, meaning, as you said, this should be just a regular work item. We can move the json path part to core as we initially thought, later on, but we sould be able to at least get something that we can start demonstraing that we can easily integrate with REST endpoints.

2020-09-25 12:05 UTC, MarianMacik commented on jbpm/jbpm-workitems/jbpm-rest-handler/pom.xml
> +    <artifactId>jbpm-workitems</artifactId>
As @cristianonicolai suggested, the best option would be `kogito-workitems` and the submodule either `kogito-workitems-rest` or `kogito-rest-workitem`.

2020-09-25 18:48 UTC, fjtirado commented
> > > @tsurdilo Yep, that makes sense to me. But how about the SW specific part, are you ok to have this in the sw runtimes module that @fjtirado proposed here? Problem was that is introduces dependecy to json path that would not be needed for bpmn projects.
> > 
> > 
> > @cristianonicolai I do not think that these "specific" SW parts are something that goes beyond just having it run for a demo, as we havent had the chance to actually implement the "real" solution for data management of SW in Kogito. I feel a little rushed here as this implementation is based on whats there **now** and assumes its right but it may be irrelevant in the near future.
> > Also this is a workitem and to bring this back one more time it should be as such a reusable component. I think talking about
> > a workitem and "sw specific parts" in the same sentence just shows a wrong approach tobegin with.
> > I don't think having even a "serverless-workflow-runtime" or whatever package or module makes sense at all.
> > So to answer your question I would really like to see this as an addon workitem that is completely independent and does not include any "specific sw features" and then we will figure out how to incorporate its use when needed.
> 
> @tsurdilo agree that this solution is not final, but rather something for us to start showing some usecases and capabilitties, which will need evolving for sure. As for the SW part, my understanding was that its only the JSON path thing wasnt neded for processes, but I see that this can actually be reused for both, meaning, as you said, this should be just a regular work item. We can move the json path part to core as we initially thought, later on, but we sould be able to at least get something that we can start demonstraing that we can easily integrate with REST endpoints.

JsonPath has been moved to the same project than RestTaskHandler

2020-09-25 20:54 UTC, ricardozanini commented on jbpm/jbpm-flow-builder/src/main/java/org/jbpm/compiler/canonical/WorkItemNodeVisitor.java
> +        } else if (workName.equals("Rest Task")) {
I think it's better to use constants instead.

2020-09-26 18:43 UTC, fjtirado commented
jenkins retest this

2020-09-28 11:59 UTC, cristianonicolai approved these changes

2020-09-28 12:00 UTC, merged