KOGITO-3393 Inject ProcessInstanceFactory and add tests to ensure per…
kiegroup/kogito-runtimes pull request #784
Opened 2020-09-25 09:19 UTC by cristianonicolai

…sistence is used

2020-09-25 09:30 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                        .addArgument(
unneeded format change,

2020-09-25 09:31 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                .addMember(constructorDeclaration)
unneeded fomat change

2020-09-25 09:37 UTC, fjtirado approved these changes
Nice work, thanks for fixing this. 
Only minor issue is that, as usual, due to different formatters in intellij and eclipse, there are some uneeded format changes. I marked those ones which I think do not improve readability.

2020-09-25 09:37 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +    public ProcessGenerator(WorkflowProcess process,
unneeded format change

2020-09-25 10:27 UTC, ricardozanini commented
> Nice work, thanks for fixing this. 
> 
> Only minor issue is that, as usual, due to different formatters in intellij and eclipse, there are some uneeded format changes. I marked those ones which I think do not clearly improve readability (they do not make it worse either) 

This formatting thing is really annoying, but I believe we have a profile for both IDEs. I got mine from the drools contribution project. @cristianonicolai what about reviewing this profile? Not sure if they are up to date or in sync. 

Plus the headers from Kogito Examples and Runtimes are different right now.

2020-09-25 11:49 UTC, cristianonicolai commented
@ricardozanini yeah, I compared my config with the one on https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration/intellij-configuration/code-style, there are some small differences, perhpaps even because the Intellij version changed. Will submit a PR. Regarding Eclipse, its probably outdated/not in sync as it is less used, but need someone to review that. Regarding headers, that has been ongoing for a while https://github.com/kiegroup/kogito-runtimes/pull/614

2020-09-25 12:00 UTC, cristianonicolai commented
actually, I reimported the code style and exported again, so same output as before, so I dont think I got anything custom here :/

2020-09-25 13:45 UTC, ricardozanini commented
> Regarding Eclipse, its probably outdated/not in sync as it is less used, but need someone to review that. Regarding headers, that has been ongoing for a while #614

@fjtirado seems like you're using Eclipse. Could you please take a look in the profiles from https://github.com/kiegroup/droolsjbpm-build-bootstrap to see if it makes sense and it's aligned? :heart:

2020-09-25 19:36 UTC, fjtirado commented
> > Regarding Eclipse, its probably outdated/not in sync as it is less used, but need someone to review that. Regarding headers, that has been ongoing for a while #614
> 
> @fjtirado seems like you're using Eclipse. Could you please take a look in the profiles from https://github.com/kiegroup/droolsjbpm-build-bootstrap to see if it makes sense and it's aligned? 
> 
> EDIT: sorry for the off-topic in your PR, baby.

Sure, Ill check. I can confirm the result of using the one in the web are not the same than in intellij. Im actually using a custom version not fully aligned with the intellij one. Ill investiage this and update the one in github when fully aligned. Sorry for the noise too.

2020-09-28 04:47 UTC, cristianonicolai commented
jenkins please retest this

2020-09-28 05:52 UTC, Sgitario requested changes
I'm good with the solution, but it's wrongly using the surefire maven plugin to run integration tests. Failsafe maven plugin should be used instead.

2020-09-28 05:52 UTC, Sgitario commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +          </includes>
Why did we include the integration tests as part of the surefire plugin? Surefire plugin should be only for unit tests and failsafe plugin for integration tests.

2020-09-28 05:52 UTC, Sgitario commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +                <include>org/kie/kogito/integrationtests/quarkus/infinispan/*</include>
Same comment as above.

2020-09-28 05:52 UTC, Sgitario commented on integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicRestTest.java
>  class BasicRestTest {
If this test requires Infinispan, then it's an Integration Test and it should be renamed from BasicRestTest to BasicRestIT.

2020-09-28 05:52 UTC, Sgitario commented on integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/infinispan/InfinispanTest.java
> +class InfinispanTest {
If this test requires Infinispan, then it's an Integration test and it should be renamed from InfinispanTest to InfinispanIT. Also, the name does not say what this suite is meant to. Can you rename it to a more meaningful name?

2020-09-28 05:52 UTC, Sgitario commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml
> +                </configuration>
We should not use surefire for integration tests.

2020-09-28 05:52 UTC, Sgitario commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/pom.xml
> +                        </configuration>
Same comments as above.

2020-09-28 05:52 UTC, Sgitario commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-it/src/test/java/org/kie/kogito/integrationtests/springboot/infinispan/InfinispanTest.java
> +class InfinispanTest extends BaseRestTest {
Same comments as in the quarkus version.

2020-09-28 05:52 UTC, Sgitario commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/pom.xml
> +                <version>@version.surefire.plugin@</version>
We should not use surefire for integration tests.

2020-09-28 05:52 UTC, Sgitario commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                                               .addStatement(new MethodCallExpr(null, "super")
Format issue here.

2020-09-28 05:52 UTC, Sgitario commented on kogito-test-utils/src/main/java/org/kie/kogito/testcontainers/KogitoInfinispanContainer.java
> +        setCommand("/opt/infinispan/bin/server.sh -c infinispan-local.xml");
Really nice! This way we don't rely on the default configuration from docker.

2020-09-28 06:10 UTC, cristianonicolai commented
jenkins please retest this

2020-09-28 06:15 UTC, cristianonicolai commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +          </includes>
Yep, that was confusion to me as well, but all tests we have here are integration tests in my perspective. So decided to keep as is, otherwise we should rename all to IT and change the plugin to failsafe, wdyt? Perhaps a follow-up JIRA.

2020-09-28 06:18 UTC, cristianonicolai commented on integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/infinispan/InfinispanTest.java
> +class InfinispanTest {
open to suggestions :) testIfinispanPersistence? just really checking if the cache was created and contains the new process in it, as the error would be that it would silently use in memory and not Infinispan.

2020-09-28 06:19 UTC, cristianonicolai commented on integration-tests/integration-tests-quarkus-processes/src/test/java/org/kie/kogito/integrationtests/quarkus/BasicRestTest.java
>  class BasicRestTest {
all tests in this module are conditional to Infinispan as we run the same set of tests, with and without persistence enabled.

2020-09-28 06:33 UTC, Sgitario commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +          </includes>
Fine with me to raise a follow-up JIRA.

2020-09-28 06:35 UTC, Sgitario approved these changes

2020-09-28 06:36 UTC, cristianonicolai commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                                               .addStatement(new MethodCallExpr(null, "super")
fixed

2020-09-28 09:27 UTC, cristianonicolai commented
jenkins please retest this

2020-09-28 10:16 UTC, cristianonicolai commented on integration-tests/integration-tests-quarkus-processes/pom.xml
> +          </includes>
FYI https://issues.redhat.com/browse/KOGITO-3448

2020-09-28 10:54 UTC, cristianonicolai commented
jenkins please retest this

2020-09-28 12:51 UTC, cristianonicolai commented
jenkins please retest this

2020-09-28 14:14 UTC, cristianonicolai commented
jenkins please retest this

2020-09-29 03:36 UTC, cristianonicolai commented
jenkins please retest this

2020-09-29 04:40 UTC, cristianonicolai commented
Moved Infinispan container changes to https://github.com/kiegroup/kogito-runtimes/pull/791 as those are not compatible with version 10 that used by kogito-apps tests.

2020-09-29 10:11 UTC, cristianonicolai commented
jenkins please retest this

2020-09-29 10:21 UTC, fjtirado commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java
> +    protected AbstractProcess(Application app, ProcessInstancesFactory factory, Collection<WorkItemHandler> handlers) {
Im now wondering if it wont be better to add factory as the third parameter rather than the second, please see comment below

2020-09-29 10:21 UTC, fjtirado commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/process/ProcessGenerator.java
> +                                                          .addArgument(new NameExpr(addonsConfig.usePersistence() ? FACTORY : "null"))
If we put factory as third parameter of super constructor, we can skip the null and just do not add the argument, wdyt?

2020-09-29 14:47 UTC, cristianonicolai commented on jbpm/jbpm-flow/src/main/java/org/kie/kogito/process/impl/AbstractProcess.java
> +    protected AbstractProcess(Application app, ProcessInstancesFactory factory, Collection<WorkItemHandler> handlers) {
done

2020-09-30 00:05 UTC, merged