[KOGITO-3460] Create native daily build
kiegroup/kogito-runtimes pull request #793
Opened 2020-09-29 15:36 UTC by danielezonca

Job that clone and compiles all the repos in native mode

@radtriste @cristianonicolai

2020-09-30 00:29 UTC, cristianonicolai commented on Jenkinsfile.native
> +        mavenCleanInstall("-Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=podman")
do we have podman installed in the Jenkins slave machines? Docker is there for sure.

2020-09-30 06:48 UTC, radtriste requested changes

2020-09-30 06:48 UTC, radtriste commented on Jenkinsfile.native
> +        string(name: 'BRANCH_NAME', defaultValue: "master", description: 'Set the branch to build&test')
I think this should be a multibranch pipeline. Thus `BRANCH_NAME` is already provided as env by Jenkins.
parameters part can be deleted ;)

2020-09-30 06:48 UTC, radtriste commented on Jenkinsfile.native
> +             subject: "[${params.BRANCH_NAME}][d] Runtimes native",
```suggestion
             subject: "[${env.BRANCH_NAME}][d] Runtimes native",
```

2020-09-30 06:48 UTC, radtriste commented on Jenkinsfile.native
> +        checkout(githubscm.resolveRepository(repoName, "kiegroup", params.BRANCH_NAME, false))
```suggestion
        checkout(githubscm.resolveRepository(repoName, "kiegroup", env.BRANCH_NAME, false))
```

2020-09-30 06:48 UTC, radtriste commented on Jenkinsfile.native
> +        mavenCleanInstall("-Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=podman")
yeah right ... could be a problem on `kie-rhel7` agent. We should use `kogito-cloud` instead

2020-09-30 06:48 UTC, radtriste commented on Jenkinsfile.native
> +        label 'kie-rhel7 && kie-mem16g'
As mentioned by @cristianonicolai 

```suggestion
        label 'kogito-cloud'
```

2020-09-30 06:50 UTC, radtriste commented on Jenkinsfile.native
> +        label 'kie-rhel7 && kie-mem16g'
`kogito-cloud` has 16GB mem already

2020-09-30 07:54 UTC, danielezonca commented on Jenkinsfile.native
> +        mavenCleanInstall("-Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=podman")
Changed agent to `kogito-cloud`. Let me know if I need to change to `docker` too or if it is fine to use `podman`

2020-09-30 07:54 UTC, danielezonca commented on Jenkinsfile.native
> +        string(name: 'BRANCH_NAME', defaultValue: "master", description: 'Set the branch to build&test')
Done

2020-09-30 07:54 UTC, danielezonca commented on Jenkinsfile.native
> +             subject: "[${params.BRANCH_NAME}][d] Runtimes native",
Done

2020-09-30 07:54 UTC, danielezonca commented on Jenkinsfile.native
> +        checkout(githubscm.resolveRepository(repoName, "kiegroup", params.BRANCH_NAME, false))
Done

2020-09-30 07:54 UTC, danielezonca commented on Jenkinsfile.native
> +        label 'kie-rhel7 && kie-mem16g'
Done

2020-09-30 08:02 UTC, radtriste commented on Jenkinsfile.native
> +        mavenCleanInstall("-Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=podman")
podman is ok on this agent

2020-09-30 08:03 UTC, radtriste commented on Jenkinsfile.native
> +    maven.runMavenWithSubmarineSettings("clean install ${env.MAVEN_EXTRA_ARGS} ${extraArgs}", false)
```suggestion
    maven.runMavenWithSubmarineSettings("clean install ${env.MAVEN_OPTS} ${extraArgs}", false)
```
or ?

2020-09-30 08:03 UTC, radtriste commented on Jenkinsfile.native
> +    maven.runMavenWithSubmarineSettings("clean install ${env.MAVEN_EXTRA_ARGS} ${extraArgs}", false)
btw, not sure we should keep `MAVEN_OPTS` for native ...

2020-09-30 08:38 UTC, danielezonca commented on Jenkinsfile.native
> +    maven.runMavenWithSubmarineSettings("clean install ${env.MAVEN_EXTRA_ARGS} ${extraArgs}", false)
Fixed. I think it could make sense to preserve `MAVEN_OPS`: the build is still a maven build with then an additional step to perform native compilation

2020-09-30 09:16 UTC, radtriste commented on Jenkinsfile.native
> +    maven.runMavenWithSubmarineSettings("clean install ${env.MAVEN_EXTRA_ARGS} ${extraArgs}", false)
yeah but will 4G be enough for compilation/testing ?

2020-09-30 11:00 UTC, cristianonicolai commented on Jenkinsfile.native
> +        mavenCleanInstall("-Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=podman")
cool

2020-09-30 12:13 UTC, radtriste commented on Jenkinsfile.native
> +    maven.runMavenWithSubmarineSettings("clean install ${env.MAVEN_OPTS} ${extraArgs}", false)
```suggestion
    maven.runMavenWithSubmarineSettings("clean install ${extraArgs}", false)
```
`MAVEN_OPTS` env is taken automatically by Maven ;)

2020-09-30 12:15 UTC, radtriste requested changes
Removed also `(-Pnative)` in stage names as I think useless

2020-09-30 12:15 UTC, radtriste commented on Jenkinsfile.native
> +        stage('Build kogito-runtimes (-Pnative)') {
```suggestion
        stage('Build kogito-runtimes') {
```

2020-09-30 12:15 UTC, radtriste commented on Jenkinsfile.native
> +        stage('Build kogito-apps (-Pnative)') {
```suggestion
        stage('Build kogito-apps') {
```

2020-09-30 12:15 UTC, radtriste commented on Jenkinsfile.native
> +        stage('Build kogito-examples (-Pnative)') {
```suggestion
        stage('Build kogito-examples') {
```

2020-09-30 12:15 UTC, danielezonca commented on Jenkinsfile.native
> +    maven.runMavenWithSubmarineSettings("clean install ${env.MAVEN_OPTS} ${extraArgs}", false)
Done :)

2020-09-30 12:16 UTC, danielezonca commented on Jenkinsfile.native
> +        stage('Build kogito-apps (-Pnative)') {
Done

2020-09-30 12:17 UTC, danielezonca commented on Jenkinsfile.native
> +        stage('Build kogito-runtimes (-Pnative)') {
Done

2020-09-30 12:17 UTC, danielezonca commented on Jenkinsfile.native
> +        stage('Build kogito-examples (-Pnative)') {
Done

2020-09-30 13:50 UTC, radtriste commented
Related PR: https://github.com/kiegroup/kogito-examples/pull/375

2020-09-30 14:22 UTC, radtriste commented
Jenkins retest this

2020-10-01 10:57 UTC, radtriste approved these changes

2020-10-01 13:30 UTC, cristianonicolai approved these changes

2020-10-06 06:43 UTC, danielezonca commented
jenkins retest this please

2020-10-06 07:08 UTC, radtriste commented
@danielezonca Seems Jenkins is having problem starting new job. Once back, I will restart this job.

2020-10-06 08:11 UTC, radtriste commented
jenkins retest this

2020-10-06 09:59 UTC, radtriste commented
@danielezonca @cristianonicolai can be merged

2020-10-06 11:21 UTC, merged