KOGITO-3309: changed parent of kogito-bom to not inherit build requir…
kiegroup/kogito-runtimes pull request #827
Opened 2020-10-14 11:44 UTC by mareknovotny

…ed dependency management

https://issues.redhat.com/browse/KOGITO-3309

kogito-bom inherits kogito-build-parent dependencyManagement so having kogito-bom only as user BOM i switched the parent of it.

2020-10-15 10:31 UTC, rsynek commented on kogito-build-parent/pom.xml
> +    <groupId>org.jboss</groupId>
I don't understand the change - kogito-bom's parent is still this pom.xml (kogito-build-parent), which defines versions of many 3rd party dependencies.

I would rather expect:
- keeping the kogito-runtimes as a parent of the kogito-build-parent
- making kogito-runtimes a parent of the kogito-bom
- importing the kogito-bom into the kogito-build-parent

2020-10-15 13:44 UTC, ge0ffrey requested changes
I agree with Radovan:
- kogito-parent extends jboss-parent and has no dependencies.
- kogito-bom extends kogito-parent and only has kie dependencies in depMgmt, no external ones.
- kogito-build-parent extends kogito-parent, imports kogito-bom and has all external dependencies in depMgmt
- every other module extends kogito-build-parent.

2020-10-19 13:35 UTC, danielezonca commented
Note, this PR is going to add a new addon so it should be updated accordingly with this new refactor
https://github.com/kiegroup/kogito-runtimes/pull/807

2020-10-19 14:31 UTC, mareknovotny commented
Jenkins retest this please

2020-10-19 15:58 UTC, mareknovotny commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/pom.xml
> +            <version>${project.version}</version>
kogito-bom doesn'ŧ contain kogito-test-utils declaration, should it or is that just for internal usage? @danielezonca @cristianonicolai  @ruromero

2020-10-19 16:07 UTC, danielezonca commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/pom.xml
> +            <version>${project.version}</version>
As far as I know that module is intended to be used only for internal usage so I'm fine to keep it outside kogito-bom

2020-10-20 07:41 UTC, mareknovotny commented on integration-tests/integration-tests-springboot/src/it/integration-tests-springboot-kafka-it/pom.xml
> +            <version>${project.version}</version>
thanks, then this is ok and kogito-examples need to have depMgmt too

2020-10-20 08:55 UTC, mareknovotny commented
Jenkins retest this

2020-10-20 09:03 UTC, rsynek approved these changes
LGTM, thank you!

2020-10-20 11:19 UTC, mareknovotny commented
> Note, this PR is going to add a new addon so it should be updated accordingly with this new refactor
> #807

then better to merge this first, all green now

2020-10-21 13:56 UTC, mareknovotny commented
merge it then @kiegroup/gatekeepers (hold my hands off from it ;) )

2020-10-21 14:02 UTC, ge0ffrey approved these changes
Great work!

2020-10-21 14:03 UTC, ge0ffrey commented
@evacchi Can we have this merged?

2020-10-22 08:24 UTC, merged