KOGITO-3254: SVG Processing to apply executed path color changes
kiegroup/kogito-runtimes pull request #846
Opened 2020-10-22 23:05 UTC by nmirasch

jira related https://issues.redhat.com/browse/KOGITO-3254.
Addon that creates and endpoint that return the SVG painting the process execution path

2020-10-26 06:45 UTC, Sara4994 approved these changes

2020-10-26 12:54 UTC, jstastny-cz requested changes

2020-10-26 12:54 UTC, jstastny-cz commented on addons/svg-process-addon/pom.xml
> +  <!-- just for DEV, TO BE REMOVED -->
either turn to draft PR or remove this already

2020-10-26 12:54 UTC, jstastny-cz commented on addons/svg-process-addon/src/main/java/org/kie/kogito/svg/service/ProcessSVGService.java
> +public class ProcessSVGService {
I would argue for ProcessSvgService naming, imo it improves readability - similarly to the HttpResponse class imported above. Though I can see legacy naming conventions dictated by SVGImageProcessort and similar ...

2020-10-26 12:54 UTC, jstastny-cz commented on addons/svg-process-addon/src/main/java/org/kie/kogito/svg/service/ProcessSVGService.java
> +    public String getProcessSVGFromVertxFileSystem(String processId) {
the field is named `svgResourcesPath`, but in method we're using different naming convention in `getProcessSVGFromVertxFileSystem`, it would be good to unify.

2020-10-26 12:54 UTC, jstastny-cz commented on addons/svg-process-addon/src/main/java/org/kie/kogito/svg/service/ProcessSVGService.java
> +    public String getProcessSVGFromVertxFileSystem(String processId) {
And below for the method `getSvgFileUni`

2020-10-26 12:54 UTC, jstastny-cz commented on addons/svg-process-addon/src/main/java/org/kie/kogito/svg/service/ProcessSVGService.java
> +    public String svgTransformToShowExecutedPath(String svg, List<String> completedNodes, List<String> activeNodes) {
the method naming - it would be good to start with a verb - does `transformSvgToShowExecutedPath` work fine?

2020-10-26 12:54 UTC, jstastny-cz commented on addons/svg-process-addon/src/main/java/org/kie/kogito/svg/service/ProcessSVGService.java
> +        if (response.statusCode() == 200) {
can we use constant for the http status code?

2020-10-26 12:54 UTC, jstastny-cz commented on addons/svg-process-addon/src/main/resources/META-INF/processSVG/README.txt
> +Place here the Process SVG to used as source where draw the execution path.
```suggestion
Place here the Process SVG to be used as source where to draw the execution path.
```

2020-10-26 14:39 UTC, nmirasch commented on addons/svg-process-addon/pom.xml
> +  <!-- just for DEV, TO BE REMOVED -->
@jstastny-cz  updated, I removed this part

2020-10-26 14:41 UTC, nmirasch commented on addons/svg-process-addon/src/main/java/org/kie/kogito/svg/service/ProcessSVGService.java
> +public class ProcessSVGService {
@jstastny-cz I renamed in many places SVG to Svg in classes and function, at least is homogeneous throw the current addon.

2020-10-26 14:43 UTC, nmirasch commented on addons/svg-process-addon/src/main/java/org/kie/kogito/svg/service/ProcessSVGService.java
> +    public String getProcessSVGFromVertxFileSystem(String processId) {
Agree, I just modify the references to getSvg, getSvgFrom.. Let me know if this fits please :)

2020-10-26 14:44 UTC, nmirasch commented on addons/svg-process-addon/src/main/java/org/kie/kogito/svg/service/ProcessSVGService.java
> +        if (response.statusCode() == 200) {
done

2020-10-26 14:51 UTC, nmirasch commented
@jstastny-cz thanks for the review!! I just added some updates, could you take a look?

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/.gitignore
> +target/
@nmirasch you can remove this as there is a .gitignore at the root level of the project already

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/pom.xml
> +  <description>Process Svg showing execution path</description>
SVG ?

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/pom.xml
> +  <name>Kogito :: Add-Ons :: process-svg :: Common</name>
Maybe 
```suggestion
  <name>Kogito :: Add-Ons :: Process SVG :: Common</name>
```

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +                InputStream svgStream = new ByteArrayInputStream(svg.getBytes());
Just make sure resources are closed
```suggestion
                try(InputStream svgStream = new ByteArrayInputStream(svg.getBytes())){
```

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +                completedNodes.stream().forEach(nodeId -> processor.defaultCompletedTransformation(nodeId, completedColor, completedBorderColor));
```suggestion
                completedNodes.forEach(nodeId -> processor.defaultCompletedTransformation(nodeId, completedColor, completedBorderColor));
```

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +                activeNodes.stream().forEach(nodeId -> processor.defaultActiveTransformation(nodeId, activeBorderColor));
```suggestion
                activeNodes.forEach(nodeId -> processor.defaultActiveTransformation(nodeId, activeBorderColor));
```

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +                nodesArray.stream()
```suggestion
                nodesArray
```

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +        return getAddonWebClient(context).get("/diagram/" + processId + ".svg")
shouldnt we simply get from the filesystem instead?

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +        }
Maybe we should log some error or even fail deployment as the image wont have the execution information?

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-quarkus-addon/.gitignore
> +target/
same here

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-quarkus-addon/pom.xml
> +  <name>Kogito :: Add-Ons :: Process svg :: Quarkus Addon</name>
```suggestion
  <name>Kogito :: Add-Ons :: Process SVG :: Quarkus Addon</name>
```

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-quarkus-addon/src/main/java/org/kie/kogito/svg/rest/ProcessSvgResource.java
> +    @Route(path = "/svg/process/:processId/instances/:processInstanceId", methods = HttpMethod.GET, produces = "application/svg+xml")
@nmirasch in the runtimes, we've been using JAX-RS to build REST services based on Quarkus, do you think would be ok to migrate to that instead of using VertX?

```suggestion
    @Route(path = "/svg/processes/:processId/instances/:processInstanceId", methods = HttpMethod.GET, produces = "application/svg+xml")
```

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +    public String transformSvgToShowExecutedPath(String svg, List<String> completedNodes, List<String> activeNodes)  {
Maybe call it _annotateExecutedPath_ ? As it is inside _ProcessSvgService_ already.

2020-11-02 05:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-quarkus-addon/pom.xml
> +  <description>Process svg Quarkus Addon to interact with Process Svg Service</description>
```suggestion
  <description>Quarkus Addon to interact with Process SVG Service</description>
```

2020-11-02 05:41 UTC, cristianonicolai commented on kogito-bom/pom.xml
> +        <artifactId>svg-process-addon</artifactId>
do we still have/need this module?

2020-11-03 07:40 UTC, jstastny-cz commented on addons/process-svg/process-svg-quarkus-addon/src/test/java/org/kie/kogito/svg/service/QuarkusProcessSvgServiceTest.java
> +    //private Vertx vertxMock;
commented code

2020-11-03 07:56 UTC, jstastny-cz commented on addons/process-svg/process-svg-quarkus-addon/src/test/java/org/kie/kogito/svg/rest/ProcessSvgResourceTest.java
> +    public String getTravelsSVGFile() {
one more method with SVG

2020-11-03 08:41 UTC, jstastny-cz commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +                !resp.bodyAsString().contains("<title>404 - Resource Not Found</title>")) {
couldn't we check http code instead of body?

2020-11-03 08:41 UTC, jstastny-cz commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +                    InputStream svgStream = new ByteArrayInputStream(svg.getBytes());
here maybe again try-with-resources for the stream

2020-11-03 08:41 UTC, jstastny-cz commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +        if(addonWebClient == null ){
formatting

2020-11-03 09:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-quarkus-addon/src/main/java/org/kie/kogito/svg/rest/ProcessSvgResource.java
> +            return service.annotateExecutedPath(svg, completedNodes, activeNodes);
@nmirasch seems like you're doing multiple calls to the same service, passing different parameters, I think it would be better if you could simply have one method `getProcessInstanceSVG` which gives you the annotated one, so everything else is considered internals of the service, wdyt?

2020-11-03 09:41 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/ProcessSvgService.java
> +    public String getSvgFromVertxFileSystem(String processId) {
maybe call it?
```suggestion
    public String getProcessSVG(String processId) {
```

2020-11-03 20:28 UTC, nmirasch commented on kogito-bom/pom.xml
> +        <artifactId>svg-process-addon</artifactId>
removed

2020-11-03 20:29 UTC, nmirasch commented on addons/process-svg/process-svg-quarkus-addon/src/test/java/org/kie/kogito/svg/service/QuarkusProcessSvgServiceTest.java
> +    //private Vertx vertxMock;
removed

2020-11-05 02:51 UTC, cristianonicolai reviewed
@nmirasch I think the SVG will actually be generated next to the bpmn file. Thats how the VSCode editor does, so I think we would need to find the svg in this way, and not expect that the SVG would be placed in a specific folder.

2020-11-05 02:51 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/main/java/org/kie/kogito/svg/processor/JBPMDesignerSVGProcessor.java
> +public class JBPMDesignerSVGProcessor extends AbstractSVGProcessor {
this can be removed, as it targets old designer?

2020-11-05 02:51 UTC, cristianonicolai commented on addons/process-svg/process-svg-quarkus-addon/src/main/java/org/kie/kogito/svg/service/QuarkusProcessSvgService.java
> +            @ConfigProperty(name = "kogito.svg.folder.path", defaultValue = "META-INF/processSVG/") String svgResourcesPath,
@nmirasch still think that this folder should not be set, it either points to an external folder of we use the classpath to find the svg?

2020-11-05 22:37 UTC, nmirasch commented
@cristianonicolai I added the Authorization header at the connection with data-index doing  the existing nodes query.  Could you take a look? Thanks!

2020-11-06 09:48 UTC, cristianonicolai commented
jenkins please retest this

2020-11-09 01:10 UTC, cristianonicolai commented
jenkins please retest this

2020-11-11 12:06 UTC, nmirasch commented
@cristianonicolai, @jstastny-cz  We achieved the green, Could you take a look please?

2020-11-12 07:05 UTC, cristianonicolai reviewed
@nmirasch overall is working fine in JVM mode, but on native mode it cant find the SVG :/

2020-11-12 07:05 UTC, cristianonicolai commented on addons/process-svg/process-svg-common/src/test/java/org/kie/kogito/svg/ProcessSvgServiceTest.java
> +            getTestedProcessSvgService().annotateExecutedPath(
@nmirasch I was checking the sonar report and I think if you define processService and the other collections as variables and then do the expected exception assertation, it would work. The problem now is that is calling multiple things that could

2020-11-12 20:39 UTC, nmirasch commented
@cristianonicolai good green now :-)

2020-11-13 03:00 UTC, cristianonicolai commented
@nmirasch perfect just missing the native part now https://github.com/nmirasch/kogito-runtimes/pull/5/ :)

2020-11-13 16:39 UTC, nmirasch commented
jenkins retest this please

2020-11-17 01:41 UTC, cristianonicolai commented
jenkins please retest this

2020-11-18 14:56 UTC, nmirasch commented
jenkins please retest this

2020-11-20 01:11 UTC, cristianonicolai commented
@nmirasch it now has conflict, please take a look.

2020-11-20 09:17 UTC, merged