KOGITO-3738 Use JDK8-compatible readBytes impl in DecisionModelResourcesProvider
kiegroup/kogito-runtimes pull request #860
Opened 2020-10-29 13:53 UTC by evacchi

https://issues.redhat.com/browse/KOGITO-3738

My IDE freaks out every time the code is generated because the `integration-test` project is set to 8, and all children inherits from them. For now I am just inserting a stock "readAllBytes()" impl, but we can move most of this stock logic to an abstract class and inherit from there

Alternative: we can set the pom.xml of the submodule to 11

-----

- [x] You have read the [contributors guide](CONTRIBUTING.md)
- [x] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [x] Pull Request title contains the target branch if not targeting master: `[0.9.x] KOGITO-XYZ Subject`
- [x] Pull Request contains link to the JIRA issue
- [x] Pull Request contains link to any dependent or related Pull Request
- [x] Pull Request contains description of the issue
- [x] Pull Request does not include fixes for issues other than the main ticket

2020-10-29 14:17 UTC, tarilabs requested changes
The abstract solution is good, I agree with overall.
There was even a recent Kogito ML comment about it, this would solve that too.

The technical implementation I do not concur. Please see proposal below.

2020-10-29 14:17 UTC, tarilabs commented on kogito-codegen/src/main/resources/class-templates/DecisionModelResourcesProviderTemplate.java
> +            byte[] bytes = readAllBytes(stream);
```suggestion
            byte[] bytes = org.drools.core.util.IoUtils.readBytesFromInputStream(stream);
```

2020-10-29 14:19 UTC, evacchi commented on kogito-codegen/src/main/resources/class-templates/DecisionModelResourcesProviderTemplate.java
> +            byte[] bytes = readAllBytes(stream);
https://media.giphy.com/media/3o8doT9BL7dgtolp7O/giphy.gif

2020-10-29 14:20 UTC, evacchi commented on kogito-codegen/src/main/resources/class-templates/DecisionModelResourcesProviderTemplate.java
> +            byte[] bytes = readAllBytes(stream);
yes I saw that thread on ML, so that makes sense anyway

2020-10-29 14:22 UTC, tarilabs approved these changes
after ec04738 👍

2020-10-30 08:36 UTC, ricardozanini commented
Oh please merge this! :)

Thanks @evacchi

2020-10-30 08:39 UTC, radtriste approved these changes

2020-10-30 08:49 UTC, merged