KOGITO-3930 Align archetype with settings from Quarkus
kiegroup/kogito-runtimes pull request #912
Opened 2020-11-25 05:00 UTC by cristianonicolai

2020-11-25 07:54 UTC, evacchi approved these changes

2020-11-25 08:36 UTC, radtriste approved these changes
just minor comment

2020-11-25 08:36 UTC, radtriste commented on archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
> +            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
could we make that property `org.jboss.logmanager.LogManager` more generic in build pom or kogito-runtimes pom ?

2020-11-26 01:45 UTC, cristianonicolai commented on archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
> +            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
@radtriste not sure I got the idea... you mean to be reused across our kogito-runtimes poms? like in the pluginManagement section?

2020-11-26 10:04 UTC, radtriste commented on archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
> +            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
that was just an idea to have

`<quarkus.logging.manager>org.jboss.logmanager.LogManager</quarkus.logging.manager>` in kogito-build-parent

and use it here 
```
<systemPropertyVariables>
            <java.util.logging.manager>${quarkus.logging.manager}</java.util.logging.manager>
```
and in other places as well

I think it is a nice to have ;)

2020-11-26 14:26 UTC, cristianonicolai commented on archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
> +            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
@radtriste thanks, added to the pr :)

2020-11-26 14:29 UTC, radtriste requested changes

2020-11-26 14:29 UTC, radtriste commented on archetypes/kogito-quarkus-archetype/src/main/resources/archetype-resources/pom.xml
> +                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
```suggestion
                    <java.util.logging.manager>${quarkus.logging.manager}</java.util.logging.manager>
```

2020-11-26 14:29 UTC, radtriste commented
maybe change also in other pom where it configures `org.jboss.logmanager.LogManager` ?

2020-11-26 15:06 UTC, cristianonicolai commented
@radtriste missed that, fixed.

2020-11-26 16:04 UTC, radtriste approved these changes

2020-11-27 01:27 UTC, merged