[KOGITO-3974] Make DecisionModels and PredictionModels injectable
kiegroup/kogito-runtimes pull request #922
Opened 2020-12-07 17:54 UTC by danielezonca

https://issues.redhat.com/browse/KOGITO-3974

Details:
- `DecisionModels` generation has now platform specific templates
- `PredictionModels` generation has now platform specific templates
- Created `AbstractDecisionModels` to share common code
- Created `AbstractPredictionModels` to share common code
- Updated `Application` generation to use injection (where available) also for `DecisionModels` and `PredictionModels`
- Now all `Applicatation` templates correctly delegate to `StaticApplication`

2020-12-09 17:53 UTC, danielezonca commented
jenkins retest this please

2020-12-10 08:51 UTC, tarilabs reviewed
thank you, this is good stuff, I have some questions if you can kindly help me understand better below please

2020-12-10 08:51 UTC, tarilabs commented on drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/AbstractDecisionModels.java
> +    private final static boolean IS_NATIVE_IMAGE = System.getProperty("org.graalvm.nativeimage.imagecode") != null;
```suggestion
    private final static boolean IS_NATIVE_IMAGE = org.kie.dmn.feel.util.ClassLoaderUtil.CAN_PLATFORM_CLASSLOAD;
```

2020-12-10 08:51 UTC, tarilabs commented on integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/InjectDecisionModels.java
> +            throw new IllegalStateException("DecisionModels should be injectable and same instance application.decisionModels()");
isn't this "pattern" which I see repeated for processes and rules, a sympthom we don't have a clear API design at the Kogito platform level?

2020-12-10 08:51 UTC, tarilabs commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationContainerGenerator.java
> +            }
I'm not sure I get this change, can you explain please?

2020-12-10 08:51 UTC, tarilabs commented on kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
> +                        .withDependencyInjection(dependencyInjectionAnnotator)
since this change, and others below, shouldn't that reflect also on ALL the `...CompilationProvider` classes??

2020-12-10 09:46 UTC, gitgabrio requested changes
@danielezonca 
Some minor comments, but I would really love to get rid of all those templates, at least the "duplicated" ones

2020-12-10 09:46 UTC, gitgabrio commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +        return getKieRuntimeFactoryFunction().apply(modelName).get(org.kie.pmml.api.runtime.PMMLRuntime.class);
@danielezonca 
Maybe just a leftover, but I guess better to use directly "kieRuntimeFactoryFunction" instead of the getter method.
Beside that, as a side note, there is not null check/NPE protection. 
Would it be possible to put the "kieRuntimeFactoryFunction" in the constructor ?
I see the setter is called in the template
`
public PredictionModels() {
        super();
        setKieRuntimeFactoryFunction(sKieRuntimeFactoryFunction);
    } 
`
so - unless for other reasons - it would just be a matter of moving "sKieRuntimeFactoryFunction" inside the "super" invocation.

2020-12-10 09:46 UTC, gitgabrio commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/prediction/PredictionModelsGenerator.java
> +                SECTION_CLASS_NAME,
@danielezonca 
If I'm not wrong, elsewhere in the code we have a strict naming convention.
As far as I see all this templates have the same schema: {context}{base model template} where "context" is "Cdi" or "Spring" and "base model template" is (for example) "PredictionModelsTemplate".
Would not be easier to just pass the latter (e.g. "PredictionModelsTemplate") to the "TemplatedGenerator", and have it infer the Cdi/Spring ones ? This would also enforce consistence between models, that is a good thing (IMHO).

Beside that, the only differences I see in the "models" templates, between different contexts, are the annotations on the class declaration (Cdi vs Spring ones). If/where this is true, I think it would be much better to remove all that useless duplications, have a "plain" template, and use JavaParser to dynamically add required annotation (Cdi/Spring) when needed. 
All those templates are pretty cumbersome; whenever a modification is needed, it must be done twice; and, after all, they not really needed (again, IMVHO)

2020-12-10 11:16 UTC, danielezonca commented on integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/InjectDecisionModels.java
> +            throw new IllegalStateException("DecisionModels should be injectable and same instance application.decisionModels()");
You are probably right: we generate classes using templates it is easy to remove an annotation and breaks without an integration tests that test it. I don't know if we can enforce this at API/design level to be honest :thinking: 
Any idea/suggestion?

2020-12-10 11:20 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationContainerGenerator.java
> +            }
If you look at `*ApplicationTemplate`s files there was a "replacement" pattern like
`this.process = null /* $Processes$ */;` -> `this.process = new Processes(this);`
Now that all the models are injectable this is no more needed except for the scenario with `annotator == null` (no Quarkus/Spring) so I decided to make this explicit and skip the replacement in this case

2020-12-10 11:22 UTC, danielezonca commented on kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
> +                        .withDependencyInjection(dependencyInjectionAnnotator)
Sorry but I don't understand what do you mean. I just created a local variable instead of instantiate multiple times  `CDIDependencyInjectionAnnotator`.
Can you please clarify your comment?

2020-12-10 12:17 UTC, danielezonca commented on drools/kogito-dmn/src/main/java/org/kie/kogito/dmn/AbstractDecisionModels.java
> +    private final static boolean IS_NATIVE_IMAGE = System.getProperty("org.graalvm.nativeimage.imagecode") != null;
Done

2020-12-10 12:29 UTC, danielezonca commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +        return getKieRuntimeFactoryFunction().apply(modelName).get(org.kie.pmml.api.runtime.PMMLRuntime.class);
Done, I reviewed all the templates and now ~all the code is inside the abstract :+1:

2020-12-10 12:29 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/prediction/PredictionModelsGenerator.java
> +                SECTION_CLASS_NAME,
Done, I reviewed all the templates and now ~all the code is inside the abstract :+1:

2020-12-10 17:07 UTC, danielezonca commented
jenkins retest this please

2020-12-10 17:47 UTC, tarilabs commented on kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
> +                        .withDependencyInjection(dependencyInjectionAnnotator)
I believe you did it with 574cf923f0cce1da08ea0675c4a8ab3c9c0d8cea

2020-12-10 17:47 UTC, tarilabs commented on kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
> +                        .withDependencyInjection(dependencyInjectionAnnotator)
do other classes of `...CompilationProvider` need this too?

2020-12-10 17:48 UTC, tarilabs commented on integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/InjectDecisionModels.java
> +            throw new IllegalStateException("DecisionModels should be injectable and same instance application.decisionModels()");
No I don't think this is solvable within the scope of this PR.
I'm saying this sounded to me a symptom the design of the Kogito API has a problem.

2020-12-10 17:49 UTC, tarilabs commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationContainerGenerator.java
> +            }
thanks for the feedback; worthy of adding it as a `// <code comment>`?

2020-12-11 08:49 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationContainerGenerator.java
> +            }
Done :+1:

2020-12-11 08:50 UTC, gitgabrio approved these changes
Thanks for the refactoring.
LGTM

2020-12-11 08:50 UTC, gitgabrio commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +    protected static void init(String ... pmmlFiles) {
@danielezonca 
Nice refactoring. Out of curiosity: is it needed for this method to be "static" ? I see it invoked inside a constructor

2020-12-11 08:51 UTC, danielezonca commented on kogito-quarkus-extension/deployment/src/main/java/org/kie/kogito/quarkus/deployment/KogitoAssetsProcessor.java
> +                        .withDependencyInjection(dependencyInjectionAnnotator)
Thanks a lot for the comment, I reviewed the usages and I realized that all `Generator`s have a `setDependencyInjection` that is automatically provided by `ApplicationGenerator` during the initialization so updated the code to use that one

2020-12-11 08:55 UTC, danielezonca commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +    protected static void init(String ... pmmlFiles) {
It is not invoked inside the constructor but with a `static` block (i.e. [link](https://github.com/kiegroup/kogito-runtimes/blob/3769ea2644548e7e397cb39ee229c316bd759a2c/kogito-codegen/src/main/resources/class-templates/CdiPredictionModelsTemplate.java#L5))

2020-12-11 08:57 UTC, gitgabrio commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +    protected static void init(String ... pmmlFiles) {
Thx, misread :+1:

2020-12-11 10:50 UTC, evacchi approved these changes
Approved, but I would move the rename of `withGenerator()` to a separate JIRA :)

2020-12-14 08:57 UTC, gitgabrio approved these changes

2020-12-14 08:57 UTC, gitgabrio commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +        final Function<String, KieRuntimeFactory> function = s -> kieRuntimeFactories.keySet().stream()
@danielezonca 
Fine if it works.
Anyway, all that still look as a painful workaround related to https://issues.redhat.com/browse/DROOLS-5724.
If I'm not wrong it all depends on the fact that DMN requires PMML for validation at building time (inside its Kogito-specific builder) even if NULL (as currently is), while model validation should be managed in previous step and should be model specific.

2020-12-14 09:02 UTC, tarilabs commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +        final Function<String, KieRuntimeFactory> function = s -> kieRuntimeFactories.keySet().stream()
> If I'm not wrong it all depends on the fact that DMN requires PMML for validation at building time

This assessment is incorrect.
This was already explained in the JIRA history (ref https://issues.redhat.com/browse/DROOLS-5724?focusedCommentId=15374787&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15374787 ) and followed up with the Kogito leads responsible for the previous Vs current directives.
Yes DMN internals will be refactored as part of DROOLS-5724 anyway.

2020-12-14 09:52 UTC, danielezonca commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +        final Function<String, KieRuntimeFactory> function = s -> kieRuntimeFactories.keySet().stream()
I added a comment to explain the reason of the `AtomicReference`. I tested it both jvm and native mode so we have the possibility to approach other refactoring incrementally without block this PR

2020-12-14 11:33 UTC, MarianMacik reviewed
Just have one question + I found the exception message confusing after first read :)

2020-12-14 11:33 UTC, MarianMacik commented on integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/InjectDecisionModels.java
> +            throw new IllegalStateException("DecisionModels should be injectable and same instance application.decisionModels()");
`DecisionModels should be injectable and same instance application.decisionModels()` - probably `same instance as application.decisionModels()`?

2020-12-14 11:33 UTC, MarianMacik commented on integration-tests/integration-tests-quarkus-predictions/src/main/java/org/kie/kogito/integrationtests/InjectPredictionModels.java
> +            throw new IllegalStateException("PredictionModels should be injectable and same instance application.predictionModels()");
Same here.

2020-12-14 11:33 UTC, MarianMacik commented on integration-tests/integration-tests-quarkus-processes/src/main/java/org/kie/kogito/integrationtests/InjectProcesses.java
> +            throw new IllegalStateException("Processes should be injectable and same instance application.processes()");
And here.

2020-12-14 11:33 UTC, MarianMacik commented on kogito-codegen/src/main/resources/class-templates/CdiApplicationTemplate.java
> +public class Application extends org.kie.kogito.StaticApplication {
I know that generated code probably shouldn't be readable that much, but wouldn't it be better to leave the imports here to make it cleaner? If the class is moved in future to a different package, we will have to change the templates anyway.

2020-12-14 11:33 UTC, MarianMacik commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +    protected static void init(String ... pmmlFiles) {
So the static block is used because of the CDI as we have to have a no-arg constructor? (Otherwise we would use just parameters of the constructor...)

2020-12-14 12:54 UTC, danielezonca commented on drools/kogito-pmml/src/main/java/org/kie/kogito/pmml/AbstractPredictionModels.java
> +    protected static void init(String ... pmmlFiles) {
No here the problem is that both DMN and PMML has some `static` code to be executed to load files. This is a trick for native compilation (and avoid parsing at runtime). So instead of duplicate this static code in all the templates, I moved it to the abstract class and created this init static method that is invoked in a `static` block codegenerated with the arguments.

2020-12-14 14:14 UTC, danielezonca commented on integration-tests/integration-tests-quarkus-decisions/src/main/java/org/kie/kogito/integrationtests/InjectDecisionModels.java
> +            throw new IllegalStateException("DecisionModels should be injectable and same instance application.decisionModels()");
Done

2020-12-14 14:15 UTC, danielezonca commented on integration-tests/integration-tests-quarkus-processes/src/main/java/org/kie/kogito/integrationtests/InjectProcesses.java
> +            throw new IllegalStateException("Processes should be injectable and same instance application.processes()");
Done

2020-12-14 14:15 UTC, danielezonca commented on integration-tests/integration-tests-quarkus-predictions/src/main/java/org/kie/kogito/integrationtests/InjectPredictionModels.java
> +            throw new IllegalStateException("PredictionModels should be injectable and same instance application.predictionModels()");
Done

2020-12-14 14:22 UTC, danielezonca commented on kogito-codegen/src/main/resources/class-templates/CdiApplicationTemplate.java
> +public class Application extends org.kie.kogito.StaticApplication {
In general I prefer to be on the safe side with templates: when we add code to the template it could produce name clashing while with FQCN this should not happen. Btw no strong opinion, if you prefer I can revert

2020-12-14 14:31 UTC, MarianMacik commented on kogito-codegen/src/main/resources/class-templates/CdiApplicationTemplate.java
> +public class Application extends org.kie.kogito.StaticApplication {
Makes sense, thanks!

2020-12-14 14:33 UTC, MarianMacik approved these changes
All sorted, thanks!

2020-12-14 14:43 UTC, merged