[KOGITO-3969] Reviewed ApplicationGenerator.logger usage + removed dead code
kiegroup/kogito-runtimes pull request #930
Opened 2020-12-10 10:32 UTC by danielezonca

https://issues.redhat.com/browse/KOGITO-3969

Details:
- `ApplicationGenerator.logger` now is a private field and each class has its own logger (to prevent misleading logging messages from a different package)
- Removed `ApplicationGenerator.log` method (a debug method that logs generated content) and moved the logic to `GeneratedFile` constructor: now if debug is enabled, all generated classes are logged with also type and relativePath
- Removed unused private fields in `ConfigGenerator`
- Removed unused `hasRuleUnits` field from `ApplicationGeneator` and updated all the existing usages (all in tests)

2020-12-10 10:37 UTC, evacchi commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java
> +        generatedFiles.add(new GeneratedFile(type, path, source));
I know that you did it to avoid repetition but I don't love that we are now logging within the constructor of this class, because now it will probably log stuff that we may not really care about (eg resources)

OTOH: I never loved this logging; this stuff is dumped to disk sooner or later, so  it's much easier to read it from a file, rather than displayed on the console log.

So I am ok with the change, although it feels a bit strange (to me).

2020-12-10 10:37 UTC, evacchi approved these changes

2020-12-10 13:22 UTC, danielezonca commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java
> +        generatedFiles.add(new GeneratedFile(type, path, source));
Yes I agree that it produce a lot of noise in the logs but my goal was to centralize it for now.
I moved the logging to `generate()` method of `ApplicationGenerator` so that it is not a side effect inside `GeneratedFile` constructor and it will be easier to change in the future (i.e. dump to disk instead of log).
Wdyt?

2020-12-10 13:26 UTC, evacchi commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/prediction/PredictionCodegen.java
> +        generatedFiles.add(new GeneratedFile(type, path, source));
I like it much better now!

2020-12-11 10:19 UTC, radtriste requested changes
just small convention

2020-12-11 10:19 UTC, radtriste commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/ApplicationGenerator.java
> +    private static final Logger logger = LoggerFactory.getLogger(ApplicationGenerator.class);
could we put the logger as `LOGGER` ?

2020-12-11 10:19 UTC, radtriste commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java
> +                LOG.debug("useMPAnnotations");
could we rename as `LOGGER` ?

2020-12-11 10:19 UTC, radtriste commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/DeclaredTypeCodegen.java
> +    private static final Logger logger = LoggerFactory.getLogger(DeclaredTypeCodegen.class);
`LOGGER`

2020-12-11 10:19 UTC, radtriste commented on kogito-codegen/src/main/java/org/kie/kogito/codegen/rules/IncrementalRuleCodegen.java
> +    private static final Logger logger = LoggerFactory.getLogger(IncrementalRuleCodegen.class);
`LOGGER`

2020-12-11 10:58 UTC, radtriste approved these changes
lgtm

2020-12-11 12:32 UTC, merged